<div class="container content">
	<div class="row"> 
	
    <!--left col-->
    <div id="left-col" class="span8">

	<article id="post-" class="post-75 post type-post status-publish format-gallery hentry category-gallery category-post-format tag-gallery-post tag-images tag-post blog-entry single-blog-entry clearfix">
		<!-- entry wrapper -->
		<div class="entry-wrapper">
		
		<p><strong><a href="<?=$templateData['remotelinkWeb'].$templateData['languageAbbreviation']?>" title="Home page">Home</a> &raquo; <?php echo $templateData['categoryName'] ?></strong> <?php if ($templateData['categoryName'] != $templateData['controllerResult']['title']): ?>&raquo; <?php echo $templateData['controllerResult']['title'] ?><?php endif; ?></p>
		
		<h3><?php echo $templateData['controllerResult']['title'] ?></h3>
		
		<header>
		<aside class="entry-meta clearfix">
		  <ul>
			<li class="meta-date">Posted on: <span>August 15, 2013</span></li>
			<li class="meta-author">by <span> skat</span></li>

			<li class="meta-category">
			  in      <a href="../category/gallery/index.html" title="View all posts in gallery">gallery</a>, <a href="../category/post-format/index.html" title="View all posts in post format">post format</a>    </li>
			<li class="meta-tag">tagged as <a href="../tag/gallery-post/index.html" rel="tag">gallery post</a> , <a href="../tag/images/index.html" rel="tag">images</a> , <a href="../tag/post/index.html" rel="tag">post</a></li>  </ul>
		</aside>
		</header>


		<!-- entry content  -->
		<div class="entry-content">
		<?php echo $templateData['controllerResult']['description'] ?>
		</div>
		
		<!-- entry content end -->

	  </div>
	  
	<!-- entry wrapper end-->
	</article>
	
	</div>

	
	<div id="right-col" class="span4">
		<div class="sidebar">
			<?php
			echo $this->partial( $this->templateData['template_path'].'sidebar.phtml');
			?>
		</div>
	</div>

	
	</div>
</div>
