<div class="container content">
	<div class="row"> 
	
    <!--left col-->
    <div id="left-col" class="span8">

	<article id="post-" class="post-75 post type-post status-publish format-gallery hentry category-gallery category-post-format tag-gallery-post tag-images tag-post blog-entry single-blog-entry clearfix">
		<!-- entry wrapper -->
		<div class="entry-wrapper">
		
		<p><strong><a href="<?=$templateData['remotelinkWeb'].$templateData['languageAbbreviation']?>" title="Home page">Home</a> &raquo; <?php echo $templateData['categoryName'] ?></strong> <?php if ($templateData['categoryName'] != $templateData['controllerResult']['title']): ?>&raquo; <?php echo $templateData['controllerResult']['title'] ?><?php endif; ?></p>
		
		<h3><?php echo $templateData['controllerResult']['title'] ?></h3>
		
		<header>
		<aside class="entry-meta clearfix">
		  <ul>
			<li class="meta-date">Posted on: <span>August 15, 2013</span></li>
			<li class="meta-author">by <span> skat</span></li>

			<li class="meta-category">
			  in      <a href="../category/gallery/index.html" title="View all posts in gallery">gallery</a>, <a href="../category/post-format/index.html" title="View all posts in post format">post format</a>    </li>
			<li class="meta-tag">tagged as <a href="../tag/gallery-post/index.html" rel="tag">gallery post</a> , <a href="../tag/images/index.html" rel="tag">images</a> , <a href="../tag/post/index.html" rel="tag">post</a></li>  </ul>
		</aside>
		</header>


		<!-- entry content  -->
		<div class="entry-content">
		<?php echo $templateData['controllerResult']['description'] ?>
		</div>
		
		<!-- entry content end -->
		<footer>
		  <div class="prev-next clearfix"> <span class="previous-article">
					</span> <span class="next-article">
			<a href="../the-interwebz-interview/index.html" rel="prev">Next Post →</a>        </span> </div>
		</footer>
	  </div>
	  
	<!-- entry wrapper end--> 
	</article>
	
	
	<div id="respond" class="comment-respond">
		
		<h3 id="reply-title" class="comment-reply-title"></h3>

		<h3 class="reply-title"><span>Leave a reply</span><span class="title-arrow"></span></h3> <small><a rel="nofollow" id="cancel-comment-reply-link" href="index.html#respond" style="display:none;">Cancel reply</a></small>

		<form action="" method="post" id="commentform" class="comment-form">

		<p class="comment-notes">Your email address will not be published. Required fields are marked <span class="required">*</span></p>

		<div class="respond-inputs">

		<p><input onblur="this.value = this.value || this.defaultValue; this.style.color = '#d1d1cd';" onfocus="this.value=''; this.style.color = '#737373';" name="author" type="text" value="Name (required)" size="30" aria-required="true"></p>

		<p><input onblur="this.value = this.value || this.defaultValue; this.style.color = '#d1d1cd';" onfocus="this.value=''; this.style.color = '#737373';" name="email" type="text" value="E-Mail (required)" size="30" aria-required="true"></p>

		<p class="last-input"><input onblur="this.value = this.value || this.defaultValue; this.style.color = '#d1d1cd';" onfocus="this.value=''; this.style.color = '#737373';" name="url" type="text" value="Website" size="30"></p>

		</div>

		<div class="respond-textarea">
		<p><textarea id="comment" name="comment" aria-required="true" cols="58" rows="10" tabindex="4"></textarea></p></div>

		<p class="form-submit">
		<input name="submit" type="submit" id="submit" value="Submit Comment!">
		<input type="hidden" name="comment_post_ID" value="75" id="comment_post_ID">
		</p>

		<p style="display: none;"><input type="hidden" id="akismet_comment_nonce" name="akismet_comment_nonce" value="f3cd2fd563"></p>
		</form>

		</div>
	
	</div>

	
	<div id="right-col" class="span4">
		<div class="sidebar">
			<?php
			echo $this->partial( $this->templateData['template_path'].'sidebar.phtml');
			?>
		</div>
	</div>

	
	</div>
</div>
