<ul class="breadcrumb">
    <li><a href="<?php echo $this->basepath() ?>/admin/main/" title="Home page">Home</a> <span class="divider"></span></li>
    <li class="active">Invio atto ad ente terzo</li>
</ul>

<h1>Invio atto ad ente terzo</h1>

<div>Articolo da inviare ad altro Ente (Comune o Prefettura) per richiederne la pubblicazione o per inviare la relata:</div>

<div><strong><?php echo $this->titolo ?></strong></div>

<?php

echo $this->render($this->formDataCommonPath.'formdata_common.phtml');