<div class="large-12 columns">
    <div class="large-6 columns">
        <h1>
        <a href="<?php echo $this->basepath() ?>/" title="Torna all'home page">
            <?php echo $this->sitename ?>
        </a>
        </h1>
    </div>
    <div class="large-6 columns">
    <ul class="inline-list right">
        <li><a href="#mainContents" accesskey="x" class="button small">Vai ai contenuti</a></li>
    </ul>
    </div>
</div>

<hr class="hidden">

<div class="large-12 columns">
    <nav class="top-bar" data-topbar role="navigation">
        <ul class="title-area">
            <li class="name">
                <h1><a href="<?php echo $this->basepath() ?>/" title="Torna all'home page" accesskey="h">Home</a></h1>
            </li>

            <li class="toggle-topbar menu-icon"><a href="#" title="Menu navigazione"><span>Menu</span></a></li>
        </ul>

        <section class="top-bar-section">
            <h2 class="hidden">Men&ugrave; navigazione</h2>
            <ul class="left">
                <li class="divider"></li>
                <li><a href="<?php echo $this->url('albo-pretorio') ?>" title="Elenco atti albo pretorio">Albo pretorio</a></li>
                <li class="divider"></li>
                <li><a href="<?php echo $this->url('stato-civile') ?>" title="Pubblicazioni stato civile">Stato civile</a></li>
                <li class="divider"></li>
                <li><a href="<?php echo $this->url('contratti-pubblici') ?>" title="Elenco bandi di gara e contratti">Bandi e contratti</a></li>
                <li class="divider"></li>
                <li><a href="<?php echo $this->url('atti-concessione') ?>" title="Elenco atti di concessione">Atti di concessione</a></li>
                <li class="divider"></li>
                <li><a href="<?php echo $this->url('amministrazione-trasparente') ?>" title="Articoli amministrazione trasparente">Amministrazione trasparente</a></li>
                <li class="divider"></li>
                <!--
                <li><a href="<?php echo $this->url('main', array('category' => 'comune-azienda', 'title' => 'dove-siamo')) ?>" title="Dove siamo">Dove siamo</a></li>
                <li class="divider"></li>
                <li><a href="<?php echo $this->url('contatti') ?>">Contatti</a></li>
                -->
            </ul>

            <ul class="right">
                <li><a href="#" title="Registrati come nuovo utente">Registrati</a></li>
                <li><a href="#" title="Iscrizione newsletter">Newsletter</a></li>
                <li class="has-dropdown">
                    <a href="#" title="Altri moduli">Altri moduli</a>
                    <ul class="dropdown">
                        <li><a href="#" title="Autocertificazioni">Autocertificazioni</a></li>
                        <li><a href="#" title="Azienda">Azienda</a></li>
                        <li><a href="#" title="Booking">Booking</a></li>
                        <li><a href="#" title="Servizio SMS">Servizio SMS</a></li>
                        <li><a href="#" title="Meteo">Meteo</a></li>
                        <li><a href="#" title="Galleria fotografica">Galleria fotografica</a></li>
                        <li><a href="#" title="E-commerce">E-commerce</a></li>
                    </ul>
                </li>
            </ul>
        </section>
    </nav>
</div>