<?php echo $this->doctype(); ?>

<html lang="it">
<head>
    <meta charset="utf-8">
    <title><?php echo $this->sitename ?></title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="<?php echo $this->description ?>">
    <meta name="keywords" content="<?php echo $this->keywords ?>">
    
    <link href="<?php echo $this->basePath(). '/'.$this->cssdir ?>" media="screen" rel="stylesheet" type="text/css">
    <link href="//netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.css" rel="stylesheet">
    
    <link href="<?php echo $this->basePath() . '/public/frontend/projects/favicon.ico' ?>" rel="shortcut icon" type="image/vnd.microsoft.icon">

    <!-- HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
    <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->

    <!-- Fav and touch icons -->
    <!--
    <link rel="apple-touch-icon-precomposed" sizes="144x144" href="img/apple-touch-icon-144-precomposed.png">
    <link rel="apple-touch-icon-precomposed" sizes="114x114" href="img/apple-touch-icon-114-precomposed.png">
    <link rel="apple-touch-icon-precomposed" sizes="72x72" href="img/apple-touch-icon-72-precomposed.png">
    <link rel="apple-touch-icon-precomposed" href="img/apple-touch-icon-57-precomposed.png">
    -->

</head>

<body>

<noscript>
    <div>
	<h1>Attenzione: javascript disabilitato</h1>
	<div>&Egrave; stato rilevato che il browser in uso ha javascript disabilitato. Consigliamo di abilitarlo o alcune funzioni del sito non saranno visibili.</div>
    </div>
</noscript>

<div class="container">
    <div class="row clearfix">
            <div class="col-md-12 column">
                    <nav class="navbar navbar-default" role="navigation">
                            <div class="navbar-header">
                                     <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1"> <span class="sr-only">Toggle navigation</span><span class="icon-bar"></span><span class="icon-bar"></span><span class="icon-bar"></span></button> <a class="navbar-brand" href="#" title=""><?php echo $this->sitename ?></a>
                            </div>

                            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                                    <ul class="nav navbar-nav">
                                        <li class="active">
                                            <a href="<?php echo $this->basePath() ?>" title="Home page"><i class="fa fa-home"></i> Home</a>
                                        </li>
                                        <li>
                                            <a href="<?php echo $this->basePath() ?>/foto" title=""><i class="fa fa-camera"></i> Foto</a>
                                        </li>

                                        <li class="dropdown">
                                                <a href="#" class="dropdown-toggle" data-toggle="dropdown"><i class="fa fa-archive"></i> Moduli<strong class="caret"></strong></a>
                                                <ul class="dropdown-menu">
                                                    <li><a href="<?php echo $this->basePath().'/albo-pretorio'; ?>">Albo Pretorio</a></li>
                                                    <li><a href="<?php echo $this->basePath().'/stato-civile'; ?>">Stato Civile</a></li>
                                                    <!-- <li class="divider"></li> -->
                                                    <li><a href="<?php echo $this->basePath() ?>/amministrazione-trasparente">Amministrazione trasparente</a></li>
                                                    <li><a href="<?php echo $this->basePath() ?>/faq/domande">F.A.Q</a></li>
                                                </ul>
                                        </li>

                                        <li>
                                            <a href="<?php echo $this->basePath() ?>/contatti/invia-messaggio/" title="Contatti"><i class="fa fa-envelope"></i> Contatti</a>
                                        </li>

                                    </ul>
                                    <form class="navbar-form navbar-left" method="post" action="<?php echo $this->basepath() ?>/ricerca/risultati/" role="search">
                                            <div class="form-group">
                                                <input type="text" class="form-control" placeholder="Cerca sul sito">
                                            </div> <button type="submit" class="btn btn-default" title="Cerca sul sito">Cerca</button>
                                    </form>
                                    <ul class="nav navbar-nav navbar-right">
                                        <li class="dropdown">
                                            <a href="javascript:void(0)" class="dropdown-toggle" data-toggle="dropdown"><i class="fa fa-user"></i> John Doe<strong class="caret"></strong></a>
                                            <ul class="dropdown-menu">
                                                <li>
                                                    <a href="javascript:void(0)" title="Profilo">Profilo</a>
                                                </li>
                                                <li>
                                                    <a href="javascript:void(0)" title="">Documenti</a>
                                                </li>
                                                <li class="divider"></li>
                                                <li>
                                                    <a href="<?php echo $this->basePath() ?>/admin/logout" title="Uscita dall'area riservata"><i class="fa fa-power-off"></i> Uscita</a>
                                                </li>
                                            </ul>
                                        </li>
                                    </ul>
                            </div>

                    </nav>
                    <div class="row clearfix">
                            <div class="col-md-12 column"></div>
                    </div>
                    <div class="row clearfix">

                            <div class="col-md-2 column">

                            <?php if ($this->preloadResponse): ?>
                            <?php foreach($this->preloadResponse as $key => $value): ?>
                                    <div class="list-group">
                                        <a href="#" class="list-group-item active"><?php echo $key ?></a>
                                        <?php foreach($value as $post): ?>
                                        <a href="<?php echo $this->basepath().$post['linkDetails'] ?>" class="list-group-item"><?php echo $post['titolo'] ?></a>
                                        <?php endforeach; ?>
                                    </div>
                            <?php endforeach; ?>
                            <?php endif; ?>

                            <div class="panel panel-info">
                                <div class="panel-heading">
                                    <h3 class="panel-title">Servizi on-line</h3>
                                </div>
                                <div class="panel-body">
                                    <ul style="list-style-type: none; padding: 0">
                                        <li style="margin-bottom: 0.5em"><a href="#" title="">Notizie</a></li>
                                        <li style="margin-bottom: 0.5em"><a href="#" title="">Albo pretorio</a></li>
                                        <li style="margin-bottom: 0.5em"><a href="#" title="">Stato civile</a></li>
                                        <li style="margin-bottom: 0.5em"><a href="#" title="">Amministrazione trasparente</a></li>
                                    </ul>
                                </div>

                            </div>
                            
                            </div>
                            

                            <div class="col-md-8 column">
                            <?php
                            // main contents
                            echo $this->partial($this->templatePartial);
                            ?>
                            </div>

                            <div class="col-md-2 column">
                            <div class="panel panel-info">
                                <div class="panel-heading">
                                        <h3 class="panel-title">
                                                Foto
                                        </h3>
                                </div>
                                <div class="panel-body">
                                    <a href="#" title=""><img src="<?php echo $this->basePath() ?>/<?php echo $this->imagedir ?>san-nicola.jpg" alt="Foto dallla galleria"></a>
                                </div>
                                <div class="panel-footer">
                                    <a href="<?php echo $this->basepath() ?>/foto" title="Visualizza tutte le foto">Visualizza tutte</a>
                                </div>
                            </div>
                            
                                <p><a href="<?php echo $this->basePath() ?>/amministrazione-trasparente"><img src="<?php echo $this->basePath() ?>/<?php echo $this->imagedir ?>amministrazione-trasparente.jpg" alt="Amministrazione trasparente"></a></p>
                                
                                <div class="panel panel-default">                                  
                                  <!-- <div class="panel-heading">Panel heading</div> -->
                                  <ul class="list-group">
                                    <li class="list-group-item"><a href="<?php echo $this->basepath() ?>/rassegna-stampa" title="">Rassegna stampa</a></li>
                                    <li class="list-group-item"><a href="<?php echo $this->basepath() ?>/eventi" title="">Eventi</a></li>
                                    <li class="list-group-item"><a href="#" title="">Informa giovani</a></li>
                                    <li class="list-group-item"><a href="#" title="">Biblioteca</a></li>
                                  </ul>
                                </div>

                            </div>
                    </div>
                    <div class="row clearfix">
                            <div class="col-md-12 column">
                                    <p class="text-muted">
                                        &copy; <?php echo date("Y") ?> <?php echo $this->sitename ?> Sito sviluppato da <a href="http://www.kronoweb.it" target="_blank" title="Kronoweb.it ITC">Kronoweb</a>. <a href="#" title="">Note Legali</a> <a href="#" title="">Accessiblit&agrave;</a> <a href="#" title="">Mobile</a> <a href="#" title="">Feed RSS</a> <a href="http://validator.w3.org/check?uri=referer" title="Validate HTML" target="_blank" class="underline footerlink">Valid HTML5</a> - <a href="http://jigsaw.w3.org/css-validator/check/referer" title="Validate CSS" target="_blank" class="underline footerlink">Valid CSS</a>
                                    </p>
                            </div>
                    </div>
            </div>
    </div>
</div>

<!-- JQuery -->
<script src="<?php echo $this->basePath() ?>/public/common/jquery/jquery.min.js"></script>
<script src="<?php echo $this->basePath() ?>/public/common/bootstrap3/js/bootstrap.min.js"></script>
<script>
jQuery(document).ready(function() {

});
</script>

<?php echo $this->inlineScript() ?>
</body>
</html>