<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Channels\Module'                        => __DIR__ . '/Module.php',
    'Channels\Controller\ChannelsController' => __DIR__ . '/src/Channels/Controller/ChannelsController.php',
);
