<ul class="breadcrumb">
    <li><a href="<?php echo $this->basepath() ?>" title="Home page">Home</a> <span class="divider"></span></li>
    <li class="active">Stato civile</li>
</ul>

<?php if (count($this->paginator)): ?>

<h1 class="text-center">Pubblicazioni stato civile</h1>

<div class="panel-group" id="accordion">
    <div class="panel panel-default">
        <div class="panel-heading">
            <h4 class="panel-title">
                <a data-toggle="collapse" data-parent="#accordion" href="#collapseOne">
                  &raquo; Ricerca
                </a>
            </h4>
        </div>
        <div id="collapseOne" class="panel-collapse collapse in">
            <div class="panel-body">
<?php

$form = $this->form;
$form->prepare();

$form->setAttribute('action', $this->serverUrl(true) );
$form->setAttribute('method', 'post');
$form->setAttribute('role', 'form');
$form->setAttribute('class', 'form-horizontal');
$form->setAttribute('id', 'stato-civile-search-form');

/* Apply bootstrap css class to the form elements */
$form->get('testo')->setAttribute('class','form-control');
$form->get('sezione')->setAttribute('class', 'form-control');
$form->get('mese')->setAttribute('class', 'form-control');
$form->get('anno')->setAttribute('class', 'form-control');
$form->get('search')->setAttribute('class', 'btn btn-primary');

echo $this->form()->openTag($this->form);

?>
<fieldset>
    <legend>Ricerca atti stato civile</legend>
    
    <div class="form-group">
        <label for="<?php echo $form->get('testo')->getAttribute('id'); ?>" class="col-sm-2 control-label"><?php echo $this->formLabel($form->get('testo')) ?>:</label>
        <div class="col-sm-8">
            <?php echo $this->formElement($form->get('testo')); ?>
        </div>
    </div>
    
    <div class="form-group">
        <label for="<?php echo $form->get('mese')->getAttribute('id'); ?>" class="col-sm-2 control-label">Atti a partire da:</label>
        <div class="col-sm-4">
            <?php echo $this->formElement($form->get('mese')); ?>
        </div>
        
        <div class="col-sm-4">
            <?php echo $this->formElement($form->get('anno')); ?>
        </div>
    </div>
    
    <div class="form-group">
        <label for="<?php echo $form->get('sezione')->getAttribute('id'); ?>" class="col-sm-2 control-label"><?php echo $this->formLabel($form->get('sezione')) ?>:</label>
        <div class="col-sm-8">
            <?php echo $this->formElement($form->get('sezione')); ?>
        </div>
    </div>
    
    <div class="form-group">
        <label class="col-sm-2 control-label">&nbsp;</label>
        <div class="col-sm-8">
            <?php echo $this->formElement($form->get('csrf')); ?>
            <?php echo $this->formElement($form->get('search')); ?>
        </div>
    </div>
    
    <?php echo $this->form()->closeTag(); ?>
    
    </fieldset>

        </div>
    </div>
</div>

<div>&nbsp;</div>

<div class="alert alert-info">Per aprire i file firmati digitalmente scaricare il software ArubaSign:<br>
<ul class="list-unstyled">
    <li><i class="fa fa-windows"></i> <a href="http://www.kronoweb.it/download/ArubaSign/ArubaSign2_3_5_WINDOWS.exe" title="Software per PC">Versione per PC (17,5MB)</a></li>
    <li><i class="fa fa-linux"></i> Versione per Linux <a href="https://www.pec.it/Download/Software/FirmaDigitale/ArubaSign32-2_8_3.tar.bz2" title="Software per Linux">(32 bit)</a> - <a href="https://www.pec.it/Download/Software/FirmaDigitale/ArubaSign64-2_8_3.tar.bz2" title="Software per Linux">(64 bit)</a></li>
    <li><i class="fa fa-apple"></i> <a href="http://www.kronoweb.it/download/ArubaSign/ArubaSign2_1_5MAC.zip" title="Software per MAC">Versione per MAC (31,2MB)</a></li>
</ul>
<br>
Si consiglia di visionare l'albo pretorio per tutta la durata della pubblicazione in quanto potrebbero verificarsi modifiche che verranno segnalate tramite rettifiche e/o annullamenti degli atti.
</div>

</div>

<?php foreach($this->paginator as $key => $row): ?>
<div>
    <h2><?php echo $row['titolo'] ?></h2>
    <div><strong>Numero \ Anno:</strong> <?php echo $row['progressivo']." / ".$row['anno']; ?></div>
    <div><strong>Scadenza:</strong> <?php echo date('d-m-Y', strtotime($row['scadenza']) ); ?></div>
    <div><strong>Sezione:</strong> <?php echo $row['nome'] ?></div>
    <!-- <div><strong>Allegati</strong></div> -->
</div>
<hr>
<?php endforeach; ?>

<?php
    if ( count($this->paginator) > 1 ):
        echo $this->paginationControl(
            $this->paginator,
            'sliding',
            'application/pagination/bootstrap.phtml',
            array(
                'category' => '',
                'route' => 'stato-civile'
            )
        );
    endif;
else:
    ?>
    <div class="alert alert-warning">
        <h1>Nessun dato in archivio</h1>
        <p>Nessun atto sullo stato civile si trova in archivio</p>
    </div>
    <?php
endif;
