<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'ApiWebService\Module'                                  => __DIR__ . '/Module.php',
    'ApiWebService\Controller\DefaultApiController'         => __DIR__ . '/src/ApiWebService/Controller/DefaultApiController.php',
    'ApiWebService\Model\ApiOutputManager'                  => __DIR__ . '/src/ApiWebService/Model/ApiOutputManager.php',
    'ApiWebService\Model\ApiResultGetterAbstract'           => __DIR__ . '/src/ApiWebService/Model/ApiResultGetterAbstract.php',
    'ApiWebService\Model\ApiSetup'                          => __DIR__ . '/src/ApiWebService/Model/ApiSetup.php',
    'ApiWebService\Model\ApiSetupAbstract'                  => __DIR__ . '/src/ApiWebService/Model/ApiSetupAbstract.php',
    'ApiWebService\Model\Resources\AlboPretorioApiResource' => __DIR__ . '/src/ApiWebService/Model/Resources/AlboPretorioApiResource.php',
    'ApiWebService\Model\Resources\PostsApiResource'        => __DIR__ . '/src/ApiWebService/Model/Resources/PostsApiResource.php',
    'ApiWebService\Model\Resources\StatoCivileApiResource'  => __DIR__ . '/src/ApiWebService/Model/Resources/StatoCivileApiResource.php',
);
