<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
  'ApiWebService\Module'                                 => __DIR__ . '/Module.php',
  'ApiWebService\Controller\DefaultApiController'        => __DIR__ . '/src/ApiWebService/Controller/DefaultApiController.php',
  'ApiWebService\Model\ApiAuthenticator'                 => __DIR__ . '/src/ApiWebService/Model/ApiAuthenticator.php',
  'ApiWebService\Model\ApiInputSetterGetter'             => __DIR__ . '/src/ApiWebService/Model/ApiInputSetterGetter.php',
  'ApiWebService\Model\ApiResourceHandler'               => __DIR__ . '/src/ApiWebService/Model/ApiResourceHandler.php',
  'ApiWebService\Model\ApiResultGetterAbstract'          => __DIR__ . '/src/ApiWebService/Model/ApiResultGetterAbstract.php',
  'ApiWebService\Model\ApiSetupAbstract'                 => __DIR__ . '/src/ApiWebService/Model/ApiSetupAbstract.php',
  'ApiResourceRecordsGetterInterface'                    => __DIR__ . '/src/ApiWebService/Model/Resources/ApiResourceRecordsGetterInterface.php',
  'ApiWebService\Model\Resources\PostsApiResource'       => __DIR__ . '/src/ApiWebService/Model/Resources/PostsApiResource.php',
);
