<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'ApiWebService\Module'                               => __DIR__ . '/Module.php',
    'ApiWebService\Controller\AlboPretorioApiController' => __DIR__ . '/src/ApiWebService/Controller/AlboPretorioApiController.php',
    'ApiWebService\Controller\DefaultApiController'      => __DIR__ . '/src/ApiWebService/Controller/DefaultApiController.php',
    'ApiWebService\Controller\PostsApiController'        => __DIR__ . '/src/ApiWebService/Controller/PostsApiController.php',
    'ApiWebService\Controller\UtentiApiController'       => __DIR__ . '/src/ApiWebService/Controller/UtentiApiController.php',
);
