<div>
    <ul class="breadcrumbs">
        <li><a href="<?php echo $this->basepath() ?>" title="Home page">Home</a> <span class="divider"></span></li>
        <li class="current">Recupero password</li>
    </ul>

    <h1>Recupero password</h1>

    <p>Inserisci l'indirizzo email per richiedere una nuova password.</p>

    <?php echo $this->render($this->templateDir.'common/show_form.phtml'); ?>
</div>