<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Language\Module'                        => __DIR__ . '/Module.php',
    'Language\Controller\LanguageController' => __DIR__ . '/src/Language/Controller/LanguageController.php',
    'LanguageTest\Framework\TestCase'        => __DIR__ . '/tests/Language/Framework/TestCase.php',
    'LanguageTest\SampleTest'                => __DIR__ . '/tests/Language/SampleTest.php',
);
