<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Auth\Module'                               => __DIR__ . '/Module.php',
    'Auth\Controller\AuthController'            => __DIR__ . '/src/Auth/Controller/AuthController.php',
    'Admin\Controller\ForgotPasswordController' => __DIR__ . '/src/Auth/Controller/ForgotPasswordController.php',
);
