<?php
/* Share and export icons */
$shareIconsView = $this->partial('frontend/projects/entilocali/templates/'.$this->template_frontend.'_share.phtml', array(
    'twitterShareText'          => $this->sitename.' - Bandi e contratti pubblici',
    'exportTxtUrl'              => '',
    'exportCsvUrl'              => '',
    'exportPdfUrl'              => '',
    'publicDirRelativePath'     => $this->publicDirRelativePath,
));
?>
<ul class="breadcrumbs">
    <li><a href="<?php echo $this->basepath() ?>" title="Torna all'home page">Home</a></li>
    <li class="current">Bandi di gara e contratti</li>
</ul>

<?php if (count($this->paginator)): ?>
<div class="text-center">
    <h1>Bandi di gara e contratti</h1>
</div>

<p><?php echo $this->paginator_total_item_count ?> bandi in archivio</p>

<fieldset>
        <legend>Ricerca atti di concessione</legend>
    <?php

    $form = $this->form;

    $form->prepare();

    $form->setAttribute('action', $this->url('contratti-pubblici'));
    $form->setAttribute('method', 'post');
    $form->setAttribute('role', 'form');
    $form->setAttribute('id',   'contrattiPubbliciSearchForm');

    $form->get('search')->setAttribute('class', 'button button-tiny tiny');
    $form->get('importo')->setLabel('Importo');
    $form->get('cig')->setLabel('<abbr title="Codice identificativo gara">CIG</abbr>');

    $formLabel = $this->plugin('formLabel');

    echo $this->form()->openTag($this->form);

    ?>

    <div class="row">
        <div class="large-2 columns">
            <label for="<?php echo $form->get('anno')->getAttribute('id'); ?>">
                <?php echo $form->get('anno')->getLabel() ?>:
            </label>
        </div>
        <div class="large-2 columns">
            <?php echo $this->formElement($form->get('anno')); ?>
        </div>

        <div class="large-2 columns">
            <label for="<?php echo $form->get('cig')->getAttribute('id'); ?>">
                <?php echo $form->get('cig')->getLabel() ?>:
            </label>
        </div>
        <div class="large-2 columns">
            <?php echo $this->formElement($form->get('cig')); ?>
        </div>

        <div class="large-2 columns">
            <label for="<?php echo $form->get('importo')->getAttribute('id'); ?>">
                <?php echo $form->get('importo')->getLabel() ?>:
            </label>
        </div>
        <div class="large-2 columns">
            <?php echo $this->formElement($form->get('importo')); ?>
        </div>
    </div>

    <div class="row">
        <div class="large-3 columns">
            <label for="<?php echo $form->get('ufficio')->getAttribute('id'); ?>">
                <?php echo $form->get('ufficio')->getLabel() ?>:
            </label>
        </div>
        <div class="large-9 columns">
            <?php echo $this->formElement($form->get('ufficio')); ?>
        </div>
    </div>

    <div class="row">
        <div class="large-2 columns">
            <label for="<?php echo $form->get('search')->getAttribute('id'); ?>">
                <?php echo $form->get('search')->getLabel() ?>:
            </label>
        </div>
        <div class="large-10 columns">
            <?php echo $this->formElement($form->get('search')); ?>
        </div>
    </div>

    <?php echo $this->form()->closeTag(); ?>
</fieldset>

<?php echo $shareIconsView; ?>

<div>
    <table class="responsive" role="grid">
        <caption>Elenco bandi di gara e contratti. <?php echo $this->paginator_total_item_count ?> bandi presenti</caption>
        <thead>
            <tr>
                <th scope="col">Bando</th>
                <th scope="col">Struttura Proponente</th>
                <th scope="col">Procedura di <br>scelta del contraente</th>
                <th scope="col">Operatori invitati a<br>presentare le offerte</th>
                <th scope="col">Aggiudicatario</th>
                <th scope="col">Importi (Euro)</th>
                <th scope="col">Tempi di completamento</th>
                <th scope="col">Allegati</th>
            </tr>
        </thead>
        <tbody>
            <?php foreach($this->records as $key => $row): ?>
            <tr>
                <td>
                    <strong>Oggetto del bando:</strong> <?php echo utf8_encode($row['titolo']) ?><br><br>
                    <strong>CIG:</strong> <?php echo $row['cig'] ?><br><br>
                    <strong>Anno:</strong> <?php echo $row['anno'] ?>
                </td>
                <td>
                    <strong>CF:</strong> <br><br>
                    <strong>Str. prop:</strong> <?php echo utf8_encode($row['nomeSettore']) ?><br><br>
                    <strong>Resp.</strong> <?php echo utf8_encode($row['responsabileUsersName'].' '.$row['responsabileUsersSurname']) ?><br><br>
                    <strong>Resp. Proc.</strong> <?php echo utf8_encode($row['responsabileUsersName'].' '.$row['responsabileUsersSurname'])?>
                </td>
                <td><?php echo utf8_encode($row['nomeScelta']) ?></td>
                <!-- TODO: operatori invitati a partecipare -->
                <td>
                    <strong>CF-PI:</strong> <br><br>
                    <strong>Nome e Ragione sociale:</strong>
                </td>
                <!-- TODO: List Aggiudicatario -->
                <td>
                    <strong>CF-PI:</strong> <br><br>
                    <strong>Nome e ragione sociale:</strong>
                </td>
                <td>
                    <strong>Importo di aggiudicazione:</strong> <?php echo utf8_encode($row['importoAggiudicazione']) ?> &euro;<br><br>
                    <strong>Importo liquidato:</strong> <?php echo utf8_encode($row['importoLiquidato']) ?> &euro;
                </td>
                <td>
                    <strong>Inizio lavori:</strong> <?php $temp2 = explode("-", $row['dataInizioLavori']); echo $temp2[2]."-".$temp2[1]."-".$temp2[0]; ?><br><br>
                    <strong>Fine lavori:</strong> <?php echo $row['dataFineLavori'] ?>
                </td>
                <td>
                    <?php if (!empty($row['attachments'])): ?>
                        <div>
                            <p><strong>Allegati:</strong></p>
                            <ul class="no-bullet">
                                <?php foreach($row['attachments'] as $attachment): ?>
                                    <li>
                                        <a href="<?php echo $this->publicDirRelativePath ?>/common/icons/attachments/<?php echo $attachment['image'] ?>" title="Scarica allegato <?php echo $attachment['title'] ?> (<?php echo $attachment['size'] ?> Kb)">
                                            <img src="<?php echo $this->publicDirRelativePath ?>/common/icons/attachments/<?php echo $attachment['image'] ?>" alt="Icona per <?php echo $attachment['title'] ?> (<?php echo $attachment['size'] ?> Kb)">
                                            <?php echo $attachment['title'] ?>
                                        </a>
                                    </li>
                                <?php endforeach ?>
                            </ul>
                        </div>
                    <?php else: ?>
                        &nbsp;
                    <?php endif; ?>
                </td>
            </tr>
            <tr>
                <td colspan="8">
                    <hr>
                </td>
            </tr>
            <?php endforeach; ?>
        </tbody>
    </table>
</div>
<?php

    if (count($this->paginator) > 1):
        echo $this->paginationControl(
            $this->paginator,
            'sliding',
            'application/pagination/foundation.phtml',
            array('route' => 'contratti-pubblici')
        );
    endif;

    echo $shareIconsView;

else:
    ?>
    <div>
        <h1>Nessun bando in archivio</h1>
        <p>Nessun bando in archivio</p>
    </div>
    <?php
endif;
