<?php echo $this->doctype(); ?>

<html lang="it">
<head>
<meta charset="utf-8">
<title><?php echo $this->sitename ?></title>
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<meta name="description" content="<?php echo $this->description ?>">
<meta name="keywords" content="<?php echo $this->keywords ?>">

<link href="<?php echo $this->basePath(). '/'.$this->cssdir ?>" media="screen" rel="stylesheet" type="text/css">
<link href="//netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.css" rel="stylesheet">
<link href="<?php echo $this->basePath() . '/favicon.ico' ?>" rel="shortcut icon" type="image/vnd.microsoft.icon">

<!-- HTML5 shim, for IE6-8 support of HTML5 elements -->
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

<!-- Fav and touch icons -->
<!--
<link rel="apple-touch-icon-precomposed" sizes="144x144" href="img/apple-touch-icon-144-precomposed.png">
<link rel="apple-touch-icon-precomposed" sizes="114x114" href="img/apple-touch-icon-114-precomposed.png">
<link rel="apple-touch-icon-precomposed" sizes="72x72" href="img/apple-touch-icon-72-precomposed.png">
<link rel="apple-touch-icon-precomposed" href="img/apple-touch-icon-57-precomposed.png">
-->

<style>
.footer {
    padding: 2.5% 0 0 0;
    margin: 1% 0 0 0;
    color: #999;
    text-align: center;
    background-color: #f9f9f9;
    border-top: 1px solid #e5e5e5;
}
</style>

<!-- JQuery -->
<script src="<?php echo $this->basePath() ?>/public/common/jquery/jquery.min.js"></script>
<!-- Bootstrap -->
<script src="<?php echo $this->basePath() ?>/public/common/bootstrap3/js/bootstrap.min.js"></script>

</head>

<body>

<noscript>
    <div>
        <h1>Attenzione: javascript disabilitato</h1>
        <div>&Egrave; stato rilevato che il browser in uso ha javascript disabilitato. Consigliamo di abilitarlo o alcune funzioni del sito non saranno visibili.</div>
    </div>
</noscript>

<div class="container">
	<div class="row clearfix">
		<div class="col-md-12 column">
			<div class="row clearfix">
                            <div class="col-xs-12 col-md-8"><a href="<?php echo $this->basePath() ?>/" title="<?php echo $this->sitename ?>"><img src="<?php echo $this->basePath() ?>/<?php echo $this->imagedir ?>logo.jpg" alt="<?php echo $this->sitename ?>"></a></div>
                            <div class="col-xs-6 col-md-4"><p class="pull-right"><span class="label label-primary">Pescheria Spano - San Teodoro - Sardegna</span></p></div>

                            <div class="col-md-8 column">

                            </div>
                            <div class="col-md-4 column"></div>
			</div>
			<nav class="navbar navbar-default" role="navigation">
                            
                            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                                <ul class="nav navbar-nav">
                                    <li class="active"><a href="<?php echo $this->basePath() ?>/" title="Torna all'home page">Home</a></li>
                                    <?php if ($this->preloadResponse): ?>
                                    <?php foreach($this->preloadResponse as $key => $value): ?>
                                        <?php foreach($value as $post): ?>
                                        <li><a href="<?php echo $this->basepath().$post['linkDetails'] ?>" title="<?php echo $post['title'] ?>"><?php echo $post['title'] ?></a></li>
                                        <?php endforeach; ?>
                                    <?php endforeach; ?>
                                    <?php endif; ?>
                                   <li><a href="#" title="Galleria fotografica">Foto</a></li>
                                   <li><a href="<?php echo $this->basepath() ?>/contatti/invia-messaggio/" title="Inviaci un messaggio">Contatti</a></li>
                                </ul>
                            </div>

			</nav>
			
                        <!--
			<div class="carousel slide" id="carousel-216645">
				<ol class="carousel-indicators">
					<li class="active" data-slide-to="0" data-target="#carousel-216645">
					</li>
					<li data-slide-to="1" data-target="#carousel-216645">
					</li>
					<li data-slide-to="2" data-target="#carousel-216645">
					</li>
				</ol>
				<div class="carousel-inner">
					<div class="item active">
						<img alt="" src="http://lorempixel.com/1600/500/sports/1">
						<div class="carousel-caption">
							<h4>
								First Thumbnail label
							</h4>
							<p>
								Cras justo odio, dapibus ac facilisis in, egestas eget quam. Donec id elit non mi porta gravida at eget metus. Nullam id dolor id nibh ultricies vehicula ut id elit.
							</p>
						</div>
					</div>
					<div class="item">
						<img alt="" src="http://lorempixel.com/1600/500/sports/2">
						<div class="carousel-caption">
							<h4>
								Second Thumbnail label
							</h4>
							<p>
								Cras justo odio, dapibus ac facilisis in, egestas eget quam. Donec id elit non mi porta gravida at eget metus. Nullam id dolor id nibh ultricies vehicula ut id elit.
							</p>
						</div>
					</div>
					<div class="item">
						<img alt="" src="http://lorempixel.com/1600/500/sports/3">
						<div class="carousel-caption">
							<h4>
								Third Thumbnail label
							</h4>
							<p>
								Cras justo odio, dapibus ac facilisis in, egestas eget quam. Donec id elit non mi porta gravida at eget metus. Nullam id dolor id nibh ultricies vehicula ut id elit.
							</p>
						</div>
					</div>
				</div> <a class="left carousel-control" href="#carousel-216645" data-slide="prev"><span class="glyphicon glyphicon-chevron-left"></span></a> <a class="right carousel-control" href="#carousel-216645" data-slide="next"><span class="glyphicon glyphicon-chevron-right"></span></a>
			</div>
			-->

                        <?php
                        // main contents
                        echo $this->partial($this->templatePartial);
                        ?>
		</div>
	</div>
</div>

<footer class="footer">
    <p>&copy; <?php echo date("Y"); ?> <strong>Pescheria Spano - San Teodoro - San Teodoro - Sardegna - Italia</strong><br>
        Tel: 0784 865933 - 0368 498537 - Email: <a href="mailto:pescheriaspano&#64;alice.it?subject=Contatto da sito Pescheria Spano">pescheriaspano&#64;alice.it</a></p>
    <p> <a href="http://validator.w3.org/check?uri=referer" title="Validate HTML">Valid HTML5</a> - Credits: <a href="http://www.kronoweb.it" target="_blank">Kronoweb</a></p>
    <p>&nbsp;</p>
</footer>

<script>  
jQuery(document).ready(function() {

});
</script>

<?php echo $this->inlineScript() ?>
</body>
</html>