<?php

$sm = $this->getHelperPluginManager()->getServiceLocator();
$currentRoute = $sm->get('Application')->getMvcEvent()->getRouteMatch()->getMatchedRouteName();

if (!$this->hideBreadcrumb):
    echo $this->render($this->formDataCommonPath.'breadcrumb.phtml');
endif;

if (!isset($this->formControlSpanWidth)): $this->formControlSpanWidth = 10; endif;
if (!isset($this->formLabelSpanWidth)): $this->formLabelSpanWidth = 2; endif;

if (!$this->form):
?>
    <div class="alert alert-danger">
        <h4>Errore verificato</h4>
        <div>Impossibile visualizzare il form: oggetto form non rilevato</div>
    </div>
<?php else: ?>
    <div id="formcontainer">

        <div id="formTitle">
            <h3><?php echo $this->formTitle ?></h3>
        </div>

        <?php if ( $this->alboRevisionWarning ): ?>
        <div class="alert alert-warning">
            <h4><i class="fa fa-pencil-square-o"></i> Si vuole effettuare oltre ad una visura la modifica dell'articolo?</h4>
            <p>Se non vuoi fare nessuna modifica, non dare conferma.</p>
            <p>Se dai conferma, l'atto verr&agrave; momentaneamente oscurato per consentire successivamente, terminato il ciclo di rettifica modificando anche la sezione Allegati, di tornare visibile on-line.</p>
            <p><strong>Data rettifica:</strong> <?php echo date("d-m-Y") ?></p>
            <p><strong>Numero \ Anno</strong> <?php echo $this->alboNumeroAtto ?> / <?php echo $this->alboAnnoAtto ?></p>
        </div>
        <?php else: ?>
            <?php if (!empty($this->formDescription)): ?>
                <p><?php echo $this->formDescription ?></p>
            <?php endif; ?>
        <?php endif; ?>

        <?php
            echo $this->partial(
                $this->formDataCommonPath.'formdata_form_elements.phtml',
                array(
                    'form'                  => $this->form,
                    'formAction'            => $this->formAction,
                    'formTitle'             => $this->formTitle,
                    'formDescription'       => $this->formDescription,
                    'formControlSpanWidth'  => $this->formControlSpanWidth,
                    'formLabelSpanWidth'    => $this->formLabelSpanWidth,
                    'CKEditorField'         => $this->CKEditorField,
                    'noCKEditor'            => $this->noCKEditor,
                )
            );

            if ($this->showRolePermissionsTemplate):
                echo $this->partial(
                    $this->templateDir.'users/_roles-permissions-handler.phtml',
                    array(
                        'roleName'    => $this->roleName,
                        'acl'         => $this->acl,
                        'permissions' => $this->permissions,
                        'adminAccess' => $this->adminAccess,
                        'templateDir' => $this->templateDir,
                    )
                );
            endif;
        ?>

        <div class="form-group">
            <label class="col-sm-<?php echo $this->formLabelSpanWidth ?> control-label">&nbsp;</label>
            <div class="col-sm-<?php echo $this->formControlSpanWidth ?>"><input type="submit" name="submit" id="submit" title="Clicca per inviare i dati del form" value="<?php echo $this->submitButtonValue ? $this->submitButtonValue : "Conferma"; ?>" class="btn btn-primary" onclick="javascript:refreshEditor();<?php if ($this->hideOnSubmit): ?>  document.getElementById('formcontainer').style.display='none'<?php endif ?>"></div>
        </div>

        <div class="form-group">
            <label class="col-sm-<?php echo $this->formLabelSpanWidth ?> control-label">&nbsp;</label>
            <div class="col-sm-<?php echo $this->formControlSpanWidth ?>">
                <label>* Campi obbligatori</label>
            </div>
        </div>

        <?php echo $this->form()->closeTag($this->form); ?>
    </div>

    <div id="formDataLoading" class="alert alert-warning" style="display: none">
        <h1>Attendere: elaborazione dati in corso...</h1>
    </div>

    <div id="formDataResponse"></div>

    <!-- Modal file too large -->
    <div class="modal fade" id="fileTooLarge" tabindex="-1" role="dialog" aria-labelledby="FileTooLargeModal" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content panel-danger">

                <div class="modal-header panel-heading">
                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                    <h4 class="modal-title" id="deleteModalLabel"><strong>File troppo grande</strong></h4>
                </div>

                <form action="" method="post" id="frmDeleteModal">
                    <div class="modal-body">
                        <p><strong>Attenzione:</strong> il file selezionato &egrave; troppo grande. Selezionare un file pi&ugrave; piccolo o non sar&agrave; possibile procedere.</p>

                        <input type="hidden" name="deleteId" id="deleteId" value="" />
                    </div>

                    <div class="modal-footer">
                        <button type="button" class="btn btn-default" data-dismiss="modal">Chiudi</button>
                    </div>
                </form>

            </div>
        </div>
    </div>

    <!-- Modal extension file not allowed -->
    <div class="modal fade" id="extensionNotAllowed" tabindex="-1" role="dialog" aria-labelledby="extensionNotAllowedModal" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content panel-danger">

                <div class="modal-header panel-heading">
                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                    <h4 class="modal-title" id="deleteModalLabel"><strong>Estensione file non consentita</strong></h4>
                </div>

                <form action="" method="post" id="frmDeleteModal">
                    <div class="modal-body">
                        <p><i class="fa fa-exclamation-triangle"></i> <strong>Attenzione:</strong> l'estensione del file selezionato non &egrave; consentita.</p>
                        <p><strong>Immagini consentite:</strong> jpg, jpeg, png, gif</p>
                        <p>Inserire immagini sufficientemente grandi</p>

                        <input type="hidden" name="deleteId" id="deleteId" value="" />
                    </div>

                    <div class="modal-footer">
                        <button type="button" class="btn btn-default" data-dismiss="modal">Chiudi</button>
                    </div>
                </form>

            </div>
        </div>
    </div>

    <script>
        $('.passwordStrength').keyup(function(e) {
            var strongRegex = new RegExp("^(?=.{8,})(?=.*[A-Z])(?=.*[a-z])(?=.*[0-9])(?=.*\\W).*$", "g");
            var mediumRegex = new RegExp("^(?=.{7,})(((?=.*[A-Z])(?=.*[a-z]))|((?=.*[A-Z])(?=.*[0-9]))|((?=.*[a-z])(?=.*[0-9]))).*$", "g");
            var enoughRegex = new RegExp("(?=.{6,}).*", "g");
            if (false == enoughRegex.test($(this).val())) {
                /* $('#pass-strength-result').className = 'passMorechars'; */
                $('#pass-strength-result').html('<span class="passMorechars">Troppi pochi caratteri!</span>');
            } else if (strongRegex.test($(this).val())) {
                $('#pass-strength-result').html('<span class="passSuccess">Forte!</span>');
            } else if (mediumRegex.test($(this).val())) {
                $('#pass-strength-result').html('<span class="passMedium">Media!</span>');
            } else {
                $('#pass-strength-result').html('<span class="passError">Password non sicura!</span>');
            }
            return true;
        });
        /* Users Roles JS */
        $('#adminAccess').change(function() {
            if ($(this).val()==1) {
                $('#permissionsContainer').show();
            } else {
                $('#permissionsContainer').hide();
            }
        });

        $('#btnSelectAll').click(function() {
            $('input[type=checkbox]').prop('checked', 'checked');
        });

        $('#btnDeselectAll').click(function() {
            $('input[type=checkbox]').prop('checked', '');
        });

        <?php if ($this->imageValidation): ?>
        /* Check File size and extension */
        $('#image').bind('change', function() {
            if (this.files[0].size > 10485760) {
                $('#fileTooLarge').modal(); /* open modal */
                $('#submit').prop("disabled", true); /* disable submit button */
            } else {
                $('#submit').prop("disabled", false);

                /* Check file extension */
                var filename = $("#image").val();
                var extension = filename.split('.').pop().toLowerCase();

                if (extension == filename) {
                    extension = '';
                } else {
                    extension = extension.toLowerCase();
                }

                switch (extension) {
                    case 'jpg': case 'jpeg': case 'png': case 'gif':
                        $('#submit').prop("disabled", false);
                    break;

                    default:
                        $('#submit').prop("disabled", true);
                        $('#extensionNotAllowed').modal();
                    break;
                }
            }
        });
        <?php endif; ?>

        <?php if (isset($this->CKEditorField)): ?>
            <?php if ( is_array($this->CKEditorField) ): ?>
                <?php foreach($this->CKEditorField as $ckEditorField): ?>
                /* CKEditor and CKFinder integration (multiple) */
                var editor = CKEDITOR.replace( '<?php echo $ckEditorField ?>', {
                    filebrowserBrowseUrl : '<?php echo $this->basepath() ?>/public/backend/javascript/ckfinder/ckfinder.html',
                    filebrowserImageBrowseUrl : '<?php echo $this->basepath() ?>/public/backend/javascript/ckfinder/ckfinder.html?type=Images',
                    filebrowserFlashBrowseUrl : '<?php echo $this->basepath() ?>/public/backend/javascript/ckfinder/ckfinder.html?type=Flash',
                    filebrowserUploadUrl : '<?php echo $this->basepath() ?>/public/backend/javascript/ckfinder/core/connector/php/connector.php?command=QuickUpload&type=Files',
                    filebrowserImageUploadUrl : '<?php echo $this->basepath() ?>/public/backend/javascript/ckfinder/core/connector/php/connector.php?command=QuickUpload&type=Images',
                    filebrowserFlashUploadUrl : '<?php echo $this->basepath() ?>/public/backend/javascript/ckfinder/core/connector/php/connector.php?command=QuickUpload&type=Flash'
                    /*, filebrowserWindowWidth : '1000', filebrowserWindowHeight : '700' */
                });
                CKFinder.setupCKEditor( editor, '../' );
                <?php endforeach; ?>
            <?php elseif(is_string($this->CKEditorField)): ?>
            /* CKEditor and CKFinder integration (single) */
            var editor = CKEDITOR.replace( '<?php echo $this->CKEditorField ?>', {
                filebrowserBrowseUrl : '<?php echo $this->basepath() ?>/public/backend/javascript/ckfinder/ckfinder.html',
                filebrowserImageBrowseUrl : '<?php echo $this->basepath() ?>/public/backend/javascript/ckfinder/ckfinder.html?type=Images',
                filebrowserFlashBrowseUrl : '<?php echo $this->basepath() ?>/public/backend/javascript/ckfinder/ckfinder.html?type=Flash',
                filebrowserUploadUrl : '<?php echo $this->basepath() ?>/public/backend/javascript/ckfinder/core/connector/php/connector.php?command=QuickUpload&type=Files',
                filebrowserImageUploadUrl : '<?php echo $this->basepath() ?>/public/backend/javascript/ckfinder/core/connector/php/connector.php?command=QuickUpload&type=Images',
                filebrowserFlashUploadUrl : '<?php echo $this->basepath() ?>/public/backend/javascript/ckfinder/core/connector/php/connector.php?command=QuickUpload&type=Flash'
                /*, filebrowserWindowWidth : '1000', filebrowserWindowHeight : '700' */
            });
            CKFinder.setupCKEditor( editor, '../' );
            <?php endif; ?>

        <?php endif; ?>

        function refreshEditor() {
            for (instance in CKEDITOR.instances) {
                CKEDITOR.instances[instance].updateElement();
            }
        }

        <?php if ($currentRoute=='admin/blogs-form'): ?>
        /* Check File size and extension */
        $('#image').bind('change', function() {
            if (this.files[0].size > 10485760) {
                $('#fileTooLarge').modal(); /* open modal */
                $('#submit').prop("disabled", true); /* disable submit button */
            } else {
                $('#submit').prop("disabled", false);

                /* Check File Extension */
                var filename = $("#file_input").val();
                var extension = $('#image').val().split('.').pop().toLowerCase();

                if (extension == filename) {
                    extension = '';
                } else {
                    extension = extension.toLowerCase();
                }

                switch (extension) {
                    case 'jpg': case 'jpeg': case 'png': case 'gif':
                        $('#submit').prop("disabled", false);
                    break;

                    default:
                        $('#submit').prop("disabled", true);
                        $('#extensionNotAllowed').modal();
                    break;
                }
            }
        });
        <?php endif; ?>
    </script>
<?php
endif;
