<ul class="breadcrumb">
    <li><a href="<?php echo $this->url('admin', array('lang'=>'it')); ?>" title="Home page">Home</a> <span class="divider"></span></li>
    <li><a href="#" title="<?php echo $this->moduleName ?>"><?php echo $this->moduleName ?></a></li>
    <li class="active">Invio atto ad ente terzo</li>
</ul>

<h2>Invio atto ad ente terzo</h2>

<div>Articolo da inviare ad altro ente</div>

<div>&nbsp;</div>

<h3><?php echo $this->titolo ?></h3>

<div>&nbsp;</div>

<?php

// $form->setAttribute('action', $this->url('contact/process'));
$this->form->setAttribute('method', 'post');
$this->form->setAttribute('role', 'form');
$this->form->setAttribute('class', 'form-horizontal');
$this->form->prepare();

echo $this->form()->openTag($this->form);

echo $this->render($this->formDataCommonPath.'formdata_form_elements.phtml');

?>
<div class="form-group">
    <label for="submit" class="col-sm-2 control-label"></label>
    <div class="col-sm-10">
        <input name="submit" type="submit" id="submit" class="btn btn-primary" value="Invia">
    </div>
</div>
<?php

echo $this->form()->closeTag();
