<?php

$form = $this->form;
$form->prepare();

$form->setAttribute('action', '');
$form->setAttribute('method', 'post');
$form->setAttribute('role', 'form');
$form->setAttribute('class', 'form-horizontal');

$formLabel = $this->plugin('formLabel');

echo $this->form()->openTag($this->form);

foreach ($this->form as $element):
    $attributes = $element->getAttributes();

    echo $this->formElementErrors($element, array(
            'class' => "formElementUlList",
        )
    );

    if ($attributes['name'] == 'csrf'):
        echo $this->formElement($element);
    elseif ($attributes['type'] == 'submit'):
    ?>
    <label for="<?php echo $attributes['id'] ?>">
        <?php
        $element->setAttribute('class', 'button primary tiny');
        echo $this->formElement($element);
        ?>
    </label>
    <?php else: ?>
        <label for="<?php echo $attributes['id'] ?>"><?php echo $element->getLabel() ?>: <?php  echo $this->formElement($element); ?></label>
    <?php
    endif;
endforeach;

?>
<label>* Campi obbligatori</label>
<?php

echo $this->form()->closeTag();
