<?php if (!empty($this->records)): ?>

    <ul class="breadcrumbs">
        <li><a href="<?php echo $this->basepath() ?>" title="Torna all'home page">Home</a></li>
        <li class="current"><?php echo $this->records[0]['nomeSezione'] ?></li>
        <li class="current"><?php echo html_entity_decode($this->records[0]['nomeSottosezione'], ENT_COMPAT, 'UTF-8') ?></li>
    </ul>

    <?php foreach($this->records as $record): ?>

        <div class="contentTitle">
            <h2><?php echo html_entity_decode($record['titolo'], ENT_COMPAT, 'UTF-8') ?></h2>
        </div>

        <?php if (isset($record['sommario'])): ?>
        <div><?php echo utf8_encode($record['sommario']) ?></div>
        <?php endif; ?>

        <div><?php echo utf8_encode($record['testo']); ?></div>

        <?php if (!empty($record['attachments'])): ?>
            <h3>Allegati</h3>
            <?php foreach($record['attachments'] as $attachment): ?>
            <div>
                <a href="<?php echo $this->url('attachments-sthree-download', array(
                    'type' => 'contenuti',
                    'id' => $attachment['id'])); ?>" title="Scarica allegato <?php echo $attachment['name'] ?>">
                    <img src="<?php echo $this->basepath() ?>/public/common/icons/attachments/<?php echo $attachment['image']; ?>" alt="Icon tipo file per <?php echo $attachment['name'] ?>">
                    <?php echo $attachment['name'] ?>
                </a> (<?php echo $attachment['size'] ?> Kb)
            </div>
            <?php endforeach ?>
        <?php endif; ?>

        <br>
        <br>
        <p class="text-right">Esporta: <a href="#" title="Esporta in formato testo"><img src="<?php echo $this->basepath() ?>/public/common/icons/txt.png" alt="Icona file di testo"></a>
            <a href="#" title="Esporta in formato PDF"><img src="<?php echo $this->basepath() ?>/public/common/icons/pdf.gif" alt="Icona PDF"></a>

            Condividi: <a href="https://www.facebook.com/sharer/sharer.php?u=<?php echo $this->currentUrl; ?>" title="Condividi su facebook" onclick="javascript:window.open(this.href, '', 'menubar=no,toolbar=no,resizable=yes,scrollbars=yes,height=300,width=600');return false;"><img src="<?php echo $this->basepath() ?>/public/common/icons/facebook.gif" alt="Icona Facebook"></a>
            <a href="http://twitter.com/share?text=<?php echo urlencode($record['titolo']) ?>&amp;url=<?php echo $this->currentUrl; ?>"><img src="<?php echo $this->basepath() ?>/public/common/icons/twitter.gif" alt="Icona Twitter"></a>
            <a href="https://plus.google.com/share?url=<?php echo $this->currentUrl; ?>" title="Condividi su google plus"><img src="<?php echo $this->basepath() ?>/public/common/icons/google-plus.png" alt="Icona Google Plus"></a>
        </p>
        <hr>
    <?php endforeach; ?>

<?php else: ?>
    <div class="panel callout">
        <h2>Nessun contenuto presente</h2>
    </div>
<?php endif; ?>
