<ul class="breadcrumb">
    <li><a href="<?php echo $this->basepath ?>/" title="Home page">Home</a> <span class="divider"></span></li>
    <li class="active">Foto</li>
</ul>

<h3>Galleria Fotografica (demo)</h3>

<!-- TODO: Selezione Categorie -->

<?php foreach($this->foto as $foto): ?>
    <!-- <div>&raquo; <?php echo $foto['titolo']; ?></div> -->
<?php endforeach; ?>

<p>Immagini in miniatura senza bordo, nessuno stile</p>
<img src="<?php echo $this->basePath() ?>/<?php echo $this->imagedir ?>cagliari.jpg" alt="">
<img src="<?php echo $this->basePath() ?>/<?php echo $this->imagedir ?>osilo.jpg" alt="">
<img src="<?php echo $this->basePath() ?>/<?php echo $this->imagedir ?>san-nicola.jpg" alt="">
<img src="<?php echo $this->basePath() ?>/<?php echo $this->imagedir ?>castello-sassari.jpg" alt="">
<img src="<?php echo $this->basePath() ?>/<?php echo $this->imagedir ?>ploaghe.jpg" alt="">

<br>
<p>Immagini in miniatura con bordo arrotondato</p>
<img src="<?php echo $this->basePath() ?>/<?php echo $this->imagedir ?>cagliari.jpg" alt="" class="img-rounded">
<img src="<?php echo $this->basePath() ?>/<?php echo $this->imagedir ?>osilo.jpg" alt="" class="img-rounded">
<img src="<?php echo $this->basePath() ?>/<?php echo $this->imagedir ?>san-nicola.jpg" alt="" class="img-rounded">
<img src="<?php echo $this->basePath() ?>/<?php echo $this->imagedir ?>castello-sassari.jpg" alt="" class="img-rounded">
<img src="<?php echo $this->basePath() ?>/<?php echo $this->imagedir ?>ploaghe.jpg" alt="" class="img-rounded">

<br><br>
<p>Immagini in miniatura con bordo</p>
<img src="<?php echo $this->basePath() ?>/<?php echo $this->imagedir ?>cagliari.jpg" alt="" class="img-thumbnail">
<img src="<?php echo $this->basePath() ?>/<?php echo $this->imagedir ?>osilo.jpg" alt="" class="img-thumbnail">
<img src="<?php echo $this->basePath() ?>/<?php echo $this->imagedir ?>san-nicola.jpg" alt="" class="img-thumbnail">
<img src="<?php echo $this->basePath() ?>/<?php echo $this->imagedir ?>castello-sassari.jpg" alt="" class="img-thumbnail">
<img src="<?php echo $this->basePath() ?>/<?php echo $this->imagedir ?>ploaghe.jpg" alt="" class="img-thumbnail">

<br><br>
<p>Immagini in miniatura a form di cerchio</p>
<img src="<?php echo $this->basePath() ?>/<?php echo $this->imagedir ?>cagliari.jpg" alt="" class="img-circle">
<img src="<?php echo $this->basePath() ?>/<?php echo $this->imagedir ?>osilo.jpg" alt="" class="img-circle">
<img src="<?php echo $this->basePath() ?>/<?php echo $this->imagedir ?>san-nicola.jpg" alt="" class="img-circle">
<img src="<?php echo $this->basePath() ?>/<?php echo $this->imagedir ?>castello-sassari.jpg" alt="" class="img-circle">
<img src="<?php echo $this->basePath() ?>/<?php echo $this->imagedir ?>ploaghe.jpg" alt="" class="img-circle">
