<ul class="breadcrumb">
    <li><a href="#" title="Home page">Home</a> <span class="divider"></span></li>
    <li class="active">Foto</li>
</ul>

<h3>Galleria Fotografica (demo)</h3>

<br>
<p>Immagini in miniatura</p>
<img src="<?php echo $this->basePath() ?>/<?php echo $this->imagedir ?>cagliari.jpg" alt="" class="img-rounded">
<img src="<?php echo $this->basePath() ?>/<?php echo $this->imagedir ?>osilo.jpg" alt="" class="img-rounded">
<img src="<?php echo $this->basePath() ?>/<?php echo $this->imagedir ?>san-nicola.jpg" alt="" class="img-rounded">
<img src="<?php echo $this->basePath() ?>/<?php echo $this->imagedir ?>castello-sassari.jpg" alt="" class="img-rounded">
<img src="<?php echo $this->basePath() ?>/<?php echo $this->imagedir ?>ploaghe.jpg" alt="" class="img-rounded">

<br><br>
<p>Immagini in miniatura con bordo</p>
<img src="<?php echo $this->basePath() ?>/<?php echo $this->imagedir ?>cagliari.jpg" alt="" class="img-thumbnail">
<img src="<?php echo $this->basePath() ?>/<?php echo $this->imagedir ?>osilo.jpg" alt="" class="img-thumbnail">
<img src="<?php echo $this->basePath() ?>/<?php echo $this->imagedir ?>san-nicola.jpg" alt="" class="img-thumbnail">
<img src="<?php echo $this->basePath() ?>/<?php echo $this->imagedir ?>castello-sassari.jpg" alt="" class="img-thumbnail">
<img src="<?php echo $this->basePath() ?>/<?php echo $this->imagedir ?>ploaghe.jpg" alt="" class="img-thumbnail">

<br><br>
<p>Immagini in miniatura a form di cerchio</p>
<img src="<?php echo $this->basePath() ?>/<?php echo $this->imagedir ?>cagliari.jpg" alt="" class="img-circle">
<img src="<?php echo $this->basePath() ?>/<?php echo $this->imagedir ?>osilo.jpg" alt="" class="img-circle">
<img src="<?php echo $this->basePath() ?>/<?php echo $this->imagedir ?>san-nicola.jpg" alt="" class="img-circle">
<img src="<?php echo $this->basePath() ?>/<?php echo $this->imagedir ?>castello-sassari.jpg" alt="" class="img-circle">
<img src="<?php echo $this->basePath() ?>/<?php echo $this->imagedir ?>ploaghe.jpg" alt="" class="img-circle">