<ul class="breadcrumb">
    <li><a href="<?php echo $this->basepath() ?>/admin/main/" title="Home page">Home</a> <span class="divider"></span></li>
    <li class="active"><?php echo $this->tableTitle ?></li>
</ul>

<?php
$columnsToPrint = '';
foreach($this->columns as $columns):
    $columnsToPrint .= '<th>'.$columns.'</th>';
endforeach;
?>

<h3><?php echo $this->tableTitle ?></h3>
<p><?php echo $this->tableDescription ?></p>

<table cellpadding="0" cellspacing="0" border="0" class="display" id="example" width="100%">
    <thead>
        <tr>
        <?php echo $columnsToPrint ?>
        </tr>
    </thead>
    <tbody>
        <?php foreach($this->records as $records): ?>
        <tr class="odd gradeX">
            <?php
            foreach($records as $record):
                ?><td><?php echo $record ?></td><?php
            endforeach;
            ?>
        </tr>
        <?php endforeach; ?>
    </tbody>
    <tfoot>
        <tr>
            <?php echo $columnsToPrint  ?>
        </tr>
    </tfoot>
</table>