<?php echo $this->render('backend/templates/'.$this->template_backend.'datatable/datatable_breadcrumb.phtml'); ?>

<ul class="nav nav-tabs" role="tablist">
    <li class="active"><a href="#home" role="tab" data-toggle="tab">Elenco articoli</a></li>
    <li><a href="#search" role="tab" data-toggle="tab">Ricerca</a></li>
    <li><a href="#export" role="tab" data-toggle="tab">Esportazione dati</a></li>
</ul>

<div class="tab-content">
    <div class="tab-pane active" id="home">
        <?php echo $this->render('backend/templates/common/datatables_zend_pagination.phtml'); ?>
    </div>
    
    <div class="tab-pane" id="search">
        <h3>Ricerca</h3>
        <div class="container">
            <?php
            echo $this->partial('backend/templates/common/formdata_common.phtml', array(
                    'form'                  => $this->form,
                    'formAction'            => $this->formAction,
                    'formTitle'             => $this->formTitle,
                    'formDescription'       => $this->formDescription,
                    'formControlSpanWidth'  => isset($this->formControlSpanWidth) ? $this->formControlSpanWidth : 10,
                    'formLabelSpanWidth'    => isset($this->formLabelSpanWidth) ? $this->formLabelSpanWidth : 2,
                )
            );
            ?>
        </div>
    </div>
    
    <div class="tab-pane" id="export">

        <h3>Esportazione dati</h3>
        <div class="container">
            <div class="alert alert-warning">
                <h4>In costruzione</h4>
                <p>Form esportazione dati in costruzione</p>
            </div>
        </div>

    </div>
</div>
