<?php echo $this->render('backend/templates/'.$this->template_backend.'datatable/datatable_breadcrumb.phtml'); ?>

<ul class="nav nav-tabs" role="tablist">
    <li class="active"><a href="#home" role="tab" data-toggle="tab">Elenco atti</a></li>
    <li><a href="#search" role="tab" data-toggle="tab">Ricerca</a></li>
    <li><a href="#export" role="tab" data-toggle="tab">Esportazione dati</a></li>
</ul>

<div class="tab-content">
    <div class="tab-pane active" id="home">
        <?php echo $this->render('backend/templates/common/datatables_zend_pagination.phtml'); ?>
    </div>
    
    <div class="tab-pane" id="search">
        <h3>Ricerca</h3>
        <div class="container">
            <?php
            $form = $this->formSearch;

            $form->setAttribute('action',   $this->serverUrl(true));
            $form->setAttribute('method',   'post');
            $form->setAttribute('role',     'form');
            $form->setAttribute('class',    'form-horizontal');
            $form->setAttribute('id',       'search-form');

            $form->prepare();

            echo $this->form()->openTag($this->formSearch);

            //$form->get('titolo')->setAttribute('class', 'form-control');
            $form->get('mese')->setAttribute('class', 'form-control');
            //$form->get('anno')->setAttribute('class', 'form-control');
            //$form->get('sezione')->setAttribute('class', 'form-control');
            $form->get('numero_atto')->setAttribute('class', 'form-control');
            $form->get('numero_progressivo')->setAttribute('class', 'form-control');
            $form->get('search')->setAttribute('class', 'btn btn-primary');
 
            $form->prepare();
        
            echo $this->form()->openTag($form);

            ?>
            <div class="form-group">
                <label for="<?php echo $form->get('numero_atto')->getAttribute('id'); ?>" class="col-sm-2 control-label">Num. atto:</label>
                <div class="col-sm-4">
                    <?php echo $this->formElement($form->get('numero_atto')); ?>
                </div>

                <label for="<?php echo $form->get('numero_progressivo')->getAttribute('id'); ?>" class="col-sm-2 control-label">Num. Progressivo:</label>
                <div class="col-sm-4">
                    <?php echo $this->formElement($form->get('numero_progressivo')); ?>
                </div>
            </div>

            <div class="form-group">
                <label for="<?php echo $form->get('mese')->getAttribute('id'); ?>" class="col-sm-2 control-label">Atti a partire da:</label>
                <div class="col-sm-4">
                    <?php echo $this->formElement($form->get('mese')); ?>
                </div>

                <div class="col-sm-4">
                    <?php // echo $this->formElement($form->get('anno')); ?>
                </div>
            </div>
            
            <div class="form-group">
                <label class="col-sm-2 control-label">&nbsp;</label>
                <div class="col-sm-8"><?php echo $this->formElement($form->get('expired')); ?>
                <label for="<?php echo $form->get('expired')->getAttribute('id') ?>" style="width: 80%"> <?php echo $this->formLabel($form->get('expired')) ?></label>
                </div>
            </div>
            
            <div class="form-group">
                <label class="col-sm-2 control-label">&nbsp;</label>
                <div class="col-sm-8">
                    <?php echo $this->formElement($form->get('search')); ?>
                </div>
            </div>
            <?php echo $this->form()->closeTag(); ?>
            
            </div>
    </div>
    
    <div class="tab-pane" id="export">
        <h3>Esportazione dati</h3>
        <div class="container">
            <div class="alert alert-warning"><h4>In costruzione</h4><p>Form esportazione dati in costruzione</p></div>
        </div>
        
        <h3>Feed RSS</h3>
        <ul>
            <li><a href="#" title="Feed Atti stato civile" target="_blank">Atti stato civile</a></li>
        </ul>
        
        <h3>API</h3>
        <ul>
            <li><a href="#" title="">JSON</a></li>
            <li><a href="#" title="">XML</a></li>
        </ul>
        
    </div>
</div>
