<?php echo $this->render('backend/templates/'.$this->template_backend.'datatable/datatable_breadcrumb.phtml'); ?>

<ul class="nav nav-tabs" role="tablist">
    <li class="active"><a href="#home" role="tab" data-toggle="tab"><i class="fa fa-list"></i> Elenco articoli</a></li>
    <li><a href="#search" role="tab" data-toggle="tab"><i class="fa fa-search"></i> Ricerca</a></li>
    <li><a href="#export" role="tab" data-toggle="tab"><i class="fa fa-external-link-square"></i> Esportazione dati</a></li>
</ul>

<div class="tab-content">
    <div class="tab-pane active" id="home">
        <?php echo $this->render('backend/templates/common/datatables_zend_pagination.phtml'); ?>
    </div>
    
    <div class="tab-pane" id="search">
        <h3>Ricerca contratti</h3>
        <div class="container">
        
        </div>
    </div>
    
    <div class="tab-pane" id="export">
        <h3>Esportazione dati</h3>
        <div class="container">
            <div class="alert alert-warning"><h4>In costruzione</h4><p>Form esportazione dati in costruzione</p></div>
        </div>
        
        <h3>Feed RSS</h3>
        <ul>
            <li><a href="#" title="Feed Bandi Contratti Pubblici" target="_blank">Bandi Contratti Pubblici</a></li>
        </ul>
        
        <h3>API Bandi contratti pubblici in formato</h3>
        <ul>
            <li><a href="#" title="Bandi contratti pubblici in formato JSON">JSON</a></li>
            <li><a href="#" title="Bandi contratti pubblici in formato XML">XML</a></li>
        </ul>
        
    </div>
</div>
