<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Gallery\Module'                        => __DIR__ . '/Module.php',
    'Gallery\Controller\GalleryController' => __DIR__ . '/src/Gallery/Controller/GalleryController.php',
    'GalleryTest\Framework\TestCase'        => __DIR__ . '/tests/Gallery/Framework/TestCase.php',
    'GalleryTest\SampleTest'                => __DIR__ . '/tests/Gallery/SampleTest.php',
);
