<h1>Editor configurazioni</h1>

<p>Opzioni principali applicazione.</p>

<div class="alert alert-warning">
    <h3>In costruzione</h3>
</div>

<?php if (isset($this->configs)): ?>
    <form class="form-horizontal">
    <?php foreach($this->configs as $config): ?>
        <?php if (in_array($config['name'], array('sitename', 'remotelink', 'description'))): ?>
        <div class="form-group">
            <label class="form-label col-sm-2"><?php echo $config['name'] ?></label>
            <div class="col-sm-4">
                <input type="text" name="config[][<?php echo $config['name'] ?>]" value="<?php echo $config['value'] ?>" class="form-control">
            </div>
        </div>
        <?php endif; ?>
    <?php endforeach; ?>
        <div class="form-group">
            <div class="col-sm-offset-2 col-sm-10">
                <button class="btn btn-primary">Modifica</button>
            </div>
        </div>
    </form>
<?php endif; ?>

<!--

TODO:
    Selezione configurazioni per lingua e canale

    Configurazioni da includere:

    Accessi Amazon S3 (riservato): amazon_s3_accesskey, amazon_s3_bucket, amazon_s3_secretkey
    SEO nome sito, descrizione
    Template frontend, Template backend
    project_frontend, project_backend
    remotelink??
    emailcontact, emailnoreply, emailwebmaster
    attachsizelimit
    atti_concessione_basiclayout
    contratti_pubblici_basiclayout
    amministrazione_trasparente_basiclayout
    amministrazione_trasparente_sottosezione_id   -> amm trasp id di partenza

    prodperpage  -> paging elementi per pagina

-->