<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Contacts\Module'                        => __DIR__ . '/Module.php',
    'Contacts\Controller\ContactsController' => __DIR__ . '/src/Contacts/Controller/ContactsController.php',
    'ContactsTest\Framework\TestCase'        => __DIR__ . '/tests/Contacts/Framework/TestCase.php',
    'ContactsTest\SampleTest'                => __DIR__ . '/tests/Contacts/SampleTest.php',
);
