<!doctype html>
<html>

<meta http-equiv="Content-Type" content="text/html; charset=utf-8">

<style>
    h1, h2 { margin-bottom: 30px; }
    p { margin-bottom: 10px }
    .text-center { text-align: center }
    .red { color: #c00c00 }
</style>

<body>

<h2><?php echo $this->sitename ?></h2>

<p>Documento generato il <?php echo date("d-m-Y") ?></p>

<br>

<p><b>Numero \ Anno:</b> <?php echo $this->record['progressivo'] ?> / <?php echo $this->record['anno'] ?></p>
<p><b>Beneficiario CF/PIVA:</b> <?php echo $this->record['beneficiario'] ?></p>
<p><b>Importo:</b> <?php echo $this->record['importo'] ?> &euro;</p>
<p><b>Modalit&agrave; Assegnazione</b> <?php echo $this->record['nomemodAssegnazione'] ?></p>
<p><b>Ufficio e responsabile del servizio</b> <?php echo $this->record['nomeSezione'].' '.$this->record['nomeResponsabileProc'] ?></p>
<p><b>Norma o titolo a base dell'attribuzione</b> <?php echo $this->record['titolo'] ?>

<br><br>

<p><?php echo date("Y").' '.$this->sitename ?></p>

</body>
</html>