<?php if (empty($records)): ?>
<div class="alert alert-warning">
    <?php if ($this->messageTitle): ?>
    <h1><?php echo $this->messageTitle ?></h1>
    <?php else: ?>
    <h1>Nessun dato in archivio</h1>
    <?php endif; ?>

    <?php if ($this->messageDescription): ?>
    <p><?php echo $this->messageDescription ?></p>
    <?php else: ?>
    <p>Nessun dato da elencare &egrave; stato trovato.</p>
    <?php endif; ?>
</div>
<?php else: ?>

<h3><?php echo $this->tableTitle ?></h3>

<p><?php echo $this->tableDescription ?></p>

<div class="table-responsive">
    <table class="table table-bordered" id="zf2-pagination-table">
    <thead>
        <tr>
            <?php foreach($this->columns as $column): ?>
                <?php if ( is_array($column) ): ?>
                <th style="width: <?php echo $column['width'] ?>"><?php echo $column['label'] ?></th>
                <?php else: ?>
                <th><?php echo $column ?></th>
                <?php endif; ?>
            <?php endforeach; ?>
        </tr>
    </thead>
    <tbody>
        <?php foreach($this->records as $records): ?>
        <tr class="odd gradeX">
            <?php foreach($records as $record): ?>
                <?php if (is_array($record)): ?>
                    <?php if ($record['type']=='updateButton'): ?>
                    <td><a href="<?php echo $record['href'] ?>" class="btn btn-lg" title="<?php echo $record['title'] ?>"><i class="fa fa-pencil"></i> </a></td>
                    <?php elseif($record['type']=='alboRettificaButton'): ?>
                    <td><a href="#alboRevisionModal" data-id="<?php echo $record['data-id'] ?>" class="open-alboRevisionModal btn btn-lg" title="Rettifica articolo"><i class="fa fa-edit"></i> </a></td>
                    <?php elseif($record['type']=='alboAnnulledButton'): ?>
                    <td colspan="4" valign="middle" class="text-center"><h4>ARTICOLO ANNULLATO</h4></td>
                    <!-- hidden fields to avoid js datatable error... -->
                    <td style="display: none">&nbsp;</td>
                    <td style="display: none">&nbsp;</td>
                    <td style="display: none">&nbsp;</td>
                    <?php elseif($record['type']=='alboAnnullButton'): ?>
                    <td><a href="#alboAnnullModal" data-id="<?php echo $record['data-id'] ?>" class="open-alboAnnullModal btn btn-lg icon-red" title="Annulla articolo"><i class="fa fa-ban"></i> </a></td>
                    <?php elseif($record['type']=='alboPublishButton'): ?>
                    <td><a href="#alboPublishModal" data-id="<?php echo $record['data-id'] ?>" class="open-alboPublishModal btn btn-lg" title="<?php echo (isset($record['title'])) ? $record['title'] : "Pubblica" ?>"><i class="fa fa-globe"></i> </a></td>
                    <?php elseif($record['type']=='activeButton'): ?>
                    <td><a href="<?php echo $record['href'] ?>" class="btn btn-lg icon-green" title="<?php echo (isset($record['title'])) ? $record['title'] : 'Attiva' ?>"><i class="fa fa-power-off"></i> </a></td>
                    <?php elseif($record['type']=='disableButton'): ?>
                    <td><a href="<?php echo $record['href'] ?>" class="btn btn-lg icon-red" title="<?php echo (isset($record['title'])) ? $record['title'] : 'Disattiva' ?>"><i class="fa fa-power-off"></i> </a></td>
                    <?php elseif($record['type']=='ignore'): ?>
                    <!-- No content -->
                    <?php elseif($record['type']=='noButton'): ?>
                    <td>&nbsp;</td>
                    <?php elseif($record['type']=='deleteButton'): ?>
                    <td><a href="#deleteModal" data-action="<?php echo $record['href'] ?>" data-id="<?php echo $record['data-id'] ?>" class="open-deleteModal btn btn-lg icon-red" title="Elimina"><i class="fa fa-times"></i> </a></td>
                    <?php elseif($record['type']=='homepagePutButton'): ?>
                    <td><a href="<?php echo $record['href'] ?>" class="btn btn-lg icon-green" title="Metti in home page"><i class="fa fa-home"></i> </a></td>
                    <?php elseif($record['type']=='homepageDelButton'): ?>
                    <td><a href="<?php echo $record['href'] ?>" class="btn btn-lg icon-red" title="Togli dalla home page"><i class="fa fa-home"></i> </a></td>
                    <?php elseif($record['type']=='tableButton'): ?>
                    <td><a href="#" class="btn btn-lg" title=""><i class="fa fa-table"></i> </a></td>
                    <?php elseif($record['type']=='attachButton'): ?>
                    <td><a href="<?php echo $record['href'] ?>" class="btn btn-lg icon-black" title="Gestione allegati"><i class="fa fa-paperclip"></i> </a></td>
                    <?php elseif($record['type']=='relatapdfButton'): ?>
                    <td><a href="<?php echo $record['href'] ?>" class="btn btn-lg icon-red" title="Genera documento relata di pubblicazione"><i class="fa fa-file-pdf-o"></i> </a></td>
                    <?php elseif($record['type']=='enteterzoButton'): ?>
                    <td><a href="<?php echo $record['href'] ?>" class="btn btn-lg icon-black" title="Invia ad ente terzo"><i class="fa fa-envelope-square"></i></a></td>
                    <?php endif; ?>
                <?php else: ?>
                <td<?php echo isset($record['class']) ? ' class="'.$record['class'].'"' : '' ?>>
                    <?php echo utf8_encode($record) ?>
                </td>
                <?php endif; ?>
            <?php endforeach; ?>
        </tr>
        <?php endforeach; ?>
    </tbody>
    </table>
</div>

<?php

if ( count($this->paginator) > 1 ):
    try {
        echo $this->paginationControl(
            $this->paginator,
            'sliding',
            'application/pagination/bootstrap.phtml',
            array(
                'route' => $this->route,
                'tablesetter' => $this->tablesetter,
                'lang'        => $this->lang ? $this->lang : 'it',
            )
        );
    } catch (Exception $e) {
        ?>
        <div class="alert alert-danger">
            <h3>Errore paginazione</h3>
            <p>Errore nella visualizzazione dei numeri di pagina: <?php echo $e->getMessage() ?></p>
        </div>
    <?php
    }
endif;

endif;

?>


<!-- Delete Modal -->
<div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="ConfirmDeleteModal" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content panel-danger">
            
            <div class="modal-header panel-heading">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                <h4 class="modal-title" id="deleteModalLabel"><strong>Conferma eliminazione?</strong></h4>
            </div>
            
            <form action="" method="post" id="frmDeleteModal">
                <div class="modal-body">
                    <p><strong>Attenzione:</strong> i dati di questo elemento e ad esso collegati verranno cancellati definitivamente e non sar&agrave; possibile recuperarli.</p>
                    
                    <input type="hidden" name="deleteId" id="deleteId" value="" />
                </div>

                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Annulla</button>
                    <button type="submit" class="btn btn-danger">Conferma</button>
                </div>
            </form>
            
        </div>
    </div>
</div>

<!-- Modale revisione articolo albo -->
<div class="modal fade" id="alboRevisionModal" tabindex="-1" role="dialog" aria-labelledby="alboRevisionModalAriaLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content panel-info">
            
            <div class="modal-header panel-heading">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                <h4 class="modal-title" id="alboRevisionModalLabel"><strong>Conferma revisione?</strong></h4>
            </div>
            
            <form action="" method="post">
                <div class="modal-body">
                    <p><strong>Attenzione:</strong> L'articolo &egrave; gi&agrave; stato pubblicato. Passare alla modalit&agrave; di revisione?</p>
                    <p>Una volta confermata la revisione, l'articolo non sar&agrave; visibile sul sito web pubblico per permettere di aggiungere o eliminare allegati e dovr&agrave; essere riattivato in questa sezione</p>

                    <input type="hidden" name="revisionId" id="revisionId" value="" />
                </div>

                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Annulla</button>
                    <button type="submit" class="btn btn-primary">Conferma</button>
                </div>
            </form>
            
        </div>
    </div>
</div>

<!-- Modale annullamento articolo albo -->
<div class="modal fade" id="alboAnnullModal" tabindex="-1" role="dialog" aria-labelledby="DisableArticleAlboPretorio" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content panel-danger">
            
            <div class="modal-header panel-heading">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                <h4 class="modal-title" id="alboAnnullModalLabel"><strong>Annulla articolo?</strong></h4>
            </div>
            
            <form action="" method="post">
                <div class="modal-body">
                    <p><strong>Attenzione:</strong> una volta annullato l'articolo non potr&agrave; pi&ugrave; essere ripristinato.</p>

                    <input type="hidden" name="annullId" id="annullId" value="" />
                </div>

                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Annulla</button>
                    <button type="submit" class="btn btn-danger">Conferma</button>
                </div>
            </form>
            
        </div>
    </div>
</div>

<!-- Modale conferma pubblicazione articolo albo -->
<div class="modal fade" id="alboPublishModal" tabindex="-1" role="dialog" aria-labelledby="alboPublishModalAlboAriaLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content panel-info">
            
            <div class="modal-header panel-heading">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                <h4 class="modal-title" id="alboPublishModalLabel"><strong>Pubblica articolo?</strong></h4>
            </div>
            
            <form action="" method="post">
                <div class="modal-body">
                    <p>L'articolo sar&agrave; visibile sul sito pubblico.</p>

                    <input type="hidden" name="publishId" id="publishId" value="" />
                </div>

                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Annulla</button>
                    <button type="submit" class="btn btn-primary">Conferma</button>
                </div>
            </form>
            
        </div>
    </div>
</div>

<script>
/* Force scroll for large tables */
function forceResponsiveTables() {
    var windowSize = $(window).width();
    if ($('.table-responsive > .table').length > 0) {
        $.each($('.table-responsive > .table'), function (index, value) {
            var thisTable = $(value);
            var tableSize = thisTable.width();
            var parent = thisTable.parent('.table-responsive');
            /* 768px is the default for bootstrap 3's responsive-table, modify if needed */
            if (windowSize <= 768) {
                parent.css('width', '').css('overflow-x', '').css('overflow-y', '').css('margin-bottom', '').css('border', '');
            } else {
                if (tableSize >= windowSize) {
                    // Change the border color based on the bootstrap theme colors
                    parent.css('width', '100%').css('overflow-x', 'scroll').css('overflow-y', 'hidden').css('margin-bottom', '15px').css('border', '1px solid #DDDDDD');
                } else {
                    parent.css('width', '').css('overflow-x', '').css('overflow-y', '').css('margin-bottom', '').css('border', '');
                }
            }
        });
    }
}

$(document).ready(function () {
    
    $(window).resize(forceResponsiveTables);
    
    forceResponsiveTables();
    
    $(".open-deleteModal").click(function(e) {
        e.preventDefault();

        var _self = $(this);

        var dataId = _self.data('id');
        var dataAction = _self.data('action');

        $("#deleteId").val(dataId);
        $('#frmDeleteModal').attr('action', dataAction);

        $(_self.attr('href')).modal('show');
    });
    
    $(".open-alboRevisionModal").click(function(e) {
        e.preventDefault();

        var _self = $(this);

        var dataId = _self.data('id');
        $("#revisionId").val(dataId); 

        $(_self.attr('href')).modal('show');
    });
    
    $(".open-alboPublishModal").click(function(e) {
        e.preventDefault();

        var _self = $(this);

        var dataId = _self.data('id');
        $("#publishId").val(dataId); 

        $(_self.attr('href')).modal('show');
    });
    
    $(".open-alboAnnullModal").click(function(e) {
        e.preventDefault();

        var _self = $(this);

        var dataId = _self.data('id');
        $("#annullId").val(dataId); 

        $(_self.attr('href')).modal('show');
    });
});
</script>
