<?php if (empty($records)): ?>
    <div class="alert alert-warning">
        <?php if ($this->messageTitle): ?>
        <h1><?php echo $this->messageTitle ?></h1>
        <?php else: ?>
        <h1>Nessun dato in archivio</h1>
        <?php endif; ?>

        <?php if ($this->messageDescription): ?>
        <p><?php echo $this->messageDescription ?></p>
        <?php else: ?>
        <p>Nessun dato da elencare &egrave; stato trovato.</p>
        <?php endif; ?>
    </div>
<?php else: ?>

    <h3><?php echo $this->tableTitle ?></h3>

    <p><?php echo $this->tableDescription ?></p>

    <?php echo $this->render($this->formDataCommonPath.'datatables_elements.phtml'); ?>
<?php
endif;