<?php if (empty($records)): ?>
    <div class="alert alert-warning" style="margin: 0; padding-top: 0">
        <?php if ($this->messageTitle): ?>
        <h1><?php echo $this->messageTitle ?></h1>
        <?php else: ?>
            <h3>Nessuna informazione trovata</h3>
        <?php endif; ?>

        <?php if ($this->messageDescription): ?>
            <p><?php echo $this->messageDescription ?></p>
        <?php else: ?>
            <p>Non &egrave; stata trovata nessuna informazione da elencare nella pagina corrente relativa al modulo richiesto.</p>
        <?php endif; ?>
    </div>
<?php else: ?>

    <h3><?php echo $this->tableTitle ?></h3>

    <p><?php echo $this->tableDescription ?></p>

    <?php echo $this->render($this->formDataCommonPath.'datatables_elements.phtml'); ?>
<?php
endif;