<div id="formcontainer">

<div id="formTitle"><h2><?php echo $this->formTitle ?></h2></div>
<p><?php echo $this->formDescription ?></p>
<?php

$this->form->prepare();

$form = $this->form;
$form->prepare();

$form->setAttribute('action',   $this->url('admin', array('lang' => 'it')).'formpost/'.$this->formAction );
$form->setAttribute('method',   'post');
$form->setAttribute('enctype',  'multipart/form-data');
$form->setAttribute('name',     'formData');
$form->setAttribute('id',       'formData');
$form->setAttribute('role',     'form');
$form->setAttribute('class',    'form-horizontal');

echo $this->form()->openTag($form);

if (!isset($this->formLabelSpanWidth)):
    $this->formLabelSpanWidth = 2;
endif;

if (!isset($this->formControlSpanWidth)):
    $this->formControlSpanWidth = 10;
endif;

foreach ($this->form as $element):
    $attributes = $element->getAttributes();
    echo $this->formElementErrors($element);
    if (isset($attributes['class']) and $attributes['class'] == 'wysiwyg'):
    ?>
    <div class="form-group">
        <div class="col-sm-12">
            <label><?php echo $element->getLabel() ?></label>
            <?php echo $this->formElement($element); ?>
        </div>
    </div>
    <?php
    elseif (isset($attributes['class']) and $attributes['class']=='DatePicker'):
    ?>
    <div class="form-group">
        <label for="<?php echo $attributes['id'] ?>" class="col-sm-<?php echo $this->formLabelSpanWidth ?> control-label"><?php echo $element->getLabel() ?></label>
        <div class="col-sm-<?php echo $this->formControlSpanWidth ?>">
            <?php echo $this->formDate($element); ?>
        </div>
    </div>
    <?php
    elseif ( ( isset($attributes['class']) and $attributes['class'] == 'hiddenField') or $attributes['name'] == 'csrf'):
        echo $this->formElement($element);
    elseif ($attributes['type'] == 'checkbox'):
        ?>
        <div class="form-group">
            <label class="col-sm-2 control-label">&nbsp;</label>
            <div class="col-sm-8"><?php echo $this->formElement($element); ?>
            <label for="<?php echo $attributes['id'] ?>" style="width: 80%"> <?php echo $element->getLabel() ?></label>
            </div>
        </div>
        <?php
    elseif ($attributes['type'] == 'radio'):
        ?>
        <div class="form-group">
            <label class="col-sm-<?php echo $this->formLabelSpanWidth ?> control-label"><?php echo $element->getLabel() ?></label>
            <div class="col-sm-<?php echo $this->formControlSpanWidth ?>">
                <?php echo $this->formElement($element) ?>
            </div>
        </div>
        <?php
    else:
        $element->setAttribute('class', 'form-control');
    ?>
    <div class="form-group">
        <label for="<?php echo $attributes['id'] ?>" class="col-sm-<?php echo $this->formLabelSpanWidth ?> control-label"><?php echo $element->getLabel() ?></label>
        <div class="col-sm-<?php echo $this->formControlSpanWidth ?>">
            <?php echo $this->formElement($element); ?>
        </div>
    </div>
    <?php
    endif;
endforeach;
    ?>
    <div class="form-group">
        <label for="submit" class="col-sm-<?php echo $this->formLabelSpanWidth ?> control-label">&nbsp;</label>
        <div class="col-sm-<?php echo $this->formControlSpanWidth ?>"><input type="submit" name="submit" id="submit" value="Conferma" class="btn btn-primary" onclick="javascript:refreshEditor();<?php if ($this->hideOnSubmit): ?>  document.getElementById('formcontainer').style.display='none'<?php endif ?>"></div>
    </div>

    <div class="form-group">
        <label class="col-sm-<?php echo $this->formLabelSpanWidth ?> control-label">&nbsp;</label>
        <div class="col-sm-<?php echo $this->formControlSpanWidth ?>">
            <label>* Campi obbligatori</label>
        </div>
    </div>
    <?php

echo $this->form()->closeTag($this->form);

?>
</div>

<div id="formDataLoading" class="alert alert-warning" style="display: none">
    <h1>Attendere: elaborazione dati in corso...</h1>
</div>
<div id="formDataResponse"></div>

<script>

</script>