<?php

$this->form->prepare();

$form = $this->form;
$form->prepare();

$formAction = !empty($this->formAction) ? $this->url('admin', array('lang' => 'it')).'formpost/'.$this->formAction : '';
$formId = !empty($this->formId) ? $this->formId : 'formData';

$form->setAttributes(array(
    'action'    => $formAction,
    'method'    => 'post',
    'enctype'   => 'multipart/form-data',
    'name'      => $formId,
    'id'        => $formId,
    'role'      => 'form',
    'class'     => 'form-horizontal'
));

if (!isset($this->formControlSpanWidth)): $this->formControlSpanWidth = 10; endif;
if (!isset($this->formLabelSpanWidth)): $this->formLabelSpanWidth = 2; endif;

echo $this->form()->openTag($form);

foreach ($this->form as $element):
    $attributes = $element->getAttributes();
    echo $this->formElementErrors($element);
    if (isset($attributes['class']) and $attributes['class'] == 'wysiwyg'):
    ?>
    <div class="form-group">
        <div class="col-sm-12">
            <label><?php echo $element->getLabel() ?></label>
            <?php echo $this->formElement($element); ?>
        </div>
    </div>
    <?php
    elseif ( ( isset($attributes['class']) and $attributes['class'] == 'hiddenField') or $attributes['name'] == 'csrf'):
        echo $this->formElement($element);
    elseif ($attributes['type'] == 'checkbox'):
        ?>
        <div class="form-group">
            <label class="col-sm-<?php echo $this->formLabelSpanWidth ?> control-label">&nbsp;</label>
            <div class="col-sm-<?php echo $this->formControlSpanWidth ?>"><?php echo $this->formElement($element); ?>
            <label for="<?php echo $attributes['id'] ?>" style="width: 80%"> <?php echo $element->getLabel() ?></label>
            </div>
        </div>
        <?php
    elseif ($attributes['type'] == 'multi_checkbox'):
        ?>
        <div class="form-group">
            <label for="<?php echo $attributes['id'] ?>" class="col-sm-<?php echo $this->formLabelSpanWidth ?> control-label"><?php echo $element->getLabel() ?></label>
            <div class="col-sm-<?php echo $this->formControlSpanWidth ?>">

                <?php echo $this->formElement($form->get($attributes['name'])); ?>

            </div>
        </div>
        <?php
    elseif ($attributes['type'] == 'PlainTextTitle'):
        ?>
        <div class="form-group">
            <label for="<?php echo $attributes['id'] ?>" class="col-sm-<?php echo $this->formLabelSpanWidth ?> control-label">&nbsp;</label>
            <div class="col-sm-<?php echo $this->formControlSpanWidth ?>">
                <h4><strong><?php echo strtoupper($element->getValue()) ?></strong></h4>
            </div>
        </div>
        <?php
    elseif ($attributes['type'] == 'PlainText'):
        ?>
        <div class="form-group">
            <label for="<?php echo $attributes['id'] ?>" class="col-sm-<?php echo $this->formLabelSpanWidth ?> control-label">&nbsp;</label>
            <div class="col-sm-<?php echo $this->formControlSpanWidth ?>">
                <p><strong><?php echo strtoupper($element->getValue()) ?></strong></p>
            </div>
        </div>
        <?php
    elseif ($attributes['type'] == 'date' or $attributes['type'] == 'datetime'):
        ?>
        <div class="form-group">
            <label for="<?php echo $attributes['id'] ?>" class="col-sm-<?php echo $this->formLabelSpanWidth ?> control-label"><?php echo $element->getLabel() ?></label>
            <div class="col-sm-<?php echo $this->formControlSpanWidth ?>">
                <input type="text" style="width: 30%; " name="<?php echo $attributes['name'] ?>" class="datetimepicker" placeholder="<?php echo (isset($attributes['placeholder'])) ? $attributes['placeholder'] : 'Seleziona data...' ?>" title="<?php echo (isset($attributes['title'])) ? $attributes['title'] : null ?>" id="<?php echo $attributes['id'] ?>" value="<?php echo $element->getValue() ?>" readonly="readonly"<?php if (isset($attributes['required'])): ?> required="required"<?php endif; ?>>
                <input type="button" class="btn btn-danger" onclick="$('#<?php echo $attributes['id'] ?>').val(''); " value="Elimina valore" title="Elimina valore data corrente">
                <input type="button" class="btn btn-info" onclick="$('#<?php echo $attributes['id'] ?>').val('0000-00-00 00:00:00'); " value="Setta &quot;data zero&quot;" title="Seleziona data 0000-00-00 00-00-00">
            </div>
        </div>
        <?php
    elseif ($attributes['type'] == 'radio'):
        ?>
        <div class="form-group">
            <label class="col-sm-<?php echo $this->formLabelSpanWidth ?> control-label"><?php echo $element->getLabel() ?></label>
            <div class="col-sm-<?php echo $this->formControlSpanWidth ?>">
                <?php echo $this->formradio($element); ?>
            </div>
        </div>
        <?php
    elseif ($attributes['type'] == 'reset'):
    ?>
    <div class="form-group">
        <label for="<?php echo $attributes['id'] ?>" class="col-sm-<?php echo $this->formLabelSpanWidth ?> control-label"><?php echo $element->getLabel() ?></label>
        <div class="col-sm-<?php echo $this->formControlSpanWidth ?>">
            <input value="<?php echo $element->getValue() ?>" type="button" class="btn btn-default" name="<?php echo $attributes['name'] ?>" onclick="resetCurrentForm('<?php echo $formId ?>');<?php if (isset($attributes['submit'])) echo ' submit()'; ?>">
        </div>
    </div>
    <?php
    else:
        if ($attributes['type'] != 'submit') {
            $element->setAttribute('class', 'form-control');
        }
    ?>
    <div class="form-group">
        <label for="<?php echo $attributes['id'] ?>" class="col-sm-<?php echo $this->formLabelSpanWidth ?> control-label"><?php echo $element->getLabel() ?></label>
        <div class="col-sm-<?php echo $this->formControlSpanWidth ?>">
            <?php echo $this->formElement($element); ?>
        </div>
    </div>
    <?php
    endif;
endforeach;

if ($this->closeForm):
    echo $this->form()->closeTag();
endif;
