<ul class="breadcrumb">
    <li>
        <a href="#" title="Home page">Home</a> <span class="divider"></span>
    </li>
    <li>
        <a href="#" title=""><?php echo $this->maindata[0]['nomeCategoria'] ?></a> <span class="divider"></span>
    </li>

    <li class="active"><?php echo $this->maindata[0]['titolo'] ?></li>
</ul>

<h3><?php echo $this->maindata[0]['titolo'] ?></h3>

<div><?php echo $this->maindata[0]['descrizione'] ?></div>

<hr>

<p class="text-right">Visualizza in versione: <a href="#" title="">PDF</a> <a href="#" title="">WORD</a> <a href="#" title="">TXT</a></p>
