<ul class="breadcrumb">
    <li><a href="<?php echo $this->url('admin', array('lang' => $this->params()->fromRoute('lang'))); ?>" title="Home page">Home</a> </li>
    <li class="active">
        <a href="<?php echo $this->formBreadCrumbCategoryLink ?>" title="<?php echo $this->formBreadCrumbCategory ?>">
            <?php echo $this->formBreadCrumbCategory ?>
        </a>
    </li>
    <li>
        <a href="#" title="Articolo <?php echo $this->formBreadCrumbCategory ?>">
            Articolo
        </a>
    </li>
    <li>
        <a href="<?php echo $this->url('admin/attachments-summary', array('lang' => $this->params()->fromRoute('lang'), 'module' => $this->moduleCode, 'referenceId' => $referenceId)) ?>" title="Gestione allegati <?php echo $this->formBreadCrumbCategory ?>">
            Gestione allegati
        </a>
    </li>
    <li class="active"><?php echo $this->breadCrumbActiveLabel ?></li>
</ul>

<div class="tab-pane" id="attachmentNew">
    <?php echo $this->render('backend/templates/'.$this->template_backend.'formdata/formdata.phtml'); ?>
</div>

<!-- Delete Modal -->
<div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="ConfirmDeleteModal" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content panel-danger">

            <div class="modal-header panel-heading">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                <h4 class="modal-title" id="deleteModalLabel"><strong>Conferma eliminazione?</strong></h4>
            </div>

            <form action="" method="post" id="frmDeleteModal">
                <div class="modal-body">
                    <p><strong>Attenzione:</strong> l'allegato e i dati relativi ad esso associati verranno eliminati definitivamente.</p>

                    <input type="hidden" name="deleteId" id="deleteId" value="" />
                </div>

                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Annulla</button>
                    <button type="submit" class="btn btn-danger">Conferma</button>
                </div>
            </form>

        </div>
    </div>
</div>

<!-- Modal file too large -->
<div class="modal fade" id="fileTooLarge" tabindex="-1" role="dialog" aria-labelledby="FileTooLargeModal" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content panel-danger">

            <div class="modal-header panel-heading">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                <h4 class="modal-title" id="deleteModalLabel"><strong>File troppo grande</strong></h4>
            </div>

            <form action="" method="post" id="frmDeleteModal">
                <div class="modal-body">
                    <p><strong>Attenzione:</strong> il file selezionato &egrave; troppo grande. Selezionare un file pi&ugrave; piccolo o non sar&agrave; possibile procedere.</p>

                    <input type="hidden" name="deleteId" id="deleteId" value="" />
                </div>

                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Chiudi</button>
                </div>
            </form>

        </div>
    </div>
</div>

<!-- Modal extension file not allowed -->
<div class="modal fade" id="extensionNotAllowed" tabindex="-1" role="dialog" aria-labelledby="extensionNotAllowedModal" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content panel-danger">

            <div class="modal-header panel-heading">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                <h4 class="modal-title" id="deleteModalLabel"><strong>Estensione file non consentita</strong></h4>
            </div>

            <form action="" method="post" id="frmDeleteModal">
                <div class="modal-body">
                    <p><strong>Attenzione:</strong> l'estensione del file selezionato non &egrave; consentita.</p>
                    <p><strong>Estensioni file consentite:</strong> jpg, jpeg, png, gif, zip, rar, doc, docx, rtf, pdf, xls, xlsx. csv, ppt, txt</p>

                    <input type="hidden" name="deleteId" id="deleteId" value="" />
                </div>

                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Chiudi</button>
                </div>
            </form>

        </div>
    </div>
</div>


<script>
    $(document).ready(function () {

        $(".open-deleteModal").click(function(e) {
            e.preventDefault();

            var _self = $(this);

            var dataId = _self.data('id');
            var dataAction = _self.data('action');

            $("#deleteId").val(dataId);
            $('#frmDeleteModal').attr('action', dataAction);

            $(_self.attr('href')).modal('show');
        });

        /* Check File size and extension */
        $('#attachmentFile').bind('change', function() {
            if (this.files[0].size > 20971520) {
                $('#fileTooLarge').modal(); /* open modal */
                $('#submit').prop("disabled", true); /* disable submit button */
            } else {
                $('#submit').prop("disabled", false);

                /* Check File Extension */
                var filename = $("#file_input").val();
                var extension = $('#attachmentFile').val().split('.').pop().toLowerCase();

                if (extension == filename) {
                    extension = '';
                } else {
                    extension = extension.toLowerCase();
                }

                switch (extension) {
                    case 'jpg': case 'jpeg': case 'png': case 'gif':
                    case 'zip': case 'rar':
                    case 'doc': case 'docx': case 'rtf':
                    case 'pdf':
                    case 'xls': case 'xlsx': case 'csv':
                    case 'ppt':
                    case 'txt':
                        $('#submit').prop("disabled", false);
                        break;

                    default:
                        $('#submit').prop("disabled", true);
                        $('#extensionNotAllowed').modal();
                        break;
                }
            }
        });
    });
</script>
