<ul class="breadcrumbs">
    <li><a href="<?php echo $this->url('main', array()) ?>" title="Vai alla home page">Home</a></li>
    <li><a href="<?php echo $this->url('autocertificazioni', array()) ?>" title="Torna all'elenco autocertificazioni">Autocertificazioni</a></li>
    <li class="current">Ufficio tecnico</li>
</ul>

<?php echo $this->partial($this->templateDir.'autocertificazioni/_autocertificazioniMenu.phtml', array('current' => 'ufficio-tecnico')); ?>

<h4>Gruppo Ufficio Tecnico</h4>

<p>Selezionare un modello da compilare:</p>

<ul>
    <li><a href="#" title="DICHIARAZIONE ALLEGATA ALLA RICHIESTA">DICHIARAZIONE ALLEGATA ALLA RICHIESTA</a></li>
    <li><a href="#" title="RICHIESTA AGIBILIT&Agrave;">RICHIESTA AGIBILIT&Agrave;</a></li>
    <li><a href="#" title="RICHIESTA APPOSIZIONE NUMERO CIVICO">RICHIESTA APPOSIZIONE NUMERO CIVICO</a></li>
    <li><a href="#" title="COMUNICAZIONE INIZIO LAVORI">COMUNICAZIONE INIZIO LAVORI</a></li>
    <li><a href="#" title="COMUNICAZIONE ULTIMAZIONE LAVORI">COMUNICAZIONE ULTIMAZIONE LAVORI</a></li>
    <li><a href="#" title="ACCESSO AGLI ATTI">ACCESSO AGLI ATTI</a></li>
    <li><a href="#" title="DICHIARAZIONE SOSTITUTIVA TITOLARITÀ">DICHIARAZIONE SOSTITUTIVA TITOLARITÀ</a></li>
    <li><a href="#" title="FINE LAVORI">FINE LAVORI</a></li>
    <li><a href="#" title="PROROGA INIZIO/FINE LAVORI">PROROGA INIZIO/FINE LAVORI</a></li>
    <li><a href="#" title="RICHIESTA PROROGA TERMINI CE">RICHIESTA PROROGA TERMINI CE</a></li>
    <li><a href="#" title="RICHIESTA RATEIZZAZIONE ONERI CONCESSORI">RICHIESTA RATEIZZAZIONE ONERI CONCESSORI</a></li>
    <li><a href="#" title="RICHIESTA CONCESSIONE EDILIZIA">RICHIESTA CONCESSIONE EDILIZIA</a></li>
</ul>
