<ul class="breadcrumbs">
    <li><a href="<?php echo $this->url('main', array()) ?>" title="Vai alla home page">Home</a></li>
    <li><a href="<?php echo $this->url('autocertificazioni', array()) ?>" title="Torna all'elenco autocertificazioni">Autocertificazioni</a></li>
    <li class="current">Polizia municipale</li>
</ul>

<?php echo $this->partial($this->templateDir.'autocertificazioni/_autocertificazioniMenu.phtml', array('current' => 'polizia-municipale')); ?>

<h4>Gruppo Polizia Municipale</h4>

<p>Selezionare un modello da compilare:</p>

<ul>
    <li><a href="#" title="">DICHIARAZIONE SOSTITUTIVA DELL'ATTO DI NOTORIET&Agrave;</a></li>
    <li><a href="#" title="">DOMANDA DI ASSENSO ALL'ESPATRIO DI MINORE</a></a></li>
    <li><a href="#" title="">RICHIESTA DI AUTORIZZAZIONE AL POSIZIONAMENTO DI: cartelli - insegne - segnali - altri mezzi pubblicitari</a></li>
    <li><a href="#" title="">MODULO PER LA RICHIESTA FORMALE DI ACCESSO AGLI ATTI</a></li>
    <li><a href="#" title="">MODULO PER LA RICHIESTA CONTRASSEGNO INVALIDI</a></li>
    <li><a href="#" title="">RICHIESTA AUTORIZZAZIONE PER PASSO CARRABILE</a></li>
    <li><a href="#" title="">RICHIESTA OCCUPAZIONE SUOLO PUBBLICO</a></li>
    <li><a href="#" title="">MODULO PER LA RICHIESTA PARCHEGGIO INVALIDI</a></li>
</ul>
