<ul class="breadcrumbs">
    <li><a href="<?php echo $this->url('main', array()) ?>" title="Vai alla home page">Home</a></li>
    <li><a href="<?php echo $this->url('autocertificazioni', array()) ?>" title="Torna all'elenco autocertificazioni">Autocertificazioni</a></li>
    <li class="current">Polizia municipale</li>
</ul>

<?php echo $this->partial($this->templateDir.'autocertificazioni/_autocertificazioniMenu.phtml', array('current' => 'polizia-municipale')); ?>

<h4>Gruppo Polizia Municipale</h4>

<p>Selezionare un modello da compilare:</p>

<ul>
    <li><a href="#" title="Vai alla dichiarazione sostitutiva dell'atto di notoriet&agrave;">DICHIARAZIONE SOSTITUTIVA DELL'ATTO DI NOTORIET&Agrave;</a></li>
    <li><a href="#" title="Vai alla domanda di assenso all'espatrio di minore">DOMANDA DI ASSENSO ALL'ESPATRIO DI MINORE</a></li>
    <li><a href="#" title="Vai alla richiesta di autorizzazione al posizionamento di: cartelli - insegne - segnali - altri mezzi pubblicitari">RICHIESTA DI AUTORIZZAZIONE AL POSIZIONAMENTO DI: cartelli - insegne - segnali - altri mezzi pubblicitari</a></li>
    <li><a href="#" title="Vai al modulo per la richiesta formale di accesso agli atti">MODULO PER LA RICHIESTA FORMALE DI ACCESSO AGLI ATTI</a></li>
    <li><a href="#" title="Vai al modulo per la richiesta contrassegno invalidi">MODULO PER LA RICHIESTA CONTRASSEGNO INVALIDI</a></li>
    <li><a href="#" title="Vai alla richiesta autorizzazione per passo carrabile">RICHIESTA AUTORIZZAZIONE PER PASSO CARRABILE</a></li>
    <li><a href="#" title="Vai alla richiesta occupazione suolo pubblico">RICHIESTA OCCUPAZIONE SUOLO PUBBLICO</a></li>
    <li><a href="#" title="Vai al modulo per la richiesta parcheggio invalidi">MODULO PER LA RICHIESTA PARCHEGGIO INVALIDI</a></li>
</ul>
