<?php
$acl = $this->userDetails->acl;
$lang = $this->params()->fromRoute('lang');
$languageSelectionFromRoute = $this->params()->fromRoute('languageSelection');
$modulename = $this->params()->fromRoute('modulename');
$languageSelection = (!empty($languageSelectionFromRoute)) ? $languageSelectionFromRoute : $lang;
?>
<!DOCTYPE html>
<html lang="it">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="<?php echo $this->sitename ?> - <?php echo $this->translate('Area riservata') ?>">
    <meta name="author" content="Kronoweb ITC">

    <title><?php echo $this->sitename ?> - Area riservata</title>

    <link href="<?php echo $this->publicDirRelativePath ?>/<?php echo $this->templateDir ?>assets/components/bootstrap/dist/css/bootstrap.min.css" rel="stylesheet">
    <link href="<?php echo $this->publicDirRelativePath ?>/<?php echo $this->templateDir ?>assets/components/metisMenu/dist/metisMenu.min.css" rel="stylesheet">
    <link href="<?php echo $this->publicDirRelativePath ?>/<?php echo $this->templateDir ?>assets/components/datatables-plugins/integration/bootstrap/3/dataTables.bootstrap.css" rel="stylesheet">
    <link href="<?php echo $this->publicDirRelativePath ?>/<?php echo $this->templateDir ?>assets/components/datatables-responsive/css/dataTables.responsive.css" rel="stylesheet">
    <link href="<?php echo $this->publicDirRelativePath ?>/<?php echo $this->templateDir ?>assets/stylesheets/sb-admin-2.css" rel="stylesheet">
    <link href="<?php echo $this->publicDirRelativePath ?>/<?php echo $this->templateDir ?>assets/components/font-awesome/css/font-awesome.min.css" rel="stylesheet" type="text/css">

    <?php
    echo $this->headLink()
        ->prependStylesheet($this->publicDirRelativePath.'/common/jquery/datetimepicker/jquery.datetimepicker.css')
    ?>

    <script src="<?php echo $this->publicDirRelativePath ?>/common/jquery/jquery.min.js"></script>
    <script src="<?php echo $this->publicDirRelativePath ?>/common/jquery/form/jquery.form.js"></script>
    <script src="<?php echo $this->publicDirRelativePath ?>/common/jquery/validate/jquery.validate.min.js"></script>
    <script src="<?php echo $this->publicDirRelativePath ?>/common/jquery/ckeditor/ckeditor.js"></script>
    <script src="<?php echo $this->publicDirRelativePath ?>/common/jquery/ckfinder/ckfinder.js"></script>
    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file: -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
    <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

    <style>
        /* JQuery Validate Label */
        label.error {
            color: red;
            margin-left: 0.5%;
        }

        fieldset label {
            font-weight: normal;
            cursor: pointer;
        }
        fieldset input  {
            cursor: pointer;
        }

        /* Icon colors */
        .icon-black, .icon-black:hover, .icon-black:active, .icon-black:focus { color: #333333; }
        .icon-red, .icon-red:hover, .icon-red:active, .icon-red:focus { color: #d9534f; }
        .icon-green, .icon-green:hover, .icon-green:active, .icon-green:focus { color: #00bb00; }
        .icon-green-light, .icon-green-light:hover, .icon-green-light:active, .icon-green-light:focus { color: #3Eaa00; }

        /* Force table scroll */
        .table-responsive {
            width: 100%;
            margin-bottom: 15px;
            overflow-y: hidden;
            overflow-x: scroll;
            -ms-overflow-style: -ms-autohiding-scrollbar;
            border: 1px solid #DDD;
            -webkit-overflow-scrolling: touch;
        }
        .positionMove {
            cursor: move;
        }
        .rowHidden {
            background-color: #eee;
            color: #888;
        }
        .rowNew {
            background-color: #337ab7;
            color: #fff;
        }
        .visibleFieldset {
            border: 1px groove #ddd !important;
            padding: 0 1.4em 1.4em 1.4em !important;
            margin: 0 0 1.5em 0 !important;
            -webkit-box-shadow:  0px 0px 0px 0px #000;
            box-shadow:  0px 0px 0px 0px #000;
        }
        .visibleLegend {
            border: 0;
            padding-left: 0.5em;
        }
        /* Password strength */
        .passError { color: #c00; font-weight: bold }
        .passMorechars { color: #808080; font-weight: bold }
        .passMedium { color: #00008b; font-weight: bold }
        .passSuccess { color: #006400; font-weight: bold }
    </style>
</head>

<body>

<div id="pageLoading"></div>

<header>
    <nav class="navbar navbar-default navbar-fixed-top" role="navigation" style="margin-bottom: 0">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="<?php echo $this->url('admin', array('lang' => $lang)); ?>" title="<?php echo $this->sitename ?> - area riservata"><?php echo $this->sitename ?></a>

            <div class="menu-toggler sidebar-toggler" title="Riduci \ espandi men&ugrave;">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </div>

            <ul class="nav navbar-top-links navbar-right">
                <li><a href="<?php echo $this->basepath() ?>" target="_blank" title="<?php echo $this->translate('Anteprima sito web') ?>"><i class="fa fa-eye"></i> <?php echo $this->translate('Anteprima') ?></a></li>
                <?php if (in_array($this->userDetails->role, array('WebMaster', 'SuperAdmin'))): ?>
                <li class="dropdown">
                    <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                        <i class="fa fa-gear fa-fw"></i> Opzioni&nbsp; <i class="fa fa-caret-down"></i>
                    </a>
                    <ul class="dropdown-menu dropdown-user">
                        <li>
                            <a href="<?php echo $this->url('admin/configurations-form', array('lang' => $lang, 'languageSelection' => $languageSelection)); ?>" title="Configurazioni applicazione">
                                Configurazioni
                            </a>
                        </li>
                        <li><a href="<?php echo $this->url('admin/log-summary', array('lang' => $lang)); ?>" title="Logs applicazione">Logs</a></li>
                        <?php if (in_array($this->userDetails->role, array('WebMaster'))): ?>
                        <!--
                        <li><a href="<?php echo $this->url('admin/migrazione', array('lang' => $lang)); ?>" title="Tool migrazione dati">Migrazione dati</a></li>
                        -->
                        <?php endif; ?>
                    </ul>
                </li>
                <?php endif; ?>
                <li class="dropdown">
                    <a class="dropdown-toggle" data-toggle="dropdown" href="#" title="">
                        <i class="fa fa-wrench fa-fw"></i> Assistenza&nbsp; <i class="fa fa-caret-down"></i>
                    </a>
                    <ul class="dropdown-menu dropdown-user">
                        <li><a href="<?php echo $this->url('admin/tickets-form', array('lang' => $lang)); ?>" title="Nuova richiesta">Nuova richiesta</a></li>
                        <li><a href="<?php echo $this->url('admin/tickets-summary', array('lang' => $lang)); ?>" title="Elenco richieste di assistenza">Elenco richieste</a></li>
                    </ul>
                </li>
                <li class="dropdown">
                    <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                        <i class="fa fa-user fa-fw"></i> <?php echo $this->userDetails->name." ".$this->userDetails->surname ?>&nbsp; <i class="fa fa-caret-down"></i>
                    </a>
                    <ul class="dropdown-menu dropdown-user">
                        <li>
                            <a href="<?php echo $this->url('admin/users-form', array('lang' => $lang, 'id' => $this->userDetails->id)); ?>" title="Modifica dati utente">
                                <i class="fa fa-user fa-fw"></i> Profilo
                            </a>
                        </li>
                        <li class="divider"></li>
                        <li><a href="<?php echo $this->url('login/process', array('action' => 'logout')); ?>" title="Uscita dall'area riservata"><i class="fa fa-sign-out fa-fw"></i> Uscita</a>
                        </li>
                    </ul>
                </li>
            </ul>
        </div>
    </div>

    </nav>
</header>

<div id="wrapper">

    <!-- Navigation -->
    <nav role="navigation" style="margin-bottom: 0; margin-top: -1px;">

        <div class="navbar-default sidebar" role="navigation">
            <div class="sidebar-nav navbar-collapse" id="sidebar-area">
                <ul class="nav" id="sidebar">
                    <li class="sidebar-search">
                        <form action="" method="post" enctype="multipart/form-data">
                        <div class="input-group custom-search-form">
                            <input type="text" class="form-control" placeholder="Cerca...">
                                <span class="input-group-btn">
                                <button class="btn btn-default" type="submit">
                                    <i class="fa fa-search"></i>
                                </button>
                            </span>
                        </div>
                        </form>
                        <div  class="search-icon">
                            <a href="#"><i class="fa fa fa-search fa-fw"></i></a>
                        </div>
                        <!-- /input-group -->
                    </li>

                    <li>
                        <a href="<?php echo $this->url('admin', array('lang' => $lang)); ?>"><i class="fa fa-dashboard fa-fw"></i> <span class="side-menu-title">Home</span></a>
                    </li>

                    <!-- Contenuti -->
                    <li>
                        <a href="#" class="dropdown-collapse" title=""><i class="fa fa-newspaper-o fa-fw"></i> <span class="side-menu-title">Contenuti</span><span class="fa arrow"></span></a>
                        <ul class="nav nav-second-level">
                            <li>
                                <a href="<?php echo $this->url('admin/contenuti-form', array('lang' => $lang, 'languageSelection' => $languageSelection, 'modulename' => 'contenuti')); ?>" title="Nuovo contenuto">
                                    Nuovo
                                </a>
                            </li>
                            <li>
                                <a href="<?php echo $this->url('admin/contenuti-summary', array('lang' => $lang, 'languageSelection' => $languageSelection, 'modulename' => 'contenuti')); ?>" title="Gestione contenuti">
                                    Modifica \ Elimina
                                </a>
                            </li>
                            <!-- Sezioni -->
                            <li>
                                <a href="#" class="dropdown-collapse" title="Gestione sezioni contenuti">Sezioni <span class="fa arrow"></span></a>
                                <ul class="nav nav-third-level">
                                    <?php if ($acl->hasResource('contenuti_sezioni_add')): ?>
                                    <li>
                                        <a href="<?php echo $this->url('admin/sezioni-form', array('lang' => $lang, 'modulename' => 'contenuti', 'languageSelection' => $languageSelection)); ?>" title="Nuova sezione contenuti">
                                            Nuova
                                        </a>
                                    </li>
                                    <?php endif; ?>
                                    <?php if ($acl->hasResource('contenuti_sezioni_update')): ?>
                                    <li>
                                        <a href="<?php echo $this->url('admin/sezioni-summary', array('lang' => $lang, 'modulename' => 'contenuti', 'languageSelection' => $languageSelection)); ?>" title="Gestione sezioni contenuti">
                                            Gestione
                                        </a>
                                    </li>
                                    <?php endif; ?>
                                    <li>
                                        <a href="<?php echo $this->url('admin/sezioni-positions', array('lang' => $lang, 'modulename' => 'contenuti', 'languageSelection' => $languageSelection)); ?>" title="Gestione posizioni sezioni">
                                            Posizioni
                                        </a>
                                    </li>
                                </ul>
                            </li>
                            <!-- SottoSezioni -->
                            <?php if ($acl->hasResource('contenuti_sottosezioni_add') or $acl->hasResource('contenuti_sottosezioni_update')): ?>
                            <li>
                                <a href="#" class="dropdown-collapse" title="Gestione sezioni contenuti">Sotto-Sezioni <span class="fa arrow"></span></a>
                                <ul class="nav nav-third-level">
                                    <?php if ($acl->hasResource('contenuti_sottosezioni_add')): ?>
                                    <li>
                                        <a href="<?php echo $this->url('admin/sottosezioni-form', array('lang' => $lang, 'modulename' => 'contenuti', 'languageSelection' => $languageSelection)) ?>" title="Nuova sottosezione">
                                            Nuova
                                        </a>
                                    </li>
                                    <?php endif; ?>
                                    <?php if ($acl->hasResource('contenuti_sottosezioni_update')): ?>
                                    <li>
                                        <a href="<?php echo $this->url('admin/sottosezioni-summary', array('lang' => $lang, 'modulename' => 'contenuti', 'languageSelection' => $languageSelection)) ?>" title="Gestione sottosezioni">
                                            Gestione
                                        </a>
                                    </li>
                                    <?php endif; ?>
                                </ul>
                            </li>
                            <?php endif; ?>
                        </ul>
                    </li>

                    <!-- Albo pretorio -->
                    <?php if ($acl->hasResource('albo_pretorio_add') or $acl->hasResource('albo_pretorio_supdate')): ?>
                    <li>
                        <a href="#" class="dropdown-collapse" title="Menu albo pretorio"><i class="fa fa-table fa-fw"></i> <span class="side-menu-title">Albo pretorio</span><span class="fa arrow"></span></a>
                        <ul class="nav nav-second-level">
                            <li><a href="<?php echo $this->url('admin/albo-pretorio-form', array('lang' => $lang) ); ?>" title="Nuovo atto">Nuovo atto</a></li>
                            <li><a href="<?php echo $this->url('admin/albo-pretorio-summary', array('lang' => $lang)); ?>" title="Gestione">Gestione</a></li>
                            <li><a href="#" title="Elenco atti ufficiali">Atti ufficiali</a></li>
                            <!-- Sezioni -->
                            <?php if ($acl->hasResource('albo_pretorio_sezioni_add') or $acl->hasResource('albo_pretorio_sezioni_update')): ?>
                            <li>
                                <a href="#" class="dropdown-collapse" title="Sezioni albo pretorio">Sezioni <span class="fa arrow"></span></a>
                                <ul class="nav nav-third-level">
                                    <li><a href="<?php echo $this->url('admin/albo-pretorio-sezioni-form', array('lang' => $lang)); ?>" title="Nuova sezione albo pretorio">Nuova</a></li>
                                    <li><a href="<?php echo $this->url('admin/albo-pretorio-sezioni-summary', array('lang' => $lang)); ?>" title="Gestione sezioni albo pretorio">Modifica \ Elimina</a></li>
                                </ul>
                            </li>
                            <?php endif; ?>
                            <!-- Enti terzi -->
                            <?php if ($acl->hasResource('enti_terzi_add') or $acl->hasResource('enti_terzi_update')): ?>
                            <li>
                                <a href="#" class="dropdown-collapse" title="Menu enti terzi">Enti terzi <span class="fa arrow"></span></a>
                                <ul class="nav nav-third-level">
                                    <li><a href="<?php echo $this->url('admin/enti-terzi-form', array( 'lang' => $lang ) ); ?>" title="Nuovo ente terzo">Nuovo</a></li>
                                    <li><a href="<?php echo $this->url('admin/enti-terzi-summary', array( 'lang' => $lang  )); ?>" title="Gestione rubrica enti terzi">Gestione</a></li>
                                </ul>
                            </li>
                            <?php endif; ?>
                        </ul>
                    </li>
                    <?php endif; ?>

                    <!-- Stato civile -->
                    <?php if ($acl->hasResource('stato_civile_add') or $acl->hasResource('stato_civile_update')): ?>
                    <li>
                        <a href="#" class="dropdown-collapse"><i class="fa fa-institution fa-fw"></i> <span class="side-menu-title">Stato civile</span><span class="fa arrow"></span></a>
                        <ul class="nav nav-second-level">
                            <?php if ($acl->hasResource('stato_civile_add')): ?>
                            <li><a href="<?php echo $this->url('admin/stato-civile-form', array('lang' => $lang)); ?>" title="Nuovo atto stato civile">Nuovo atto</a></li>
                            <?php endif; ?>
                            <?php if ($acl->hasResource('stato_civile_update')): ?>
                            <li><a href="<?php echo $this->url('admin/stato-civile-summary', array('lang' => $lang)); ?>" title="Gestione atti stato civile">Gestione</a></li>
                            <?php endif; ?>
                            <?php if ($acl->hasResource('stato_civile_sezioni_add') or $acl->hasResource('stato_civile_sezioni_update')): ?>
                            <li>
                                <a href="#" class="dropdown-collapse" title="Sezioni stato civile">Sezioni <span class="fa arrow"></span></a>
                                <ul class="nav nav-third-level">
                                    <li><a href="<?php echo $this->url('admin/stato-civile-sezioni-form', array('lang' => $lang)); ?>" title="Nuova sezione albo">Nuova</a></li>
                                    <li><a href="<?php echo $this->url('admin/stato-civile-sezioni-summary', array('lang' => $lang)); ?>" title="Gestione sezioni">Gestione</a></li>
                                </ul>
                            </li>
                            <?php endif; ?>
                            <?php if ($acl->hasResource('enti_terzi_add') or $acl->hasResource('enti_terzi_update')): ?>
                                <li>
                                    <a href="#" class="dropdown-collapse" title="Gestione enti terzi">Enti terzi <span class="fa arrow"></span></a>
                                    <ul class="nav nav-third-level">
                                        <li><a href="<?php echo $this->url('admin/enti-terzi-form', array('lang' => $lang) ); ?>" title="Nuovo ente terzo">Nuovo indirizzo</a></li>
                                        <li><a href="<?php echo $this->url('admin/enti-terzi-summary', array('lang' => $lang) ); ?>" title="Gestione rubrica enti terzi">Gestione</a></li>
                                    </ul>
                                </li>
                            <?php endif; ?>
                        </ul>
                    </li>
                    <?php endif; ?>

                    <!-- Amministrazione trasparente -->
                    <?php if ($acl->hasResource('amministrazione_trsparente_add') or $acl->hasResource('amministrazione_trsparente_update')): ?>
                    <li>
                        <a href="#" class="dropdown-collapse"><i class="fa fa-laptop fa-fw"></i> <span class="side-menu-title">Amm. trasparente</span><span class="fa arrow"></span></a>
                        <ul class="nav nav-second-level">
                            <?php if ($acl->hasResource('amministrazione_trsparente_add')): ?>
                            <li><a href="<?php echo $this->url('admin/contenuti-form', array('lang' => $lang, 'languageSelection' => $languageSelection, 'modulename' => 'amministrazione-trasparente')); ?>" title="Nuovo articolo">Nuovo articolo</a></li>
                            <?php endif; ?>
                            <?php if ($acl->hasResource('amministrazione_trsparente_update')): ?>
                            <li><a href="<?php echo $this->url('admin/contenuti-summary', array('lang' => $lang, 'languageSelection' => $languageSelection, 'modulename' => 'amministrazione-trasparente')); ?>" title="Gestione">Gestione</a></li>
                            <?php endif; ?>
                            <!-- Sezioni -->
                            <li>
                                <a href="#" class="dropdown-collapse" title="Gestione sezioni amministrazione trasparente">Sezioni <span class="fa arrow"></span></a>
                                <ul class="nav nav-third-level">
                                    <li><a href="<?php echo $this->url('admin/sezioni-form', array('lang' => $lang, 'modulename' => 'amministrazione-trasparente', 'languageSelection' => $languageSelection)); ?>" title="Inserisci nuova sezione">Nuova</a></li>
                                    <li><a href="<?php echo $this->url('admin/sezioni-summary', array('lang' => $lang, 'modulename' => 'amministrazione-trasparente', 'languageSelection' => $languageSelection)); ?>" title="Gestione">Gestione</a></li>
                                </ul>
                            </li>

                            <!-- Sottosezioni -->
                            <li>
                                <a href="#" class="dropdown-collapse" title="Gestione sottosezioni amministrazione trasparente">Sottosezioni <span class="fa arrow"></span></a>
                                <ul class="nav nav-third-level">
                                    <li><a href="#" title="Inserisci nuova sottosezione">Nuova</a></li>
                                    <li><a href="#" title="Gestione">Gestione</a></li>
                                </ul>
                            </li>

                        </ul>
                    </li>
                    <?php endif; ?>

                    <!-- Atti di concessione -->
                    <?php if ($acl->hasResource('atti_concessione_add') or $acl->hasResource('atti_concessione_update')): ?>
                    <li>
                        <a href="#" class="dropdown-collapse"><i class="fa fa-list-alt fa-fw"></i> <span class="side-menu-title">Atti di concessione</span><span class="fa arrow"></span></a>
                        <ul class="nav nav-second-level">
                            <?php if ($acl->hasResource('atti_concessione_add')): ?>
                            <li><a href="<?php echo $this->url('admin/atti-concessione-form', array('lang' => $lang) ); ?>" title="Nuovo articolo">Nuovo atto</a></li>
                            <?php endif; ?>
                            <?php if ($acl->hasResource('atti_concessione_update')): ?>
                            <li><a href="<?php echo $this->url('admin/atti-concessione-summary', array('lang' => $lang) ); ?>" title="Gestione">Gestione</a></li>
                            <?php endif; ?>

                            <!-- Responsabili di procedimento -->
                            <li><a href="<?php echo $this->url('admin/users-responsabili-procedimento', array('lang' => $lang)); ?>" title="Gestione">Responsabili procedimento</a></li>

                            <?php if (!$acl->hasResource('atti_concessione_modassign_add') or $acl->hasResource('atti_concessione_modassign_update')): ?>
                                <!-- Modalita assegnazione -->
                                <li>
                                    <a href="#" class="dropdown-collapse" title="">Modalit&agrave; assegnazione <span class="fa arrow"></span></a>
                                    <ul class="nav nav-third-level">
                                        <li><a href="<?php echo $this->url('admin/atti-concessione-modalita-assegnazione-form', array( 'lang' => $lang, ) ); ?>" title="Nuova modalit&agrave; assegnazione">Nuova</a></li>
                                        <li><a href="<?php echo $this->url('admin/atti-concessione-modalita-assegnazione-summary', array( 'lang' => $lang, ) ); ?>" title="Gestione modalit&agrave; assegnazione">Gestione</a></li>
                                    </ul>
                                </li>
                            <?php endif; ?>
                        </ul>
                    </li>
                    <?php endif; ?>

                    <!-- Contratti pubblici -->
                    <?php if ($acl->hasResource('contratti_pubblici_add') or $acl->hasResource('contratti_pubblici_update')): ?>
                    <li>
                        <a href="#" class="dropdown-collapse"><i class="fa fa-edit fa-fw"></i> <span class="side-menu-title">Contratti pubblici</span><span class="fa arrow"></span></a>
                        <ul class="nav nav-second-level">
                            <li><a href="<?php echo $this->url('admin/contratti-pubblici-form', array('lang' => $lang) ); ?>" title="Nuovo bando contratto">Nuovo bando</a></li>
                            <li><a href="<?php echo $this->url('admin/contratti-pubblici-summary', array('lang' => $lang) ); ?>" title="Gestione contratti pubblici">Gestione</a></li>

                            <!-- Operatori / Aziende / Aggiudicatari -->
                            <li>
                                <a href="#" class="dropdown-collapse" title="Operatori contratti pubblici">Aziende <span class="fa arrow"></span></a>
                                <ul class="nav nav-third-level">
                                    <li><a href="<?php echo $this->url('admin/contratti-pubblici-operatori-form', array('lang' => $lang) ); ?>" title="Nuovo operatore \ azienda">Nuova</a></li>
                                    <li><a href="<?php echo $this->url('admin/contratti-pubblici-operatori-summary', array('lang' => $lang) ); ?>" title="Gestione aziende contratti pubblici">Gestione</a></li>
                                </ul>
                            </li>

                            <?php if ($acl->hasResource('contratti_pubblici_scelta_contraente_add') or $acl->hasResource('contratti_pubblici_scelta_contraente_update')): ?>
                            <!-- Voci scelta contraente -->
                            <li>
                                <a href="#" class="dropdown-collapse" title="Gestione voci scelta contraente">Voci scelta contraente <span class="fa arrow"></span></a>
                                <ul class="nav nav-third-level">
                                    <?php if ($acl->hasResource('contratti_pubblici_scelta_contraente_add')): ?>
                                    <li><a href="<?php echo $this->url('admin/contratti-pubblici-scelta-contraente-form', array('lang' => $lang )) ?>" title="Nuova voce scelta contraente">Nuova</a></li>
                                    <?php endif; ?>
                                    <?php if ($acl->hasResource('contratti_pubblici_scelta_contraente_update')): ?>
                                    <li><a href="<?php echo $this->url('admin/contratti-pubblici-scelta-contraente-summary', array('lang' => $lang )) ?>" title="Gestione voci scelta contraente">Gestione</a></li>
                                    <?php endif; ?>
                                </ul>
                            </li>
                            <?php endif; ?>

                        </ul>
                    </li>
                    <?php endif; ?>

                    <!-- Blogs -->
                    <?php if ($acl->hasResource('blogs_add') or $acl->hasResource('blogs_update')): ?>
                    <li>
                        <a href="#" class="dropdown-collapse"><i class="fa fa-list-alt fa-fw"></i> <span class="side-menu-title">Blogs</span><span class="fa arrow"></span></a>
                        <ul class="nav nav-second-level">
                            <?php if ($acl->hasResource('blogs_add')): ?>
                            <li><a href="<?php echo $this->url('admin/blogs-form', array('lang' => $lang, 'languageSelection' => $languageSelection
                                , 'formtype' => 'blogs')) ?>" title="Aggiungi nuovo post">Nuovo post</a></li>
                            <?php endif; ?>
                            <?php if ($acl->hasResource('blogs_update')): ?>
                            <li><a href="<?php echo $this->url('admin/blogs-summary', array('lang' => $lang, 'languageSelection' => $languageSelection) ); ?>" title="Gestione posts blogs">Modifica \ Elimina</a></li>
                            <?php endif; ?>
                            <!-- Categories -->
                            <?php if ($acl->hasResource('blogs_categories_add') or $acl->hasResource('blogs_categories_update')): ?>
                            <li>
                                <a href="#" class="dropdown-collapse" title="Categorie">Categorie <span class="fa arrow"></span></a>
                                <ul class="nav nav-third-level">
                                    <?php if ($acl->hasResource('blogs_categories_add')): ?>
                                    <li><a href="<?php echo $this->url('admin/posts-categories-form', array(
                                                'lang'              => $lang,
                                                'formtype'          => 'blogs',
                                                'languageSelection' => $languageSelection
                                            )
                                        );
                                        ?>" title="">Nuova</a></li>
                                    <?php endif; ?>
                                    <?php if ($acl->hasResource('blogs_categories_update')): ?>
                                    <li><a href="<?php echo $this->url('admin/posts-categories-summary', array(
                                                'lang'          => $lang,
                                                'moduleCode'    => 'blogs',
                                                'languageSelection' => $languageSelection
                                            )
                                        );
                                        ?>" title="Gestione categorie blogs">Modifica \ Elimina</a></li>
                                    <?php endif; ?>
                                </ul>
                            </li>
                            <?php endif; ?>
                        </ul>
                    </li>
                    <?php endif; ?>

                    <!-- Photo -->
                    <?php if ($acl->hasResource('photo_add') or $acl->hasResource('photo_update')): ?>
                    <li>
                        <a href="#" class="dropdown-collapse"><i class="fa fa-camera fa-fw"></i> <span class="side-menu-title">Foto</span><span class="fa arrow"></span></a>
                        <ul class="nav nav-second-level">
                            <li><a href="<?php echo $this->url('admin/photo-form', array('lang' => $lang, 'languageSelection' => $languageSelection)) ?>" title="Aggiungi nuova foto">Nuova</a></li>
                            <li><a href="<?php echo $this->url('admin/photo-summary', array('lang' => $lang, 'languageSelection' => $languageSelection)) ?>" title="Gestione gallerie fotografice">Gestione</a></li>
                            <!-- Categories -->
                            <li>
                                <a href="#" class="dropdown-collapse" title="">Categorie <span class="fa arrow"></span></a>
                                <ul class="nav nav-third-level">
                                    <li><a href="<?php echo $this->url('admin/posts-categories-form', array(
                                                'lang'              => $lang,
                                                'formtype'          => 'photo',
                                                'languageSelection' => $languageSelection
                                            )
                                        );
                                        ?>" title="Nuova categoria foto">Nuova</a></li>
                                    <li>
                                        <a href="<?php echo $this->url('admin/posts-categories-summary', array(
                                                'lang'              => $lang,
                                                'moduleCode'        => 'photo',
                                                'languageSelection' => $languageSelection
                                            )
                                        );
                                        ?>" title="Gestione foto">
                                            Modifica \ Elimina
                                        </a>
                                    </li>
                                </ul>
                            </li>
                        </ul>
                    </li>
                    <?php endif; ?>

                    <!-- Newsletter -->
                    <?php if ($acl->hasResource('newsletter_add') or $acl->hasResource('newsletter_update')): ?>
                    <li>
                        <a href="#" class="dropdown-collapse" title="Newsletter"><i class="fa fa-newspaper-o fa-fw"></i> <span class="side-menu-title">Newsletter</span><span class="fa arrow"></span></a>
                        <ul class="nav nav-second-level">
                            <?php if ($acl->hasResource('newsletter_add')): ?>
                                <li><a href="<?php echo $this->url('admin/newsletter-form', array('lang' => $lang, 'languageSelection' => $languageSelection)); ?>" title="Nuova newsletter">Nuova</a></li>
                            <?php endif; ?>

                            <?php if ($acl->hasResource('newsletter_update')): ?>
                                <li><a href="<?php echo $this->url('admin/newsletter-summary', array('lang' => $lang, 'languageSelection' => $languageSelection)); ?>" title="Gestione newsletter">Gestione</a></li>
                            <?php endif; ?>

                            <?php if ($acl->hasResource('newsletter_update')): ?>
                            <!-- Utenti iscritti e utenti "solo email" -->
                            <li>
                                <a href="#" title="Elenco iscritti">
                                    Iscritti
                                </a>
                            </li>
                            <?php endif; ?>
                            <!-- Newsletter templates -->
                            <?php if ($acl->hasResource('newsletter_templates_add') or $acl->hasResource('newsletter_templates_update')): ?>
                                <li>
                                    <a href="#" class="dropdown-collapse" title="">Templates <span class="fa arrow"></span></a>
                                    <ul class="nav nav-third-level">
                                        <?php if ($acl->hasResource('newsletter_templates_add')): ?>
                                            <li><a href="#" title="Nuovo">Nuovo</a></li>
                                        <?php endif; ?>
                                        <?php if ($acl->hasResource('newsletter_templates_update')): ?>
                                            <li><a href="#" title="Gestione newsletter templates">Modifica \ Elimina</a></li>
                                        <?php endif; ?>
                                    </ul>
                                </li>
                            <?php endif; ?>
                        </ul>
                    </li>
                    <?php endif; ?>

                    <!-- Utenti -->
                    <?php if ($acl->hasResource('users_add') or $acl->hasResource('users_roles_update')): ?>
                    <li>
                        <a href="#" class="dropdown-collapse"><i class="fa fa-list-alt fa-users"></i> <span class="side-menu-title">Utenti</span><span class="fa arrow"></span></a>
                        <ul class="nav nav-second-level">
                            <?php if ($acl->hasResource('users_add')): ?>
                            <li><a href="<?php echo $this->url('admin/users-form', array('lang' => $lang)); ?>" title="Aggiungi nuovo utente">Nuovo</a></li>
                            <?php endif; ?>
                            <?php if ($acl->hasResource('users_roles_update')): ?>
                            <li><a href="<?php echo $this->url('admin/users-summary', array('lang' => $lang)); ?>" title="Gestione utenti">Gestione</a></li>
                            <?php endif; ?>

                            <!-- Responsabili procedimento -->
                            <li><a href="<?php echo $this->url('admin/users-responsabili-procedimento', array('lang' => $lang)); ?>" title="Gestione">Responsabili procedimento</a></li>

                            <!-- Ruoli -->
                            <?php if ($acl->hasResource('users_roles_add') or $acl->hasResource('users_roles_update')): ?>
                            <li>
                                <a href="#" class="dropdown-collapse" title="">Ruoli <span class="fa arrow"></span></a>
                                <ul class="nav nav-third-level">
                                    <?php if ($acl->hasResource('users_roles_add')): ?>
                                    <li><a href="<?php echo $this->url('admin/users-roles-form', array('lang' => $lang) ); ?>" title="Nuovo ruolo utente">Nuovo</a></li>
                                    <?php endif; ?>
                                    <?php if ($acl->hasResource('users_roles_update')): ?>
                                    <li><a href="<?php echo $this->url('admin/users-roles-summary', array('lang' => $lang) ); ?>" title="Gestione ruoli utente">Modifica \ Elimina</a></li>
                                    <?php endif; ?>
                                </ul>
                            </li>
                            <?php endif; ?>

                            <!-- Settori -->
                            <?php if ($acl->hasResource('users_settori_add') or $acl->hasResource('users_settori_update')): ?>
                            <li>
                                <a href="#" class="dropdown-collapse" title="Menu Settori">Settori <span class="fa arrow"></span></a>
                                <ul class="nav nav-third-level">
                                    <?php if ($acl->hasResource('users_settori_add')): ?>
                                        <li><a href="<?php echo $this->url('admin/users-settori-form', array('lang' => $lang) ); ?>" title="Nuovo settore utente">Nuovo</a></li>
                                    <?php endif; ?>
                                    <?php if ($acl->hasResource('users_settori_update')): ?>
                                        <li><a href="<?php echo $this->url('admin/users-settori-summary', array('lang' => $lang) ); ?>" title="Gestione settori utente">Modifica \ Elimina</a></li>
                                    <?php endif; ?>
                                </ul>
                            </li>
                            <?php endif; ?>

                        </ul>
                    </li>
                    <?php endif; ?>
                </ul>
            </div>
            <!-- /.sidebar-collapse -->
        </div>
        <!-- /.navbar-static-side -->
    </nav>

    <div id="page-wrapper">
        <br>
        <?php
        if (!empty($this->templatePartial)) {
            echo $this->partial($this->templateDir.$this->templatePartial);
        }
        ?>
    </div>

</div>

<script src="<?php echo $this->publicDirRelativePath ?>/<?php echo $this->templateDir ?>assets/components/jquery-cookie-master/src/jquery.cookie.js"></script>
<script src="<?php echo $this->publicDirRelativePath ?>/<?php echo $this->templateDir ?>assets/components/bootstrap/dist/js/bootstrap.min.js"></script>
<script src="<?php echo $this->publicDirRelativePath ?>/<?php echo $this->templateDir ?>assets/components/metisMenu/dist/metisMenu.min.js"></script>
<script src="<?php echo $this->publicDirRelativePath ?>/<?php echo $this->templateDir ?>assets/components/datatables/media/js/jquery.dataTables.min.js"></script>
<script src="<?php echo $this->publicDirRelativePath ?>/<?php echo $this->templateDir ?>assets/components/datatables-plugins/integration/bootstrap/3/dataTables.bootstrap.min.js"></script>
<script src="<?php echo $this->publicDirRelativePath ?>/<?php echo $this->templateDir ?>assets/javascripts/sb-admin-2.js"></script>
<script src="<?php echo $this->publicDirRelativePath ?>/common/jquery/datetimepicker/jquery.datetimepicker.js"></script>

<script>

function showLoading()
{
    $("#formDataResponse").hide();
    $("#formDataLoading").show();
}

function showResponse()
{
    $("#formDataResponse").show();
    $("#formDataLoading").hide();
}

function resetCurrentForm(id)
{
    $(':text, :password, :file', '#'+id).val('');
    $(':input,select option', '#'+id).removeAttr('checked').removeAttr('selected');
    $('select option:first', '#'+id).attr('selected',true);
}

function clear_form_elements(id_name) {
    jQuery("#"+id_name).find(':input').each(function() {
        switch(this.type) {
            case 'password':
            case 'text': case 'email': case 'number':
            case 'textarea':
            case 'file':
            case 'select-one':
                jQuery(this).val('');
            break;

            case 'checkbox':
            case 'radio':
                this.checked = false;
        }
    });
}

function reloadPage()
{
    window.location.reload();
}

$(document).ready(function () {

    $("#lnkSearchExport").click(function() {
        $("#frmFrmSearchExport").slideToggle("slow");
    });

    $("#resetForm").click(function() {
        resetCurrentForm('frmSearchExport');

        $('#frmSearchExport').submit();
    });

    $('#dataTable').dataTable({
        "pagingType": "full_numbers",
        "aaSorting": [],
        "language": {
            "lengthMenu": "Mostra _MENU_ elementi per pagina",
            "zeroRecords": "Nessun elemento trovato",
            "info": "Mostra pagina _PAGE_ di _PAGES_",
            "infoEmpty": "Nessun elemento presente in archivio",
            "infoFiltered": "(filtered from _MAX_ total records)"
        },
        "oLanguage": { "sSearch": "Cerca:" }
    });

    $('#zf2-pagination-table').DataTable({
        responsive: true,
        bPaginate: false,
        "info": false,
        "aaSorting": [],
        "language": {
            "lengthMenu": "Mostra _MENU_ elementi per pagina",
            "zeroRecords": "Nessun elemento trovato",
            "info": "Mostra pagina _PAGE_ di _PAGES_",
            "infoEmpty": "Nessun elemento presente in archivio",
            "infoFiltered": "(filtered from _MAX_ total records)"
        },
        "oLanguage": { "sSearch": "Cerca:" }
    });

    $('#contratti-operatori-rubrica-table').DataTable({
        responsive: true,
        bPaginate: false,
        /* "pagingType": "full_numbers", */
        searching: false,
        "info": false,
        "pageLength": 10,
        "multipleSelection": true
    });

    var validate = $("#formData").validate({
        submitHandler: function(form) {
            $("#formData").ajaxSubmit({
                target: "#formDataResponse",
                type:   "post",
                beforeSubmit: showLoading,
                success: showResponse,
                onkeyup: false
            });

            $("#formcontainer").hide();
        }
    });

    $('.datetimepicker').datetimepicker({
        format: 'Y-m-d H:i:s',
        lang: '<?php echo $lang ?>'
    });

});
</script>

</body>
</html>