
<?php if ($this->showBreadCrumb): ?>
    <?php echo $this->render($this->formDataCommonPath.'breadcrumb.phtml'); ?>
<?php endif; ?>

<div style="padding: 1%; margin: 0" class="alert alert-<?php if ($this->messageType) echo $this->messageType; else echo "info"; ?>" id="formdataresultmessage">

    <h1><?php echo $this->messageTitle ?></h1>

    <div><?php echo $this->messageText ?></div>

    <div>&nbsp;</div>

    <?php if (isset($this->messageList)): ?>
    <!-- Message list -->
    <div>
        <ul>
            <?php foreach($this->messageList as $message): ?>
            <li><?php echo $message ?></li>
            <?php endforeach; ?>
        </ul>
    </div>
    <?php endif; ?>

    <?php if (isset($this->formInputFilter)): ?>
        <!-- Form validation error messages -->
        <?php
        $invalidInputs = $this->formInputFilter->getInvalidInput();
        if ( !empty($invalidInputs) ):
            ?>
            <h4>Campi non validi:</h4>
            <?php
            foreach($invalidInputs as $key => $value):
                echo $key."<br>";
            endforeach;
            ?>
            <br>
            <?php
        endif;
        ?>
    <?php endif; ?>

    <?php if (!empty($this->form)): ?>
        <!-- Form Errors -->
        <?php foreach ($this->form as $element): ?>
            <?php
            $elementError = $this->formElementerrors($element);
            if (!empty($elementError)):
                if (!isset($printDebugFormRow)):
                    $printDebugFormRow = 1;
                endif;
                echo $element->getName().' '.$elementError;
            endif;
            ?>
        <?php endforeach; ?>

        <?php
        if (isset($printDebugFormRow)):
            ?><br><?php
        endif;
        ?>
    <?php endif; ?>

    <?php if ($this->messageShowFormLink): ?>
        <div id="showFormContainer">
            <p>
                <a href="javascript:void(0)" id="reShowForm" title="Mostra nuovamente il form">
                    <i class="fa fa-arrow-left"></i> <?php echo ($this->messageShowForm) ? $this->messageShowForm : 'Torna al form' ?>
                </a>
            </p>
        </div>
    <?php endif; ?>

    <?php if ($this->showLinkResetFormAndShowIt): ?>
        <!-- Clear form fields and show form again -->
        <div>
            <p>
                <a href="javascript:void(0)" id="showForNewInsert" title="Inserisci un nuovo record">
                    <i class="fa fa-plus-circle"></i> Inserisci un nuovo elemento
                </a>
            </p>
        </div>
    <?php endif; ?>

    <?php if ($this->attachmentsLink): ?>
        <div id="attachmentsManagementLink">
            <p>
                <a href="<?php echo $this->attachmentsLink ?>" title="Vai alla gestione allegati">
                    <i class="fa fa-paperclip"></i> Allegati
                </a>
            </p>
        </div>
    <?php endif; ?>

    <?php if ($this->backToSummaryLink): ?>
        <div id="backToSummary">
            <p>
                <a href="<?php echo $this->backToSummaryLink ?>" title="Torna all'elenco dati del modulo corrente">
                    <i class="fa fa-list"></i> <?php echo ($this->backToSummaryText) ? $this->backToSummaryText : "Torna all'elenco dati" ?>
                </a>
            </p>
        </div>
    <?php endif; ?>

    <?php if (isset($this->attachmentFilesModule)): ?>
        <p>
            <a href="<?php echo $this->attachmentLink; ?>" title="Completa gestione allegati">
                <i class="fa fa-paperclip"></i> Vai alla gestione allegati per completare la rettifica
            </a>
        </p>
    <?php endif; ?>

    <?php if ($this->redirectRouteTableSetter): ?>
        <?php
        $routeParams = $this->params()->fromRoute('admin/datatable', array('lang'=>'it','tablesetter' => $this->redirectRouteTableSetter) );
        $urlRedirect = str_replace('//', '/', $this->url('admin/datatable', array('lang' => $routeParams['lang'], 'tablesetter' => $routeParams['tablesetter'])));
        ?>
        <div id="showFormContainer">
            &raquo; <a href="<?php echo $urlRedirect ?>" title="Torna all'elenco \ riepilogo dati">Torna all'elenco</a>
        </div>
    <?php endif; ?>
</div>

<div>&nbsp;</div>

<script>
$('#reShowForm').click(function() {
    $('#formcontainer').show();
    $('input:submit').attr('disabled', false);
    $('#showFormContainer').hide();

    $("#formdataresultmessage").fadeOut("slow", function () {
        $("#formdataresultmessage").remove();
    });
});

$('#showForNewInsert').click(function() {

    clear_form_elements('formcontainer');

    $('#formcontainer').show();
    $('input:submit').attr('disabled', false);
    $('#showFormContainer').hide();

    $("#formdataresultmessage").fadeOut("slow", function () {
        $("#formdataresultmessage").remove();
    });
});
</script>
