<ul class="breadcrumb">
    <li>
        <a href="<?php echo $this->url('admin', array('lang' => $this->params()->fromRoute('lang'))); ?>" title="Home page">
            Home
        </a>
    </li>
    <li class="active">Accesso non autorizzato</li>
</ul>

<div class="alert alert-danger">
    <h4>Accesso non autorizzato</h4>
    <p>Si &egrave; registrato un tentativo ad un accesso ad una pagina per cui non si posseggono i permessi per l'accesso.</p>
    <p>Se si desidera o si pensa di dover avere accesso a questa pagina, si prega di contattare l'amministrazione del sito.</p>
</div>