<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Setup\Module'                        => __DIR__ . '/Module.php',
    'Setup\Controller\SetupController' => __DIR__ . '/src/Setup/Controller/SetupController.php',
    'SetupTest\Framework\TestCase'        => __DIR__ . '/tests/Setup/Framework/TestCase.php',
    'SetupTest\SampleTest'                => __DIR__ . '/tests/Setup/SampleTest.php',
);
