<?php if ($this->pageCount): ?>
    <?php
    $paginationParameters = array_filter(array(
        'lang'              => $this->lang,
        'tablesetter'       => $this->tablesetter,
        'pageCount'         => $this->current,
        'category'          => $this->category,
        'order_by'          => $this->order_by,
        'order'             => $this->order,
        'languageSelection' => $this->languageSelection,
        'modulename'        => $this->modulename,
    ));
    ?>
    <div class="pagination pagination-centered">
        <ul class="pagination">
            <li<?php echo !isset($this->previous) ? ' class="disabled"' : ''; ?>>
                <a href="<?php echo $this->url($this->route, array_merge($paginationParameters, array('page'=> $this->first))); ?>" title="Prima pagina">&laquo;</a></li>
            <li<?php echo !isset($this->previous) ? ' class="disabled"' : ''; ?>>
                <a href="<?php echo $this->url($this->route, array_merge($paginationParameters, array('page'=> $this->previous))); ?>" title="Pagina precedente">&lsaquo;</a></li>

            <!-- Numbered page links -->
            <?php foreach ($this->pagesInRange as $page): ?>
                <li<?php echo $page == $this->current ? ' class="active"' : ''; ?>><a href="<?php echo $this->url($this->route, array_merge($paginationParameters, array('page'=>$page))); ?>" title="Vai a pagina <?php echo $page; ?>">
                    <?php echo $page; ?>
                </a></li>
            <?php endforeach; ?>

            <!-- Next page link -->
            <li<?php echo !isset($this->next) ? ' class="disabled"' : ''; ?>>
                <a href="<?php echo $this->url($this->route, array_merge($paginationParameters, array('page'=>$this->next))); ?>" title="Pagina successiva">&rsaquo;</a></li>
            <!-- Last page link -->
            <li<?php echo !isset($this->next) ? ' class="disabled"' : ''; ?>>
                <a href="<?php echo $this->url($this->route, array_merge($paginationParameters, array('page'=> $this->last))); ?>" title="Ultima pagina">&raquo;</a></li>
        </ul>
    </div>
<?php endif; ?>