<?php if ($this->pageCount): ?>
    <div class="pagination pagination-centered">
        <ul class="pagination">
            <li <?php echo!isset($this->previous) ? 'class="disabled"' : ''; ?>>
                <a href="<?php echo $this->url($this->route, array('page' => $this->first, 'category' => $this->category, 'order_by' => $this->order_by, 'order' => $this->order,)); ?>" title="Prima pagina">&laquo;</a></li>
            <li <?php echo!isset($this->previous) ? 'class="disabled"' : ''; ?>>
                <a href="<?php echo $this->url($this->route, array('page' => $this->previous, 'category' => $this->category, 'order_by' => $this->order_by, 'order' => $this->order,)); ?>" title="Ultima pagina">&lsaquo;</a></li>

            <!-- Numbered page links -->
            <?php foreach ($this->pagesInRange as $page): ?>
                <li <?php echo $page == $this->current ? 'class="active"' : ''; ?>><a href="<?php echo $this->url($this->route, array('page' => $page, 'category' => $this->category, 'order_by' => $this->order_by, 'order' => $this->order,)); ?>" title="Vai a pagina <?php echo $page; ?>">
                        <?php echo $page; ?>
                    </a></li>
            <?php endforeach; ?>

            <!-- Next page link -->
            <li <?php echo !isset($this->next) ? 'class="disabled"' : ''; ?>>
                <a href="<?php echo $this->url($this->route, array('page' => $this->next, 'order_by' => $this->order_by, 'order' => $this->order,)); ?>">&rsaquo;</a></li>
            <!-- Last page link -->
            <li <?php echo!isset($this->next) ? 'class="disabled"' : ''; ?>>
                <a href="<?php echo $this->url($this->route, array( 'page' => $this->last, 'order_by' => $this->order_by, 'order' => $this->order,)); ?>">&raquo;</a></li>
        </ul>
    </div>
<?php endif; ?>