<ul class="breadcrumb">
    <li><a href="<?php echo $this->basepath() ?>/" title="Home page">Home</a> <span class="divider"></span></li>
    <li><a href="<?php echo $this->basepath()."/".$this->category_seo ?>" title="Vai a <?php echo $this->category; ?>"><?php echo $this->category; ?></a></li>
    <li class="active"><?php echo $this->title ?></li>
</ul>

<?php foreach($this->paginator as $key => $row): ?>
<div class="blog_details">

    <h1><?php echo utf8_encode($row['title']) ?></h1>

    <div><?php echo utf8_encode($row['description']) ?></div>
    
    <?php if ($row['flagAttachments'] == 'si'): ?>

    <?php endif; ?>

    <br>
    <p class="text-right">
        <img src="<?php echo $this->basepath() ?>/public/common/icons/export.gif" alt="Icona file esportazione"> Esporta:
        <a href="#" title="Esporta in formato testo"><img src="<?php echo $this->basepath() ?>/public/common/icons/txt.png" alt="Icona file di testo"></a>
        <a href="#" title="Esporta in formato CSV"><img src="<?php echo $this->basepath() ?>/public/common/icons/csv.gif" alt="Icona CSV"></a>
        <a href="#" title="Esporta in formato PDF"><img src="<?php echo $this->basepath() ?>/public/common/icons/pdf.gif" alt="Icona PDF"></a>
        <br>
        <br>
        <img src="<?php echo $this->basepath() ?>/public/common/icons/share.gif" alt="Icona file condivisione"> Condividi: <a href="https://www.facebook.com/sharer/sharer.php?u=<?php echo $this->currentUrl; ?>" title="Condividi su facebook" onclick="javascript:window.open(this.href, '', 'menubar=no,toolbar=no,resizable=yes,scrollbars=yes,height=300,width=600');return false;"><img src="<?php echo $this->basepath() ?>/public/common/icons/facebook.gif" alt="Icona Facebook"></a>
        <a href="http://twitter.com/share?text=<?php echo urlencode($record['titolo']) ?>&amp;url=<?php echo $this->currentUrl; ?>"><img src="<?php echo $this->basepath() ?>/public/common/icons/twitter.gif" alt="Icona Twitter"></a>
        <a href="https://plus.google.com/share?url=<?php echo $this->currentUrl; ?>" title="Condividi su google plus"><img src="<?php echo $this->basepath() ?>/public/common/icons/google-plus.png" alt="Icona Google Plus"></a>
    </p>

    <hr>

</div>
<?php endforeach; ?>
