<div class="sixteen columns mb0">
	<div class="gdl-page-title-wrapper">
		<h1 class="gdl-page-title gdl-title title-color"><?php echo $templateData['controllerResult']['title'] ?></h1>
		<div class="gdl-page-caption"></div>
		<div class="gdl-page-title-left-bar"></div>
		<div class="clear"></div>
	</div>
</div>

<div class="gdl-page-float-left">
	<div class='gdl-page-item'>
		<div class="sixteen columns mt0">
			<div class="gdl-page-content">
			
			<p><strong><a href="<?=$templateData['remotelinkWeb'].$templateData['languageAbbreviation']?>" title="Home page">Home</a> &raquo; <?php echo $templateData['categoryName'] ?></strong> <?php if ($templateData['categoryName'] != $templateData['controllerResult']['title']): ?>&raquo; <?php echo $templateData['controllerResult']['title'] ?><?php endif; ?></p>

			<div><?php echo $templateData['controllerResult']['description'] ?></div>

			<div style="clear:both; height: 20px"></div>

			</div>
		</div>
	</div>
</div>

<div class="five columns mt0 gdl-right-sidebar">
	<div class="right-sidebar-wrapper gdl-divider">
		<?php
		echo $this->partial( $templateData['templatedir'].'sidebar.phtml');
		?>
		<div class="pt30"></div>
	</div>
</div>
