<!doctype>
<html>
<head>
    <title>Pagina non trovata</title>

    <link rel="stylesheet" href="//netdna.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap.min.css">
    <link rel="stylesheet" href="//netdna.bootstrapcdn.com/font-awesome/3.2.1/css/font-awesome.min.css">

    <style>
        body { background-image: url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABoAAAAaCAYAAACpSkzOAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAALEgAACxIB0t1+/AAAABZ0RVh0Q3JlYXRpb24gVGltZQAxMC8yOS8xMiKqq3kAAAAcdEVYdFNvZnR3YXJlAEFkb2JlIEZpcmV3b3JrcyBDUzVxteM2AAABHklEQVRIib2Vyw6EIAxFW5idr///Qx9sfG3pLEyJ3tAwi5EmBqRo7vHawiEEERHS6x7MTMxMVv6+z3tPMUYSkfTM/R0fEaG2bbMv+Gc4nZzn+dN4HAcREa3r+hi3bcuu68jLskhVIlW073tWaYlQ9+F9IpqmSfq+fwskhdO/AwmUTJXrOuaRQNeRkOd5lq7rXmS5InmERKoER/QMvUAPlZDHcZRhGN4CSeGY+aHMqgcks5RrHv/eeh455x5KrMq2yHQdibDO6ncG/KZWL7M8xDyS1/MIO0NJqdULLS81X6/X6aR0nqBSJcPeZnlZrzN477NKURn2Nus8sjzmEII0TfMiyxUuxphVWjpJkbx0btUnshRihVv70Bv8ItXq6Asoi/ZiCbU6YgAAAABJRU5ErkJggg==);}
        .error-template {padding: 40px 15px;text-align: center;}
        .error-actions {margin-top:15px;margin-bottom:15px;}
        .error-actions .btn { margin-right:10px; }
    </style>
</head>
<body>

    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="error-template">
                    <h1>Pagina non trovata!</h1>
                    <div class="error-details">
                        La pagina richiesta non &egrave; stata trovata
                    </div>
                    <div class="error-actions">
                        <a href="<?php echo $this->basePath() ?>" class="btn btn-primary btn-lg"><span class="glyphicon glyphicon-home"></span>
                            Torna alla home page
                        </a>
                    </div>
                </div>
            </div>
        </div>
    </div>


    <?php if (isset($this->reason) && $this->reason): ?>

        <h1><?php echo $this->translate('A 404 error occurred') ?></h1>

        <h2><?php echo $this->message ?></h2>
        <?php
        $reasonMessage= '';
        switch ($this->reason) {
            case 'error-controller-cannot-dispatch':
                $reasonMessage = $this->translate('The requested controller was unable to dispatch the request.');
                break;
            case 'error-controller-not-found':
                $reasonMessage = $this->translate('The requested controller could not be mapped to an existing controller class.');
                break;
            case 'error-controller-invalid':
                $reasonMessage = $this->translate('The requested controller was not dispatchable.');
                break;
            case 'error-router-no-match':
                $reasonMessage = $this->translate('The requested URL could not be matched by routing.');
                break;
            default:
                $reasonMessage = $this->translate('We cannot determine at this time why a 404 was generated.');
                break;
        }
        ?>

        <p><?php echo $reasonMessage ?></p>

    <?php endif ?>

    <?php if (isset($this->controller) && $this->controller): ?>

        <dl>
            <dt><?php echo $this->translate('Controller') ?>:</dt>
            <dd><?php echo $this->escapeHtml($this->controller) ?>
                <?php
                if (isset($this->controller_class)
                    && $this->controller_class
                    && $this->controller_class != $this->controller
                ) {
                    echo '(' . sprintf($this->translate('resolves to %s'), $this->escapeHtml($this->controller_class)) . ')';
                }
                ?>
            </dd>
        </dl>

    <?php endif ?>

    <?php if (isset($this->display_exceptions) && $this->display_exceptions): ?>

        <?php if(isset($this->exception) && $this->exception instanceof Exception): ?>
            <hr/>
            <h2><?php echo $this->translate('Additional information') ?>:</h2>
            <h3><?php echo get_class($this->exception); ?></h3>
            <dl>
                <dt><?php echo $this->translate('File') ?>:</dt>
                <dd>
                    <pre class="prettyprint linenums"><?php echo $this->exception->getFile() ?>:<?php echo $this->exception->getLine() ?></pre>
                </dd>
                <dt><?php echo $this->translate('Message') ?>:</dt>
                <dd>
                    <pre class="prettyprint linenums"><?php echo $this->exception->getMessage() ?></pre>
                </dd>
                <dt><?php echo $this->translate('Stack trace') ?>:</dt>
                <dd>
                    <pre class="prettyprint linenums"><?php echo $this->exception->getTraceAsString() ?></pre>
                </dd>
            </dl>
            <?php
            $e = $this->exception->getPrevious();
            if ($e) :
                ?>
                <hr/>
                <h2><?php echo $this->translate('Previous exceptions') ?>:</h2>
                <ul class="unstyled">
                    <?php while($e) : ?>
                        <li>
                            <h3><?php echo get_class($e); ?></h3>
                            <dl>
                                <dt><?php echo $this->translate('File') ?>:</dt>
                                <dd>
                                    <pre class="prettyprint linenums"><?php echo $e->getFile() ?>:<?php echo $e->getLine() ?></pre>
                                </dd>
                                <dt><?php echo $this->translate('Message') ?>:</dt>
                                <dd>
                                    <pre class="prettyprint linenums"><?php echo $e->getMessage() ?></pre>
                                </dd>
                                <dt><?php echo $this->translate('Stack trace') ?>:</dt>
                                <dd>
                                    <pre class="prettyprint linenums"><?php echo $e->getTraceAsString() ?></pre>
                                </dd>
                            </dl>
                        </li>
                        <?php
                        $e = $e->getPrevious();
                    endwhile;
                    ?>
                </ul>
            <?php endif; ?>

        <?php else: ?>

            <h3><?php echo $this->translate('No Exception available') ?></h3>

        <?php endif ?>

    <?php endif ?>

</body>
</html>