<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Feed\Module'                         => __DIR__ . '/Module.php',
    'Feed\Controller\FeedController'      => __DIR__ . '/src/Feed/Controller/FeedController.php',
    'Feed\Model\AlboPretorioFeedResource' => __DIR__ . '/src/Feed/Model/AlboPretorioFeedResource.php',
    'Feed\Model\FeedBuilderAbstract'      => __DIR__ . '/src/Feed/Model/FeedBuilderAbstract.php',
);
