<?php
// Generated by ZF2's ./bin/templatemap_generator.php
return array(
    'feed/feed/foo'   => __DIR__ . '/view/feed/feed/foo.phtml',
    'feed/feed/index' => __DIR__ . '/view/feed/feed/index.phtml',
);
