<?php

$form = $this->form;
$form->prepare();

$form->setAttribute('action', '');
$form->setAttribute('method', 'post');
$form->setAttribute('role', 'form');
$form->setAttribute('class', 'form-horizontal');

$formLabel = $this->plugin('formLabel');

echo $this->form()->openTag($this->form);

foreach ($this->form as $element):
    $attributes = $element->getAttributes();
    echo $this->formElementErrors($element);
    if ($attributes['name'] == 'csrf'):
        echo $this->formElement($element);
    elseif ($attributes['type'] == 'submit'):
    ?>
    <div class="form-group">
        <label class="col-sm-2 control-label">&nbsp;</label>
        <div class="col-sm-10">
        <?php
        $element->setAttribute('class', 'btn btn-primary');
        echo $this->formElement($element);
        ?>
        </div>
    </div>
    <?php
    else:
    ?>
    <div class="form-group">
        <label for="<?php echo $attributes['id'] ?>" class="col-sm-2 control-label"><?php echo $element->getLabel() ?>:</label>
        <div class="col-sm-10">
        <?php
        $element->setAttribute('class', 'form-control');
        echo $this->formElement($element);
        ?>
        </div>
    </div>
    <?php
    endif;
endforeach;

echo $this->form()->closeTag();
