<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('ZF2 '. $this->translate('Skeleton Application'))->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                        ->prependStylesheet($this->basePath() . '/common/bootstrap2/css/bootstrap.min.css')
                        ->prependStylesheet($this->basePath() . '/frontend/css/bootstrap.min.css')
        ?>

    <!-- Scripts -->
    
    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
      <script src="https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"></script>
    <![endif]-->
    
        <?php echo $this->headScript()
            ->prependFile($this->basePath() . '/frontend/js/bootstrap.min.js')
            ->prependFile($this->basePath() . '/frontend/js/jquery.js')
        ; ?>

    </head>
    <body>

	<!-- Fixed navbar -->
	<div class="navbar navbar-default navbar-fixed-top" role="navigation">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="#" title="">Comment system</a>
        </div>
        <div class="navbar-collapse collapse">
          <ul class="nav navbar-nav">
            <li class="active"><a href="<?php echo $this->url('home') ?>" title="Home page">Home</a></li>
        </div>
      </div>
    </div>
    
    <div class="container">

	<?php // echo $this->content; ?>
	<?php echo $this->partial('frontend/templates/fossobandito/default/index.phtml'); ?>

	<hr>

	<footer>
		<p>&copy; <?php echo date('Y') ?> Andrea Fiori</p>
	</footer>
	
    </div>
	
	<?php echo $this->inlineScript() ?>
	
    </body>
</html>