
<div class="templateColumn">
    <?php

    foreach($this->sezioni as $sezione):

        switch($sezione['moduleCode']):

            default: case("contenuti"):

            if (isset($sezione['sottosezioni'])):
                ?>
                <h2 class="sezioniTitle">
                    <?php if ($sezione['image']!=''): ?>
                        <img src="<?php echo $this->publicDirRelativePath ?>/common/icons/<?php echo $sezione['image'] ?>" alt="Icona per <?php echo strtoupper( html_entity_decode($sezione['nome'], ENT_COMPAT, 'UTF-8') ); ?>">
                    <?php endif; ?>

                    <?php if ($sezione['url']!=''): ?>
                        <a href="<?php echo htmlentities($sezione['url']) ?>" title="<?php echo strtoupper( html_entity_decode($sezione['nome'], ENT_COMPAT, 'UTF-8') ); ?> [apre in un'altra pagina]" target="_blank">
                            <img src="<?php echo $this->publicDirRelativePath ?>/frontend/projects/entilocali/templates/telti/assets/images/external-link-icon.gif" alt="Apre in un'altra finestra">
                            <?php echo strtoupper(html_entity_decode($sezione['nome'], ENT_COMPAT, 'UTF-8')); ?>
                        </a>
                    <?php else: ?>
                        <?php echo strtoupper( html_entity_decode($sezione['nome'], ENT_COMPAT, 'UTF-8')); ?>
                    <?php endif; ?>
                </h2>

                <ul class="side-nav">
                    <?php
                    foreach($sezione['sottosezioni'] as $sottoSezione):

                        if ( \preg_match("/^http/i", $sottoSezione['url']) ):
                            $target = "_blank";
                        endif;

                        if ($sottoSezione['url']):
                            ?>
                            <li><a href="<?php echo htmlentities($sottoSezione['url']) ?>"<?php if (isset($target)): ?> target="<?php echo $target ?>"<?php endif ?> title="<?php echo isset($sottoSezione['urlTitle']) ? utf8_encode($sottoSezione['urlTitle']) : 'Vai alla sezione '.utf8_encode($sottoSezione['nomeSottoSezione']) ?>">
                                    <?php if (isset($target)): ?>
                                        <img src="<?php echo $this->publicDirRelativePath ?>/frontend/projects/entilocali/templates/telti/assets/images/external-link-icon.gif" alt="Apre in un'altra finestra">
                                    <?php endif ?>
                                    <?php echo utf8_encode($sottoSezione['nomeSottoSezione']) ?>
                                </a>
                            </li>
                        <?php
                        else:
                            ?>
                            <li><a href="<?php echo $this->url('main/contenuti', array('lang' => $this->lang, 'subsectionid' => $sottoSezione['idSottoSezione'])) ?>" title="<?php echo isset($sottoSezione['urlTitle']) ? utf8_encode($sottoSezione['urlTitle']) : 'Vai alla sezione '.utf8_encode($sottoSezione['nomeSottoSezione']) ?>"><?php echo utf8_encode($sottoSezione['nomeSottoSezione']) ?></a></li>
                        <?php
                        endif;

                    endforeach;
                    ?>
                </ul>
            <?php
            endif;

            break;

            case('atti-concessione'):
                ?>
                <h2>
                    <?php if ($sezione['image']!=''): ?>
                        <img src="<?php echo $this->publicDirRelativePath ?>/common/icons/<?php echo $sezione['image'] ?>" alt="Icona per <?php echo strtoupper( html_entity_decode($sezione['nome'], ENT_COMPAT, 'UTF-8') ); ?>">
                    <?php endif; ?>

                    <?php echo strtoupper( html_entity_decode($sezione['nome'], ENT_COMPAT, 'UTF-8') ); ?>
                </h2>
                <ul class="side-nav">
                    <li><a href="<?php echo $this->url('amministrazione-trasparente', array('profondita' => 200)) ?>">Amministrazione trasparente</a></li>
                </ul>
                <?php
                break;

            case("blogs"):
                ?>
                <h2 class="sezioniTitle">BLOGS</h2>

                <ul class="side-nav">
                    <li><a href="<?php echo $this->url('main/blogs-categories', array('lang' => $this->lang, 'category' => 'eventi')) ?>" title="Leggi elenco articoli 'Eventi'">Eventi</a></li>
                    <li><a href="<?php echo $this->url('main/blogs-categories', array('lang' => $this->lang, 'category' => 'news')) ?>" title="Leggi elenco articoli 'News'">News</a></li>
                    <li><a href="<?php echo $this->url('main/blogs-categories', array('lang' => $this->lang, 'category' => 'rassegna-stampa')) ?>" title="Leggi elenco articoli 'Rassegna stampa'">Rassegna stampa</a></li>
                </ul>
                <?php
            break;

            case('community'):
                ?>
                <form action="#" method="post" id="frmCommunity">
                    <fieldset>
                        <legend><img src="<?php echo $this->publicDirRelativePath ?>/common/icons/<?php echo $sezione['image'] ?>" alt="Icona per <?php echo strtoupper( html_entity_decode($sezione['nome'], ENT_COMPAT, 'UTF-8') ); ?>"> <?php echo strtoupper( html_entity_decode($sezione['nome'], ENT_COMPAT, 'UTF-8') ); ?></legend>

                        <label for="username">Nome utente
                            <input type="text" placeholder="Nome utente..." id="username" required="required" title="Inserisci nome utente">
                        </label>

                        <label for="password">Password
                            <input type="password" placeholder="Password..." id="password" required="required" title="Inserisci password">
                        </label>

                        <label>
                            <input type="submit" id="loginButton" name="login" value="Accedi" title="Clicca per accedere all'area riservata" class="button tiny">
                        </label>

                        <div>&raquo; <a href="<?php echo $this->url('registrazione', array()); ?>" title="Registrati come nuovo utente">Registrati</a></div>
                        <div>&raquo; <a href="<?php echo $this->url('recupero-password', array()); ?>" title="Recupero password area riservata">Recupero password</a></div>
                    </fieldset>
                </form>
                <?php
                break;

        endswitch;

    endforeach;

    ?>
</div>
