    <div class="row">
        <div class="medium-4 large-4 columns">
        <h2><?php echo $this->translate('Informazioni'); ?></h2>
        <ul>
            <li><a href="<?php echo $this->url('main', array('category' => 'info', 'title' => 'note-legali')) ?>" title="Note Legali <?php $this->sitename ?>">Note Legali</a></li>
            <li><a href="<?php echo $this->url('main', array('category' => 'info', 'title' => 'accessibilita')) ?>" title="">Accessiblit&agrave;</a></li>
            <li><a href="http://104.245.33.210/~serviziokronoweb/co/cms_co/?comune=telti" target="_blank" title="Continuit&agrave; operativa <?php echo $this->sitename ?> [apre in un'altra pagina]">Continuit&agrave; operativa</a></li>
            <li><a href="<?php echo $this->url('main', array('category' => 'info', 'title' => 'privacy')) ?>" title="Privacy informativa">Privacy</a></li>
            <li><a href="<?php echo $this->url('main', array('category' => 'info', 'title' => 'credit')) ?>" title="Credits del progetto">Credit</a></li>
            <li><a href="<?php echo $this->url('main', array('category' => 'info', 'title' => 'mobile')) ?>" title="Visualizzazione sito su tutti i dispositivi">Mobile</a></li>
        </ul>
        </div>

        <div class="medium-4 large-4 columns">
        <h2><?php echo $this->translate('Accessibilit&agrave;'); ?></h2>
        <ul>
            <?php if ($this->cssName!='default' and $this->cssName!=''): ?>
            <li><a href="<?php echo $this->url('css-style-switch', array('cssname' => 'default')) ?>" title="Torna alla visualizzazione del sito grafico">Sito grafico</a></li>
            <?php endif; ?>

            <?php if ($this->cssName!='text'): ?>
                <li>
                    <a href="<?php echo $this->url('css-style-switch', array('cssname' => 'text')) ?>" title="Passa alla visualizzazione solo testo">
                        <?php echo $this->translate('Sito testuale') ?>
                    </a>
                </li>
            <?php endif; ?>

            <?php if ($this->cssName!='rosso-su-nero'): ?>
            <li>
                <a href="<?php echo $this->url('css-style-switch', array('cssname' => 'rosso-su-nero')) ?>" title="Passa alla visualizzazione <?php echo $this->translate('Rosso su nero'); ?>">
                    <?php echo $this->translate('Rosso su nero'); ?>
                </a>
            </li>
            <?php endif; ?>

            <?php if ($this->cssName!='high-visibility'): ?>
                <li>
                    <a href="<?php echo $this->url('css-style-switch', array('cssname' => 'high-visibility')) ?>" title="Passa alla visualizzazione ad alta visibilit&agrave;">
                        <?php echo $this->translate('Alta visibilit&agrave;') ?>
                    </a>
                </li>
            <?php endif; ?>

            <li>
                <a href="#" title="Elenco accessi da tastiera (Shortcut)">
                    <?php echo $this->translate('Accesso da tastiera') ?>
                </a>
            </li>
            <li>
                <a href="#" title="<?php echo $this->translate('Dichiarazione di accessibilit&agrave; Legge Stanca'); ?>">
                    <?php echo $this->translate('Dichiarazione di accessibilit&agrave;'); ?>
                </a>
            </li>
        </ul>
        </div>

        <div class="medium-4 large-4 columns">
        <h2>Kronoweb ITC </h2>
        <p>
            Partita IVA 01848120901<br>
            R.E.A 143513 C.C.I.A.A<br><br>
            <strong>Sede Legale</strong>: Via IV Novembre, 28 - 07100 Sassari (SS)<br>
            Tel: 079 272120 - Cell: 3465753065
        </p>
        </div>
    </div>

    <footer>
        <div class="large-12 columns"><hr>
            <div>
                <div class="large-6 columns">
                    <p>&copy; <?php echo date("Y") ?> <?php echo $this->sitename ?></p>
                </div>

                <div class="large-6 small-12 columns">
                    <ul class="inline-list right">
                        <li><a href="http://www.kronoweb.it" target="_blank" title="Vai al sito della Kronoweb.it ICT [apre in un'altra pagina]">Kronoweb ICT</a></li>
                        <li><a href="http://validator.w3.org/check?uri=referer" title="Validate HTML [apre in un'altra pagina]" target="_blank">Valid HTML5</a></li>
                        <li><a href="http://jigsaw.w3.org/css-validator/check/referer" title="Validate CSS [apre in un'altra pagina]" target="_blank">Valid CSS</a></li>
                    </ul>
                </div>
            </div>
        </div>
    </footer>
