<?php echo $this->doctype(); ?>
<html lang="it" class="no-js">
<head>
<meta charset="utf-8">
<?php echo $this->headTitle($this->sitename)->setSeparator(' - ')->setAutoEscape(false) ?>
<meta name="viewport" content="width=device-width, initial-scale=1.0" />
<meta name="description" content="<?php echo $this->description ?>">
<meta name="keywords" content="<?php echo $this->keywords ?>">

<?php if (!$this->cssName or $this->cssName == 'default'): ?>
<link href="<?php echo $this->publicDirRelativePath ?>/common/foundation/css/foundation.min.css" media="screen" rel="stylesheet" type="text/css">
<?php elseif($this->cssName=='rosso-su-nero'): ?>
<link href="<?php echo $this->publicDirRelativePath ?>/common/css/red_on_black.css" media="screen" rel="stylesheet" type="text/css">
<?php elseif($this->cssName=='high-visibility'): ?>
<link href="<?php echo $this->publicDirRelativePath ?>/common/css/high_visibility.css" media="screen" rel="stylesheet" type="text/css">
<?php elseif($this->cssName=='text'): ?>

<?php endif; ?>

<link href="<?php echo $this->publicDirRelativePath ?>/frontend/projects/favicon.ico" rel="shortcut icon" type="image/vnd.microsoft.icon">
<script src="<?php echo $this->publicDirRelativePath ?>/common/foundation/js/vendor/modernizr.js"></script>

<!--[if lt IE 9]>
    <link rel="stylesheet" href="<?php echo $this->publicDirRelativePath ?>/common/foundation/css/ie.css">
<![endif]-->

<style>
table { width: 100% }

.hidden {
    display: none;
}

.templateColumn h1 {
    font-size: 120%;
}

.fullWidth {
    width: 100%;
    margin-left: auto;
    margin-right: auto;
    max-width: initial;
}

.sezioniTitle {
    font-size: 120%;
}

.formElementUlList {
    list-style-type: none;
    padding: 0;
    margin-left: 0;
}

.formElementUlList li {
    color: #cc0000;
}

@media only screen and (min-width: 768px) {
    .pull-left {float: left !important;}
    .pull-right {float: right !important;}
}

.redString {
    color: #d14;
}

.blueString {
    color: #000080;
}

.imageLeft {
    margin-right: 1%;
    max-width: 250px;
}
aside h2 {
    font-size: 100%;
}
</style>

<!-- HTML5 shim, for IE6-8 support of HTML5 elements -->
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

<?php if (!$this->cssName or $this->cssName == 'default'): ?>
<style>
.hidden {
    display: none;
}

.templateColumn h1 {
    font-size: 120%;
}

.fullWidth {
    width: 100%;
    margin-left: auto;
    margin-right: auto;
    max-width: initial;
}

.sezioniTitle {
    font-size: 120%;
}

.formElementUlList {
    list-style-type: none;
    padding: 0;
    margin-left: 0;
}

.formElementUlList li {
    color: #cc0000;
}

.cookieWarning {
    padding: 1.2em 0 0 0;
}
</style>
<?php endif; ?>

<script src="<?php echo $this->publicDirRelativePath ?>/common/jquery/jquery.min.js"></script>

</head>

<body>

<?php if ($this->passwordPreviewArea): ?>
    <div class="alert-box info text-center" id="previewAreaAlert">
        <strong>Anteprima <?php echo $this->sitename ?>.
            <a href="<?php echo $this->url('password-preview-logout', array('action' => 'logout')); ?>" title="Uscita area risevata">Uscita</a>
        </strong>
        <a href="#" class="close" onclick="$('#previewAreaAlert').hide();" title="Nascondi avviso">&times;</a>
    </div>
<?php endif; ?>

<?php if ($this->cookieWarning!=1): ?>
    <div class="alert-box secondary text-center cookieWarning" id="previewAreaAlert">Questo sito utilizza cookie di sessione e di profilazione di terze parti per le sue funzionalit&agrave;. Se vuoi saperne di pi&ugrave; o negare il consenso a tutti o ad alcuni cookie, consulta la nostra <a href="#" title="Leggi la privacy policy">privacy policy</a>. Continuando la navigazione o chiudendo questo avviso, acconsenti all'utilizzo dei cookie. <a href="<?php echo $this->url('cookie-warning-confirm', array('action' => 'confirm')); ?>" class="button tiny">OK ho capito</a> <a href="#" class="button warning tiny">Maggiori informazioni</a>
    </div>
<?php endif; ?>

