<?php if ($this->cssName!='default' and $this->cssName!=''): ?>
    <div>&raquo; <a href="<?php echo $this->url('css-style-switch', array('cssname' => 'default')) ?>" title="Torna alla visualizzazione del sito grafico">Torna al sito grafico</a></div>
<?php endif; ?>

<div class="large-12 columns">
    
    <div class="large-12 columns">
        <ul class="inline-list right">
            <li>
                <a href="#mainContents" accesskey="x" class="button small" title="<?php echo $this->translate('Salta ai contenuti'); ?>">
                    <?php echo $this->translate('Vai ai contenuti'); ?>
                </a>
            </li>
        </ul>
        <h1>
            <a href="<?php echo $this->basepath() ?>/" title="Torna alla home page di <?php echo $this->sitename ?>">
                <?php echo $this->sitename ?>
            </a>
        </h1>
    </div>

</div>

<hr class="hidden">

<div class="large-12 columns">
    <nav class="top-bar" data-topbar role="navigation">
        <ul class="title-area">
            <li class="name">
                <h2><a href="<?php echo $this->url('main', array('lang' => $this->lang)); ?>" title="Torna all'home page" accesskey="h">Home</a></h2>
            </li>

            <?php if (!$this->cssName or $this->cssName == 'default'): ?>
                <li class="toggle-topbar menu-icon"><a href="#"><span>Menu</span></a></li>
            <?php endif; ?>
        </ul>

        <section class="top-bar-section">

            <h2 class="hidden">Men&ugrave; navigazione</h2>

            <ul class="left">
                <?php if (!$this->cssName or $this->cssName == 'default'): ?>
                <li class="divider"></li>
                <?php endif; ?>

                <li><a href="<?php echo $this->url('albo-pretorio') ?>" title="Consultazione elenco atti albo pretorio">Albo pretorio</a></li>
                <?php if (!$this->cssName or $this->cssName == 'default'): ?>
                    <li class="divider"></li>
                <?php endif; ?>
                <li><a href="<?php echo $this->url('stato-civile') ?>" title="Pubblicazioni stato civile">Stato civile</a></li>
                <?php if (!$this->cssName or $this->cssName == 'default'): ?>
                    <li class="divider"></li>
                <?php endif; ?>
                <li><a href="<?php echo $this->url('contratti-pubblici') ?>" title="Elenco bandi di gara e contratti">Bandi e contratti</a></li>
                <?php if (!$this->cssName or $this->cssName == 'default'): ?>
                    <li class="divider"></li>
                <?php endif; ?>
                <li><a href="<?php echo $this->url('atti-concessione') ?>" title="Elenco atti di concessione">Atti di concessione</a></li>
                <?php if (!$this->cssName or $this->cssName == 'default'): ?>
                    <li class="divider"></li>
                <?php endif; ?>
                <li>
                    <a href="<?php echo $this->url('amministrazione-trasparente', array('profondita' => 200)) ?>" title="Articoli amministrazione trasparente">
                        Amministrazione trasparente
                    </a>
                </li>
            </ul>

            <ul class="right">

                <li class="has-form">
                    <div class="row collapse">
                        <?php

                        /* Search engine form */
                        $form = $this->searchEngineForm;
                        $form->prepare();

                        $formAction = $this->url('main/search-engine', array(
                            'lang' => $this->params()->fromRoute('lang') ? $this->params()->fromRoute('lang') : 'it',
                        ));

                        $formId = !empty($this->formId) ? $this->formId : 'searchEngineForm';

                        $form->setAttributes(array(
                            'action'    => $formAction,
                            'method'    => 'post',
                            'name'      => $formId,
                            'id'        => $formId,
                            'role'      => 'form',
                        ));

                        echo $this->form()->openTag($form);

                        ?>
                        <div class="large-8 columns">
                            <label for="searchtext">
                                <?php echo $this->formElement($form->get('searchtext')); ?>
                            </label>
                            <label>
                                <?php echo $this->formElement($form->get('csrf')); ?>
                            </label>
                        </div>
                        <div class="large-4 columns">
                            <button type="submit" class="alert button expand" title="<?php echo $this->translate('Cerca sul sito'); ?>">
                                <?php echo $this->translate('Cerca'); ?>
                            </button>
                        </div>

                        <?php echo $this->form()->closeTag(); ?>

                    </div>
                </li>

                <li class="has-dropdown">
                    <a href="javascript:void(0)" title="<?php echo $this->translate('Lingue disponibili'); ?>">
                        <?php echo $this->translate('Lingue'); ?>
                    </a>
                    <ul class="dropdown">
                        <li><a href="<?php echo $this->url('main', array('lang' => 'it')) ?>" title="Sito in lingua italiana">Italiano</a></li>
                        <li><a href="<?php echo $this->url('main', array('lang' => 'en')) ?>" title="Switch to English language">English</a></li>
                    </ul>
                </li>

                <li class="has-dropdown">
                    <a href="#" title="<?php echo $this->translate('Altri moduli') ?>"><?php echo $this->translate('Altri moduli') ?></a>
                    <ul class="dropdown">
                        <li><a href="#" title="Moduli Autocertificazioni"><?php echo $this->translate('Autocertificazioni') ?></a></li>
                        <li><a href="#" title="Servizi personalizzati per aziende"><?php echo $this->translate('Azienda') ?></a></li>
                        <li><a href="#" title="<?php echo $this->translate('Servizio SMS, invio messaggi') ?>"><?php echo $this->translate('Servizio SMS') ?></a></li>
                        <li><a href="#" title="<?php echo $this->translate('Servizio Meteo') ?>"><?php echo $this->translate('Meteo') ?></a></li>
                        <li><a href="#" title="Booking">Booking</a></li>
                        <li><a href="#" title="E-commerce">E-commerce</a></li>
                        <li><a href="#" title="<?php echo $this->translate('Iscrizione newsletter') ?>">Newsletter</a></li>
                        <li>
                            <a href="<?php echo $this->url('main/photo-gallery', array('lang' => ($this->lang) ? $this->lang : 'it')) ?>" title="Vai alla galleria fotografica">
                                <?php echo $this->translate('Galleria fotografica') ?>
                            </a>
                        </li>
                        <li>
                            <a href="<?php echo $this->url('main/contatti', array('lang' => ($this->lang) ? $this->lang : 'it')) ?>" title="Form contatti">
                                <?php echo $this->translate('Contatti') ?>
                            </a>
                        </li>
                    </ul>
                </li>

            </ul>

        </section>
    </nav>
</div>