<?php if ($this->cssName!='default' and $this->cssName!=''): ?>
    <div>&raquo; <a href="<?php echo $this->url('css-style-switch', array('cssname' => 'default')) ?>" title="Torna alla visualizzazione del sito grafico">Torna al sito grafico</a></div>
<?php endif; ?>

<div class="large-12 columns">
    
    <div class="large-12 columns">
        
        <ul class="inline-list right">
            <li><a href="#mainContents" accesskey="x" class="button small" title="Salta ai contenuti">Vai ai contenuti</a></li>
        </ul>
        
        <h1>
            <a href="<?php echo $this->basepath() ?>/" title="Torna alla home page di <?php echo $this->sitename ?>">
                <?php echo $this->sitename ?>
            </a>
        </h1>
        
    </div>
</div>

<hr class="hidden">

<div class="large-12 columns">
    <nav class="top-bar" data-topbar role="navigation">
        <ul class="title-area">
            <li class="name">
                <h2><a href="<?php echo $this->basepath() ?>/" title="Torna all'home page" accesskey="h">Home</a></h2>
            </li>

            <?php if (!$this->cssName or $this->cssName == 'default'): ?>
                <li class="toggle-topbar menu-icon"><a href="#"><span>Menu</span></a></li>
            <?php endif; ?>
        </ul>

        <section class="top-bar-section">

            <h2 class="hidden">Men&ugrave; navigazione</h2>

            <ul class="left">
                <?php if (!$this->cssName or $this->cssName == 'default'): ?>
                <li class="divider"></li>
                <?php endif; ?>

                <li><a href="<?php echo $this->url('albo-pretorio') ?>" title="Consultazione elenco atti albo pretorio">Albo pretorio</a></li>
                <?php if (!$this->cssName or $this->cssName == 'default'): ?>
                    <li class="divider"></li>
                <?php endif; ?>
                <li><a href="<?php echo $this->url('stato-civile') ?>" title="Pubblicazioni stato civile">Stato civile</a></li>
                <?php if (!$this->cssName or $this->cssName == 'default'): ?>
                    <li class="divider"></li>
                <?php endif; ?>
                <li><a href="<?php echo $this->url('contratti-pubblici') ?>" title="Elenco bandi di gara e contratti">Bandi e contratti</a></li>
                <?php if (!$this->cssName or $this->cssName == 'default'): ?>
                    <li class="divider"></li>
                <?php endif; ?>
                <li><a href="<?php echo $this->url('atti-concessione') ?>" title="Elenco atti di concessione">Atti di concessione</a></li>
                <?php if (!$this->cssName or $this->cssName == 'default'): ?>
                    <li class="divider"></li>
                <?php endif; ?>
                <li><a href="<?php echo $this->url('amministrazione-trasparente') ?>" title="Articoli amministrazione trasparente">Amministrazione trasparente</a></li>
            </ul>

            <ul class="right">

                <!--
                <li class="has-form">
                    <div class="row collapse">
                        <div class="large-8 small-9 columns">
                            <input type="text" name="search" placeholder="Cerca...">
                        </div>
                        <div class="large-4 small-3 columns">
                            <a href="#" class="alert button expand" title="Cerca sul sito">Cerca</a>
                        </div>
                    </div>
                </li>
                -->

                <li><a href="<?php echo $this->url('registrazione', array()); ?>" title="Registrati come nuovo utente">Registrati</a></li>

                <li class="has-dropdown">
                    <a href="#" title="Altri moduli">Altri moduli</a>
                    <ul class="dropdown">
                        <li><a href="#" title="Moduli Autocertificazioni">Autocertificazioni</a></li>
                        <li><a href="#" title="Servizi personalizzati per aziende">Azienda</a></li>
                        <li><a href="#" title="Servizio SMS, invio messaggi">Servizio SMS</a></li>
                        <li><a href="#" title="Servizio Meteo">Meteo</a></li>
                        <li><a href="#" title="Booking">Booking</a></li>
                        <li><a href="#" title="E-commerce">E-commerce</a></li>
                        <li><a href="#" title="Iscrizione newsletter">Newsletter</a></li>
                        <li><a href="<?php echo $this->url('posts-photo-gallery') ?>" title="Galleria fotografica e categorie di foto">Galleria fotografica</a></li>
                        <li><a href="<?php echo $this->url('contatti') ?>" title="Form contatti">Contatti</a></li>
                    </ul>
                </li>

            </ul>

        </section>
    </nav>
</div>
