<p class="text-right">
    <?php if ($this->exportTxtUrl or $this->exportCsvUrl or $this->exportPdfUrl or $this->exportJSONUrl): ?>
    <img src="<?php echo $this->publicDirRelativePath ?>/common/icons/export.gif" alt="<?php echo $this->translate('Icona file esportazione'); ?>"> <?php echo $this->translate('Esporta'); ?>:
    <?php if ($this->exportTxtUrl): ?>
    <a href="<?php echo $this->exportTxtUrl ?>" title="<?php echo $this->translate('Esporta in formato testo'); ?>"><img src="<?php echo $this->publicDirRelativePath ?>/common/icons/txt.png" alt="<?php echo $this->translate('Icona file di testo'); ?>"></a>
    <?php endif; ?>
    <?php if ($this->exportCsvUrl): ?>
    <a href="<?php echo $this->exportCsvUrl ?>" title="<?php echo $this->translate('Esporta in formato CSV'); ?>"><img src="<?php echo $this->publicDirRelativePath ?>/common/icons/csv.gif" alt="<?php echo $this->translate('Icona CSV'); ?>"></a>
    <?php endif; ?>
    <?php if ($this->exportPdfUrl): ?>
    <a href="<?php echo $this->exportPdfUrl ?>" title="<?php echo $this->translate('Esporta in formato PDF'); ?>"><img src="<?php echo $this->publicDirRelativePath ?>/common/icons/pdf.gif" alt="<?php echo $this->translate('Icona PDF'); ?>"></a>
    <?php endif; ?>
    <?php if ($this->exportJSONUrl): ?>
    <a href="<?php echo $this->exportJSONUrl ?>" title="<?php echo $this->translate('Esporta in formato JSON'); ?>"><img src="<?php echo $this->publicDirRelativePath ?>/common/icons/json.gif" alt="<?php echo $this->translate('Icona JSON'); ?>"></a>
    <?php endif; ?>
    <br>
    <br>
    <?php endif; ?>

    <img src="<?php echo $this->publicDirRelativePath ?>/common/icons/share.gif" alt="<?php echo $this->translate('Icona file condivisione'); ?>" title="<?php echo $this->translate('Icona file condivisione'); ?>"> <?php echo $this->translate('Condividi'); ?>: <a href="https://www.facebook.com/sharer/sharer.php?u=<?php echo $this->currentUrl; ?>" title="<?php echo $this->translate('Condividi su facebook'); ?>" onclick="javascript:window.open(this.href, '', 'menubar=no,toolbar=no,resizable=yes,scrollbars=yes,height=300,width=600');return false;"><img src="<?php echo $this->publicDirRelativePath ?>/common/icons/facebook.gif" alt="Icona Facebook"></a>
    <a href="http://twitter.com/share?text=<?php echo urlencode($twitterShareText) ?>&amp;url=<?php echo $this->currentUrl; ?>" title="<?php echo $this->translate('Condividi su Twitter'); ?>"><img src="<?php echo $this->publicDirRelativePath ?>/common/icons/twitter.gif" alt="<?php echo $this->translate('Icona Twitter'); ?>"></a>
    <a href="https://plus.google.com/share?url=<?php echo $this->currentUrl; ?>" title="<?php echo $this->translate('Condividi su Google Plus'); ?>"><img src="<?php echo $this->publicDirRelativePath ?>/common/icons/google-plus.png" alt="<?php echo $this->translate('Icona Google Plus'); ?>"></a>
</p>