
<?php
    echo $this->partial($this->templateDir.'_header');
    
    echo $this->partial($this->templateDir.'_navigation');
?>

<div class="large-12 columns">
    <br>
        <div class="large-12 columns">
            <div class="large-12 small-12 columns">
                <div id="mainContents"></div>
                <?php
                if (!empty($this->templatePartial)) {
                    echo $this->partial($this->templateDir.$this->templatePartial);
                }
                ?>
            </div>
        </div>
    <hr>

    <?php  echo $this->partial($this->templateDir.'_footer'); ?>
</div>

<script src="<?php echo $publicDirRelativePath ?>/common/foundation/js/foundation.min.js"></script>
<script src="<?php echo $publicDirRelativePath ?>/common/foundation/js/foundation/foundation.topbar.js"></script>
<script src="<?php echo $publicDirRelativePath ?>/common/foundation/js/responsive-tables.js"></script>
<script>
    $(document).foundation();
</script>

</body>
</html>