<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Admin\Module'                                         => __DIR__ . '/Module.php',
    'Admin\Controller\AdminController'                     => __DIR__ . '/src/Admin/Controller/AdminController.php',
    'Admin\Controller\AuthController'                      => __DIR__ . '/src/Admin/Controller/AuthController.php',
);
