<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Admin\Module'                                   => __DIR__ . '/Module.php',
    'Admin\Controller\AdminController'               => __DIR__ . '/src/Admin/Controller/AdminController.php',
    'Admin\Controller\AuthController'                => __DIR__ . '/src/Admin/Controller/AuthController.php',
    'Admin\Model\AdminDashboard'                     => __DIR__ . '/src/Admin/Model/AdminDashboard.php',
    'Admin\Model\AlboPretorio\AlboPretorioDataTable' => __DIR__ . '/src/Admin/Model/AlboPretorio/AlboPretorioDataTable.php',
    'Admin\Model\Assistenza\AssistenzaDataTable'     => __DIR__ . '/src/Admin/Model/Assistenza/AssistenzaDataTable.php',
    'Admin\Model\Assistenza\AssistenzaForm'          => __DIR__ . '/src/Admin/Model/Assistenza/AssistenzaForm.php',
    'Admin\Model\DataTable\DataTableAbstract'        => __DIR__ . '/src/Admin/Model/DataTable/DataTableAbstract.php',
    'Admin\Model\DataTable\DataTableHandler'         => __DIR__ . '/src/Admin/Model/DataTable/DataTableHandler.php',
    'Admin\Model\DataTable\DataTableInterface'       => __DIR__ . '/src/Admin/Model/DataTable/DataTableInterface.php',
    'Admin\Model\FormData\FormDataAbstract'          => __DIR__ . '/src/Admin/Model/FormData/FormDataAbstract.php',
    'Admin\Model\FormData\FormDataHandler'           => __DIR__ . '/src/Admin/Model/FormData/FormDataHandler.php',
    'Admin\Model\FormData\FormDataHandlerInterface'  => __DIR__ . '/src/Admin/Model/FormData/FormDataHandlerInterface.php',
    'Admin\Model\InputSetupAbstract'                 => __DIR__ . '/src/Admin/Model/InputSetupAbstract.php',
    'Admin\Model\Posts\PostsDataTable'               => __DIR__ . '/src/Admin/Model/Posts/PostsDataTable.php',
    'Admin\Model\Posts\PostsForm'                    => __DIR__ . '/src/Admin/Model/Posts/PostsForm.php',
    'Admin\Model\Posts\PostsFormDataHandler'         => __DIR__ . '/src/Admin/Model/Posts/PostsFormDataHandler.php',
    'Admin\Model\Utenti\AuthStorage'                 => __DIR__ . '/src/Admin/Model/Utenti/AuthStorage.php',
    'Admin\Model\Utenti\UserFormAuthentication'      => __DIR__ . '/src/Admin/Model/Utenti/UserFormAuthentication.php',
    'Admin\Model\Utenti\UtenteForm'                  => __DIR__ . '/src/Admin/Model/Utenti/UtenteForm.php',
);
