<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Admin\Module'                          => __DIR__ . '/Module.php',
    'Admin\Controller\AdminController'      => __DIR__ . '/src/Admin/Controller/AdminController.php',
    'Admin\Controller\AuthController'       => __DIR__ . '/src/Admin/Controller/AuthController.php',
    'Admin\Model\Assistenza\AssistenzaForm' => __DIR__ . '/src/Admin/Model/Assistenza/AssistenzaForm.php',
    'Admin\Model\MyAuthStorage'             => __DIR__ . '/src/Admin/Model/MyAuthStorage.php',
    'Admin\Model\User'                      => __DIR__ . '/src/Admin/Model/User.php',
);
