<?php
// Generated by ZF2's ./bin/templatemap_generator.php
return array(
    'admin/albo-pretorio-relata-pdf/index' => __DIR__ . '/view/admin/albo-pretorio-relata-pdf/index.phtml',
    'admin/auth/login'                     => __DIR__ . '/view/admin/auth/login.phtml',
    'admin/empty'                          => __DIR__ . '/view/admin/empty.phtml',
    'admin/index/index'                    => __DIR__ . '/view/admin/index/index.phtml',
    'admin/success/index'                  => __DIR__ . '/view/admin/success/index.phtml',
);
