<ul class="breadcrumbs">
    <li><a href="<?php echo $this->basepath() ?>" title="Home page">Home</a></li>
    <li class="current">Atti di concessione</li>
</ul>

<?php if (count($this->paginator)): ?>

<h1>Atti di concessione</h1>

<div>
    <?php
    
    /*
    $form = $this->form;
    $form->prepare();

    $form->setAttribute('action',   $this->serverUrl(true));
    $form->setAttribute('method',   'post');
    $form->setAttribute('role',     'form');
    $form->setAttribute('id',       'atti-concessione-search-form');

    $form->get('search')->setAttribute('class', 'button button-tiny');
    
    echo $this->form()->openTag($form);
    */
    
    ?>
    <!--
    <fieldset>
        <legend>Ricerca atti di concessione</legend>
        <div>Form di ricerca in costruzione</div>
    </fieldset>
    -->
    <?php //echo $this->form()->closeTag(); ?>

</div>

<?php
    echo $this->partial('frontend/projects/entilocali/templates/'.$this->template_frontend.'_share.phtml',array(
        'twitterShareText' => $this->sitename.' - Atti di concessione',
    ));
?>

<table class="responsive" role="grid">
    <thead>
    <tr>
        <th scope="col"><b>N</b></th>
        <th scope="col"><b>Anno</b></th>
        <th scope="col"><b>Beneficiario CF/PIVA</b></th>
        <th scope="col"><b>Importo</b></th>
        <th scope="col"><b>Modalità Assegnazione</b></th>
        <th scope="col"><b>Ufficio e Responsabile del Servizio</b></th>
        <th scope="col"><b>Norma o Titolo a base dell'attribuzione</b></th>
        <th scope="col"><b>Progetto</b><br><b>Capitolato</b><br><b>Contratto</b><br><b>Curriculum</b></th>
    </tr>
    </thead>
    <tbody>
    <?php foreach($this->paginator as $key => $row): ?>
    <tr>
        <td><?php echo utf8_encode($row['progressivo']) ?></td>
        <td><?php echo utf8_encode($row['anno']) ?></td>
        <td><?php echo utf8_encode($row['beneficiario']) ?></td>
        <td><?php echo utf8_encode($row['importo']) ?></td>
        <td><?php echo utf8_encode($row['modassegn']) ?></td>
        <td><?php echo utf8_encode($row['nomeSezione']).'<br><br>'.utf8_encode($row['responsabile']) ?></td>
        <td><?php echo utf8_encode($row['titolo']) ?></td>
        <td>&nbsp;</td>
    </tr>
    <tr>
        <td colspan="8"><hr></td>
    </tr>
    <?php endforeach; ?>
    </tbody>
</table>

<?php
echo $this->partial('frontend/projects/entilocali/templates/'.$this->template_frontend.'_share.phtml',array(
    'twitterShareText' => $this->sitename.' - Atti di concessione',
));
?>

<?php
    if ( count($this->paginator) > 1 ):
        echo $this->paginationControl(
            $this->paginator,
            'sliding',
            'application/pagination/foundation.phtml',
            array(
                'route' => 'atti-concessione'
            )
        );
    endif;
else:
    ?>
    <div class="panel info">
        <h1>Nessun atto di concessione in archivio</h1>
        <p>Nessun articolo presente in archivio</p>
    </div>
    <?php
endif;
