<div>
    <ul class="breadcrumb">
        <li><a href="<?php echo $this->basepath() ?>" title="Home page">Home</a> <span class="divider"></span></li>
        <li class="active">Recupero password</li>
    </ul>

    <h1>Recupero password</h1>

    <p>Inserisci l'indirizzo email. Verr&agrave; inviato un link ad una pagina per generare una nuova password.</p>

    <?php echo $this->render('frontend/projects/entilocali/templates/default/common/show_form.phtml'); ?>
</div>