<ul class="breadcrumb">
    <li><a href="<?php echo $this->basepath() ?>/" title="Home page">Home</a> <span class="divider"></span></li>
    <li><a href="<?php echo $this->basepath()."/".$this->category_seo ?>" title="Vai a <?php echo $this->category; ?>"><?php echo $this->category; ?></a></li>
    <li class="active"><?php echo $this->title ?></li>
</ul>

<?php foreach($this->paginator as $key => $row): ?>
<div class="blog_details">

    <h1><?php echo $row['title'] ?></h1>

    <div><?php echo $row['description'] ?></div>
    
    <?php if ($row['flagAttachments'] == 'si'): ?>
    <!--
    <h2>Allegati</h2>
    <ul>
        <li>Allegato 1</li>
        <li>Allegato 2</li>
        <li>Allegato 3</li>
    </ul>
    -->
    <?php endif; ?>

    <p class="text-right">
        Esporta: <a href="#" title="Visualizza documento in formato PDF">PDF</a> 
        <a href="#" title="Visualizza documento in formato Word">WORD</a> 
        <a href="#" title="Visualizza documento in formato testo">TXT</a> 
        
        Condividi: <a href="https://www.facebook.com/sharer/sharer.php?u=<?php echo $this->currentUrl; ?>" title="Condividi pagina su facebook" target="_blank"><i class="fa fa-facebook"></i> 
        Facebook</a> <a href="https://twitter.com/home?status=<?php echo $this->currentUrl; ?>" title="Condividi pagina su Twitter"><i class="fa fa-twitter"></i> Twitter</a> 
        <!-- <a href="https://plus.google.com/share?url=<?php echo $this->currentUrl ?>">Google Plus</a> <a href="https://www.linkedin.com/shareArticle?mini=true&amp;url=<?php echo $this->currentUrl ?>&amp;title=<?php echo $row['seoTitle'] ?>">Linkedin</a> <a href="https://pinterest.com/pin/create/button/?url=<?php echo $this->currentUrl ?>">Pinterest</a>-->
    </p>

    <hr>

</div>
<?php endforeach; ?>
