<ul class="breadcrumb">
    <li><a href="<?php echo $this->basepath() ?>/" title="Home page">Home</a> <span class="divider"></span></li>
    <li class="active"><?php echo $this->maindata[0]['nomeCategoria']; ?></li>
</ul>

<p><a href="#" class="btn btn-warning" title="Visualizza Feed RSS per la categoria blog <?php echo $this->maindata[0]['nomeCategoria']; ?>"><i class="fa fa-rss"></i> Feed RSS <?php echo $this->maindata[0]['nomeCategoria']; ?></a></p>