<ul class="breadcrumbs">
    <li><a href="<?php echo $this->basepath() ?>" title="Torna alla pagina principale">Home</a></li>
    <li class="current">Albo pretorio</li>
</ul>

<?php if (count($this->paginator)): ?>

<h2>Albo pretorio</h2>
 
<div>
    <div>
    <?php
    
    $form = $this->form;
    $form->prepare();

    $form->setAttribute('action',   $this->serverUrl(true));
    $form->setAttribute('method',   'post');
    $form->setAttribute('role',     'form');
    $form->setAttribute('id',       'albo-pretorio-search-form');
        
    $form->get('search')->setAttribute('class', 'button button-tiny tiny');
    
    echo $this->form()->openTag($form);
    
    ?>
    <fieldset>
        <legend>Ricerca atti nell'albo</legend>
        
        <div class="row">
            
            <div class="large-4 columns">
                <label for="<?php echo $form->get('numero_progressivo')->getAttribute('id'); ?>">
                    <?php echo $form->get('numero_progressivo')->getLabel() ?>:
                </label>
            </div>
            
            <div class="large-2 columns">
                <?php echo $this->formElement($form->get('numero_progressivo')); ?>
            </div>
            
            <div class="large-2 columns">
                <label for="<?php echo $form->get('numero_atto')->getAttribute('id'); ?>">
                    <?php echo $form->get('numero_atto')->getLabel() ?>:
                </label>
            </div>
            
            <div class="large-2 columns">
                <?php echo $this->formElement($form->get('numero_atto')); ?>
            </div>
            
            <div class="large-2 columns">
                &nbsp;
            </div>
        </div>
        
        <div class="row">
            <div class="large-12 columns">
                <label for="<?php echo $form->get('testo')->getAttribute('id'); ?>">
                    <?php echo $form->get('testo')->getLabel() ?>:
                </label>
                <?php echo $this->formElement($form->get('testo')); ?>
            </div>
        </div>
        
        <div class="row">
            <div class="large-4 columns">
            <label for="<?php echo $form->get('mese')->getAttribute('id'); ?>">
                Atti a partire da:
            </label>
            </div>
            
            <div class="large-4 columns">
                <?php echo $this->formElement($form->get('mese')); ?>
            </div>

            <div class="large-4 columns">
                <?php echo $this->formElement($form->get('anno')); ?>
            </div>
        </div>
        
        <div class="row">
            <div class="large-12 columns">
                <label for="<?php echo $form->get('sezione')->getAttribute('id'); ?>">
                    <?php echo $form->get('sezione')->getLabel() ?>:
                </label>
                <?php echo $this->formElement($form->get('sezione')); ?>
            </div>
        </div>
        
        <div class="row">
            <div class="large-12 columns">
                <label for="<?php echo $form->get('settore')->getAttribute('id'); ?>">
                    <?php echo $form->get('settore')->getLabel() ?>:
                </label>
            
                <?php echo $this->formElement($form->get('settore')); ?>
            </div>
        </div>
        
        <div class="row">
            <div class="large-12 columns">
                <label for="<?php echo $form->get('expired')->getAttribute('id'); ?>" aria-label="Clicca sul bottone per avviare la ricerca sugli atti dell'albo">
                    <?php echo $this->formElement($form->get('expired')); ?>
                    <?php echo $form->get('expired')->getLabel() ?>
                </label>
            </div>
        </div>
        
        <div class="row">
            <div class="large-12 columns">
                <?php echo $this->formElement($form->get('csrf')); ?>
                <?php echo $this->formElement($form->get('search')); ?>
            </div>
        </div>

    </fieldset>
    <?php echo $this->form()->closeTag(); ?>

    </div>

    <div class="panel callout">Per aprire i file firmati digitalmente scaricare il software ArubaSign:<br>
        <ul class="unstyled">
            <li><i class="fa fa-windows"></i> <a href="#" title="Software per PC">Versione per PC (17,5MB)</a></li>
            <li><i class="fa fa-linux"></i> Versione per Linux <a href="#" title="ArubaSign per Linux 32bit">(32 bit)</a> - <a href="#" title="ArubaSign per Linux 64bit">(64 bit)</a></li>
            <li><i class="fa fa-apple"></i> <a href="#" title="Software per MAC">Versione per MAC (31,2MB)</a></li>
        </ul>

        <br>

        Si consiglia di visionare l'albo pretorio per tutta la durata della pubblicazione in quanto potrebbero verificarsi modifiche che verranno segnalate tramite rettifiche e/o annullamenti degli atti.
    </div>

</div>

<?php foreach($this->paginator as $key => $row): ?>

    <div<?php if ($row['annullato'] == 1): ?> class="panel"<?php endif; ?>>

    <?php if ($row['annullato'] == 1): ?>
        <h3>Atto annullato il <span class="redString"><?php echo date("d-m-Y", strtotime($row['dataAnnullamento'])) ?></span></h3>

        <blockquote>

        <h4><?php echo $row['titolo'] ?></h4>
    <?php else: ?>
        <h3><?php echo $row['titolo'] ?></h3>
    <?php endif;?>

    <p><strong>Rep.:</strong> <?php echo $row['numeroProgressivo'] ?> / <?php echo $row['numeroAtto'] ?></p>
    <p><strong>Pubblicato il:</strong> <?php echo $row['dataAttivazione'] ?> / <strong>Ore:</strong> <?php echo $row['oraAttivazione'] ?></p>
    <p><strong>Scadenza:</strong> <?php echo $row['dataScadenza'] ?></p>
    <p><strong>Sezione:</strong> <?php echo $row['nomeSezione'] ?></p>

    <?php if (isset($row['attachments'])): ?>
        <div>
            <p><strong>Allegati:</strong></p>
            <ul class="no-bullet">
        <?php foreach($row['attachments'] as $attachment): ?>
            <li>
                <a href="#" title="Scarica allegato <?php echo $attachment['title'] ?> (<?php echo $attachment['size'] ?> Kb)">
                    <img src="<?php echo $this->publicDirRelativePath ?>/common/icons/attachments/<?php echo $attachment['image'] ?>" alt="Icona per <?php echo $attachment['title'] ?> (<?php echo $attachment['size'] ?> Kb)">
                    <?php echo $attachment['title'] ?>
                </a>
                </li>
        <?php endforeach ?>
            </ul>
        </div>
    <?php endif;?>

    <?php

    echo $this->partial('frontend/projects/entilocali/templates/'.$this->template_frontend.'_share.phtml', array(
        'twitterShareText' => urlencode($this->record['title']),
        'publicDirRelativePath' => $this->publicDirRelativePath,
    ));

    ?>

    <?php if ($row['annullato'] == 1): ?>
        </blockquote>
    <?php endif; ?>

    </div>

    <?php if ($row['annullato'] != 1): ?><hr><?php endif; ?>

<?php endforeach; ?>

<?php
    if ( count($this->paginator) > 1 ):
        echo $this->paginationControl(
            $this->paginator,
            'sliding',
            'application/pagination/foundation.phtml',
            array(
                'route' => 'albo-pretorio'
            )
        );
    endif;
else:
    ?>
    <div>
        <h1>Nessun atto albo pretorio in archivio</h1>
        <p>Nessun articolo dell'albo pretorio risulta presente in archivio</p>
    </div>
    <?php
endif;
