<?php
$lang = $this->params()->fromRoute('lang') ? $this->params()->fromRoute('lang') : 'it';

if ($this->homepage):

    foreach($this->homepage as $key => $value):

        if ($key == 'blogs'):
            $basePath = (substr($this->publicDirRelativePath, -1) == '/') ? $this->publicDirRelativePath : $this->publicDirRelativePath.'/';
            ?>
            <h3>Blogs</h3>
            <div class="row">
                <?php foreach($value as $content): ?>
                    <?php
                    $linkDetails = $this->url('main/blogs-details', array(
                        'lang'      => $lang,
                        'category'  => $content['categories'][0]['name'],
                        'title'     => \ModelModule\Model\Slugifier::slugify($content['title']),
                    ));
                    ?>
                    <div class="large-12 columns">
                        <div class="panel">
                            <div class="row">
                                <div class="large-2 small-12 columns">
                                    <a href="<?php echo $linkDetails ?>" title="<?php echo $this->translate("Leggi blog post").' '.$content['title'] ?>">
                                        <img src="<?php echo $basePath.$this->configurations['media_dir'].$this->configurations['media_project'].'blogs/thumbs/'.$content['image'] ?>" alt="Miniatura per <?php echo $content['title'] ?>" class="th">
                                    </a>
                                </div>
                                <div class="large-10 small-12 columns">
                                    <h4>
                                        <a href="<?php echo $linkDetails ?>" title="<?php echo $this->translate("Leggi blog post").' '.$content['title'] ?>">
                                        <?php echo $content['title']; ?>
                                        </a>
                                    </h4>
                                    <!-- <div>Pubblicato in: <a href="#" title="Leggi posts <?php echo $content['categories'][0]['name']; ?>"><?php echo $content['categories'][0]['name']; ?></a></div> -->
                                    <?php echo $this->TextShortener($content['description'], 30, 30); ?>
                                    <a href="<?php echo $linkDetails ?>" title="Clicca per leggere il post">Leggi</a>
                                </div>
                            </div>
                        </div>
                    </div>
                <?php  endforeach; ?>
            </div>

            <hr class="hidden">

        <?php elseif ($key == 'photo'):
            $basePath = (substr($this->publicDirRelativePath, -1) == '/') ? $this->publicDirRelativePath : $this->publicDirRelativePath.'/';
            ?>
            <h3>Foto</h3>
            <ul class="clearing-thumbs" data-clearing>
                <?php foreach($value as $content): ?>
                    <?php
                    $thumbPath = $basePath.$this->configurations['media_dir'].$this->configurations['media_project'].'photo/thumbs/'.$content['image'];
                    $bigImagePath = $basePath.$this->configurations['media_dir'].$this->configurations['media_project'].'photo/big/'.$content['image'];
                    $linkDetails = $this->url('main/photo-gallery', array(
                        'lang'      => $lang,
                        'category'  => $content['categories'][0]['name'],
                        'title'     => \ModelModule\Model\Slugifier::slugify($content['title']),
                    ));
                    ?>
                    <li>
                    <a href="<?php echo $bigImagePath ?>" title="<?php echo $content['title'] ?>">
                        <img src="<?php echo $thumbPath ?>" alt="Miniatura per <?php echo $content['title'] ?>" class="th">
                    </a>
                    </li>
                <?php  endforeach; ?>
            </ul>

            <hr class="hidden">

        <?php elseif ($key == 'contenuti'): ?>
            <h3>In evidenza</h3>
            <div>
                <ul>
                <?php foreach($value as $record): ?>
                <li>
                    <a href="<?php echo $this->url('main/contenuti', array('lang' => $lang, 'subsectionid' => $record['sottosezione'])) ?>" title="Vai alla pagina <?php echo $record['titolo'] ?>">
                        <?php echo $record['titolo'] ?>
                    </a>
                </li>
                <?php endforeach; ?>
                </ul>
            </div>
            <hr class="hidden">
        <?php elseif ($key == 'amministrazione-trasparente'): ?>
            <h3>Amministrazione trasparente</h3>
            <div>
                <ul>
                    <?php foreach($value as $record): ?>
                        <li>
                            <a href="<?php echo $this->url('amministrazione-trasparente', array(
                                'lang'          => $lang,
                                'profondita'    => $record['sottosezione'],
                                'id'            => $record['id'],
                            ));
                            ?>" title="Vai alla pagina <?php echo $record['titolo'] ?>">
                                <?php echo $record['titolo'] ?>
                            </a>
                        </li>
                    <?php endforeach; ?>
                </ul>
            </div>
            <hr class="hidden">
        <?php elseif ($key == 'contents'): ?>
            <div class="row">
            <?php

            $i=0;
            foreach($value as $content):
                ?>
                <div class="large-6 column">
                    <div>
                        <img data-src="holder.js/300x200" alt="300x200" src="data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSIzMDAiIGhlaWdodD0iMjAwIj48cmVjdCB3aWR0aD0iMzAwIiBoZWlnaHQ9IjIwMCIgZmlsbD0iI2VlZSI+PC9yZWN0Pjx0ZXh0IHRleHQtYW5jaG9yPSJtaWRkbGUiIHg9IjE1MCIgeT0iMTAwIiBzdHlsZT0iZmlsbDojYWFhO2ZvbnQtd2VpZ2h0OmJvbGQ7Zm9udC1zaXplOjE5cHg7Zm9udC1mYW1pbHk6QXJpYWwsSGVsdmV0aWNhLHNhbnMtc2VyaWY7ZG9taW5hbnQtYmFzZWxpbmU6Y2VudHJhbCI+MzAweDIwMDwvdGV4dD48L3N2Zz4=" style="width: 300px; height: 200px;">
                        <div>
                            <h3><?php echo $content['title'] ?></h3>
                            <p><?php echo $this->TextShortener($content['description'], 30, 30); ?></p>
                            <p>
                                <a href="<?php echo $this->basepath().$content['linkDetails'] ?>" class="button secondary small" title="Continua a leggere l'articolo">
                                    Leggi
                                </a>
                            </p>
                        </div>
                    </div>
                </div>
                <?php

                $i++;
                if ($i==2):
                    ?>
                    </div><div class="row">
                    <?php
                    $i=0;
                endif;

                ?>
            <?php endforeach; ?>
            </div>
            <hr class="hidden">
        <?php elseif ($key == 'albo-pretorio'): ?>
            <h3>Albo pretorio</h3>
            <ul>
            <?php foreach($value as $record): ?>
                <li>
                    <a href="<?php echo $this->url('albo-pretorio-details', array('id' => $record['id'])) ?>" title="<?php echo ucfirst($record['titolo']) ?>">
                        <?php echo ucfirst($record['titolo']) ?>
                    </a>
                </li>
            <?php endforeach ?>
            </ul>
            <hr class="hidden">
        <?php elseif ($key == 'contratti-pubblici'): ?>
            <h3>Bandi di gara e contratti</h3>
            <ul>
            <?php foreach($value as $record): ?>
                <li>
                    <a href="<?php echo $this->url('contratti-pubblici-details', array('id' => $record['id'])) ?>" title="<?php echo ucfirst($record['titolo']) ?>">
                        <?php echo ucfirst($record['titolo']) ?>
                    </a>
                </li>
            <?php endforeach ?>
            </ul>
            <hr class="hidden">
        <?php elseif ($key == 'stato-civile'): ?>
            <h3>Stato civile</h3>
            <?php foreach($value as $record): ?>
            <div>
                <?php echo ucfirst($record['titolo']) ?>
            </div>
            <?php endforeach ?>
            <hr class="hidden">
        <?php elseif ($key == 'atti-concessione'): ?>
            <h3>Atti di concessione</h3>
            <ul>
            <?php foreach($value as $record): ?>
                <li>
                    <a href="<?php echo $this->url('atti-concessione-details', array('lang' => 'it', 'id' => $record['id'])) ?>" title="Dettagli atto <?php echo ucfirst($record['titolo']) ?>">
                        <?php echo ucfirst($record['titolo']) ?>
                    </a>
                </li>
            <?php endforeach ?>
            </ul>

            <hr class="hidden">
        <?php elseif ($key == 'freeText'):

            if ( !empty($value) ):
                foreach($value as $record):
                    ?>
                    <div><?php echo $record['freeText'] ?></div>
                    <?php
                endforeach;
            endif;

        endif;

    endforeach;
endif;
