<?php
// Generated by ZF2's ./bin/templatemap_generator.php
return array(
    'application/index/index'           => __DIR__ . '/view/application/index/index.phtml',
    'application/pagination/bootstrap'  => __DIR__ . '/view/application/pagination/bootstrap.phtml',
    'application/pagination/foundation' => __DIR__ . '/view/application/pagination/foundation.phtml',
    'application/pagination/numbers'    => __DIR__ . '/view/application/pagination/numbers.phtml',
    'error/404'                         => __DIR__ . '/view/error/404.phtml',
    'error/dbconnection'                => __DIR__ . '/view/error/dbconnection.phtml',
    'error/index'                       => __DIR__ . '/view/error/index.phtml',
    'layout/layout'                     => __DIR__ . '/view/layout/layout.phtml',
);
