<ul class="breadcrumb">
    <li><a href="<?php echo $this->basepath() ?>/admin/main/" title="Home page">Home</a> <span class="divider"></span></li>
    <li class="active">Dashboard</li>
</ul>

<h1>Area di amministrazione</h1>

<div class="alert alert-warning">
    <h2>In costruzione</h2>
    <p>Area in costruzione. Alcune sezioni non sono presenti o sono in fase di sviluppo.</p>
</div>

<!--

TODO:
    riepilogo contatti (link)
    opzioni sito (link)
    moduli \ opzioni per ogni modulo
        
    E-commerce:
        panoramica ordini, prodotti

    Check se tool migrazione attivo, mostra link
-->

<div class="alert alert-info">
    <h2>Consigli per l'utilizzo di quest'area:</h2>
    <p>Alcuni consigli per un utilizzo ottimale di quest'area:</p>
    <ul>
        <li>Utilizzare un browser moderno come Google Chrome, Mozilla Firefox, Opera, Safari o Internet Explorer 10 con supporto Javascript attivo</li>
        <li>Utilizzare i link dell'applicazione e non i pulsanti indietro \ avanti del browser poich&egrave; potrebbero confondere la navigazione o danneggiare i dati che si stanno manipolando</li>
    </ul>
</div>
