<ul class="breadcrumb">
    <li><a href="<?php echo $this->basepath() ?>/admin/main/" title="Home page">Home</a> <span class="divider"></span></li>
    <li class="active">Dashboard</li>
</ul>

<h1>Area di amministrazione</h1>

<h2>Contenuti online:</h2>

<?php if ($this->preloadResponse): ?>
    <?php foreach($this->preloadResponse as $key => $value): ?>
    <ul>
        <strong><?php echo $key ?></strong>
        <?php foreach($value as $post): ?>
        <li><a href="#"><?php echo $post['titolo'] ?></a></li>
        <?php endforeach; ?>
    </ul>
    <?php endforeach; ?>
<?php endif; ?>

