<?php echo $this->doctype(); ?>

<html lang="it">
<head>
    <meta charset="utf-8">
    <?php

    echo $this->headTitle('')->setSeparator(' - ')->setAutoEscape(false);

    echo $this->headMeta()
        ->appendName('viewport', 'width=device-width, initial-scale=1.0')
        ->appendHttpEquiv('X-UA-Compatible', 'IE=edge');

    echo $this->headLink()
        ->prependStylesheet($this->publicDirRelativePath.'/common/bootstrap3/css/bootstrap.min.css')
    ?>

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
    <script src="https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"></script>
    <![endif]-->

    <?php

    echo $this->headScript()
        ->prependFile($this->publicDirRelativePath. '/common/bootstrap3/js/bootstrap.min.js')
        ->prependFile($this->publicDirRelativePath. '/common/jquery/jquery.min.js');

    ?>

</head>
<body>

<div class="container">

    <br>

    <?php

    $this->headTitle($this->sitename);

    $form = $this->form;
    $form->prepare();

    $form->setAttribute('method', 'post');
    $form->setAttribute('action', $this->url('password-preview'));
    $form->setAttribute('role',  'form');
    $form->setAttribute('class', 'form-horizontal');

    $formLabel = $this->plugin('formLabel');

    echo $this->form()->openTag($form);

    ?>

    <div class="row">

        <div class="col-md-2">&nbsp;</div>

        <div class="col-md-8">
            <h1>Area riservata</h1>

            <p>&Egrave; necessaria una password per poter utilizzare l'applicazione.</p>

            <div class="form-group">
                <?php
                $name = $form->get('password');
                $name->setAttribute('class','form-control');
                ?>
                <label for="password" class="col-sm-2 control-label"><?php echo $name->getOption('label') ?></label>
                <div class="col-sm-10">
                    <?php
                    echo $this->formInput($name);
                    echo $this->formElementErrors($name);
                    ?>
                </div>
            </div>

            <div class="form-group">
                <div class="col-sm-offset-2 col-sm-10">
                    <button type="submit" class="btn btn-primary">Accedi</button>
                </div>
            </div>

            <?php if (isset($this->errorMessage)): ?>
            <div class="form-group">
                <div class="alert alert-danger">
                    <?php echo $this->errorMessage ?>
                </div>
            </div>
            <?php endif; ?>
        </div>

        <div class="col-md-2">&nbsp;</div>

    </div>

    <?php echo $this->form()->closeTag($form); ?>



</div>

<?php echo $this->inlineScript() ?>

</body>
</html>