<p>TODO for the backend:</p>
<ul>
	<li>Login template: translate labels, select language, let it works!!!</li>
	<li>Check authentication backend</li>
	<li>Recover password form (on login page or separated)</li>
	<li>Centralize PHPUNIT TESTS</li>
	<li>URL rewrite backend  public \ website: create a subdomain for it?</li>
	<li>Bootstrap 3 for the the main admin template?!</li>
	<li>Set link menu and image paths on the main template</li>
	<li>Create modules for the setup: config, language, </li>
	<li>Set URLs for Grid and FormData</li>
	<li>Try to set a form post for example. All form posts must have 1 template for the view</li>
</ul>

<p>TODO for the frontend:</p>
<ul>
	<li>Redirect from home page to /it/ (default language) like fossobandito</li>
	<li>Load custom controller for the frontend</li>
	<li>Let the view load language and config options</li>
	<li>Set post category / content for the backend</li>
	<li>Work with us form</li>
	<li>Contact form (sample, Send mail?)</li>
</ul>

<p>TODO both frontend and backend:</p>
<ul>
	<li>Breadcrumbs (see the Abdul's navigation tutorial)</li>
	<li>Posts module:
		 inject setup data to any sub module
		 get all posts on home page?
  		 get a single posts with detail
  		 factory to get blog posts, photo, </li>
	<li>Channel (watch about multi website...)</li>
	<li>Check if is admin</li>
	<li>Load configuration from language and config?!</li>
	<li>Home page handling with multiple templates...!?</li>
</ul>
SELECT id, language, abbrev1, abbrev3 FROM languages WHERE active = '1' 
SELECT SQL_CALC_FOUND_ROWS language, abbrev1, abbrev3, l.id, l.id AS idlabel, labelname, labelvalue FROM languages l, languages_labels ll WHERE active = '1' AND l.id = ll.riflang AND abbrev1 = 'it' 
SELECT name, value FROM config WHERE (rifchannel = 1 OR rifchannel = '0') AND (riflanguage = 1 OR riflanguage = '0') 

<p>TODO (test)</p>
<ul>
	<li>Fix PHPUnit errors</li>
	<li>Codeception module?</li>
</ul>