<h3>hello, this is my backend!</h3>

<p>TODO for the backend:</p>
<ul>
	<li>Load configuration from language and config?!</li>
	<li>Template management?! Move templates on the public folder?!</li>
	<li>Set bootstrap 3</li>
	<li>Set link menu</li>
	<li>Set URLs for Grid and FormData</li>
	<li>Try to set a form post for example. All form posts must have 1 template for the view</li>
</ul>

<p>TODO for the frontend:</p>
<ul>
	<li>Load configuration from language and config?!</li>
	<li>Template management?!</li>
	<li>Redirect from home page to /it/ (default language) like fossobandito</li>
	<li>Contact form (sample)</li>
</ul>
