<p>TODO for the backend:</p>
<ul>
	<li>Login template (bootstrap2)</li>
	<li>Let the login template work</li>
	<li>URL rewrite backend  public \ website: create a subdomain for it?</li>
	<li>Bootstrap 3 for the the main admin template?!</li>
	<li>Set link menu and image paths on the main template</li>
	<li>Create modules for the setup: config, language, </li>
	<li>Set URLs for Grid and FormData</li>
	<li>Try to set a form post for example. All form posts must have 1 template for the view</li>
</ul>

<p>TODO for the frontend:</p>
<ul>
	<li>Redirect from home page to /it/ (default language) like fossobandito</li>
	<li>Use the fossobandito db</li>
	<li>Set post category / content for the backend</li>
	<li>Work with us form</li>
	<li>Contact form (sample, Send mail?)</li>
</ul>

<p>TODO both frontend and backend:</p>
<ul>
	<li>Load configuration from language and config?!</li>
</ul>
