<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'ModelModule\Module'      => __DIR__ . '/Module.php',
    'ModelModule\Model\Prova' => __DIR__ . '/src/ModelModule/Model/Prova.php',
);
