<ul class="breadcrumbs">
    <li>
        <a href="<?php echo $this->url('main', array('lang' => $this->lang)); ?>" title="<?php echo $this->translate('Torna alla home page') ?>">
            Home
        </a>
        <span class="divider"></span>
    </li>
    <li><?php echo $this->categoryName ?></li>
</ul>

<?php
if ($this->formSearch):

    ?>
    <h2><?php echo ucfirst($this->categoryName) ?></h2>

    <p><?php echo $this->item_count ?> <?php echo $this->translate('posts in archivio'); ?>.</p>
    <?php

    $form = $this->formSearch;

    $form->setAttribute('action',   '#');
    $form->setAttribute('method',   'post');
    $form->setAttribute('role',     'form');
    $form->setAttribute('id',       'frmBlogSearch');

    $form->get('search')->setAttribute('class', 'button button-tiny tiny');
    $form->get('testo')->setAttributes(array(
            'placeholder' => $this->translate('Cerca').'...',
            'title' => $this->translate('Digita il testo da cercare'),
        )
    );
    $form->get('category')->setOptions(array('empty_option'  => $this->translate('Seleziona')));
    $form->get('category')->setAttributes(array('title' => $this->translate('Seleziona categoria')));
    $form->get('search')->setAttributes(array('value' => $this->translate('Cerca')));
    $form->prepare();

    echo $this->form()->openTag($form);

    ?>
    <fieldset>
        <legend><?php echo $this->translate('Cerca fra i blogs'); ?></legend>

        <div class="row">
            <div class="large-6 columns">
                <label for="<?php echo $form->get('testo')->getAttribute('id'); ?>">
                    <?php echo $this->translate( $form->get('testo')->getLabel() ); ?>:
                </label>
                <?php echo $this->formElement($form->get('testo')); ?>
            </div>

            <div class="large-6 columns">
                <label for="<?php echo $form->get('category')->getAttribute('id'); ?>">
                    <?php echo $this->translate( $form->get('category')->getLabel() ); ?>:
                </label>
                <?php echo $this->formElement($form->get('category')); ?>
            </div>
        </div>

        <div class="row">
            <div class="large-12 columns">
                <label for="<?php echo $form->get('search')->getAttribute('id'); ?>">
                    <?php echo $this->formElement($form->get('search')); ?>
                </label>
            </div>
        </div>

    </fieldset>
    <?php echo $this->form()->closeTag(); ?>
<?php endif; ?>

<?php if ( count($this->records) ): ?>

    <?php foreach($this->records as $key => $row): ?>

        <?php $linkDetails = $this->url('main/posts-blogs-details', array('lang' => $this->lang, 'category' => $row['categorySlug'], 'title' => $row['slug'])) ?>

        <div class="row">
            <h2>
                <a href="<?php echo $linkDetails ?>" title="Continua a leggere <?php echo $row['title'] ?>">
                    <?php echo $row['title'] ?>
                </a>
            </h2>

            <?php if (!empty($row['subtitle'])): ?>
                <div>
                    <h4><?php echo $row['subtitle'] ?></h4>
                </div>
            <?php endif; ?>

            <div class="large-3 columns">
                <a href="<?php echo $linkDetails ?>" title="Continua a leggere <?php echo $row['title'] ?>">
                    <img src="http://placehold.it/160x120&amp;text=immagine" alt="Placeholder image for <?php echo $row['title'] ?>">
                </a>
            </div>

            <div class="large-9 columns">
                <?php echo $this->TextShortener(strip_tags($row['description']), 50, 100, '...'); ?>
                <a href="<?php echo $linkDetails ?>" title="Continua a leggere <?php echo $row['title'] ?>">
                    <?php echo $this->translate('Leggi tutto'); ?>
                </a>
            </div>

            <?php
            echo $this->partial('frontend/projects/entilocali/templates/'.$this->template_frontend.'_share.phtml',array(
                'twitterShareText' => urlencode($row['title']),
                'publicDirRelativePath' => $this->publicDirRelativePath,
            ));
            ?>

        </div>

        <hr>

    <?php endforeach; ?>
<?php else: ?>
    <h2><?php echo $this->translate('Nessun post presente') ?></h2>

    <p><?php echo $this->translate('Nessun post trovato in archivio per la categoria selezionata') ?></p>
<?php endif; ?>
<?php

if ( count($this->paginator) > 1 ):

    echo $this->paginationControl(
        $this->paginator,
        'sliding',
        'application/pagination/foundation.phtml',
        array(
            'category'  => $this->category,
            'route'     => 'posts-blogs-categories'
        )
    );

endif;
