<?php echo $this->render($this->formDataCommonPath.'formdata_breadcrumb.phtml'); ?>

<h3><?php echo $this->articleTitle ?></h3>

<p><?php echo $this->translate('Gestione file allegati.') ?></p>

<ul class="nav nav-tabs" role="tablist">
    <li class="active"><a href="#attachmentSummary" role="tab" data-toggle="tab"><i class="fa fa-list"></i> <?php echo $this->translate('Elenco') ?></a></li>
    <li><a href="#attachmentNew" role="tab" data-toggle="tab"><i class="fa fa-paperclip"></i> <?php echo $this->translate('Nuovo file') ?></a></li>
</ul>

<div class="tab-content">
    <div class="tab-pane active" id="attachmentSummary">
    <?php if (!isset($this->attachmentsList) or empty($this->attachmentsList)): ?>
        <div>&nbsp;</div>
        <div class="alert alert-warning">
            <h3><?php echo $this->translate('Nessun allegato presente') ?></h3>
            <div><?php echo $this->translate("Nessun allegato presente per l'articolo corrente. Inserisci un nuovo allegato.") ?></div>
        </div>
        
    <?php else: ?>
    <div>&nbsp;</div>
    <form action="#" method="post" enctype="multipart/form-data">
    <div class="table-responsive">
        <table border="0" class="table table-bordered" width="100%">
        <thead>
        <tr>
            <th>&nbsp;</th>
            <th><?php echo $this->translate('Nome file') ?></th>
            <th><?php echo $this->translate('Descrizione') ?></th>
            <th><?php echo $this->translate('Data inserimento') ?></th>
            <th><?php echo $this->translate('Inserito da') ?></th>
            <th>&nbsp;</th>
            <th>&nbsp;</th>
        </tr>
        </thead>
        <tbody>
        <?php foreach($this->attachmentsList as $record): ?>
        <tr>
            <td><input type="checkbox" id="chk<?php echo $record['id'] ?>" name="attachmentId[]" value="<?php echo $record['id'] ?>"></td>
            <td><label for="chk<?php echo $record['id'] ?>"><?php echo $record['name'] ?> (<?php echo $record['size'] ?> Kb)</label></td>
            <td><?php echo isset($record['description']) ? $record['description'] : null ?></td>
            <td><?php echo $record['insertDate']->format('Y-m-d H:i:s') ?></td>
            <td>&nbsp;</td>
            <td><a href="#" class="btn btn-primary" title="<?php echo $this->translate('Modifica file allegato') ?>"><i class="fa fa-pencil"></i></a></td>
            <td><a href="#" class="btn btn-default" title="<?php echo $this->translate('Scarica file allegato') ?>"><i class="fa fa-download"></i> Scarica</a></td>
        </tr>
        <?php endforeach; ?>
        <tr>
            <td colspan="7">
                <a href="#" class="btn btn-danger" title="<?php echo $this->translate('Elimina file\s selezionato\i') ?>"><i class="fa fa-trash-o"></i> <?php echo $this->translate('Elimina file\s selezionato\i') ?></a>
                <a href="#" class="btn btn-primary" title="<?php echo $this->translate('Scarica tutti gli allegati') ?>"><i class="fa fa-download"></i> <?php echo $this->translate('Scarica tutti gli allegati') ?></a>
            </td>
        </tr>
        </tbody>
    </table>
    </div>
    </form>
    <?php endif; ?>
    </div>
    <div class="tab-pane" id="attachmentNew">
        <?php echo $this->render('backend/templates/default/formdata/formdata.phtml'); ?>
    </div>
</div>
