<h3>Titolo form</h3>
<p>Descrizione breve form</p>

<?php

$this->form->setAttribute('action', $this->url);
$this->form->prepare();

echo $this->form()->openTag($this->form);

foreach ($this->form as $element):
	$attributes = $element->getAttributes();
	if ($attributes['class']=='ckeditor'):
	?>
	<div class="form-group">
		<div class="col-sm-12">
			<label><?php echo $element->getLabel() ?></label>
	    	<?php echo $this->formElement($element); ?>	      
	    </div>
	</div>
	<?php
	else:
	?>
	<div class="form-group">
		<label for="<?php echo $attributes['id'] ?>" class="col-sm-2 control-label"><?php echo $element->getLabel() ?></label>
		<div class="col-sm-10">
	      <?php echo $this->formElement($element); ?>	      
	    </div>
	</div>
	<?php
	endif;
endforeach;
?>

<?php echo $this->form()->closeTag($this->form); ?>

<div id="result"></div>
