<?php if (!$this->form): ?>
<div class="alert alert-danger">
	<h4>Errore verificato:</h4>
	<div>. Impossibile visualizzare il form: oggetto form non rilevato</div>
</div>
<?php else :?>
<h3>Titolo form</h3>
<div>Descrizione breve del form</div>
<?php

$formAction = $this->templateData['remotelinkWeb'].'backend/formpost/';
$this->form->setAttribute('action', $formAction);
$this->form->prepare();

echo $this->form()->openTag($this->form);

foreach ($this->form as $element):
	$attributes = $element->getAttributes();
	if ($attributes['class']=='ckeditor'):
	?>
	<div class="form-group">
		<div class="col-sm-12">
			<label><?php echo $element->getLabel() ?></label>
	    	<?php echo $this->formElement($element); ?>	      
	    </div>
	</div>
	<?php
	else:
	?>
	<div class="form-group">
		<label for="<?php echo $attributes['id'] ?>" class="col-sm-2 control-label"><?php echo $element->getLabel() ?></label>
		<div class="col-sm-10">
	      <?php echo $this->formElement($element); ?>	      
	    </div>
	</div>
	<?php
	endif;
endforeach;
?>

<?php echo $this->form()->closeTag($this->form); ?>

<div id="formDataLoading" class="alert alert-warning" style="display: none"><h4>Attendere: elaborazione dati in corso...</h4></div>
<div id="formDataResponse"></div>
<?php endif; ?>