<ul class="breadcrumbs">
    <li><a href="<?php echo $this->basepath() ?>" title="Home page">Home</a></li>
    <li class="current">Stato civile</li>
</ul>

<?php if (count($this->paginator)): ?>

<h1 class="text-center">Pubblicazioni stato civile</h1>

<div>
    <div>   
    <?php

    $form = $this->form;
    $form->prepare();

    $form->setAttribute('action', $this->serverUrl(true) );
    $form->setAttribute('method', 'post');
    $form->setAttribute('id', 'stato-civile-search-form');

    /* Apply bootstrap css class to the form elements */
    $form->get('testo')->setAttribute('class','form-control');
    $form->get('sezione')->setAttribute('class', 'form-control');
    $form->get('mese')->setAttribute('class', 'form-control');
    $form->get('anno')->setAttribute('class', 'form-control');
    $form->get('search')->setAttribute('class', 'button tiny');

    echo $this->form()->openTag($this->form);

    ?>
    <fieldset>
        <legend>Ricerca atti stato civile</legend>

        <div class="row">
            <div class="large-12 columns">
            <label for="<?php echo $form->get('testo')->getAttribute('id'); ?>">
                <?php echo $form->get('testo')->getLabel() ?>:
                <?php echo $this->formElement($form->get('testo')); ?>
            </label>
            </div>
        </div>

        <div class="row">
            <div class="large-4 columns">
                <label for="<?php echo $form->get('mese')->getAttribute('id'); ?>">Atti a partire da:</label>
            </div>

            <div class="large-4 columns">
                <?php echo $this->formElement($form->get('mese')); ?>
            </div>

            <div class="large-4 columns">
                <?php echo $this->formElement($form->get('anno')); ?>
            </div>
        </div>

        <div class="row">
            <div class="large-12 columns">
            <label for="<?php echo $form->get('sezione')->getAttribute('id'); ?>">
                <?php echo $form->get('sezione')->getLabel() ?>:
            </label>

            <?php echo $this->formElement($form->get('sezione')); ?>
            
            </div>
        </div>

        <div class="row">
            <div class="large-12 columns">
            <label aria-label="Cerca" for="search">
                <?php echo $this->formElement($form->get('csrf')); ?>
                <?php echo $this->formElement($form->get('search')); ?>
            </label>
            </div>
        </div>

        <?php echo $this->form()->closeTag(); ?>

        </fieldset>

    </div>

    <div>Per aprire i file firmati digitalmente scaricare il software ArubaSign:<br>

    <ul class="unstyled">
        <li><a href="http://www.kronoweb.it/download/ArubaSign/ArubaSign2_3_5_WINDOWS.exe" title="Software per PC">Versione per PC (17,5MB)</a></li>
        <li>Versione per Linux <a href="https://www.pec.it/Download/Software/FirmaDigitale/ArubaSign32-2_8_3.tar.bz2" title="Software per Linux">(32 bit)</a> - <a href="https://www.pec.it/Download/Software/FirmaDigitale/ArubaSign64-2_8_3.tar.bz2" title="Software per Linux">(64 bit)</a></li>
        <li><a href="http://www.kronoweb.it/download/ArubaSign/ArubaSign2_1_5MAC.zip" title="Software per MAC">Versione per MAC (31,2MB)</a></li>
    </ul>

    Si consiglia di visionare l'albo pretorio per tutta la durata della pubblicazione in quanto potrebbero verificarsi modifiche che verranno segnalate tramite rettifiche e/o annullamenti degli atti.
    </div>
    <hr>
</div>

<?php foreach($this->paginator as $key => $row): ?>
<article>
<div>
    <h2><?php echo $row['titolo'] ?></h2>
    <div><strong>Numero \ Anno:</strong> <?php echo $row['progressivo']." / ".$row['anno']; ?></div>
    <div><strong>Scadenza:</strong> <?php echo date('d-m-Y', strtotime($row['scadenza']) ); ?></div>
    <div><strong>Sezione:</strong> <?php echo $row['nome'] ?></div>
    <!-- <div><strong>Allegati</strong></div> -->
</div>
</article>
<hr>
<?php endforeach; ?>

<?php
    if ( count($this->paginator) > 1 ):
        echo $this->paginationControl(
            $this->paginator,
            'sliding',
            'application/pagination/foundation.phtml',
            array(
                'category' => '',
                'route' => 'stato-civile'
            )
        );
    endif;
else:
    ?>
    <div class="alert-box info">
        <h1>Nessun dato in archivio</h1>
        <p>Nessun atto sullo stato civile si trova in archivio</p>
    </div>
    <?php
endif;
