<!doctype html>
<html>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8">

<style>
    h1, h2 { margin-bottom: 30px; }
    p { margin-bottom: 10px }
    .text-center { text-align: center }
    .red { color: #c00c00 }
</style>

<body>

<h2><?php echo $this->sitename ?></h2>

<p>Documento generato il <?php echo date("d-m-Y") ?></p>

<h2><?php echo $this->record['titolo'] ?></h2>

<?php echo $this->record['testo'] ?>

<p><strong>Sezione:</strong> <?php echo $this->record['nomeSezione'] ?></p>

</body>
</html>