<div>
    <ul class="breadcrumb">
        <li><a href="<?php echo $this->basepath() ?>" title="Home page">Home</a> <span class="divider"></span></li>
        <li class="active">Registrazione nuovo utente</li>
    </ul>
    
    <h1>Registrati</h1>
    
    <p>Compila il form per registrarti come nuovo utente</p>
    
    <?php echo $this->render('frontend/projects/entilocali/templates/default/common/show_form.phtml'); ?>
    
    <div class="form-group">
        <label class="col-sm-2 control-label">&nbsp;</label>
        <div class="col-sm-10">
            <label>* Campi obbligatori</label>
        </div>
    </div>
    
</div>
