<?php $editLinkBasic =  $this->templateData['remotelinkWeb'].$this->templateData['loggedSectionPathBackend'].$this->templateData['languageAbbreviation'].'/formdata/PostsFormSetter/'; ?>

<?php if ( is_array($this->templateData['preloadrecord']) ): ?>
<div class="col-md-3 column">
	<div class="list-group">
		<!-- Passato -->
		<a href="#" class="list-group-item active"> <?php echo $this->templateData['languageLabels']['PAST'] ?></a>
		<a href="<?php echo $editLinkBasic.$this->templateData['preloadrecord']['repetti']['postid'] ?>" title="<?php echo $this->templateData['preloadrecord']['repetti']['title'] ?>" class="list-group-item"><?php echo $this->templateData['preloadrecord']['repetti']['title'] ?></a>						

		<!-- Presente -->
		<a href="#" class="list-group-item active"> <?php echo $this->templateData['languageLabels']['PRESENT'] ?></a>
		<a href="<?php echo $editLinkBasic.$this->templateData['preloadrecord']['present']['postid'] ?>" title="<?php echo $this->templateData['preloadrecord']['present']['title'] ?>" class="list-group-item"><?php echo $this->templateData['preloadrecord']['present']['title'] ?></a>
		
		<!-- Futuro -->
		<a href="#" class="list-group-item active"> <?php echo $this->templateData['languageLabels']['FUTURE'] ?></a>
		<a href="<?php echo $editLinkBasic.$this->templateData['preloadrecord']['future']['postid'] ?>" title="<?php echo $this->templateData['preloadrecord']['future']['title'] ?>" class="list-group-item"><?php echo $this->templateData['preloadrecord']['future']['title'] ?></a>
		
		<a href="#" class="list-group-item active"> Blogs</a>
		<a href="#" title="<?php echo $this->templateData['languageLabels']['RASSEGNA_STAMPA_MENU'] ?>" class="list-group-item"><i class="fa fa-print"></i> <?php echo $this->templateData['languageLabels']['RASSEGNA_STAMPA_MENU'] ?></a>
		<a href="#" title="" class="list-group-item"><i class="fa fa-calendar"></i> Eventi</a>
		
		<a href="<?php echo $editLinkBasic.$this->templateData['preloadrecord']['contacts']['postid'] ?>" class="list-group-item active"> <?php echo $this->templateData['preloadrecord']['contacts']['title'] ?></a>
		<a href="#" title="<?php echo $this->templateData['preloadrecord']['credits']['title'] ?>" class="list-group-item"><?php echo $this->templateData['preloadrecord']['credits']['title'] ?></a>
		<a href="#" title="<?php echo $this->templateData['languageLabels']['LAVORA_CON_NOI_MENU'] ?>" class="list-group-item"><i class="fa fa-briefcase"></i> <?php echo $this->templateData['languageLabels']['LAVORA_CON_NOI_MENU'] ?></a>
		<a href="#" title="" class="list-group-item"><i class="fa fa-archive"></i> Gestione Contatti</a>
	</div>
	<!-- 
	<div class="panel panel-default">
		<div class="panel-heading">
			<h3 class="panel-title">
				Panel title
			</h3>
		</div>
		<div class="panel-body">
			Panel content
		</div>
		<div class="panel-footer">
			Panel footer
		</div>
	</div>
	 -->
</div>
<?php endif; ?>