<div class="col-md-3 column">    
    <div class="list-group">
        <a href="#" class="list-group-item active">Contenuti</a>
        <a href="#" class="list-group-item" title="">Foto</a>
        <a href="#" class="list-group-item">Blogs</a>
        <a href="#" class="list-group-item" title="">Albo pretorio</a>
        <a href="#" class="list-group-item" title="">Stato civile</a>
        <a href="#" class="list-group-item" title="">Amministrazione trasparente</a>
        
    </div>
    
    <div class="list-group">
        <a href="#" class="list-group-item">Servizio SMS</a>
        <a href="#" class="list-group-item" title="">Booking</a>
        <a href="#" class="list-group-item" title="">E-commerce</a>
    </div>
</div>
