<div class="col-md-3 column">
    <div class="list-group">
        <a href="<?php echo $this->baseUrl ?>datatable/posts/?type=content" class="list-group-item active">Contenuti</a>
        <a href="<?php echo $this->baseUrl ?>datatable/posts/?type=foto" class="list-group-item" title="">Foto</a>
        <a href="<?php echo $this->baseUrl ?>datatable/albo-pretorio" class="list-group-item" title="Albo pretorio">Albo pretorio</a>
        <a href="<?php echo $this->baseUrl ?>datatable/stato-civile" class="list-group-item" title="Stato civile">Stato civile</a>
        <a href="<?php echo $this->baseUrl ?>datatable/amministrazione-trasparente" class="list-group-item" title="">Amministrazione trasparente</a>
    </div>

    <div class="list-group">
        <a href="#" class="list-group-item active" title="">Blogs</a>
        <a href="#" class="list-group-item" title="">Eventi</a>
        <a href="#" class="list-group-item" title="">Rassegna Stampa</a>
    </div>
    
    <div class="list-group">
        <a href="#" class="list-group-item">Servizio SMS</a>
        <a href="#" class="list-group-item" title="">Booking</a>
    </div>
    
    <div class="list-group">
        <a href="<?php echo $this->baseUrl ?>datatable/ecommerce" class="list-group-item active" title="">E-commerce</a>
        <a href="#" class="list-group-item" title="">Prodotti</a>
        <a href="#" class="list-group-item" title="">Categorie</a>
        <a href="#" class="list-group-item" title="">Ordini</a>
        <a href="#" class="list-group-item" title="">Marchi</a>
    </div>
    
</div>
