<div class="col-md-3 column">
    <div class="list-group">
        <a href="#" class="list-group-item active"> Contenuti</a>
        
        <a href="#" class="list-group-item" title="">Albo pretorio</a>
        <a href="#" class="list-group-item" title="">Stato civile</a>
        <a href="#" class="list-group-item" title="">Amministrazione aperta</a>
        <a href="#" class="list-group-item" title="">Amministrazione trasparente</a>
        
    </div>
</div>
