<ul class="breadcrumb">
    <li>
        <a href="<?php echo $this->basepath() ?>/" title="Torna all'home page">Home</a> <span class="divider"></span>
    </li>
    <li>
        <a href="<?php echo $this->basepath()."/".$this->category_seo ?>" title="<?php echo $this->categoryName ?>"><?php echo $this->category ?></a> <span class="divider"></span>
    </li>

    <li class="active"><?php echo $this->title ?></li>
</ul>

<?php foreach($this->paginator as $key => $row): ?>
<div class="content_details">
    <h1><?php echo $row['title'] ?></h1>

    <?php if ( isset($row['subtitle']) ): ?>
    <p><strong><?php echo $row['subtitle'] ?></strong></p>
    <?php endif; ?>

    <div><?php echo $row['description'] ?></div>

    <?php if ($row['flagAttachments'] == 'si'): ?>
    <!--
    <h3>Allegati</h3>
    <p>Scarica i file allegati</p>
    <ul>
        <li><a href="#" title="">File 1</a></li>
        <li><a href="#" title="">File 2</a></li>
        <li><a href="#" title="">File 3</a></li>
    </ul>
    -->
    <?php endif; ?>

    <p class="text-right">
        Esporta: <a href="#" title="Visualizza documento in formato PDF">PDF</a> 
        <a href="#" title="Visualizza documento in formato Word">WORD</a> 
        <a href="#" title="Visualizza documento in formato testo">TXT</a> 
        
        Condividi: <a href="https://www.facebook.com/sharer/sharer.php?u=<?php echo $this->currentUrl; ?>" title="Condividi pagina su facebook" target="_blank"><i class="fa fa-facebook"></i> 
        Facebook</a> <a href="https://twitter.com/home?status=<?php echo $this->currentUrl; ?>" title="Condividi pagina su Twitter"><i class="fa fa-twitter"></i> Twitter</a> 
        
    </p>

    <hr>
</div>
<?php endforeach; ?>