<?php echo $this->doctype(); ?>

<html lang="it">
<head>
    <meta charset="utf-8">
    <?php

    echo $this->headTitle('')->setSeparator(' - ')->setAutoEscape(false);

    echo $this->headMeta()
        ->appendName('viewport', 'width=device-width, initial-scale=1.0')
        ->appendHttpEquiv('X-UA-Compatible', 'IE=edge');

    echo $this->headLink()
              ->prependStylesheet($this->basePath().'/public/common/bootstrap3/css/bootstrap.min.css')
              ->prependStylesheet('//netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.css')

    ?>

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"></script>
    <![endif]-->

    <?php

    echo $this->headScript()
        ->prependFile($this->basePath() . '/public/common/bootstrap3/js/bootstrap.min.js')
        ->prependFile($this->basePath() . '/public/common/jquery/jquery.min.js');

    ?>

</head>
<body>

    <div class="container">
	    <?php echo $this->content; ?>
    </div>
	
	<?php echo $this->inlineScript() ?>
	
    </body>
</html>
