<div class="container content">
	<div class="row">
	
    <!--left col-->
    <div id="left-col" class="span8">
		
		<div class="entry-content">
		
		<!-- Category Label -->
		<div class="sixteen columns mb0">
			<div class="gdl-page-title-wrapper">
				<h1 class="gdl-page-title gdl-title title-color"><?php echo $this->templateData['controllerResult'][0]['name'] ?></h1>
				<div class="gdl-page-caption"></div>
				<div class="gdl-page-title-left-bar"></div>
				<div class="clear"></div>
			</div>
		</div>

		<!-- Breadcrumb -->
		<p><strong><a href="<?=$templateData['remotelinkWeb'].$templateData['languageAbbreviation']?>" title="Home page">Home</a> &raquo; <?php echo $templateData['categoryName'] ?></strong> <?php if ($templateData['categoryName'] != $templateData['controllerResult']['title']): ?>&raquo; <?php echo $templateData['controllerResult']['title'] ?><?php endif; ?></p>
		
		<!--  Main Content -->
		<?php if ($this->templateData['languageAbbreviation']=='it'): ?>
		<ul class="gdl-accordion">
			<li class="gdl-divider">
				<h2 class="accordion-head title-color gdl-title"><span class="accordion-head-image active"></span>Come sar&agrave;?</h2>
				<div class="accordion-content" style="display: block;">
					<div><a href="<?php echo $this->basePath().'/'.$this->templateData['imagedir'] ?>plant/big/main.jpg" class="fancyboxsingleimage" title="Pianta panormica nuovo Parco Cascine Firenze"><img src="<?php echo $this->basePath().'/'.$this->templateData['imagedir'] ?>plant/thumbs/main.jpg" alt="Pianta panoramica"></a></div></div>
			</li>
			<li class="gdl-divider">
				<h2 class="accordion-head title-color gdl-title"><span class="accordion-head-image"><img src="<?php echo $this->basePath().'/'.$this->templateData['imagedir'] ?>icon/plant/ristorante.jpg" alt="Ristorante icona colore"></span>Ristorante</h2>
				<div class="accordion-content" style="display: none;">
					<div><a href="<?php echo $this->basePath().'/'.$this->templateData['imagedir'] ?>plant/big/ristorante.jpg" class="fancyboxsingleimage" title="Pianta panormaica area ristorante"><img src="<?php echo $this->basePath().'/'.$this->templateData['imagedir'] ?>plant/thumbs/ristorante.jpg" alt="Icona Ristorante"></a></div>
					<strong>Ristorante</strong>, un posto dove trovare pietanze inusuali, legate all'ambiente di un parco fluviale, storico e internazionale, una sorpresa, speriamo.</div>
			</li>
			<li class="gdl-divider">
				<h2 class="accordion-head title-color gdl-title"><span class="accordion-head-image"><img src="<?php echo $this->basePath().'/'.$this->templateData['imagedir'] ?>icon/plant/pizzeria.jpg" alt="Pizzeria icona colore"></span>Pizzeria</h2>
				<div class="accordion-content" style="display: none;">
					<div><a href="<?php echo $this->basePath().'/'.$this->templateData['imagedir'] ?>plant/big/pizzeria.jpg" class="fancyboxsingleimage" title="Pianta area pizzeria"><img src="<?php echo $this->basePath().'/'.$this->templateData['imagedir'] ?>plant/thumbs/pizzeria.jpg" alt="Pianta area pizzeria"></a></div>
					<strong>Pizzeria</strong>, un posto dove tutti possono trovare qualcosa da mangiare un po' a tutte le ore del giorno e della sera... un posto tranquillo e comodo, immerso nel verde, ma in citt&agrave;, una fantastica pizza nel forno a legna o qualcosa di veloce...</div>
			</li>
			<li class="gdl-divider">
				<h2 class="accordion-head title-color gdl-title"><span class="accordion-head-image"><img src="<?php echo $this->basePath().'/'.$this->templateData['imagedir'] ?>icon/plant/bar.jpg" alt="Bar icon"></span>Bar</h2>
				<div class="accordion-content" style="display: none;">
					<div><a href="<?php echo $this->basePath().'/'.$this->templateData['imagedir'] ?>plant/big/bar.jpg" class="fancyboxsingleimage" title="Pianta area Bar"><img src="<?php echo $this->basePath().'/'.$this->templateData['imagedir'] ?>plant/thumbs/bar.jpg" alt="Pianta Bar"></a></div>
					<strong>Bar</strong>, accogliente e mattiniero per una buona colazione, uno spuntino in qualsiasi momento della giornata, fornito di un gelato freschissimo e informato sugli aperitivi del momento.
				</div>
			</li>
			<li class="gdl-divider">
				<h2 class="accordion-head title-color gdl-title"><span class="accordion-head-image"><img src="<?php echo $this->basePath().'/'.$this->templateData['imagedir'] ?>icon/plant/arena-freewifi.jpg" alt="Icon colore arena wifi"></span>Arena wi-fi</h2>
				<div class="accordion-content" style="display: none;">
					<div><a href="<?php echo $this->basePath().'/'.$this->templateData['imagedir'] ?>plant/big/arena-freewifi.jpg" class="fancyboxsingleimage" title="Pianta arena wi-fi"><img src="<?php echo $this->basePath().'/'.$this->templateData['imagedir'] ?>plant/thumbs/arena-freewifi.jpg" alt="Icona colore arena free wifi"></a></div>
				<strong>Arena wi-fi</strong>, navigazione libera immersi nel verde, comodamente seduti ai tavoli o sulle gradinate.</div>
			</li>
			<li class="gdl-divider">
				<h2 class="accordion-head title-color gdl-title"><span class="accordion-head-image"><img src="<?php echo $this->basePath().'/'.$this->templateData['imagedir'] ?>icon/plant/teatro-aperto.jpg" alt="Teatro all'aperto icona colore"></span>Teatro</h2>
				<div class="accordion-content" style="display: none;">
					<div><a href="<?php echo $this->basePath().'/'.$this->templateData['imagedir'] ?>plant/big/teatro-aperto.jpg" class="fancyboxsingleimage" title="Pianta teatro all'aperto"><img src="<?php echo $this->basePath().'/'.$this->templateData['imagedir'] ?>plant/thumbs/teatro-aperto.jpg" alt="Teatro all'aperto"></a></div>
					<strong>Teatro</strong>, la scommessa più grande e stimolante, la voglia di spaziare e curiosare, musica e intrattenimento, qualche esperimento...</div>
			</li>
			<li class="gdl-divider">
				<h2 class="accordion-head title-color gdl-title"><span class="accordion-head-image"><img src="<?php echo $this->basePath().'/'.$this->templateData['imagedir'] ?>icon/plant/spogliatoio-sportivi.jpg" alt="Spogliatoio icona colore"></span>Spogliatoio per sportivi</h2>
				<div class="accordion-content" style="display: none;">
					<div><a href="<?php echo $this->basePath().'/'.$this->templateData['imagedir'] ?>plant/big/spogliatoio-sportivi.jpg" class="fancyboxsingleimage" title="Pianta spogliatoio sportivi"><img src="<?php echo $this->basePath().'/'.$this->templateData['imagedir'] ?>plant/thumbs/spogliatoio-sportivi.jpg" alt=""></a></div><strong>Area Sportivi</strong>, la svolta, l'accoglienza, il pensiero che va a farsi un giro all'estero e torna indietro arricchito di voglia di fare.</div>
			</li>
			<li class="gdl-divider">
				<h2 class="accordion-head title-color gdl-title"><span class="accordion-head-image"><img src="<?php echo $this->basePath().'/'.$this->templateData['imagedir'] ?>icon/plant/infopoint.jpg" alt="Spogliatoio icona colore"></span>Info point parco</h2>
				<div class="accordion-content" style="display: none;">
					<div><a href="<?php echo $this->basePath().'/'.$this->templateData['imagedir'] ?>plant/big/infopoint.jpg" class="fancyboxsingleimage"><img src="<?php echo $this->basePath().'/'.$this->templateData['imagedir'] ?>plant/thumbs/infopoint.jpg" alt="Info point parco"></a></div>
					<strong>Info Point Parco</strong>, abbiamo accennato al fatto che questo parco inizia la sua storia nel 1300 d.c. oggi torna ad estendere le sue possibilit&agrave; di itinerari fino al Parco dei Renai di Signa... prima l'atmosfera di parco cittadino, poi di parco fluviale ed infine di parco a carattere lacustre... ma per sapere tutto su iniziative, dove andare e fino dove &egrave; possibile arrivare con i mezzi pubblici, passate a trovarci!</div>
			</li>
			<li class="gdl-divider">
				<h2 class="accordion-head title-color gdl-title"><span class="accordion-head-image"><img src="<?php echo $this->basePath().'/'.$this->templateData['imagedir'] ?>icon/plant/noleggio-bici.jpg" alt="Noleggio bici elettriche icona colore"></span>Noleggio bici elettriche</h2>
				<div class="accordion-content" style="display: none;">
					<div><a href="<?php echo $this->basePath().'/'.$this->templateData['imagedir'] ?>plant/big/noleggio-bici.jpg" class="fancyboxsingleimage" title="Pianta area noleggio bici elettriche"><img src="<?php echo $this->basePath().'/'.$this->templateData['imagedir'] ?>plant/thumbs/noleggio-bici.jpg" alt="Pianta area noleggio bici elettriche"></a></div>
					<strong>Noleggio bici elettriche</strong>, e se c'&egrave; da fare per un giorno intero, con una bici elettrica le possibilit&agrave; si decuplicano in totale indipendenza e se il tempo tiene... vai!</div>
			</li>
			<li class="gdl-divider">
				<h2 class="accordion-head title-color gdl-title"><span class="accordion-head-image"><img src="<?php echo $this->basePath().'/'.$this->templateData['imagedir'] ?>icon/plant/parcheggio.jpg" alt="Parcheggio icona colore"></span>Parcheggio</h2>
				<div class="accordion-content" style="display: none;">
				<div><a href="<?php echo $this->basePath().'/'.$this->templateData['imagedir'] ?>plant/big/parcheggio.jpg" class="fancyboxsingleimage" title="Pianta parcheggio"><img src="<?php echo $this->basePath().'/'.$this->templateData['imagedir'] ?>plant/thumbs/parcheggio.jpg" alt="Pianta parcheggio"></a></div>
				<strong>Parcheggio</strong> gratuito per i clienti.
			</div>
			</li>
		</ul>
		<?php else: ?>
		<ul class="gdl-accordion">
		
			<li class="gdl-divider">
				<h2 class="accordion-head title-color gdl-title"><span class="accordion-head-image active"></span>The progect (will be like?)</h2>
				<div class="accordion-content" style="display: block;">
				<div><a class="fancyboxsingleimage" href="<?php echo $this->basePath().'/'.$this->templateData['imagedir'] ?>plant/big/main.jpg" title=""><img alt="" src="<?php echo $this->basePath().'/'.$this->templateData['imagedir'] ?>plant/thumbs/main.jpg"></a></div>
				</div>
			</li>
			
			<li class="gdl-divider">
			<h2 class="accordion-head title-color gdl-title"><span class="accordion-head-image active"><img alt="Restaurant icon" src="<?php echo $this->basePath().'/'.$this->templateData['imagedir'] ?>icon/plant/ristorante.jpg"></span>Restaurant</h2>
			<div class="accordion-content" style="display: none;">
			<div><a class="fancyboxsingleimage" href="<?php echo $this->basePath().'/'.$this->templateData['imagedir'] ?>plant/big/ristorante.jpg" title="Restaurant plant"><img alt="Plant" src="<?php echo $this->basePath().'/'.$this->templateData['imagedir'] ?>plant/thumbs/ristorante.jpg" title="Restaurant plant"></a></div>
			<strong>Restaurant</strong>, a place to find unusual dishes, related to the environment of a river park, historical and international, a surprise, we hope.</div>
			</li>
			
			<li class="gdl-divider">
			<h2 class="accordion-head title-color gdl-title"><span class="accordion-head-image active"><img alt="Pizzeria icon" src="<?php echo $this->basePath().'/'.$this->templateData['imagedir'] ?>icon/plant/pizzeria.jpg"></span>Pizzeria</h2>
			<div class="accordion-content" style="display: none;">
			<div><a class="fancyboxsingleimage" href="<?php echo $this->basePath().'/'.$this->templateData['imagedir'] ?>plant/big/pizzeria.jpg" title="Pizzeria plant"><img alt="Pizzeria plant" src="<?php echo $this->basePath().'/'.$this->templateData['imagedir'] ?>plant/thumbs/pizzeria.jpg"></a></div>
			<strong>Pizzeria</strong>, a place where everyone can find something to eat, at any hour of the day and evening ... a quiet and comfortable place, in the green, but in the city, a fantastic pizza in the wood oven or something fast ...</div>
			</li>
		
			<li class="gdl-divider">
			<h2 class="accordion-head title-color gdl-title"><span class="accordion-head-image active"><img src="<?php echo $this->basePath().'/'.$this->templateData['imagedir'] ?>icon/plant/bar.jpg" alt="Bar icon"></span>Bar</h2>
			<div class="accordion-content" style="display: none;">
			<div><a class="fancyboxsingleimage" href="<?php echo $this->basePath().'/'.$this->templateData['imagedir'] ?>plant/big/bar.jpg" title="Bar plant"><img alt="Bar plant" src="<?php echo $this->basePath().'/'.$this->templateData['imagedir'] ?>plant/thumbs/bar.jpg"></a></div>
			<strong>Bar</strong>,Cozy and early open for a good breakfast, a snack at any time of the day, equipped with a fresh ice cream and informed about new cocktails in town.</div>
			</li>
		
			<li class="gdl-divider">
			<h2 class="accordion-head title-color gdl-title"><span class="accordion-head-image active"><img alt="Wi-fi area" src="<?php echo $this->basePath().'/'.$this->templateData['imagedir'] ?>icon/plant/arena-freewifi.jpg"></span>Wi-fi Area</h2>
			<div class="accordion-content" style="display: none;">
			<div><a class="fancyboxsingleimage" href="<?php echo $this->basePath().'/'.$this->templateData['imagedir'] ?>plant/big/arena-freewifi.jpg" title="Wi-fi plant"><img alt="Icona colore arena free wifi" src="<?php echo $this->basePath().'/'.$this->templateData['imagedir'] ?>plant/thumbs/arena-freewifi.jpg"></a></div>
			<strong>Free wi-fi</strong>, Free navigation in the green, sit at the tables or in the stands.</div>
			</li>
		
			<li class="gdl-divider">
			<h2 class="accordion-head title-color gdl-title"><span class="accordion-head-image active"><img alt="Theater" src="<?php echo $this->basePath().'/'.$this->templateData['imagedir'] ?>icon/plant/teatro-aperto.jpg"></span>Theater</h2>
			<div class="accordion-content" style="display: none;">
			<div><a class="fancyboxsingleimage" href="<?php echo $this->basePath().'/'.$this->templateData['imagedir'] ?>plant/big/teatro-aperto.jpg" title="Pianta teatro all'aperto"><img alt="Teatro all'aperto" src="<?php echo $this->basePath().'/'.$this->templateData['imagedir'] ?>plant/thumbs/teatro-aperto.jpg"></a></div>
			<strong>Theatre</strong>, big and stimulating challenge, the desire to wander and browse, music and entertainment, some experiment ...</div>
			</li>
		
			<li class="gdl-divider">
			<h2 class="accordion-head title-color gdl-title"><span class="accordion-head-image active"><img alt="Area Sports" src="<?php echo $this->basePath().'/'.$this->templateData['imagedir'] ?>icon/plant/spogliatoio-sportivi.jpg"></span>Area Sports</h2>
			<div class="accordion-content" style="display: none;">
			<div><a class="fancyboxsingleimage" href="<?php echo $this->basePath().'/'.$this->templateData['imagedir'] ?>plant/big/spogliatoio-sportivi.jpg" title="Pianta spogliatoio sportivi"><img alt="" src="<?php echo $this->basePath().'/'.$this->templateData['imagedir'] ?>plant/thumbs/spogliatoio-sportivi.jpg"></a></div>
			<strong>Area Sports</strong>, the turning point, the reception, the thought that run to take a trip abroad and come back enriched with enthusiasm and news.</div>
			</li>
		
			<li class="gdl-divider">
			<h2 class="accordion-head title-color gdl-title"><span class="accordion-head-image active"><img alt="" src="<?php echo $this->basePath().'/'.$this->templateData['imagedir'] ?>icon/plant/infopoint.jpg"></span>Info point park</h2>
			<div class="accordion-content" style="display: none;">
			<div><a class="fancyboxsingleimage" href="<?php echo $this->basePath().'/'.$this->templateData['imagedir'] ?>plant/big/infopoint.jpg"><img alt="Info point parco" src="<?php echo $this->basePath().'/'.$this->templateData['imagedir'] ?>plant/thumbs/infopoint.jpg"></a></div>
			<strong>Info Point Park</strong>, we mentioned the fact that this park begins its history in 1300 A.C. Now back to extend its range of itineraries to the Parco dei Renai Signa ... before the atmosphere of the city park, then a river park and finally a lake park ... but to know everything about events, where to go and where you can get to by public transport, come and visit us!</div>
			</li>
		
			<li class="gdl-divider">
			<h2 class="accordion-head title-color gdl-title"><span class="accordion-head-image active"><img alt="Noleggio bici elettriche icona colore" src="<?php echo $this->basePath().'/'.$this->templateData['imagedir'] ?>icon/plant/noleggio-bici.jpg"></span>Rent a bike</h2>
			<div class="accordion-content" style="display: none;">
			<div><a class="fancyboxsingleimage" href="<?php echo $this->basePath().'/'.$this->templateData['imagedir'] ?>plant/big/noleggio-bici.jpg" title="Rental electric bikes"><img alt="Rental electric bikes" src="<?php echo $this->basePath().'/'.$this->templateData['imagedir'] ?>plant/thumbs/noleggio-bici.jpg"></a></div>
			<strong>Rental electric bikes</strong>, and if there are things to do for a whole day, with an electric bike possibilities increases tenfold in total independence and if the weather holds ... Go!</div>
			</li>
		
			<li class="gdl-divider">
			<h2 class="accordion-head title-color gdl-title"><span class="accordion-head-image active"><img alt="Parking area" src="<?php echo $this->basePath().'/'.$this->templateData['imagedir'] ?>icon/plant/parcheggio.jpg"></span>Parking</h2>
			<div class="accordion-content" style="display: none;">
			<div><a class="fancyboxsingleimage" href="<?php echo $this->basePath().'/'.$this->templateData['imagedir'] ?>plant/big/parcheggio.jpg" title="Pianta parcheggio"><img alt="Pianta parcheggio" src="<?php echo $this->basePath().'/'.$this->templateData['imagedir'] ?>plant/thumbs/parcheggio.jpg"></a></div>
			<strong>Parking</strong>, free parking for customers.</div>
			</li>
		</ul>
		<?php endif; ?>
		</div>
		
	</div>

	
	<div id="right-col" class="span4">
		<div class="sidebar">
			<?php
			echo $this->partial( $this->templateData['template_path'].'sidebar.phtml');
			?>
		</div>
	</div>

	
	</div>
</div>
