<div class="container content">
	<div class="row"> 
	
    <!--left col-->
    <div id="left-col" class="span8">
		
		<div class="entry-content">
		
		<!-- Category Label -->
		<div class="sixteen columns mb0">
			<div class="gdl-page-title-wrapper">
				<h1 class="gdl-page-title gdl-title title-color"><?php echo $this->templateData['controllerResult'][0]['name'] ?></h1>
				<div class="gdl-page-caption"></div>
				<div class="gdl-page-title-left-bar"></div>
				<div class="clear"></div>
			</div>
		</div>

		<!-- Breadcrumb -->
		<p><strong><a href="<?=$templateData['remotelinkWeb'].$templateData['languageAbbreviation']?>" title="Home page">Home</a> &raquo; <?php echo $templateData['categoryName'] ?></strong> <?php if ($templateData['categoryName'] != $templateData['controllerResult']['title']): ?>&raquo; <?php echo $templateData['controllerResult']['title'] ?><?php endif; ?></p>
		
		<h3><?php echo $templateData['controllerResult']['title'] ?></h3>
		
		<div><?php echo $templateData['controllerResult']['description'] ?></div>
	
		</div>
		
	</div>

	
	<div id="right-col" class="span4">
		<div class="sidebar">
			<?php
			echo $this->partial( $this->templateData['template_path'].'sidebar.phtml');
			?>
		</div>
	</div>

	
	</div>
</div>
