<!-- Category Label -->
<div class="sixteen columns mb0">
	<div class="gdl-page-title-wrapper">
		<h1 class="gdl-page-title gdl-title title-color"><?php echo $this->templateData['controllerResult'][0]['name'] ?></h1>
		<div class="gdl-page-caption"></div>
		<div class="gdl-page-title-left-bar"></div>
		<div class="clear"></div>
	</div>
</div>

<div class="gdl-page-float-left">
	<div class='gdl-page-item'>
		<div class="sixteen columns mt0">
			<div class="gdl-page-content">
			
			<!--  Breadcrumb -->
			<p><strong><a href="<?=$this->templateData['remotelinkWeb'].$this->templateData['languageAbbreviation']?>" title="Home page">Home</a></strong> &raquo; <?php echo $this->templateData['categoryName'] ?></p>
			
			<p>Nella sezione <strong><?php echo $this->templateData['categoryName'] ?></strong> sono presenti <?php echo count($this->templateData['controllerResult']) ?> pagine: </p>
			
			<ul>
			<?php foreach($this->templateData['controllerResult'] as $controllerResult): ?>
			
			<li><a href="<?php echo $controllerResult['linkDetails'] ?>" title="<?php echo $controllerResult['title'] ?>"><?php if ($this->templateData['categoryName'] != $controllerResult['title']): ?><?php echo $controllerResult['title'] ?></a><?php endif; ?></li>
			
			<?php endforeach; ?>
			</ul>
			
			<div style="clear:both; height: 20px"></div>
			
			</div>
		</div>
	</div>
</div>

<div class="five columns mt0 gdl-right-sidebar">
	<div class="right-sidebar-wrapper gdl-divider">
		<?php
		echo $this->partial( $this->templateData['template_path'].'sidebar.phtml');
		?>
		<div class="pt30"></div>
	</div>
</div>
