<!doctype html>
<html>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
<title>DICHIARAZIONE SOSTITUTIVA DELL’ATTO DI NOTORIET&Agrave; (Art. 5 e 47 D.P.R. 445 del 28/12/2000)</title>
<style>
    h1, h2 { margin-bottom: 50px; text-align: center; }
    p { margin-bottom: 10px }
    .text-center { text-align: center }
    .text-right { text-align: right }
</style>
<body>

<h3 class="text-center">DICHIARAZIONE SOSTITUTIVA DELL’ATTO DI NOTORIET&Agrave; <br>(Art. 5 e 47 D.P.R. 445 del 28/12/2000)</h3>

<p>Il/La Sottoscritto/a</p>

<p>
    <strong>Cognome:</strong> <?php echo $this->records->cognome ?> <strong>Nome:</strong> <?php echo $this->records->nome ?> <strong>Sesso:</strong> <?php echo $this->records->sesso ?>
</p>

<p><strong>Nato/a:</strong> <?php echo $this->records->luogo_nascita ?> <strong>Stato:</strong> <?php echo $this->records->stato_nascita ?> <strong>Provincia:</strong> <?php echo $this->records->provincia_nascita ?> <strong>Comune:</strong> <?php echo $this->records->luogo_nascita ?> <strong>il:</strong> <?php echo $this->records->data_nascita ?></p>

<p><strong>Residente a:</strong> <?php echo $this->records->luogo_residenza ?> <strong>Prov:</strong> <?php echo $this->records->provincia_residenza ?> <strong>Indirizzo:</strong> <?php echo $this->records->indirizzo_residenza ?> <strong>Numero:</strong> <?php echo $this->records->numero_residenza ?> </p>

<!--
<p><strong>Domiciliato a:</strong> <strong>Prov:</strong> </p>
<p><strong>Indirizzo:</strong> </p>
<p><strong>Numero:</strong> </p>
-->

<p>consapevole delle sanzioni penali richiamate dall'art.76 del d.P.R. 28.12.2000 n.445, in caso di dichiarazioni mendaci e di formazione o uso di atti falsi</p>

<h4 class="text-center">DICHIARA</h4>

<p>(indicare gli stati, qualit&agrave; personali o fatti necessari ai fini dell'autorizzazione richiesta ed autocertificabili ai sensi dell'art .47 D.P.R. 445/2000)</p>

<p><strong>Luogo:<?php echo $this->records->luogodichiarazione ?></strong> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<strong>Data:</strong> <?php echo $this->records->datadichiarazione ?></p>

<p>Ai sensi dell'art.38 del D.P.R. del 28.12.2000, n.445 la dichiarazione &egrave; sottoscritta dall'interessato in presenza del dipendente addetto ovvero sottoscritta e presentata all'ufficio competente, unitamente a copia fotostatica non autenticata di un documento di identit&agrave; del sottoscrittore. &Egrave; ammessa la presentazione anche via fax, per via telematica o a mezzo posta.</p>

<p><strong>Firma:</strong></p>

<p>_________________________________________</p>

<p>Allego fotocopia documento di identit&agrave;</p>