<ul class="breadcrumb">
    <li><a href="<?php echo $this->basepath() ?>/" title="Home page">Home</a> <span class="divider"></span></li>
    <li class="active"><?php echo $this->category; ?></li>
</ul>

<p class="text-right"><a href="#" class="btn btn-warning" title="Visualizza Feed RSS per la categoria blog <?php //echo $this->maindata[0]['nomeCategoria']; ?>"><i class="fa fa-rss"></i> Feed RSS <?php echo $this->category; ?></a></p>

<?php foreach($this->paginator as $key => $row): ?>
    <h1><?php echo $row['title'] ?></h1>
    <?php if ($row['subtitle']): ?>
        <h2><?php echo $row['subtitle'] ?></h2>
    <?php endif; ?>
    <div class="blog_list_description">
        <?php echo $row['description'] ?> <strong>&raquo; <a href="<?php echo $this->basepath().$row['linkDetails'] ?>" title="<?php echo $row['title'] ?>">Leggi tutto</a></strong>
    </div>
<?php endforeach; ?>

<?php

if ( count($this->paginator) > 1 ):
    echo $this->paginationControl(
        $this->paginator,
        'sliding',
        'application/pagination/bootstrap.phtml',
        array(
            'category' => $category,
            'route' => 'posts'
        )
    );
endif;
