<ul class="breadcrumb">
    <li><a href="<?php echo $this->url('admin', array('lang' => $this->params()->fromRoute('lang'))); ?>" title="Home page">Home</a> <span class="divider"></span></li>
    <li class="active">Migrazione</li>
</ul>

<h2>Migrazione dati vecchio CMS enti locali</h2>

<p>Migrazione dati dal <strong>database vecchio CMS enti locali</strong>.</p>

<div class="alert alert-warning">
    <p><strong>Attenzione: i dati dei moduli attualmente presenti veranno eliminati.</strong></p>
    <p>Assicurarsi che le <strong>tabelle del vecchio database</strong> siano presenti per il relativo modulo che si vuole migrare</p>
</div>

<div class="row">
    <div class="col-md-6">
        <h4>Sezioni e sottosezioni</h4>
        <ul>
            <li>Sezioni</li>
            <li>Sottosezioni</li>
        </ul>
    </div>
    <div class="col-md-6">
        <h4>Contenuti</h4>
        <ul>
            <li><a href="<?php echo $this->url('admin/migrazione-contenuti', array('lang' => 'it', 'action' => 'index')); ?>" title="">Articoli</a></li>
            <li><a href="<?php echo $this->url('admin/migrazione-contenuti', array('lang' => 'it', 'action' => 'attachments')); ?>" title="">
                    <i class="fa fa-paperclip"></i> Allegati</a>
            </li>
        </ul>

        <h4>Amministrazione trasparente</h4>
        <ul>
            <li><a href="#" title="Migrazione Allegati Amm.Trasparente">
                    <i class="fa fa-paperclip"></i> Allegati</a>
            </li>
        </ul>
    </div>
</div>

<div class="row">
    <div class="col-md-6">
        <h4>Albo pretorio</h4>
        <ul>
            <li><a href="<?php echo $this->url('admin/migrazione-albopretorio', array('lang' => 'it', 'action' => 'index')); ?>" title="">Articoli</a></li>
            <li><a href="<?php echo $this->url('admin/migrazione-albopretorio', array('lang' => 'it', 'action' => 'sezioni')); ?>"" title="">Sezioni</a></li>
            <li><a href="<?php echo $this->url('admin/migrazione-albopretorio', array('lang' => 'it', 'action' => 'attachments')); ?>" title=""><i class="fa fa-paperclip"></i> Allegati</a></li>
        </ul>
    </div>
    <div class="col-md-6">
        <h4>Stato Civile</h4>
        <ul>
            <li><a href="<?php echo $this->url('admin/migrazione-statocivile', array('lang' => 'it', 'action' => 'index')); ?>" title="">Atti</a></li>
            <li><a href="<?php echo $this->url('admin/migrazione-statocivile', array('lang' => 'it', 'action' => 'sezioni')); ?>" title="">Sezioni</a></li>
            <li><a href="<?php echo $this->url('admin/migrazione-statocivile', array('lang' => 'it', 'action' => 'attachments')); ?>" title=""><i class="fa fa-paperclip"></i> Allegati</a></li>
        </ul>
    </div>
</div>


<div class="row">
    <div class="col-md-6">
        <h4>Atti di concessione</h4>
        <ul>
            <li>Atti</a></li>
        </ul>
    </div>
    <div class="col-md-6">
        <h4>Contratti pubblici</h4>
        <ul>
            <li>Bandi</a></li>
            <li><i class="fa fa-paperclip"></i> Allegati</a></li>
        </ul>
    </div>
</div>

<div class="row">
    <div class="col-md-12">
        <h4>Enti Terzi</h4>
        <ul>
            <li>Enti Terzi</li>
        </ul>
    </div>
</div>

<div class="row">
    <div class="col-md-6">
        <h4>Blogs</h4>
        <ul>
            <li>Eventi</li>
            <li><i class="fa fa-paperclip"></i> Allegati</a></li>
        </ul>
    </div>
    <div class="col-md-6">
        <h4>Foto</h4>
        <ul>
            <li>Foto</a></li>
            <li>Categorie</a></li>
        </ul>
    </div>
</div>

<div class="row">
    <div class="col-md-12">
        <h4>Utenti</h4>
        <ul>
            <li>Utenti</li>
            <li>Responsabili procedimento</a></li>
            <li>Settori</a></li>
        </ul>
    </div>
</div>

<h3>Elimina tabelle database versione precedente</h3>

<p>Attenzione: prima di procedere con l'eliminazione delle tabelle del vecchio CMS, assicurarsi che TUTTI precedenti siano stati importati.</p>

<a href="#myModal" class="btn btn-danger" data-toggle="modal">
    Conferma cancellazione
</a>

<br>
<br>

<!-- Modal delete old CMS db tables -->
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content panel-danger">

            <div class="modal-header panel-heading">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                <h4 class="modal-title" id="deleteModalLabel"><strong>Conferma eliminazione?</strong></h4>
            </div>

            <form action="" method="post" id="deleteOldCMSFormMigration" role="form">
                <div class="modal-body">
                    <p><strong>Attenzione:</strong> le tabelle della versione precedente del database verranno eliminate definitivamente.</p>

                    <input type="hidden" name="deleteId" id="deleteId" value="" />
                </div>

                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Annulla</button>
                    <button type="submit" name="btnconfirmdeleteoldcmstables" class="btn btn-danger">Conferma</button>
                </div>
            </form>

        </div>
    </div>
</div>

