<?php echo $this->doctype(); ?>
<html lang="<?php echo $this->templateData['languageAbbreviation'] ?>">
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
	<title><?php echo $this->templateData['sitename'] ?> - <?php echo $this->templateData['languageLabels']['ADMIN_RESERVED_AREA']?></title>
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	
	<?php
	echo $this->headLink()
              ->prependStylesheet($this->basePath().'/common/bootstrap3/css/bootstrap.min.css')
              ->prependStylesheet('//netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.css')
	?>
	
	<!-- HTML5 shim, for IE6-8 support of HTML5 elements -->
	<!--[if lt IE 9]>
	<script src="<?php echo $this->basePath().'/common/js/html5shiv.js'; ?>"></script>
	<![endif]-->

	<!-- Fav and touch icons
	<link rel="apple-touch-icon-precomposed" sizes="144x144" href="img/apple-touch-icon-144-precomposed.png">
	<link rel="apple-touch-icon-precomposed" sizes="114x114" href="img/apple-touch-icon-114-precomposed.png">
	<link rel="apple-touch-icon-precomposed" sizes="72x72" href="img/apple-touch-icon-72-precomposed.png">
	<link rel="apple-touch-icon-precomposed" href="img/apple-touch-icon-57-precomposed.png">
	<link rel="shortcut icon" href="img/favicon.png">
	-->

</head>

<body>

<noscript>
	<div>
		<h3><?php echo $this->templateData['languageLabels']['ADMIN_NOJAVSCRPT_TITLE']; ?></h3>
		<div><?php echo $this->templateData['languageLabels']['ADMIN_NOJAVSCRPT_DESCRIPTION'] ?></div>
	</div>
</noscript>

<div class="container">
	<div class="row clearfix">
		<div class="col-md-12 column">
			<nav class="navbar navbar-default" role="navigation">
				<div class="navbar-header">
					 <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1"> <span class="sr-only">Toggle navigation</span><span class="icon-bar"></span><span class="icon-bar"></span><span class="icon-bar"></span></button> <a class="navbar-brand" href="javascript:void(0)"><?php echo $this->templateData['sitename'] ?></a>
				</div>
				
				<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
					<ul class="nav navbar-nav">
						<li class="active">
							<a href="javascript:void(0)" title="Back to the home page"><i class="fa fa-home"></i> Home</a>
						</li>
						<!-- Preview -->
						<li>
							<a href="<?php echo $this->templateData['remotelinkWeb'] ?>" target="_blank" title="<?php echo $this->templateData['languageLabels']['ADMIN_PREVIEW_TITLE'] ?>"><i class="fa fa-eye"></i> <?php echo $this->templateData['languageLabels']['ADMIN_PREVIEW'] ?></a>
						</li>
						<?php
						/*
						<li class="dropdown">
							<a data-toggle="dropdown" class="dropdown-toggle" href="#">Moduli <b class="caret"></b></a>
								<ul class="dropdown-menu">
									<li class="dropdown submenu">
										<a href="#" class="dropdown-toggle" data-toggle="dropdown">Pagine</a>
										<ul class="dropdown-menu submenu-show submenu-hide">
										<li><a href="#" title="">Nuovo</a></li>
										<li><a href="#" title="">Modifica \ Elimina</a></li>
										<li class="dropdown submenu">
											<a href="#" class="dropdown-toggle" data-toggle="dropdown">Categorie</a>
												<ul class="dropdown-menu submenu-show submenu-hide">
													<li><a href="#">Level 1.1.1</a></li>
													<li><a href="#">Level 1.1.2</a></li>
													<li><a href="#">Level 1.1.3</a></li>
													<li><a href="#">Level 1.1.4</a></li>
												</ul>
										</li>
										
									</ul>
								</li>

								<li><a href="#" title="">Blogs</a></li>
								<li><a href="#" title="">Foto</a></li>
								<li><a href="#" title="">Video</a></li>
								<li><a href="#" title="">E-commerce</a></li>
								<li><a href="#" title="">Annunci</a></li>
								<li><a href="#" title="">Takeaway</a></li>
								
							</ul>
						</li>
						*/
						?>
						<!-- Languages -->
						<li class="dropdown"><a href="javascript:void(0)" title="<?php echo $this->templateData['languageLabels']['ADMIN_LANGUAGE'] ?>" class="dropdown-toggle" data-toggle="dropdown"><i class="fa fa-flag"></i> <?php echo $this->templateData['languageLabels']['ADMIN_LANGUAGE'] ?> <b class="caret"></b></a>
							<ul class="dropdown-menu">
								<?php
								foreach($this->templateData['languageAllAvailable'] as $availableLanguages):
								?>
								<li><a href="/backend/'<?php echo $availableLanguages['abbreviation1'].'/'; ?>" title="<?php echo $availableLanguages['abbreviation3'] ?>"><?php echo $availableLanguages['abbreviation3'] ?></a></li>
								<?php
								endforeach;
								?>
							</ul>
						</li>
						<!-- Options -->
						<li>
							<a href="?lang=<?php echo $this->templateData['languageAbbreviation'] ?>" title="<?php echo $this->templateData['languageLabels']['ADMIN_OPTIONS'] ?>"><i class="fa fa-wrench"></i> <?php echo $this->templateData['languageLabels']['ADMIN_OPTIONS'] ?></a>
						</li>
						<!-- Assistance \ Ticketing -->
						<li>
							<a href="?lang=<?php echo $this->templateData['languageAbbreviation'] ?>&amp;controller=formDataController&amp;adminObject=ticketFormData" title="<?php echo $this->templateData['languageLabels']['ADMIN_ASSISTANCE'] ?>"><i class="fa fa-stethoscope"></i> <?php echo $this->templateData['languageLabels']['ADMIN_ASSISTANCE'] ?></a>
						</li>
					</ul>
					
					<!-- User Dropdown Menu -->
					<ul class="nav navbar-nav navbar-right">
						<li class="dropdown">
							<a href="javascript:void(0)" class="dropdown-toggle" data-toggle="dropdown"><i class="fa fa-user"></i> Andrea Fiori <strong class="caret"></strong></a>
							<ul class="dropdown-menu">
								<li>
									<a href="javascript:void(0)" title="<?php echo $this->templateData['languageLabels']['ADMIN_USER_PROFILE'] ?>"><?php echo $this->templateData['languageLabels']['ADMIN_USER_PROFILE'] ?></a>
								</li>
								<li>
									<a href="javascript:void(0)" title="Documentazione"><i class="fa fa-book"></i> Documentazione</a>
								</li>
								<li>
									<a href="javascript:void(0)" title="Application Program Interface"><i class="fa fa-external-link-square"></i> API</a>
								</li>
								<li>
									<a href="javascript:void(0)" title="Database Backup">Database Backup</a>
								</li>
								<li class="divider">
								</li>
								<li>
									<a href="<?php echo $this->templateData['remotelinkWeb'].$this->templateData['loginaction_backend'] ?>" title="<?php echo $this->templateData['languageLabels']['ADMIN_USER_EXIT'] ?>"><i class="fa fa-power-off"></i> <?php echo $this->templateData['languageLabels']['ADMIN_USER_EXIT'] ?></a>
								</li>
							</ul>
						</li>
					</ul>
				</div>
			</nav>
			<div class="row clearfix">
				<?php
				/* Sidebar */
				echo $this->partial($this->templateData['sidebar']);
				?>
				<div class="col-md-9 column">
					<ul class="breadcrumb">
						<li>
							<a href="javascript:void(0)" title="">Home</a> <span class="divider">/</span>
						</li>
						<li>
							<a href="javascript:void(0)" title="">Library</a> <span class="divider">/</span>
						</li>
						<li class="active">
							Data
						</li>
					</ul>
					<?php
					/* Main Template */
					echo $this->partial($this->templateData['templatePartial']);
					?>
				</div>
			</div>
			<div class="row clearfix">
				<div class="col-md-12 column">
					<p class="text-muted">
						&copy; <?php echo date("Y"); ?> <?php echo $this->templateData['sitename'] ?>
					</p>
				</div>
			</div>
		</div>
	</div>
</div>

<!-- JavaScript -->
<script src="<?php echo $this->basePath() ?>/common/jquery/jquery.min.js"></script>
<script src="<?php echo $this->basePath() ?>/common/jquery/form/jquery.form.js"></script>
<!-- <script src="<?php echo $this->basePath() ?>/common/angularjs/angualar.js"></script> -->
<script src="<?php echo $this->basePath() ?>/common/bootstrap3/js/bootstrap.min.js"></script>

<script src="<?php echo $this->basePath() ?>/common/jquery/ckeditor/ckeditor.js"></script>
<script src="<?php echo $this->basePath() ?>/common/ckfinder/ckfinder.js"></script>

<script>
$(document).ready(function () {

});
</script>

<?php echo $this->inlineScript() ?>
</body>
</html>