<?php echo $this->doctype(); ?>
<html lang="it">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    <title><?php echo $this->sitename ?> - Area riservata</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <?php
    echo $this->headLink()
          ->prependStylesheet($this->basePath().'/public/common/bootstrap3/css/bootstrap.min.css')
          ->prependStylesheet($this->basePath().'/public/common/font-awesome/css/font-awesome.min.css')
          ->prependStylesheet($this->basePath().'/public/common/jquery/datetimepicker/jquery.datetimepicker.css')
    ?>
    <style>
    /* Dropdown onmouse over */
    ul.nav li.dropdown:hover ul.dropdown-menu {
        display: block;
    }

    /* Multi level menu */
    .dropdown-submenu {
        position: relative;
    }

    .dropdown-submenu>.dropdown-menu {
        top: 0;
        left: 100%;
        margin-top: -6px;
        margin-left: -1px;
        -webkit-border-radius: 0 6px 6px 6px;
        -moz-border-radius: 0 6px 6px;
        border-radius: 0 6px 6px 6px;
    }

    .dropdown-submenu:hover>.dropdown-menu {
        display: block;
    }

    .dropdown-submenu>a:after {
        display: block;
        content: " ";
        float: right;
        width: 0;
        height: 0;
        border-color: transparent;
        border-style: solid;
        border-width: 5px 0 5px 5px;
        border-left-color: #ccc;
        margin-top: 5px;
        margin-right: -10px;
    }

    .dropdown-submenu:hover>a:after {
        border-left-color: #fff;
    }

    .dropdown-submenu.pull-left {
        float: none;
    }

    .dropdown-submenu.pull-left>.dropdown-menu {
        left: -100%;
        margin-left: 10px;
        -webkit-border-radius: 6px 0 6px 6px;
        -moz-border-radius: 6px 0 6px 6px;
        border-radius: 6px 0 6px 6px;
    }
    
    /* JQuery Validate Label */
    label.error {
        color: red;
        margin-left: 0.5%;
    }
    
    fieldset label {
        font-weight: normal;
        cursor: pointer;
    }
    fieldset input  {
        cursor: pointer
    }
    </style>
    
    <!-- HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
    <script src="<?php echo $this->basePath().'/public/common/js/html5shiv.js'; ?>"></script>
    <![endif]-->

    <!-- Fav and touch icons -->
    <!--
    <link rel="apple-touch-icon-precomposed" sizes="144x144" href="img/apple-touch-icon-144-precomposed.png">
    <link rel="apple-touch-icon-precomposed" sizes="114x114" href="img/apple-touch-icon-114-precomposed.png">
    <link rel="apple-touch-icon-precomposed" sizes="72x72" href="img/apple-touch-icon-72-precomposed.png">
    <link rel="apple-touch-icon-precomposed" href="img/apple-touch-icon-57-precomposed.png">
    <link rel="shortcut icon" href="img/favicon.png">
    -->

    <script src="<?php echo $this->basePath() ?>/public/common/jquery/jquery.min.js"></script>
    <script src="<?php echo $this->basePath() ?>/public/common/jquery/form/jquery.form.js"></script>
    <script src="<?php echo $this->basePath() ?>/public/common/jquery/validate/jquery.validate.min.js"></script>

    <script src="<?php echo $this->basePath() ?>/public/common/jquery/ckeditor/ckeditor.js"></script>
    <script src="<?php echo $this->basePath() ?>/public/common/jquery/ckfinder/ckfinder.js"></script>

</head>

<body>

<noscript>
    <div>
        <h3>Attenzione: Javascript disattivato</h3>
        <div>&Egrave; stato rilevato che Javascript risulta disattivato nel browser in uso. Abilitare il browser all'utilizzo di Javascript o la presente area risulter&agrave; inutilizzabile.</div>
    </div>
</noscript>

<div class="container">
    <div class="row clearfix">
        <div class="col-md-12 column">
            <nav class="navbar navbar-default" role="navigation">
                
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1"> <span class="sr-only">Toggle navigation</span><span class="icon-bar"></span><span class="icon-bar"></span><span class="icon-bar"></span></button> <a class="navbar-brand" href="<?php echo $this->url('admin', array('lang' => 'it')); ?>" title="<?php echo $this->sitename ?>"><?php echo $this->sitename ?></a>
                </div>

                <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                    <ul class="nav navbar-nav">
                        <li class="active">
                            <a href="<?php echo $this->url('admin', array('lang' => 'it')); ?>" title="Torna alla home page"><i class="fa fa-home"></i> Home</a>
                        </li>
                        <li><a href="<?php echo $this->basepath() ?>" target="_blank" title="Anteprima sito web"><i class="fa fa-eye"></i> Anteprima</a></li>
                    <li>
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">Moduli <b class="caret"></b></a>
                    <ul class="dropdown-menu multi-level">
                        <li class="dropdown-submenu">
                            <a href="<?php echo $this->baseUrl ?>datatable/contents" class="dropdown-toggle" data-toggle="dropdown">Contenuti</a>
                            <ul class="dropdown-menu">
                                <li><a href="<?php echo $this->baseUrl ?>formdata/posts/" title="">Nuovo</a></li>
                                <li><a href="<?php echo $this->baseUrl ?>datatable/contents" title="Modifica \ elimina contenuti">Modifica \ Elimina</a></li>
                                <li class="dropdown-submenu">
                                    <a href="<?php echo $this->baseUrl ?>datatable/categories/?moduleId=4" class="dropdown-toggle" data-toggle="dropdown" title="">Categorie</a>
                                    <ul class="dropdown-menu">
                                        <li><a href="<?php echo $this->baseUrl ?>formdata/categories/?moduleId=4" title="Nuova categoria contenuti">Nuova</a></li>
                                        <li><a href="<?php echo $this->baseUrl ?>datatable/categories/?moduleId=4" title="Modifica \ elimina categorie contenuti">Modifica \ Elimina</a></li>
                                    </ul>
                                </li>
                            </ul>
                        </li>

                        <li class="dropdown-submenu">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown" title="Albo pretorio">Albo pretorio</a>
                            <ul class="dropdown-menu">
                                <li><a href="<?php echo $this->baseUrl ?>formdata/albo-pretorio" title="Nuovo atto">Nuovo atto</a></li>
                                <li><a href="<?php echo $this->baseUrl ?>datatable/albo-pretorio" title="Gestione">Gestione</a></li>
                                <li><a href="<?php echo $this->baseUrl ?>datatable/atti-ufficiali" title="">Atti ufficiali</a></li>
                                <li class="dropdown-submenu">
                                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" title="Sezioni albo pretorio">Sezioni</a>
                                    <ul class="dropdown-menu">
                                        <li><a href="<?php echo $this->baseUrl ?>formdata/albo-pretorio-sezioni" title="Nuova sezione albo">Nuova</a></li>
                                        <li><a href="<?php echo $this->baseUrl ?>datatable/albo-pretorio-sezioni" title="Gestione sezioni albo">Modifica \ Elimina</a></li>
                                    </ul>
                                </li>
                            </ul>
                        </li>
                        
                        <li class="dropdown-submenu">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown" title="Stato civile">Stato civile</a>
                            <ul class="dropdown-menu">
                                <li><a href="<?php echo $this->baseUrl ?>formdata/stato-civile" title="">Nuovo atto</a></li>
                                <li><a href="<?php echo $this->baseUrl ?>datatable/stato-civile" title="">Gestione</a></li>
                                <li class="dropdown-submenu">
                                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" title="">Sezioni</a>
                                    <ul class="dropdown-menu">
                                        <li><a href="<?php echo $this->baseUrl ?>formdata/stato-civile-sezioni" title="Nuova sezione stato civile">Nuova</a></li>
                                        <li><a href="<?php echo $this->baseUrl ?>datatable/stato-civile-sezioni" title="">Modifica \ Elimina</a></li>
                                    </ul>
                                </li>
                            </ul>
                        </li>
                        
                        <li class="dropdown-submenu">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown">Amministrazione trasparente</a>
                            <ul class="dropdown-menu">
                                <li><a href="<?php echo $this->baseUrl ?>formdata/amministrazione-trasparente" title="">Nuovo articolo</a></li>
                                <li><a href="<?php echo $this->baseUrl ?>datatable/amministrazione-trasparente" title="">Modifica \ Elimina</a></li>
                                <li class="dropdown-submenu">
                                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" title="">Macro-link</a>
                                    <ul class="dropdown-menu">
                                        <li><a href="#" title="Nuova">Nuova</a></li>
                                        <li><a href="#" title="Modifica \ Elimina">Modifica \ Elimina</a></li>
                                    </ul>
                                </li>
                                <li class="dropdown-submenu">
                                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" title="">Sotto-link</a>
                                    <ul class="dropdown-menu">
                                        <li><a href="#" title="Nuovo">Nuovo</a></li>
                                        <li><a href="#" title="Modifica \ Elimina">Modifica \ Elimina</a></li>
                                    </ul>
                                </li>
                            </ul>
                        </li>
                        
                        <li class="dropdown-submenu">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown" title="">Atti di concessione</a>
                            <ul class="dropdown-menu">
                                <li><a href="<?php echo $this->baseUrl ?>formdata/atti-concessione" title="">Nuovo atto</a></li>
                                <li><a href="<?php echo $this->baseUrl ?>datatable/atti-concessione" title="">Gestione</a></li>
                                <li class="dropdown-submenu">
                                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" title="">Settore</a>
                                    <ul class="dropdown-menu">
                                        <li><a href="<?php echo $this->baseUrl ?>formdata/contratti-pubblici-settori" title="">Nuovo</a></li>
                                        <li><a href="<?php echo $this->baseUrl ?>datatable/contratti-pubblici-settori" title="Gestione settori atti di concessione">Gestione</a></li>
                                    </ul>
                                </li>
                                <li class="dropdown-submenu">
                                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" title="Responsabili procedimento">Responsabili procedimento</a>
                                    <ul class="dropdown-menu">
                                        <li><a href="<?php echo $this->baseUrl ?>formdata/contratti-pubblici-responsabili" title="Nuovo responsabile procedimento">Nuovo</a></li>
                                        <li><a href="<?php echo $this->baseUrl ?>datatable/contratti-pubblici-responsabili" title="Gestione responsabile procedimento">Gestione</a></li>
                                    </ul>
                                </li>
                            </ul>
                        </li>
                        
                        <li class="dropdown-submenu">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown" title="">Contratti pubblici</a>
                            <ul class="dropdown-menu">
                                <li><a href="<?php echo $this->baseUrl ?>formdata/contratti-pubblici" title="Nuovo bando contratti pubblici">Nuovo bando</a></li>
                                <li><a href="<?php echo $this->baseUrl ?>datatable/contratti-pubblici" title="Gestione contratti pubblici">Gestione</a></li>
                                <li class="dropdown-submenu">
                                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" title="">Settori</a>
                                    <ul class="dropdown-menu">
                                        <li><a href="<?php echo $this->baseUrl ?>formdata/contratti-pubblici-settori" title="">Nuovo</a></li>
                                        <li><a href="<?php echo $this->baseUrl ?>datatable/contratti-pubblici-settori" title="">Modifica \ Elimina</a></li>
                                    </ul>
                                </li>
                                <li class="dropdown-submenu">
                                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" title="Responsabile procedimento">Responsabile procedimento</a>
                                    <ul class="dropdown-menu">
                                        <li><a href="#" title="Nuovo responsabile procedimento contratti pubblici">Nuovo</a></li>
                                        <li><a href="#" title="Gestione responsabili procedimento contratti pubblici">Gestione</a></li>
                                    </ul>
                                </li>
                                <li class="dropdown-submenu">
                                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" title="Voci Scelta del Contraente">Voci Scelta del Contraente</a>
                                    <ul class="dropdown-menu">
                                        <li><a href="<?php echo $this->baseUrl ?>formdata/contratti-pubblici-scelta-contraente" title="">Nuovo</a></li>
                                        <li><a href="<?php echo $this->baseUrl ?>datatable/contratti-pubblici-scelta-contraente" title="">Gestione</a></li>
                                    </ul>
                                </li>
                                <li class="dropdown-submenu">
                                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" title="">Operatori</a>
                                    <ul class="dropdown-menu">
                                        <li><a href="<?php echo $this->baseUrl ?>formdata/contratti-pubblici-operatore" title="Nuovo operatore">Nuovo</a></li>
                                        <li><a href="<?php echo $this->baseUrl ?>datatable/contratti-pubblici-operatore" title="Gestione operatori">Gestione</a></li>
                                    </ul>
                                </li>
                            </ul>
                        </li>
                        
                        <li class="dropdown-submenu">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown" title="Rubrica enti terzi">Enti terzi</a>
                            <ul class="dropdown-menu">
                                 <li><a href="<?php echo $this->baseUrl ?>formdata/enti-terzi" title="Nuovo ente terzo">Nuovo indirizzo</a></li>
                                <li><a href="<?php echo $this->baseUrl ?>datatable/enti-terzi" title="Gestione rubrica enti terzi">Gestione</a></li>
                            </ul>
                        </li>
                        
                        <li><a href="<?php echo $this->baseUrl ?>datatable/contacts" title="Contatti">Contatti</a></li>   
                        
                        <li class="dropdown-submenu">
                            <a href="<?php echo $this->baseUrl ?>datatable/posts/foto" class="dropdown-toggle" data-toggle="dropdown">Foto</a>
                            <ul class="dropdown-menu">
                                <li><a href="<?php echo $this->baseUrl ?>formdata/photo" title="Aggiungi nuova foto">Nuova</a></li>
                                <li><a href="<?php echo $this->baseUrl ?>datatable/photo" title="Gestione gallerie fotografice">Gestione</a></li>
                                <li class="dropdown-submenu">
                                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" title="">Categorie</a>
                                    <ul class="dropdown-menu">
                                        <li><a href="<?php echo $this->baseUrl ?>formdata/categories/?moduleId=6" title="">Nuovo</a></li>
                                        <li><a href="<?php echo $this->baseUrl ?>datatable/categories/?moduleId=6" title="">Modifica \ Elimina</a></li>
                                    </ul>
                                </li>
                            </ul>
                        </li>
                        <li><a href="#" title="">Forum</a></li>
                        <li><a href="#" title="">Newsletter</a></li>
                        
                        <li><a href="#" title="Booking">Booking</a></li>
                        <li class="dropdown-submenu">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown">E-commerce</a>
                            <ul class="dropdown-menu">
                                <li class="dropdown-submenu">
                                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" title="">Prodotti</a>
                                    <ul class="dropdown-menu">
                                        <li><a href="#" title="">Nuovo</a></li>
                                        <li><a href="#" title="">Modifica \ Elimina</a></li>
                                    </ul>
                                </li>
                                <li class="dropdown-submenu">
                                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" title="">Categorie</a>
                                    <ul class="dropdown-menu">
                                        <li><a href="#" title="">Nuovo</a></li>
                                        <li><a href="#" title="">Modifica \ Elimina</a></li>
                                    </ul>
                                </li>
                                <li><a href="#" title="">Ordini</a></li>
                                <li><a href="#" title="">Marchi</a></li>
                            </ul>
                        </li>
                        
                        <li class="dropdown-submenu">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown">Utenti</a>
                            <ul class="dropdown-menu">
                                <li><a href="<?php echo $this->baseUrl ?>formdata/users" title="">Nuovo</a></li>
                                <li><a href="<?php echo $this->baseUrl ?>datatable/users" title="">Modifica \ elimina</a></li>
                                <li class="divider"></li>
                                <li><a href="<?php echo $this->baseUrl ?>datatable/usersRoles" title="">Ruoli</a></li>
                            </ul>
                        </li>
                        <!--
                        <li><a href="#" title="F.A.Q">F.A.Q</a></li>
                        <li><a href="#" title="">Video</a></li>
                        <li><a href="#" title="">Annunci</a></li>
                        <li><a href="#" title="">Aste</a></li>
                        <li><a href="#" title="">Takeaway</a></li>
                        -->
                    </ul>
                </li>

                <li>
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">Blogs <b class="caret"></b></a>
                    
                    <ul class="dropdown-menu multi-level">
                        <li><a href="<?php echo $this->baseUrl ?>datatable/blog" title="">Tutti i posts</a></li>
                        <li class="dropdown-submenu">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown">Categorie</a>
                            <ul class="dropdown-menu">
                                <li><a href="<?php echo $this->baseUrl ?>formdata/categories/?moduleId=1" title="">Nuova</a></li>
                                <li><a href="<?php echo $this->baseUrl ?>datatable/categories/?moduleId=1" title="">Modifica \ Elimina</a></li>   
                            </ul>
                        </li>
                    </ul>
                </li>
                <li>
                    <a href="#" title="Opzioni"><i class="fa fa-wrench"></i> Opzioni</a>
                </li>

                <li>
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">Assistenza <b class="caret"></b></a>
                    
                    <ul class="dropdown-menu multi-level">
                        <li><a href="<?php echo $this->baseUrl ?>formdata/tickets" title="">Nuova richiesta</a></li>
                        <li><a href="<?php echo $this->baseUrl ?>datatable/tickets" title="">Elenco richieste</a></li>
                    </ul>
                </li>
                
            </ul>

            <ul class="nav navbar-nav navbar-right">
                <li class="dropdown">
                    <a href="javascript:void(0)" class="dropdown-toggle" data-toggle="dropdown"><i class="fa fa-user"></i> <?php echo $this->userDetails->name." ".$this->userDetails->surname ?><strong class="caret"></strong></a>
                    <ul class="dropdown-menu">
                        <li>
                            <a href="<?php echo $this->baseUrl ?>formdata/users/<?php echo $this->userDetails->id ?>" title="Profilo">Profilo</a>
                        </li>
                        <!--
                        <li>
                            <a href="javascript:void(0)" title="Documentazione">Documentazione</a>
                        </li>
                        <li>
                            <a href="javascript:void(0)" title="Application Program Interface">API</a>
                        </li>
                        <li>
                            <a href="javascript:void(0)" title="Backup Database">Backup Database</a>
                        </li>
                        -->
                        <li class="divider"></li>
                        <li>
                            <a href="<?php echo $this->url('login/process', array('action' => 'logout')); ?>" title="Uscita dall'area riservata"><i class="fa fa-power-off"></i> Uscita</a>
                        </li>
                    </ul>
                </li>
            </ul>
            </div>
            </nav>
        <div class="row clearfix">
            
            <?php
            // Sidebar
            // echo $this->partial('backend/templates/'.$this->template_backend.'sidebar/sidebar_entilocali.phtml');
            ?>
            
            <div class="col-md-12 column">
                <?php
                // Main Template
                echo $this->partial($this->templatePartial);
                ?>
            </div>
        </div>
        <div class="row clearfix">
            <div class="col-md-12 column">
                <p class="text-muted">&copy; <?php echo date("Y"); ?> <?php echo $this->sitename ?></p>
            </div>
        </div>
        </div>
    </div>
</div>

<script src="<?php echo $this->basePath() ?>/public/common/bootstrap3/js/bootstrap.min.js"></script>
<script src="<?php echo $this->basePath() ?>/public/common/bootstrap3/js/bootstrap-hover-dropdown.js"></script>
<script src="<?php echo $this->basePath() ?>/public/common/jquery/datatable/js/jquery.dataTables_it.min.js"></script>
<script src="<?php echo $this->basePath() ?>/public/common/jquery/datetimepicker/jquery.datetimepicker.js"></script>
    
<script>
//<![CDATA[

function showLoading()
{
    $("#formDataResponse").hide();
    $("#formDataLoading").show();
}

function showResponse()
{
    $("#formDataResponse").show();
    $("#formDataLoading").hide();
}

$(document).ready(function () {
    
    /* Datatable */
    $('#dataTable').dataTable( {
        "pagingType": "full_numbers"
    } );
    
    /* Validate and form post */
    var validate = $("#formData").validate({
        submitHandler: function(form) {
            $("#formData").ajaxSubmit({
                target: "#formDataResponse",
                type: "post",
                beforeSubmit: showLoading,
                success: showResponse,
                onkeyup: false
            });
        }
    });

    /* FadeOut FormData Div */
    setTimeout( function() {
        $("div.formDataResponse").fadeOut("slow", function () {
            $("div.formDataResponse").remove();
        });
    }, 2000);
    
    /* Bootstrap Tooltip */
    $('.btooltip').tooltip();
    
    $('.js-activated').dropdownHover().dropdown();
    
    jQuery('.datetimepicker').datetimepicker({
        format: 'Y-m-d H:i:s',
        lang: 'it'
    });

});
//]]>
</script>

<?php echo $this->inlineScript() ?>
</body>
</html>