<?php echo $this->doctype(); ?>
<html lang="it">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    <title><?php echo $this->sitename ?> - Area riservata</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <?php
    echo $this->headLink()
          ->prependStylesheet($this->basePath().'/public/common/bootstrap3/css/bootstrap.min.css')
          ->prependStylesheet('//netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.css')
          ->prependStylesheet('//cdn.datatables.net/1.10.0/css/jquery.dataTables.css');        
    ?>
    <style>
    .dropdown-submenu {
        position: relative;
    }

    .dropdown-submenu>.dropdown-menu {
        top: 0;
        left: 100%;
        margin-top: -6px;
        margin-left: -1px;
        -webkit-border-radius: 0 6px 6px 6px;
        -moz-border-radius: 0 6px 6px;
        border-radius: 0 6px 6px 6px;
    }

    .dropdown-submenu:hover>.dropdown-menu {
        display: block;
    }

    .dropdown-submenu>a:after {
        display: block;
        content: " ";
        float: right;
        width: 0;
        height: 0;
        border-color: transparent;
        border-style: solid;
        border-width: 5px 0 5px 5px;
        border-left-color: #ccc;
        margin-top: 5px;
        margin-right: -10px;
    }

    .dropdown-submenu:hover>a:after {
        border-left-color: #fff;
    }

    .dropdown-submenu.pull-left {
        float: none;
    }

    .dropdown-submenu.pull-left>.dropdown-menu {
        left: -100%;
        margin-left: 10px;
        -webkit-border-radius: 6px 0 6px 6px;
        -moz-border-radius: 6px 0 6px 6px;
        border-radius: 6px 0 6px 6px;
    }
    label.error {
        color: red;
        margin-left: 0.5%;
    }
    </style>
    
    <!-- HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
    <script src="<?php echo $this->basePath().'/public/common/js/html5shiv.js'; ?>"></script>
    <![endif]-->

    <!-- Fav and touch icons
    <link rel="apple-touch-icon-precomposed" sizes="144x144" href="img/apple-touch-icon-144-precomposed.png">
    <link rel="apple-touch-icon-precomposed" sizes="114x114" href="img/apple-touch-icon-114-precomposed.png">
    <link rel="apple-touch-icon-precomposed" sizes="72x72" href="img/apple-touch-icon-72-precomposed.png">
    <link rel="apple-touch-icon-precomposed" href="img/apple-touch-icon-57-precomposed.png">
    <link rel="shortcut icon" href="img/favicon.png"> -->
    
    <script src="<?php echo $this->basePath() ?>/public/common/jquery/jquery.min.js"></script>
    <script src="<?php echo $this->basePath() ?>/public/common/jquery/form/jquery.form.js"></script>
    <script src="<?php echo $this->basePath() ?>/public/common/jquery/validate/jquery.validate.min.js"></script>

    <script src="<?php echo $this->basePath() ?>/public/common/bootstrap3/js/bootstrap.min.js"></script>

    <script src="<?php echo $this->basePath() ?>/public/common/jquery/ckeditor/ckeditor.js"></script>
    <script src="<?php echo $this->basePath() ?>/public/common/jquery/ckfinder/ckfinder.js"></script>

    <script src="<?php echo $this->basePath() ?>/public/common/jquery/datatable/js/jquery.dataTables_it.min.js"></script>
</head>

<body>

<noscript>
    <div>
        <h3>Attenzione: Javascript disattivato</h3>
        <div>&Egrave; stato rilevato che Javascript risulta disattivato nel browser in uso. Abilitare il browser all'utilizzo di Javascript o la presente area risulter&agrave; inutilizzabile.</div>
    </div>
</noscript>

<div class="container">
    <div class="row clearfix">
        <div class="col-md-12 column">
            <nav class="navbar navbar-default" role="navigation">
                
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1"> <span class="sr-only">Toggle navigation</span><span class="icon-bar"></span><span class="icon-bar"></span><span class="icon-bar"></span></button> <a class="navbar-brand" href="<?php echo $this->url('admin', array('lang' => 'it')); ?>" title="<?php echo $this->sitename ?>"><?php echo $this->sitename ?></a>
                </div>

                <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                    <ul class="nav navbar-nav">
                        <li class="active">
                            <a href="<?php echo $this->url('admin', array('lang' => 'it')); ?>" title="Torna alla home page"><i class="fa fa-home"></i> Home</a>
                        </li>
                        <li><a href="<?php echo $this->basepath() ?>" target="_blank" title="Anteprima sito web"><i class="fa fa-eye"></i> Anteprima</a></li>
                    <li>
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">Moduli <b class="caret"></b></a>
                    <ul class="dropdown-menu multi-level">
                        <li class="dropdown-submenu">
                            <a href="<?php echo $this->baseUrl ?>datatable/posts/?tipo=content" class="dropdown-toggle" data-toggle="dropdown">Contenuti</a>
                            <ul class="dropdown-menu">
                                <li><a href="<?php echo $this->baseUrl ?>formdata/posts/" title="">Nuovo</a></li>
                                <li><a href="<?php echo $this->baseUrl ?>datatable/posts/?tipo=content" title="Modifica \ elimina contenuti">Modifica \ Elimina</a></li>
                                <li class="dropdown-submenu">
                                    <a href="<?php echo $this->baseUrl ?>datatable/categories/?moduleId=4" class="dropdown-toggle" data-toggle="dropdown" title="">Categorie</a>
                                    <ul class="dropdown-menu">
                                        <li><a href="<?php echo $this->baseUrl ?>formdata/categories/?moduleId=4" title="Nuova categoria contenuti">Nuova</a></li>
                                        <li><a href="<?php echo $this->baseUrl ?>datatable/categories/?moduloId=4" title="Modifica \ elimina categorie contenuti">Modifica \ Elimina</a></li>
                                    </ul>
                                </li>
                            </ul>
                        </li>
                        <li class="dropdown-submenu">
                            <a href="<?php echo $this->baseUrl ?>datatable/posts/?tipo=foto" class="dropdown-toggle" data-toggle="dropdown">Foto</a>
                            <ul class="dropdown-menu">
                                <li><a href="<?php echo $this->baseUrl ?>formdata/posts/?tipo=foto" title="">Nuova</a></li>
                                <li><a href="<?php echo $this->baseUrl ?>datatable/posts/?tipo=foto" title="">Modifica \ Elimina</a></li>
                                <li class="dropdown-submenu">
                                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" title="">Categorie</a>
                                    <ul class="dropdown-menu">
                                        <li><a href="<?php echo $this->baseUrl ?>formdata/categories/?moduloId=6" title="">Nuovo</a></li>
                                        <li><a href="<?php echo $this->baseUrl ?>datatable/categories/?moduloId=6" title="">Modifica \ Elimina</a></li>
                                    </ul>
                                </li>
                            </ul>
                        </li>
                        <li><a href="<?php echo $this->baseUrl ?>datatable/albo-pretorio" title="Albo pretorio">Albo pretorio</a></li>
                        <li><a href="<?php echo $this->baseUrl ?>datatable/amministrazione-trasparente" title="Amministrazione trasparente">Amministrazione trasparente</a></li>
                        <li><a href="<?php echo $this->baseUrl ?>datatable/stato-civile" title="Stato civile">Stato civile</a></li>
                        <li><a href="<?php echo $this->baseUrl ?>datatable/contacts" title="Contatti">Contatti</a></li>
                        <li><a href="#" title="Booking">Booking</a></li>
                        <li class="dropdown-submenu">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown">E-commerce</a>
                            <ul class="dropdown-menu">
                                <li class="dropdown-submenu">
                                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" title="">Prodotti</a>
                                    <ul class="dropdown-menu">
                                        <li><a href="#" title="">Nuovo</a></li>
                                        <li><a href="#" title="">Modifica \ Elimina</a></li>
                                    </ul>
                                    <li class="dropdown-submenu">
                                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" title="">Categorie</a>
                                        <ul class="dropdown-menu">
                                            <li><a href="#" title="">Nuovo</a></li>
                                            <li><a href="#" title="">Modifica \ Elimina</a></li>
                                        </ul>
                                    </li>
                                </li>
                                <li><a href="#" title="">Ordini</a></li>
                                <li><a href="#" title="">Marchi</a></li>
                            </ul>
                        </li>
                        
                        <li class="dropdown-submenu">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown">Utenti</a>
                            <ul class="dropdown-menu">
                                <li><a href="<?php echo $this->baseUrl ?>formdata/users" title="">Nuovo</a></li>
                                <li><a href="<?php echo $this->baseUrl ?>datatable/users" title="">Modifica \ elimina</a></li>
                                <li class="divider"></li>
                                <li><a href="<?php echo $this->baseUrl ?>datatable/usersRoles" title="">Ruoli</a></li>
                            </ul>
                        </li>
                        <!--
                        <li><a href="#" title="F.A.Q">F.A.Q</a></li>
                        <li><a href="#" title="">Video</a></li>
                        <li><a href="#" title="">Annunci</a></li>
                        <li><a href="#" title="">Aste</a></li>
                        <li><a href="#" title="">Takeaway</a></li>
                        -->
                    </ul>
                </li>
                    
                <li>
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">Blogs <b class="caret"></b></a>
                    
                    <ul class="dropdown-menu multi-level">
                        <li><a href="<?php echo $this->baseUrl ?>datatable/posts/?tipo=blog" title="">Tutti i posts</a></li>
                        <li class="dropdown-submenu">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown">Categorie</a>
                            <ul class="dropdown-menu">
                                <li><a href="<?php echo $this->baseUrl ?>formdata/categories/?moduloId=1" title="">Nuova</a></li>
                                <li><a href="<?php echo $this->baseUrl ?>datatable/categories/?moduloId=1" title="">Modifica \ Elimina</a></li>
                                
                            </ul>
                        </li>
                    </ul>
                </li>
                        <li>
                            <a href="#" title="Opzioni"><i class="fa fa-wrench"></i> Opzioni</a>
                        </li>

                        <li>
                            <a href="<?php echo $this->baseUrl ?>datatable/assistenza" title="Assistenza"><i class="fa fa-stethoscope"></i> Assistenza</a>
                        </li>
                    </ul>

                    <ul class="nav navbar-nav navbar-right">
                        <li class="dropdown">
                            <a href="javascript:void(0)" class="dropdown-toggle" data-toggle="dropdown"><i class="fa fa-user"></i> Utente<strong class="caret"></strong></a>
                            <ul class="dropdown-menu">
                                <li>
                                    <a href="javascript:void(0)" title="Profilo">Profilo</a>
                                </li>
                                <!--
                                <li>
                                    <a href="javascript:void(0)" title="Documentazione">Documentazione</a>
                                </li>
                                <li>
                                    <a href="javascript:void(0)" title="Application Program Interface">API</a>
                                </li>
                                <li>
                                    <a href="javascript:void(0)" title="Backup Database">Backup Database</a>
                                </li>
                                -->
                                <li class="divider"></li>
                                <li>
                                    <a href="<?php echo $this->url('login/process', array('action' => 'logout')); ?>" title="Uscita dall'area riservata"><i class="fa fa-power-off"></i> Uscita</a>
                                </li>
                            </ul>
                        </li>
                    </ul>
            </div>
            </nav>
        <div class="row clearfix">
            <!--
            <?php
            // Sidebar
            // echo $this->partial('backend/templates/'.$this->template_backend.'sidebar/sidebar_entilocali.phtml');
            ?>
            -->
            <div class="col-md-12 column">
                <?php
                // Main Template
                echo $this->partial($this->templatePartial);
                ?>
            </div>
        </div>
        <div class="row clearfix">
            <div class="col-md-12 column">
                <p class="text-muted">&copy; <?php echo date("Y"); ?> <?php echo $this->sitename ?></p>
            </div>
        </div>
        </div>
    </div>
</div>

<script>

function showLoading()
{
    $("#formDataResponse").hide();
    $("#formDataLoading").show();
}

function showResponse()
{
    $("#formDataResponse").show();
    $("#formDataLoading").hide();
}

$(document).ready(function () {

    // Datatable options
    $('#dataTable').dataTable( {
        "pagingType": "full_numbers"
    } );
 
    // Validate and form post
    var validate = $("#formData").validate({
        submitHandler: function(form) {
            $("#formData").ajaxSubmit({
                target: "#formDataResponse",
                type: "post",
                beforeSubmit: showLoading,
                success: showResponse,
                onkeyup: false
            });
        }
    });

    // FadeOut FormData Div
    setTimeout( function() {
        $("div.formDataResponse").fadeOut("slow", function () {
            $("div.formDataResponse").remove();
        });
    }, 2000);
    
    // Bootstrap Tooltip
    $('.btooltip').tooltip();
});
</script>

<?php echo $this->inlineScript() ?>
</body>
</html>