<?php echo $this->doctype(); ?>
<html lang="it">
	<head>
	<meta charset="utf-8">
	<?php echo $this->headTitle($this->translate($this->templateData['sitename']))->setSeparator(' - ')->setAutoEscape(false) ?>

	<meta name="viewport" content="width=device-width, initial-scale=1.0">

	<?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/favicon.ico'))
		 ->prependStylesheet($this->basePath().'/public/common/bootstrap3/css/bootstrap.min.css')
	?>
	<style>
	body {
		padding-top: 40px;
		padding-bottom: 40px;
		background-color: #eee;
	}
	.form-signin {
		max-width: 330px;
		padding: 15px;
		margin: 0 auto;
	}
	.form-signin .form-signin-heading,
	.form-signin .checkbox {
		margin-bottom: 10px;
	}
	.form-signin .checkbox {
		font-weight: normal;
	}
	.form-signin .form-control {
		 position: relative;
		 font-size: 16px;
		 height: auto;
		 padding: 10px;
		 -webkit-box-sizing: border-box;
			-moz-box-sizing: border-box;
				 box-sizing: border-box;
	}
	.form-signin .form-control:focus {
		z-index: 2;
	}
	.form-signin input[type="text"] {
		margin-bottom: -1px;
		border-bottom-left-radius: 0;
		border-bottom-right-radius: 0;
	}
	.form-signin input[type="password"] {
		margin-bottom: 10px;
		border-top-left-radius: 0;
		border-top-right-radius: 0;
	}
	</style>
	<!-- Scripts -->

	<!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
	<!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
	<!--[if lt IE 9]>
		<script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
		<script src="https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"></script>
	<![endif]-->
	</head>

<body>

<noscript>
    <div>
        <h3>Attenzione: Javascript disattivato</h3>
        <div>&Egrave; stato rilevato che Javascript risulta disattivato nel browser in uso. Abilitare il browser all'utilizzo di Javascript o la presente area risulter&agrave; inutilizzabile.</div>
    </div>
</noscript>

<div class="container">

<form class="form-signin" action="" method="post" id="frmlogin" role="form">
    <div>
    <h2 class="form-signin-heading">Area Riservata</h2>
    <input type="text" name="username" id="username" class="form-control" placeholder="Email o nome utente" required autofocus>

    <div>&nbsp;</div>
    
    <input type="password" name="password" class="form-control" placeholder="Password" required>
    
    <label class="checkbox">
            <input type="checkbox" value="remember-me" title="Ricordami"> Ricordami su questo computer
    </label>

    <button class="btn btn-lg btn-primary btn-block" type="submit" title="Accedi all'area riservata">Accedi</button>

    <p>&nbsp;</p>

    <p><a href="javascript:void(0)" title="Recupero password" onclick="$('#recoverPasswordContainer').show(); $('#frmLogin').hide()"><span class="glyphicon glyphicon-arrow-right"></span> Recupero password</a></p>

    <p><a href="<?php echo $this->basePath() ?>" title="Torna al sito web"><span class="glyphicon glyphicon-arrow-right"></span> Torna al sito web</a></p>
    </div>
</form>

</div>

<?php echo $this->inlineScript() ?>
</body>
</html>