<?php echo $this->doctype(); ?>
<html lang="<?php echo $this->templateData['languageAbbreviation'] ?>">
	<head>
	<meta charset="utf-8">
	<?php echo $this->headTitle($this->translate($this->templateData['sitename']))->setSeparator(' - ')->setAutoEscape(false) ?>

	<?php echo $this->headMeta()
		->appendName('viewport', 'width=device-width, initial-scale=1.0')
		->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
	?>

	<?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/favicon.ico'))
		 ->prependStylesheet($this->basePath().'/common/bootstrap3/css/bootstrap.min.css')
	?>
	<style>
	body {
		padding-top: 40px;
		padding-bottom: 40px;
		background-color: #eee;
	}
	.form-signin {
		max-width: 330px;
		padding: 15px;
		margin: 0 auto;
	}
	.form-signin .form-signin-heading,
	.form-signin .checkbox {
		margin-bottom: 10px;
	}
	.form-signin .checkbox {
		font-weight: normal;
	}
	.form-signin .form-control {
		 position: relative;
		 font-size: 16px;
		 height: auto;
		 padding: 10px;
		 -webkit-box-sizing: border-box;
			-moz-box-sizing: border-box;
				 box-sizing: border-box;
	}
	.form-signin .form-control:focus {
		z-index: 2;
	}
	.form-signin input[type="text"] {
		margin-bottom: -1px;
		border-bottom-left-radius: 0;
		border-bottom-right-radius: 0;
	}
	.form-signin input[type="password"] {
		margin-bottom: 10px;
		border-top-left-radius: 0;
		border-top-right-radius: 0;
	}
	</style>
	<!-- Scripts -->

	<!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
	<!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
	<!--[if lt IE 9]>
		<script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
		<script src="https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"></script>
	<![endif]-->
	</head>

<body>

<noscript>
	<div>
		<h3><?php echo $this->templateData['languageLabels']['ADMIN_NOJAVSCRPT_TITLE']; ?></h3>
		<div><?php echo $this->templateData['languageLabels']['ADMIN_NOJAVSCRPT_DESCRIPTION'] ?></div>
	</div>
</noscript>

<div class="container">

<form class="form-signin" action="<?php echo $this->templateData['remotelinkWeb'].$this->templateData['loginActionBackend'] ?>" method="post" id="frmlogin" role="form">
	<div>
	<h2 class="form-signin-heading"><?php echo $this->templateData['languageLabels']['ADMIN_RESERVED_AREA']?></h2>
	<input type="text" name="username" id="username" class="form-control" placeholder="<?php echo $this->templateData['languageLabels']['ADMIN_EMAILUSERPLACEHOLDER']?>" required autofocus>
	<div>&nbsp;</div>
	<input type="password" name="password" class="form-control" placeholder="<?php echo $this->templateData['languageLabels']['ADMIN_PASSWORDPLACEHOLDER']?>" required>
	<label class="checkbox">
		<input type="checkbox" value="remember-me" title="<?php echo $this->templateData['languageLabels']['ADMIN_REMEMBERME']?>"> <?php echo $this->templateData['languageLabels']['ADMIN_REMEMBERME']?>
	</label>
	<?php if ($this->templateData['languageAvailables'] and count($this->templateData['languageAvailables']) > 1): ?>
	<!-- Language selection -->
	<label>
		<select name="adminLanguage" id="adminLanguage">
			<option value=""><?php echo $this->templateData['languageLabels']['ADMIN_LANGUAGE']?></option>
			<?php foreach($this->templateData['languageAvailables'] as $availableLanguages): ?>
			<option value="<?php echo $availableLanguages['abbreviation1'] ?>"><?php echo $availableLanguages['abbreviation3'] ?></option>
			<?php endforeach; ?>
		</select>
	</label>
	<?php endif; ?>
	<button class="btn btn-lg btn-primary btn-block" type="submit" title="<?php echo $this->templateData['languageLabels']['ADMIN_ACCESSBUTTONTITLE']?>"><?php echo $this->templateData['languageLabels']['ADMIN_ACCESSBUTTON']?></button>
	
	<p>&nbsp;</p>

	<p><a href="javascript:void(0)" title="<?php echo $this->templateData['languageLabels']['ADMIN_RECOVERPASSWORD']?>" onclick="$('#recoverPasswordContainer').show(); $('#frmLogin').hide()"><span class="glyphicon glyphicon-arrow-right"></span> <?php echo $this->templateData['languageLabels']['ADMIN_RECOVERPASSWORD']?></a></p>
	
	<p><a href="<?php echo $this->templateData['remotelinkWeb'] ?>" title="<?php echo $this->templateData['languageLabels']['ADMIN_BACK_TO_WEBSITE'] ?>"><span class="glyphicon glyphicon-arrow-right"></span> <?php echo $this->templateData['languageLabels']['ADMIN_BACK_TO_WEBSITE'] ?></a></p>
	
	</div>
</form>

</div>

<?php echo $this->inlineScript() ?>
</body>
</html>