<div class="alert alert-<?php if ($this->messageType) echo $this->messageType; else echo "info"; ?>" id="formdataresultmessage">
	<h4><?php echo $this->messageTitle ?></h4>
	<div><?php echo $this->messageText ?></div>
</div>

<!--
<div class="alert alert-success">...</div>
<div class="alert alert-info">...</div>
<div class="alert alert-warning">...</div>
<div class="alert alert-danger">...</div>
-->