<!doctype html>
<html>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    <style>
        h1, h2 { margin-bottom: 50px; text-align: center; }
        p { margin-bottom: 10px }
        .text-center { text-align: center }
    </style>

    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css">
    <body>

        <h1>CERTIFICATO DI PUBBLICAZIONE</h1>

        <p>Si attesta che l'atto avente oggetto: </p>

        <h2><?php echo utf8_encode($this->record['titolo']) ?></h2>

        <p><strong>Richiesto da:</strong> <?php echo $this->record['userName']." ".$this->record['userSurname'] ?></p>

        <p class="text-center">&Egrave; stato pubblicato sull'albo pretorio online del sito istituzionale di questo Ente con i seguenti dati:</p>

        <p><strong>Numero / anno.:</strong> <?php echo $this->record['numeroAtto'] ?> / <?php echo $this->record['anno'] ?></p>

        <p><strong>Pubblicato il:</strong> <?php echo $this->record['dataPubblicare']->format('d-m-Y H:i:s') ?></p>

        <p><strong>Scadenza:</strong> <?php echo $this->record['dataScadenza']->format('d-m-Y H:i:s') ?></p>

        <p><strong>Sezione:</strong> <?php echo $this->record['nomeSezione'] ?></p>

        <p><strong>Settore:</strong> <?php echo $this->record['nomeSettore'] ?></p>

        <?php if ( !empty($this->record['note']) ): ?>
            <p><strong>Note:</strong> <?php echo $this->record['note'] ?></p>
        <?php endif; ?>

    </body>
</html>