<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Migrazione\Module'                        => __DIR__ . '/Module.php',
    'Migrazione\Controller\MigrazioneController' => __DIR__ . '/src/Migrazione/Controller/MigrazioneController.php',
);
