<?php
// Generated by ZF2's ./bin/templatemap_generator.php
return array(
    'migrazione/migrazione/foo'   => __DIR__ . '/view/migrazione/migrazione/foo.phtml',
    'migrazione/migrazione/index' => __DIR__ . '/view/migrazione/migrazione/index.phtml',
);
