<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Config\Module'                        => __DIR__ . '/Module.php',
    'Config\Controller\IndexController' => __DIR__ . '/src/Config/Controller/IndexController.php',
    'ConfigTest\Framework\TestCase'        => __DIR__ . '/tests/Config/Framework/TestCase.php',
    'ConfigTest\SampleTest'                => __DIR__ . '/tests/Config/SampleTest.php',
);
