<ul class="breadcrumb">
    <li><a href="<?php echo $this->url('admin', array('lang'=>'it')); ?>" title="Home page">Home</a> <span class="divider"></span></li>
    <li><a href="<?php echo $this->url('admin/formdata', array('lang' => 'it', 'formsetter' => 'sezioni-contenuti')); ?>" title="Sezioni">Sezioni</a> <span class="divider"></span></li>
    <li class="active">Posizioni</li>
</ul>

<h3>Gestione posizioni</h3>
<?php echo $this->url('admin/posizioni-sezioni-update', array('lang'=>'it')); ?>
<p>In questa sezione vengono visualizzate le sezioni <strong>visibili sul sito web</strong>.</p>

<p>Trascinare i nomi delle sezioni disponendoli secondo l'ordine desiderato. L'aggiornamento sar&agrave; automatico ed il risultato sar&agrave; visualizzato in questa pagina.</p>


<div id="info"></div>

<div class="row">

    <div class="col-md-6">
        <h4>Colonna sinistra</h4>
        <?php if (!empty($this->records['sx'])): ?>
            <ul class="sezioniColumn" style="margin-left: 0; padding: 0">
                <?php foreach($this->records['sx'] as $sezioniColonna): ?>
                    <li class="positionMove list-group-item list-group-item-info" id="oggettoItem_<?php echo $sezioniColonna['id'] ?>">
                        <span class="trascinabile"><?php echo $sezioniColonna['nome']; ?></span>
                    </li>
                <?php endforeach ?>
            </ul>
        <?php endif; ?>
    </div>

    <div class="col-md-6">
        <h4>Colonna destra</h4>
        <?php if (!empty($this->records['dx'])): ?>
            <ul class="sezioniColumn" style="margin-left: 0; padding: 0">
                <?php foreach($this->records['dx'] as $sezioniColonna): ?>
                    <li class="positionMove list-group-item list-group-item-warning" id="oggettoItem_<?php echo $sezioniColonna['id'] ?>">
                        <span class="trascinabile"><?php echo $sezioniColonna['nome']; ?></span>
                    </li>
                <?php endforeach ?>
            </ul>
        <?php endif; ?>

    </div>
</div>


<script type="text/javascript" src="http://code.jquery.com/ui/1.9.2/jquery-ui.js"></script>
<script type="text/javascript">
$(document).ready(function() {
    $(".sezioniColumn").sortable({
        handle : '.trascinabile',
        update : function () {
            var ordina = $('.sezioniColumn').sortable('serialize');
            $("#info").load("<?php echo $this->url('admin/posizioni-sezioni-update', array('lang'=>'it')); ?>?"+ordina+'&group='+$('#1').attr('id') );
        }
    });
});
</script>
