<ul class="breadcrumb">
    <li><a href="<?php echo $this->basepath() ?>/admin/main/" title="Home page">Home</a> <span class="divider"></span></li>
    <li class="active">Dashboard</li>
</ul>

<h1><?php echo $this->sitename ?> - area di amministrazione</h1>

<div class="alert alert-warning">
    <p><i class="fa fa-exclamation-triangle"></i> <strong>Area in costruzione:</strong> l'applicazione risulta in fase di sviluppo. Stiamo lavorando per pubblicare periodicamente nuovi aggiornamenti</p>
</div>

<div>
    <a href="<?php echo $this->url('admin/datatable', array('lang' => 'it', 'tablesetter'  => 'contacts')); ?>"><i class="fa fa-envelope-o"></i> Messaggi ricevuti dal form contatti</a>
</div>

<!--
    Statistiche
    Motori di ricerca (Analytics)
    Sommario records contenuti presenti per ogni modulo (se attivo)
-->

<h2>Consigli per l'utilizzo di quest'area:</h2>

<div role="tabpanel">

    <ul class="nav nav-tabs" role="tablist">
        <li role="presentation" class="active"><a href="#home" aria-controls="home" role="tab" data-toggle="tab">Navigazione</a></li>
        <li role="presentation"><a href="#forms" aria-controls="profile" role="tab" data-toggle="tab">Forms e Contenuti</a></li>
        <li role="presentation"><a href="#tabs" aria-controls="profile" role="tab" data-toggle="tab">Tabelle dati</a></li>
    </ul>

    <div class="tab-content">
        <div role="tabpanel" class="tab-pane active" id="home">
            <h2>Browsers</h2>
            Utilizzare un browser moderno per la visualizzazione di quest'area. La stessa &egrave; testata con:
            <ul>
                <li>Google Chrome</li>
                <li>Mozilla Firefox</li>
                <li>Opera</li>
                <li>Safari</li>
                <li>Internet Explorer 10+</li>
            </ul>

            <h2>Javascript</h2>
            <p>Per l'utilizzo dell'area, occorre attivare il supporto Javascript normalmente attivo in tutti i browsers. Nel caso fosse disattivato, un messaggio comparir&agrave; per ricordare di riattivarlo.</p>

            <h2>Links</h2>
            <p>Utilizzare i link dell'applicazione e non i pulsanti indietro \ avanti del browser poich&egrave; potrebbero confondere la navigazione o danneggiare i dati</p>
        </div>

        <div role="tabpanel" class="tab-pane" id="forms">
            <h2>Titoli e testi</h2>
            <ul>
                <li><strong>Inserire contenuti e titoli brevi e concisi</strong> in modo da essere facilmente leggibili, consultabili e aggiornabili in un secondo momento</li>
                <li><strong>Evitare i copia \ incolla da file word</strong> o altri tipi di file non testuali poich&egrave; potrebbero introdurre parti di codice che "sporcano" o danneggiano la presentazione visuale della pagina</li>
            </ul>
        </div>

        <div role="tabpanel" class="tab-pane" id="tabs">
            <h2>Tabelle dati</h2>
            <ul>
                <li>Le tabelle con elenchi dati hanno dei <strong>pulsanti</strong> per determinate azioni. &Egrave; possibile leggere la descrizione del pulsante posizionando il mouse sopra di esso</li>
                <li>Gli elenchi hanno in fondo numeri di pagina e una barra per scorrere eventualmente i dati da sinistra a destra</li>
            </ul>
        </div>

    </div>

</div>
