<ul class="breadcrumbs">
    <li><a href="<?php echo $this->basepath() ?>/" title="Torna alla home page">Home</a> <span class="divider"></span></li>
    <li class="current">Foto</li>
</ul>

<div>
    <h3>Galleria fotografica</h3>

    <p>Anteprima della galleria fotografica, sezione attualmente in costruzion.</p>

    <div class="large-12 columns">

        <div class="row">
            <?php for($i=0; $i<6; $i++): ?>
            <div class="large-4 small-6 columns">
                <img src="">
                <a class="th" role="button" aria-label="Thumbnail" href="#">
                    <img aria-hidden=true src="http://placehold.it/400x400&amp;text=Immagine" alt="Thumbnail">
                </a>
                <div class="panel">
                    <h5>Titolo foto</h5>
                    <h6 class="subheader">Mini descrizione foto qui...</h6>
                </div>
            </div>
            <?php endfor; ?>
        </div>
        <!--
        <div class="row">
            <div class="large-12 columns">
                <div class="panel">
                    <div class="row">
                        <div class="large-2 small-6 columns"><img src="http://placehold.it/300x300&amp;text=Site%20Owner"></div>
                        <div class="large-10 small-6 columns">
                            <strong>This Site Is Managed By</strong>
                            <hr>
                            Risus ligula, aliquam nec fermentum vitae, sollicitudin eget urna. Donec dignissim nibh fermentum
                            odio ornare sagittis
                        </div>
                    </div>
                </div>
            </div>
        </div>
        -->
    </div>
</div>
