<p class="aligncenter"><?php echo $templateData['languageLabels']['HOME_SUBTITLE_1'] ?></p>

<p class="aligncenter" style="padding-top: 2%"><strong><a class="iframexternal fancybox.iframe" href="https://maps.google.it/maps?q=Le+Cascine,+Via+delle+Cascine,+.,+50144+Firenze,+Toscana&amp;layer=c&amp;sll=43.783785,11.223199&amp;cbp=13,138.72,,0,1&amp;cbll=43.784027,11.222794&amp;hl=it&amp;gl=it&amp;ie=UTF8&amp;hq=Le+Cascine,+Via+delle+Cascine,+.,+50144+Firenze,+Toscana&amp;t=m&amp;panoid=GsdRTLa1oajN-ivSb75ErQ&amp;source=embed&amp;ll=43.781308,11.224315&amp;spn=0.004865,0.012059&amp;z=16&amp;output=svembed" title="<?php echo $templateData['languageLabels']['HOME_SUBTITLE_2'] ?>"><?php echo $templateData['languageLabels']['HOME_SUBTITLE_2'] ?></a></strong></p>

<p class="aligncenter" style="padding-top: 2%"><?php echo $templateData['languageLabels']['HOME_SUBTITLE_3'] ?></p>

<div style="width: 85%; margin: 0 auto">
	<a href="<?php echo $templateData['activities']['linkDetails'] ?>" title="<?php echo $templateData['activities']['title'] ?>"><img src="<?php echo $this->basePath() ?>/frontend/projects/fossobandito/templates/default/assets/images/fosso-bandito-home.jpg" alt="<?php echo $templateData['sitename'] ?>" title="<?php echo $templateData['sitename'] ?>"></a>
</div>

<div><?php echo $templateData['languageLabels']['HOME_PARAGRAPH_1'] ?></div>

<!-- Past -->
<div class="one-third column ">
	<div class="column-service-wrapper">
	<div class="column-service-title-wrapper">
	 
		<div class="column-service-image"><img src="<?php echo $this->basePath() ?>/frontend/projects/fossobandito/templates/default/assets/images/icona-passato.jpg" alt="<?php echo $templateData['languageLabels']['PAST'] ?>" title="<?php echo $templateData['languageLabels']['PAST'] ?>"></div>
		
		<h2 class="column-service-title gdl-title"><?php echo $templateData['languageLabels']['PAST'] ?></h2>
		
		<div class="clear"></div>
		
	</div>
	
	<ul class="colorgreen">
		<li><a href="<?php echo $templateData['remotelinkWeb'].$templateData['languageAbbreviation'] ?>/Timeline/" class="iframexternal underline" title="<?php echo $templateData['languageLabels']['STORIA'] ?>"><?php echo $templateData['languageLabels']['STORIA'] ?></a></li>
		
		<li><a class="underline gallery_degrado" href="javascript:void(0);" title="<?php echo $templateData['languageLabels']['DEGRADO']?>"><?php echo $templateData['languageLabels']['DEGRADO']?></a></li>
		
		<li><a href="<?php echo $templateData['repetti']['linkDetails'] ?>" class="underline" title="<?php echo $templateData['repetti']['title'] ?>"><?php echo $templateData['repetti']['title'] ?></a></li>
	</ul>

</div>
</div>

<!-- Present -->
<div class="one-third column">
	<div class="column-service-wrapper">
	
	<div class="column-service-title-wrapper">
		
		<div class="column-service-image"><img src="<?php echo $this->basePath() ?>/frontend/projects/fossobandito/templates/default/assets/images/icona-presente.jpg" alt="<?php echo $templateData['languageLabels']['PRESENT'] ?>" title="<?php echo $templateData['languageLabels']['PRESENT'] ?>"></div>

		<h2 class="column-service-title gdl-title"><?php echo $templateData['languageLabels']['PRESENT'] ?></h2>
				
		<div style="padding-top: 4%"><?php echo $templateData['languageLabels']['PRESENT_HOME_PARAGRAPH'] ?></div>
				
		<div class="clear"></div>
		
	</div>
	
	<ul class="colorgreen">
		<li><a href="<?php echo $templateData['present']['linkDetails'] ?>" title="<?php echo $templateData['present']['title'] ?>" class="underline"><?php echo $templateData['present']['title'] ?> (<?php echo $templateData['languageLabels']['CONTINUE'] ?>...)</a></li>
		<li><a href="http://player.vimeo.com/video/70095637" class="iframexternal underline" title="<?php echo $templateData['languageLabels']['PRESENT_WORK_IN_PROGRESS'] ?>"><?php echo $templateData['languageLabels']['PRESENT_WORK_IN_PROGRESS'] ?></a></li>
		<!--
		<li><a href="" class="underline" title="">[foto montate progressive]</a></li>
		-->
	</ul>
	
	<div style="padding-top: 4%"><?php echo $templateData['languageLabels']['PIERATTELLI_STUDIO'] ?></div>
	
	</div>
</div>

<!-- Future -->
<div class="one-third column">

	<div class="column-service-wrapper">
		
		<div class="column-service-title-wrapper">
			
			<div class="column-service-image"><img src="<?php echo $this->basePath() ?>/frontend/projects/fossobandito/templates/default/assets/images/icona-futuro.jpg" alt="<?php echo $templateData['languageLabels']['FUTURE'] ?>" title="<?php echo $templateData['languageLabels']['FUTURE'] ?>"></div>
			<h2 class="column-service-title gdl-title"><?php echo $templateData['languageLabels']['FUTURE'] ?></h2>
			
			<p style="padding-top: 4%"><?php echo $templateData['languageLabels']['FUTURE_HOME_PARAGRAPH'] ?></p>
			
			<ul class="colorgreen">
			
				<li><a href="<?php echo $templateData['future']['linkDetails'] ?>" class="underline" title="<?php echo $templateData['future']['title'] ?>"><?php echo $templateData['future']['title'] ?>, (<?php echo $templateData['languageLabels']['CONTINUE'] ?>...)</a></li>
				
				<li><a href="<?=$templateData['activities']['linkDetails']?>" class="underline" title="<?=$templateData['activities']['title']?>"><?=$templateData['activities']['title']?></a></li>
				
				<li><a href="http://player.vimeo.com/video/69875407" class="iframexternal underline" title="<?php echo $templateData['languageLabels']['VIDEO'] ?>"><?php echo $templateData['languageLabels']['VIDEO'] ?></a></li>
				
			</ul>
		</div>
		
		<div class="clear"></div>
		
	</div>
</div>
