<style>
.imghomeicon {
	float: left;
	margin-right: 0.5%
}
</style>
<div style="width: 90%; margin: auto">

<a href="" title=""><img src="<?php echo $this->basePath() ?>/frontend/projects/fossobandito/templates/default/assets/images/ristorante-roll.jpg" alt="Ristorante" class="imghomeicon"></a>

<a href="" title="321"><img src="<?php echo $this->basePath() ?>/frontend/projects/fossobandito/templates/default/assets/images/321-roll.jpg" alt="321" class="imghomeicon"></a>

</div>
<div style="clear: both"></div>

<ul>
	<li><a href="" title="">Grigliata</a></li>
	<li><a href="" title="">Eventi</a></li>
	<li><a href="" title="">Parcheggio</a></li>
	<li><a href="" title="">Merchandise</a></li>
	<li><a href="" title="">Info</a></li>
</ul>