<aside class="sidebar-widget clearfix">
	<h3>Fosso Bandito</h3>
	<div class="menu-features-container">
		<ul id="menu-features" class="menu">
			<!-- Ristorante \ Pizzeria -->
			<li class="menu-item menu-item-type-post_type menu-item-object-page"><a href="<?php echo $this->templateData['preloadrecord']['ristorante']['linkDetails'] ?>" title=""><?php echo $this->templateData['preloadrecord']['ristorante']['title'] ?></a></li>
			<!-- 321 -->
			<li class="menu-item menu-item-type-post_type menu-item-object-page"><a href="<?php echo $this->templateData['preloadrecord']['321']['linkDetails'] ?>" title=""><?php echo $this->templateData['preloadrecord']['321']['title'] ?></a></li>
			<!-- Griglieria -->
			<li class="menu-item menu-item-type-post_type menu-item-object-page"><a href="<?php echo $this->templateData['preloadrecord']['griglieria']['linkDetails'] ?>" title=""><?php echo $this->templateData['preloadrecord']['griglieria']['title'] ?></a></li>
			<!-- Bar \ Gelateria -->
			<li class="menu-item menu-item-type-post_type menu-item-object-page"><a href="<?php echo $this->templateData['preloadrecord']['bar']['linkDetails'] ?>" title=""><?php echo $this->templateData['preloadrecord']['bar']['title'] ?></a></li>
			<!-- Sport -->
			<li class="menu-item menu-item-type-post_type menu-item-object-page"><a href="<?php echo $this->templateData['preloadrecord']['sport']['linkDetails'] ?>" title=""><?php echo $this->templateData['preloadrecord']['sport']['title'] ?></a></li>
			<!-- Noleggio -->
			<li class="menu-item menu-item-type-post_type menu-item-object-page"><a href="<?php echo $this->templateData['preloadrecord']['noleggio']['linkDetails'] ?>" title=""><?php echo $this->templateData['preloadrecord']['noleggio']['title'] ?></a></li>
			<!-- Parcheggio -->
			<li class="menu-item menu-item-type-post_type menu-item-object-page"><a href="<?php echo $this->templateData['preloadrecord']['parcheggio']['linkDetails'] ?>" title=""><?php echo $this->templateData['preloadrecord']['parcheggio']['title'] ?></a></li>
			<!-- Merchandising -->
			<li class="menu-item menu-item-type-post_type menu-item-object-page"><a href="<?php echo $this->templateData['preloadrecord']['merchandising']['linkDetails'] ?>" title=""><?php echo $this->templateData['preloadrecord']['merchandising']['title'] ?></a></li>
			<!-- Associazione \ Info -->
			<li class="menu-item menu-item-type-post_type menu-item-object-page"><a href="<?php echo $this->templateData['preloadrecord']['associazione']['linkDetails'] ?>" title=""><?php echo $this->templateData['preloadrecord']['associazione']['title'] ?></a></li>
		</ul>
	</div>
</aside>
