	
	<!-- PAST -->
	<div class="custom-sidebar gdl-divider">
		
		<div class="sidebar-title-wrapper"><h3 class="custom-sidebar-title sidebar-title-color gdl-title"><?php echo $templateData['languageLabels']['PAST'] ?></h3><div class="sidebar-title-wrapper-line gdl-divider"></div><div class="clear"></div></div>
		
		<ul class="xoxo blogroll">		
			<li><a href="<?php echo $templateData['remotelinkWeb'].$templateData['languageAbbreviation'] ?>/Timeline/" class="iframexternal" title="<?php echo $templateData['languageLabels']['STORIA'] ?>"><?php echo $templateData['languageLabels']['STORIA'] ?></a></li>				
			<li><a class="gallery_degrado" href="javascript:void(0);" title=""><?php echo $templateData['languageLabels']['DEGRADO']?></a></li>
			<li><a href="<?php echo $templateData['repetti']['linkDetails'] ?>" title="<?php echo $templateData['repetti']['title'] ?>"><?php echo $templateData['repetti']['title'] ?></a></li>
		</ul>
		
	</div>
	
	<!-- PRESENT -->
	<div class="custom-sidebar gdl-divider">
		
		<div class="sidebar-title-wrapper"><h3 class="custom-sidebar-title sidebar-title-color gdl-title"><?php echo $templateData['languageLabels']['PRESENT'] ?></h3><div class="sidebar-title-wrapper-line gdl-divider"></div>
		<div class="clear"></div>
		</div>
		
		<ul class="xoxo blogroll">
			<li><a href="<?php echo $templateData['present']['linkDetails'] ?>" title="<?php echo $templateData['present']['title'] ?>"><?php echo $templateData['present']['title'] ?></a></li>
			<li><a href="http://player.vimeo.com/video/70095637" class="iframexternal" title="<?php echo $templateData['languageLabels']['PRESENT_WORK_IN_PROGRESS'] ?>"><?php echo $templateData['languageLabels']['PRESENT_WORK_IN_PROGRESS'] ?></a></li>
		</ul>
			
	</div>
	
	<!-- FUTURE -->
	<div class="custom-sidebar gdl-divider">
		
		<div class="sidebar-title-wrapper"><h3 class="custom-sidebar-title sidebar-title-color gdl-title"><?php echo $templateData['languageLabels']['FUTURE'] ?></h3><div class="sidebar-title-wrapper-line gdl-divider"></div><div class="clear"></div></div>
		
		<ul class="xoxo blogroll">
			<li><a href="<?php echo $templateData['future']['linkDetails'] ?>" title="<?php echo $templateData['future']['title'] ?>"><?php echo $templateData['future']['title'] ?></a></li>
			<li><a href="<?php echo $templateData['activities']['linkDetails'] ?>" title="<?php echo $templateData['activities']['title'] ?>"><?php echo $templateData['activities']['title'] ?></a></li>
			<li><a href="http://player.vimeo.com/video/69875407" class="iframexternal" title="<?php echo $templateData['languageLabels']['VIDEO'] ?>"><?php echo $templateData['languageLabels']['VIDEO'] ?></a></li>
		</ul>
		
	</div>