<ul class="breadcrumbs">
    <li><a href="<?php echo $this->url('main', array()) ?>" title="Vai alla home page">Home</a></li>
    <li>
        <a href="<?php echo $this->url('autocertificazioni', array('current' => 'demografico')) ?>" title="Torna all'elenco autocertificazioni">
            Autocertificazioni
        </a>
    </li>
    <li><a href="<?php echo $this->url('autocertificazioni/demografico', array()); ?>" title="Vai all'elenco autocertificazioni gruppo demografico">Demografico</a></li>
    <li class="current">DICHIARAZIONE SOSTITUTIVA DELL’ATTO DI NOTORIET&Agrave;</li>
</ul>

<h3>DICHIARAZIONE SOSTITUTIVA DELL’ATTO DI NOTORIET&Agrave; (Art. 46 D.P.R. 445 del 28 dicembre 2000)</h3>

<p>In costruzione</p>
