<ul class="breadcrumbs">
    <li><a href="<?php echo $this->basepath() ?>" title="Torna alla home page">Home</a></li>
    <li class="current">Galleria fotografica</li>
</ul>

<div>

    <div class="large-12 columns">

        <div class="row">

            <?php if (!empty($this->records)): ?>
                <ul class="clearing-thumbs" data-clearing>
            <?php foreach($this->records as $record): ?>
                <li style="min-height: 15em">
                    <a href="<?php echo $this->publicDirRelativePath.'/'.$this->directoryBig.$record['image'] ?>" class="th" role="button" aria-label="Miniatura <?php echo $record['title'] ?>">
                        <img aria-hidden="true" src="<?php echo $this->publicDirRelativePath.'/'.$this->directoryThumb.$record['image'] ?>" alt="Miniatura <?php echo $record['title'] ?>">
                    </a>
                    <br>

                    <h5><?php echo $record['title'] ?></h5>

                    <h6 class="subheader">
                        <?php echo $this->TextShortener(strip_tags($record['description']), 3, 15, ''); ?>
                    </h6>

                </li>
            <?php endforeach; ?>
                </ul>
            <?php endif; ?>

        </div>

        <?php
        if (count($this->paginator) > 1):
            ?>
            <br>
            <?php
            echo $this->paginationControl(
                $this->paginator,
                'sliding',
                'application/pagination/foundation.phtml',
                array(
                    'route' => 'main/photo-gallery',
                    'lang' => 'it',
                )
            );
        endif;
        ?>

    </div>
</div>
