<?php

echo $this->render($this->formDataCommonPath.'breadcrumb.phtml');

if (!isset($this->formControlSpanWidth)): $this->formControlSpanWidth = 10; endif;
if (!isset($this->formLabelSpanWidth)): $this->formLabelSpanWidth = 2; endif;

?>
<h2>Gestione responsabili procedimento</h2>

<p>Elenco utenti responsabili procedimento</p>

<?php if (!empty($this->usersRespProc)): ?>
    <table class="table table-bordered">
        <tr>
            <th>Nome</th>
            <th>Settore</th>
            <th>&nbsp;</th>
        </tr>
        <?php foreach($this->usersRespProc as $respProc): ?>
        <tr>
            <td><?php echo $respProc['name'].' '.$respProc['surname'] ?></td>
            <td><?php echo $respProc['nomeSettore'] ?></td>
            <td>
                <a href="#deleteModal" data-action="#" data-id="<?php echo $respProc['id'] ?>" class="open-deleteModal btn btn-lg icon-red" title="Elimina dall'elenco responsabili procedimento">
                    <i class="fa fa-times"></i>
                </a>
            </td>
        </tr>
        <?php endforeach ?>
    </table>
<?php else: ?>
    <div class="alert alert-warning">
        <h3>Nessun responsabile di procedimento</h3>
        <div>Aggiungi un nuovo responsabile di procedimento selezionando un utente dall'elenco sottostante</div>
    </div>
<?php endif; ?>

<h3>Aggiungi utente</h3>

<p>Aggiungi un utente all'elenco responsabili procedimento.</p>

<!-- Form aggiungi agli utenti -->
<div>
    <?php

    $form = $this->form;
    $form->prepare();

    $formId = 'frmAddRespProc';
    $formAction = '';

    $form->setAttributes(array(
        'action'    => $formAction,
        'method'    => 'post',
        'enctype'   => 'multipart/form-data',
        'name'      => $formId,
        'id'        => $formId,
        'role'      => 'form',
        'class'     => 'form-horizontal'
    ));

    echo $this->partial($this->formDataCommonPath.'formdata_form_elements.phtml', array(
            'form'                  => $this->form,
            'formId'                => $formId,
            'formName'              => $formId,
            'formAction'            => $formAction,
            'formTitle'             => $this->formTitle,
            'formDescription'       => $this->formDescription,
        )
    );

    echo $this->form()->openTag($form);

    ?>
    <div class="form-group">
        <label for="sbmtButton" class="col-sm-2 control-label">&nbsp;</label>
        <div class="col-sm-10">
            <button type="submit" class="btn btn-primary" title="Aggiungi all'elenco responsabili procedimento">Aggiungi</button>
        </div>
    </div>
    <?php

    echo $this->form()->closeTag();

    ?>
</div>


<!-- Delete Modal -->
<div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="ConfirmDeleteModal" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content panel-danger">

            <div class="modal-header panel-heading">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                <h4 class="modal-title" id="deleteModalLabel"><strong>Conferma eliminazione?</strong></h4>
            </div>

            <form action="" method="post" id="frmDeleteModal">
                <div class="modal-body">
                    <p><strong>Attenzione:</strong> l'utente verr&agrave; eliminato dall'elenco dei responsabili di procedimento ma sar&agrave; possibile aggiungerlo nuovamente selezionandolo dall'elenco degli utenti sotto riportato.</p>

                    <input type="hidden" name="deleteId" id="deleteId" value="" />
                </div>

                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Annulla</button>
                    <button type="submit" class="btn btn-danger">Conferma</button>
                </div>
            </form>

        </div>
    </div>
</div>


<script>
    $(document).ready(function () {
        $(".open-deleteModal").click(function(e) {
            e.preventDefault();

            var _self = $(this);

            var dataId = _self.data('id');
            var dataAction = _self.data('action');

            $("#deleteId").val(dataId);
            $('#frmDeleteModal').attr('action', dataAction);

            $(_self.attr('href')).modal('show');
        });
    });
</script>