        <div class="row">
            <div class="medium-4 large-4 columns">
            <h2>Informazioni</h2>
            <ul>
                <li><a href="<?php echo $this->url('main', array('category' => 'info', 'title' => 'note-legali')) ?>" title="">Note Legali</a></li>
                <li><a href="<?php echo $this->url('main', array('category' => 'info', 'title' => 'accessibilita')) ?>" title="">Accessiblit&agrave;</a></li>
                <li><a href="<?php echo $this->url('main', array('category' => 'info', 'title' => 'continuita-operativa')) ?>" title="">Continuit&agrave; operativa</a></li>
                <li><a href="<?php echo $this->url('main', array('category' => 'info', 'title' => 'privacy')) ?>" title="">Privacy</a></li>
                <li><a href="<?php echo $this->url('main', array('category' => 'info', 'title' => 'credit')) ?>" title="">Credit</a></li>
                <li><a href="<?php echo $this->url('main', array('category' => 'info', 'title' => 'mobile')) ?>" title="Visualizzazione sito su tutti i dispositivi">Mobile</a></li>
            </ul>
            </div>

            <div class="medium-4 large-4 columns">
            <h2>Accessibilit&agrave;</h2>
            <ul>
                <li><a href="<?php echo $this->url('css', array('cssname' => 'text')) ?>" title="Passa alla visualizzazione solo testo">Sito testuale</a></li>
                <li><a href="#" title="Passa alla visualizzazione rosso su nero">Rosso su nero</a></li>
                <li><a href="#" title="Passa alla visualizzazione ad alta visibilit&agrave;">Alta visibilit&agrave;</a></li>
                <li><a href="#" title="Accesso da tastiera">Accesso da tastiera</a></li>
                <li><a href="#" title="Dichiarazione di accessibilit&agrave;">Dichiarazione di accessibilit&agrave;</a></li>
            </ul>
            </div>

            <div class="medium-4 large-4 columns">
            <h2>Comune di Telti</h2>
            <p>
                Via Kennedy 2, 07020 Telti<br>
                <strong>C.F:</strong> 00124140906<br>
                <strong>Codice Istat:</strong> 104024<br>
                <strong>Codice catastale:</strong> L088                
            </p>
            </div>

        </div>


        <footer>
            <div class="large-12 columns"><hr>
                <div>

                    <div class="large-6 columns">
                        <p>&copy; <?php echo date("Y") ?> <?php echo $this->sitename ?></p>
                    </div>

                    <div class="large-6 small-12 columns">
                        <ul class="inline-list right">
                            <li><a href="http://www.kronoweb.it" target="_blank" title="Kronoweb.it ITC">Kronoweb ITC</a></li>
                            <li><a href="http://validator.w3.org/check?uri=referer" title="Validate HTML" target="_blank">Valid HTML5</a></li>
                            <li><a href="http://jigsaw.w3.org/css-validator/check/referer" title="Validate CSS" target="_blank">Valid CSS</a></li>
                        </ul>
                    </div>

                </div>
            </div>
        </footer>
