<?php echo $this->doctype(); ?>

<html lang="it" class="no-js">
<head>
<meta charset="utf-8">
<?php echo $this->headTitle($this->sitename)->setSeparator(' - ')->setAutoEscape(false) ?>
<meta name="viewport" content="width=device-width, initial-scale=1.0" />
<meta name="description" content="<?php echo $this->description ?>">
<meta name="keywords" content="<?php echo $this->keywords ?>">

<?php if (!$this->cssName or $this->cssName == 'default'): ?>
<link href="<?php echo $this->basePath() ?>/public/common/foundation/css/foundation.min.css" media="screen" rel="stylesheet" type="text/css">
<?php elseif($this->cssName=='rosso-su-nero'): ?>
<link href="<?php echo $this->basePath() ?>/public/common/css/red_on_black.css" media="screen" rel="stylesheet" type="text/css">
<?php elseif($this->cssName=='high-visibility'): ?>
<link href="<?php echo $this->basePath() ?>/public/common/css/high_visibility.css" media="screen" rel="stylesheet" type="text/css">
<?php elseif($this->cssName=='text'): ?>

<?php endif; ?>

<link href="<?php echo $this->basePath() . '/public/frontend/projects/favicon.ico' ?>" rel="shortcut icon" type="image/vnd.microsoft.icon">
<script src="<?php echo $this->basePath() ?>/public/common/foundation/js/vendor/modernizr.js"></script>

<!--[if lt IE 9]>
<link rel="stylesheet" href="<?php echo $this->basePath() ?>/public/common/foundation/css/ie.css">
<![endif]-->

<!-- HTML5 shim, for IE6-8 support of HTML5 elements -->
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

<?php if (!$this->cssName or $this->cssName == 'default'): ?>
<style>
table { width: 100% }

.alert-box h2 { color: #fff }

.hidden {
    display: none;
}

.templateColumn h1 {
    font-size: 120%;
}

.fullWidth {
    width: 100%;
    margin-left: auto;
    margin-right: auto;
    max-width: initial;
}

.sezioniTitle {
    font-size: 120%;
}

.formElementUlList {
    list-style-type: none;
    padding: 0;
    margin-left: 0;
}

.formElementUlList li {
    color: #cc0000;
}
</style>
<?php endif; ?>

<script src="<?php echo $this->basePath() ?>/public/common/jquery/jquery.min.js"></script>

</head>

<body>

<?php if ($this->passwordPreviewArea): ?>
    <div class="alert-box info text-center" id="previewAreaAlert">
        Anteprima <strong><?php echo $this->sitename ?></strong>. Validazione HTML e CSS sono riferite al form di login di quest'area pertanto possono contenere errori.
        <strong>
            <a href="<?php echo $this->url('password-preview-logout', array('action' => 'logout')); ?>" title="Uscita area risevata">Uscita</a>
        </strong>
        <a href="#" class="close" onclick="$('#previewAreaAlert').hide();">&times;</a>
    </div>
<?php endif; ?>
