<?php if ($this->cssName!='default' and $this->cssName!=''): ?>
    <div>&raquo; <a href="<?php echo $this->url('css-style-switch', array('cssname' => 'default')) ?>" title="Torna alla visualizzazione del sito grafico">
            <?php echo $this->translate('Sito grafico'); ?>
        </a>
    </div>
<?php endif; ?>

<div class="large-12 columns">

    <div class="large-12 columns">
        
        <ul class="inline-list right">
            <li><a href="#mainContents" accesskey="x" class="button small"><?php echo $this->translate('Vai ai contenuti'); ?></a></li>
        </ul>
        
        <h1>
            <a href="<?php echo $this->url('main', array('lang' => $this->lang)) ?>" title="<?php echo $this->sitename ?>">
                <img src="<?php echo  $this->publicDirRelativePath ?>/frontend/projects/entilocali/templates/telti/assets/images/telti_logo.jpg" alt="">
            </a>
        </h1>
        
    </div>
</div>

<hr class="hidden">

<div class="large-12 columns">
    <nav class="top-bar" data-topbar role="navigation">
        <ul class="title-area">
            <li class="name">
                <h1><a href="<?php echo $this->basepath() ?>/" title="<?php echo $this->translate('Vai alla home page'); ?>" accesskey="h">Home</a></h1>
            </li>
        </ul>

        <section class="top-bar-section">
            <h2 class="hidden">Men&ugrave; navigazione</h2>
            <ul class="left">
                <li class="divider"></li>

                <li><a href="<?php echo $this->url('albo-pretorio') ?>" title="Consultazione elenco atti albo pretorio">Albo pretorio</a></li>
                <!--
                <li class="divider"></li>
                <li><a href="<?php echo $this->url('stato-civile') ?>" title="Pubblicazioni stato civile">Stato civile</a></li>
                <li class="divider"></li>
                <li><a href="<?php echo $this->url('contratti-pubblici') ?>" title="Elenco bandi di gara e contratti">Bandi e contratti</a></li>
                <li class="divider"></li>
                <li><a href="<?php echo $this->url('atti-concessione') ?>" title="Elenco atti di concessione">Atti di concessione</a></li>
                <li class="divider"></li>
                <li><a href="<?php echo $this->url('amministrazione-trasparente') ?>" title="Articoli amministrazione trasparente">Amministrazione trasparente</a></li>
                <li class="divider"></li>
                
                <li><a href="<?php echo $this->url('main', array('category' => 'comune-azienda', 'title' => 'dove-siamo')) ?>" title="Dove siamo">Dove siamo</a></li>
                <li class="divider"></li>
                <li><a href="<?php echo $this->url('contatti') ?>">Contatti</a></li>
                -->
            </ul>
            
            <ul class="right">
                <!-- <li><a href="#" title="Feed RSS di <?php echo $this->sitename ?>">RSS</a></li> -->
                <li class="has-form">
                    <div class="row collapse">
                        <div class="large-8 small-9 columns">
                            <input type="text" name="search" placeholder="<?php echo $this->translate('Cerca'); ?>...">
                        </div>
                        <div class="large-4 small-3 columns">
                            <a href="#" class="alert button expand" title="<?php echo $this->translate('Cerca sul sito'); ?>"><?php echo $this->translate('Cerca'); ?></a>
                        </div>
                    </div>
                </li>
                <!--
                    <li><a href="#" title="Registrati come nuovo utente">Registrati</a></li>
                    <li><a href="#" title="Iscrizione newsletter">Newsletter</a></li>
                -->

                <li class="has-dropdown">
                    <a href="javascript:void(0)" title="<?php echo $this->translate('Lingue disponibili'); ?>">
                        <?php echo $this->translate('Lingue'); ?>
                    </a>
                    <ul class="dropdown">
                        <li><a href="<?php echo $this->url('main', array('lang' => 'it')) ?>" title="Sito in lingua italiana">Italiano</a></li>
                        <li><a href="<?php echo $this->url('main', array('lang' => 'en')) ?>" title="Switch to English language">English</a></li>
                    </ul>
                </li>

            </ul>
            
        </section>
    </nav>
</div>
