<p class="text-right">
    <img src="<?php echo $this->publicDirRelativePath ?>/common/icons/export.gif" alt="Icona file esportazione"> Esporta:
    <a href="<?php echo (!empty($this->exportTxtUrl)) ? $this->exportTxtUrl : '#' ?>" title="Esporta in formato testo"><img src="<?php echo $this->publicDirRelativePath ?>/common/icons/txt.png" alt="Icona file di testo"></a>
    <a href="<?php echo (!empty($this->exportCsvUrl)) ? $this->exportCsvUrl : '#' ?>" title="Esporta in formato CSV"><img src="<?php echo $this->publicDirRelativePath ?>/common/icons/csv.gif" alt="Icona CSV"></a>
    <a href="<?php echo (!empty($this->exportPdfUrl)) ? $this->exportPdfUrl : '#' ?>" title="Esporta in formato PDF"><img src="<?php echo $this->publicDirRelativePath ?>/common/icons/pdf.gif" alt="Icona PDF"></a>
    <br>
    <br>

    <img src="<?php echo $this->publicDirRelativePath ?>/common/icons/share.gif" alt="Icona file condivisione" title="Icona file condivisione"> Condividi: <a href="https://www.facebook.com/sharer/sharer.php?u=<?php echo $this->currentUrl; ?>" title="Condividi su facebook" onclick="javascript:window.open(this.href, '', 'menubar=no,toolbar=no,resizable=yes,scrollbars=yes,height=300,width=600');return false;"><img src="<?php echo $this->publicDirRelativePath ?>/common/icons/facebook.gif" alt="Icona Facebook"></a>
    <a href="http://twitter.com/share?text=<?php echo $twitterShareText ?>&amp;url=<?php echo $this->currentUrl; ?>" title="Condividi su Twitter"><img src="<?php echo $this->publicDirRelativePath ?>/common/icons/twitter.gif" alt="Icona Twitter"></a>
    <a href="https://plus.google.com/share?url=<?php echo $this->currentUrl; ?>" title="Condividi su Google Plus"><img src="<?php echo $this->publicDirRelativePath ?>/common/icons/google-plus.png" alt="Icona Google Plus"></a>
</p>