<?php
echo $this->partial($this->templateDir.'_header');
    
echo $this->partial($this->templateDir.'_navigation');
?>
<div class="large-12 columns">

    <br>
        <hr class="hidden">

        <div class="large-12 columns">

                <div class="large-2 small-12 columns">
                    <aside>
                        <?php
                        if (!empty($this->sezioni['sx'])):
                            echo $this->partial($this->templateDir.'_column', array(
                                'sezioni' => $this->sezioni['sx']
                            ));
                        else:
                            ?>
                            <h1>Nessuna sezione</h1>
                            <?php
                        endif;
                        ?>
                    </aside>
                </div>


                <div class="large-8 small-12 columns">
                    <div id="mainContents"></div>
                    <?php
                    if (!empty($this->templatePartial)) {
                        echo $this->partial($this->templatePartial);
                    }
                    ?>
                </div>


                <div class="large-2 small-12 columns">

                    <aside>
                        <?php
                        if (!empty($this->sezioni['dx'])):
                            echo $this->partial($this->templateDir.'_column', array(
                                'sezioni' => $this->sezioni['dx']
                            ));
                        else:
                            ?>
                            <h1>Nessuna sezione</h1>
                            <?php
                        endif;
                        ?>
                    </aside>
                    
                </div>

        </div>

    <hr>

    <?php echo $this->partial($this->templateDir.'_footer'); ?>

</div>

<script src="<?php echo $this->basePath() ?>/public/common/jquery/jquery.min.js"></script>
<script src="<?php echo $this->basePath() ?>/public/common/foundation/js/foundation.min.js"></script>
<script src="<?php echo $this->basePath() ?>/public/common/foundation/js/foundation/foundation.topbar.js"></script>
<script src="<?php echo $this->basePath() ?>/public/common/foundation/js/responsive-tables.js"></script>
<script>
    $(document).foundation();
</script>

</body>
</html>