<ul class="breadcrumbs">
    <li>
        <a href="<?php echo $this->basepath() ?>/" title="Torna all'home page">Home</a>
    </li>
    <li>
        <a href="<?php echo $this->basepath()."/".$this->category_seo ?>" title="<?php echo $this->category ?>"><?php echo $this->category ?></a> <span class="divider"></span>
    </li>

    <li class="current"><?php echo $this->title ?></li>
</ul>

<?php foreach($this->paginator as $key => $row): ?>
<div class="content_details">
    <h1><?php echo $row['title'] ?></h1>

    <?php if ( isset($row['subtitle']) ): ?>
    <p><strong><?php echo $row['subtitle'] ?></strong></p>
    <?php endif; ?>

    <div><?php echo $row['description'] ?></div>

    <?php if ($row['flagAttachments'] == 'si'): ?>
    <h3>Allegati</h3>
    <p>Scarica i file allegati</p>
    <ul>
        <li><a href="#" title="">File 1</a></li>
        <li><a href="#" title="">File 2</a></li>
        <li><a href="#" title="">File 3</a></li>
    </ul>
    <?php endif; ?>

    <p class="text-right">
        Esporta: <a href="#" title="Visualizza documento in formato PDF">PDF</a> 
        <a href="#" title="Visualizza documento in formato Word">WORD</a> 
        <a href="#" title="Visualizza documento in formato testo">TXT</a> 
        
        Condividi: <a href="https://www.facebook.com/sharer/sharer.php?u=<?php echo $this->currentUrl; ?>" title="Condividi pagina su facebook" target="_blank">Facebook</a> <a href="https://twitter.com/home?status=<?php echo $this->currentUrl; ?>" title="Condividi pagina su Twitter">Twitter</a> 
        <!-- <a href="https://plus.google.com/share?url=<?php echo $this->currentUrl ?>">Google Plus</a> <a href="https://www.linkedin.com/shareArticle?mini=true&amp;url=<?php echo $this->currentUrl ?>&amp;title=<?php echo $row['seoTitle'] ?>">Linkedin</a> <a href="https://pinterest.com/pin/create/button/?url=<?php echo $this->currentUrl ?>">Pinterest</a>-->
    </p>

    <hr>
</div>
<?php endforeach; ?>