<ul class="breadcrumbs">
    <li>
        <a href="<?php echo $this->basepath() ?>/" title="Torna all'home page">Home</a>
    </li>
    <li>
        <a href="<?php echo $this->basepath()."/".$this->category_seo ?>" title="<?php echo $this->category ?>"><?php echo $this->category ?></a> <span class="divider"></span>
    </li>

    <li class="current"><?php echo $this->title ?></li>
</ul>

<?php foreach($this->paginator as $key => $row): ?>
<div class="content_details">
    <h1><?php echo $row['title'] ?></h1>

    <?php if ( isset($row['subtitle']) ): ?>
    <p><strong><?php echo $row['subtitle'] ?></strong></p>
    <?php endif; ?>

    <div><?php echo $row['description'] ?></div>

    <?php if ($row['flagAttachments'] == 'si'): ?>
    <h3>Allegati</h3>
    <p>Scarica i file allegati</p>
    <ul>
        <li><a href="#" title="">File 1</a></li>
        <li><a href="#" title="">File 2</a></li>
        <li><a href="#" title="">File 3</a></li>
    </ul>
    <?php endif; ?>

    <br>
    <br>
    <p class="text-right">Esporta: <a href="#" title="Esporta in formato testo"><img src="<?php echo $this->basepath() ?>/public/common/icons/txt.png" alt="Icona file di testo"></a>
        <a href="#" title="Esporta in formato PDF"><img src="<?php echo $this->basepath() ?>/public/common/icons/pdf.gif" alt="Icona PDF"></a>
        Condividi: <a href="https://www.facebook.com/sharer/sharer.php?u=<?php echo $this->currentUrl; ?>" title="Condividi su facebook" onclick="javascript:window.open(this.href, '', 'menubar=no,toolbar=no,resizable=yes,scrollbars=yes,height=300,width=600');return false;"><img src="<?php echo $this->basepath() ?>/public/common/icons/facebook.gif" alt="Icona Facebook"></a>
        <a href="http://twitter.com/share?text=<?php echo urlencode($row['title']) ?>&amp;url=<?php echo $this->currentUrl; ?>"><img src="<?php echo $this->basepath() ?>/public/common/icons/twitter.gif" alt="Icona Twitter"></a>
        <a href="https://plus.google.com/share?url=<?php echo $this->currentUrl; ?>" title="Condividi su google plus"><img src="<?php echo $this->basepath() ?>/public/common/icons/google-plus.png" alt="Icona Google Plus"></a>
    </p>
    <hr>

</div>
<?php endforeach; ?>