<ul class="breadcrumbs">
    <li><a href="<?php echo $this->basepath() ?>/" title="Torna all' home page">Home</a></li>
    <li class="current"><?php echo $this->category ?></li>
</ul>

<p>Pagine presenti per la categoria <strong><?php echo $this->category; ?></strong>:</p>

<ul>
<?php foreach($this->maindata as $content): ?>
    <li><a href="<?php echo $this->basepath().$content['linkDetails'] ?>" title="<?php echo $content['title'] ?>"><?php echo $content['title'] ?></a></li>
<?php endforeach; ?>
</ul>