<?php if (empty($this->error)): ?>
    <ul class="breadcrumb">
        <li><a href="" title="Home page">Home</a></li>
        <li><a href="<?php echo $this->url('admin/contratti-pubblici-summary', array('lang' => $this->params()->fromRoute('lang'))); ?>">Contratti pubblici</a></li>
        <li><a href="<?php echo $this->url('admin/contratti-pubblici-form', array('lang' => $this->params()->fromRoute('lang'), 'id' => $this->params()->fromRoute('id'))); ?>">Bando</a></li>
        <li class="active">Partecipanti e aggiudicatari</li>
    </ul>

    <h3 class="text-center"><?php echo $this->contratto[0]['titolo'] ?></h3>

    <h3>Operatori aggiudicatari</h3>
    <p>Elenco operatori aggiudicatari</p>
    <?php if (!empty($this->operatoriAggiudicatari)): ?>
    <table width="100%" class="table table-bordered">
        <tr>
            <th><abbr title="Codice fiscale">C.F</abbr></th>
            <th>Ragione Sociale</th>
            <th>Nome</th>
            <th>Gruppo</th>
            <th>Ruolo</th>
            <th>Membro</th>
            <th>Aggiudicatario</th>
        </tr>
    <?php foreach($this->operatoriAggiudicatari as $partecipante): ?>
        <tr>
            <td><?php echo $partecipante['cf'] ?></td>
            <td><?php echo $partecipante['ragioneSociale'] ?></td>
            <td><?php echo $partecipante['nome'] ?></td>
            <td><?php echo $partecipante['gruppo'] ?></td>
            <td>&nbsp;</td>
            <td><?php echo $partecipante['membro'] + 0 ?></td>
            <td>
                <form role="form" action="<?php echo $this->url('admin/contratti-pubblici-aggiudicatari-operations', array(
                    'lang' => $this->params()->fromRoute('lang'),
                    'id' => $this->params()->fromRoute('id'),
                    'action' => 'removeaggiudicatario'
                )); ?>" method="post">
                    <input type="hidden" value="<?php echo $partecipante['idPartecipante'] ?>" name="removeAggiudicatario">
                    <input type="hidden" value="<?php echo $partecipante['id'] ?>" name="idContratto">
                    <input type="hidden" value="<?php echo $partecipante['idRelation'] ?>" name="idRelation">
                    <button type="submit" class="btn btn-danger" title="Elimina aggiudicatario dalla lista"><i class="fa fa-times"></i></button>
                </form>
            </td>
        </tr>
    <?php endforeach; ?>
    </table>
    <?php else: ?>
    <div class="alert alert-warning"><strong><i class="fa fa-warning"></i> Nessun operatore aggiudicatario</strong></div>
    <?php endif; ?>

    <h3>Elenco degli operatori invitati a presentare offerte</h3>
    <?php if (!empty($this->operatoriPartecipanti)): ?>
        <table width="100%" class="table table-bordered">
            <tr>
                <th><abbr title="Codice fiscale">C.F</abbr></th>
                <th>Ragione Sociale</th>
                <th>Nome</th>
                <th>Gruppo</th>
                <th>Ruolo</th>
                <th>Membro</th>
                <th>&nbsp;</th>
            </tr>
        <?php foreach($this->operatoriPartecipanti as $partecipante): ?>
            <tr>
                <td><?php echo $partecipante['cf'] ?></td>
                <td><?php echo $partecipante['ragioneSociale'] ?></td>
                <td><?php echo $partecipante['nome'] ?></td>
                <td>
                    <?php
                    /* Form Numero Gruppo */
                    $form = $this->formGruppo;

                    $form->setAttribute('action',   $this->url('admin/contratti-pubblici-aggiudicatari-operations', array(
                        'lang'      => $this->params()->fromRoute('lang'),
                        'id'        => $this->params()->fromRoute('id'),
                        'action'    => 'updategruppo'
                    )));
                    $form->setAttribute('method',   'post');
                    $form->setAttribute('role',     'form');
                    $form->setAttribute('class',    'form-horizontal');
                    $form->setAttribute('id',       'frmGruppo');

                    $form->get('gruppo')->setAttribute('class', 'form-control');
                    $form->get('okGroup')->setAttribute('class', 'btn btn-primary');

                    $form->prepare();
                    $form->setData(array(
                        'contrattoId'       => $this->params()->fromRoute('id'),
                        'partecipanteId'    => $partecipante['idPartecipante'],
                        'relationId'        => $partecipante['idRelation'],
                        'gruppo'            => isset($partecipante['gruppo']) ? $partecipante['gruppo'] : 0,
                    ));
                    echo $this->form()->openTag($form);
                    ?>
                    <div class="row">
                        <div class="col-sm-6">
                            <?php echo $this->formElement($form->get('partecipanteId')); ?>
                            <?php echo $this->formElement($form->get('contrattoId')); ?>
                            <?php echo $this->formElement($form->get('relationId')); ?>

                            <?php echo $this->formElement($form->get('gruppo')); ?>
                        </div>
                        <div class="col-sm-4">
                            <?php echo $this->formElement($form->get('okGroup')); ?>
                        </div>
                    </div>
                    <?php echo $this->form()->closeTag(); ?>
                </td>
                <?php if ($partecipante['gruppo']!=0 and $partecipante['gruppo']!=''): ?>
                <td>
                    <?php
                    /* Form Selezione Ruolo (categoria) */
                    $form = $this->formRuolo;

                    $form->setAttribute('action',   $this->url('admin/contratti-pubblici-aggiudicatari-operations', array(
                        'lang'      => $this->params()->fromRoute('lang'),
                        'id'        => $this->params()->fromRoute('id'),
                        'action'    => 'updateruolo'
                    )));
                    $form->setAttribute('method',   'post');
                    $form->setAttribute('role',     'form');
                    $form->setAttribute('class',    'form-horizontal');
                    $form->setAttribute('id',       'frmRuolo');

                    $form->get('ruolo')->setAttribute('class', 'form-control');
                    $form->get('okRole')->setAttribute('class', 'btn btn-primary');

                    $form->prepare();
                    $form->setData(array(
                        'relationId'    => $partecipante['idRelation'],
                        'ruolo'         => $partecipante['stato']
                    ));

                    echo $this->form()->openTag($form);

                    ?>
                    <div class="row">
                        <div class="col-sm-8">
                            <?php echo $this->formElement($form->get('relationId')); ?>

                            <?php echo $this->formElement($form->get('ruolo')); ?>
                        </div>
                        <div class="col-sm-2">
                            <?php echo $this->formElement($form->get('okRole')); ?>
                        </div>
                    </div>
                    <?php echo $this->form()->closeTag(); ?>
                </td>
                <?php else: ?>
                <td>Nessuno</td>
                <?php endif; ?>
                <td><?php echo ($partecipante['membro']!=0) ? $partecipante['membro'] + 0 : 'No' ?></td>
                <td>
                    <form role="form" action="<?php echo $this->url('admin/contratti-pubblici-aggiudicatari-operations', array(
                        'lang' => $this->params()->fromRoute('lang'),
                        'id' => $this->params()->fromRoute('id'),
                        'action' => 'removepartecipante'
                    )); ?>" method="post">
                        <input type="hidden" value="<?php echo $partecipante['idPartecipante'] ?>" name="removePartecipante">
                        <input type="hidden" value="<?php echo $partecipante['id'] ?>" name="idContratto">
                        <input type="hidden" value="<?php echo $partecipante['idRelation'] ?>" name="idRelation">
                        <button type="submit" class="btn btn-danger" title="Elimina partecipante"><i class="fa fa-times"></i></button>
                    </form>
                </td>
                <td>
                    <form role="form" action="<?php echo $this->url('admin/contratti-pubblici-aggiudicatari-operations', array(
                        'lang' => $this->params()->fromRoute('lang'),
                        'id' => $this->params()->fromRoute('id'),
                        'action' => 'addaggiudicatario'
                    )); ?>" method="post">
                        <input type="hidden" value="<?php echo $partecipante['idPartecipante'] ?>" name="addAggiudicatario">
                        <input type="hidden" value="<?php echo $partecipante['id'] ?>" name="idContratto">
                        <input type="hidden" value="<?php echo $partecipante['idRelation'] ?>" name="idRelation">
                        <button type="submit" class="btn btn-info" title="Aggiungi all'elenco degli aggiudicatari"><i class="fa fa-plus"></i></button>
                    </form>
                </td>
            </tr>
        <?php endforeach; ?>
        </table>
    <?php else: ?>
        <div class="alert alert-warning">
            <strong><i class="fa fa-warning"></i> Nessun operatore invitato a presentare offerte</strong>
        </div>
    <?php endif; ?>

    <!-- Elenco completo operatori -->
    <h3>Elenco operatori</h3>

    <p>Seleziona e aggiungi operatori all'elenco partecipanti:</p>

    <?php if (!empty($this->operatori)): ?>
        <form action="<?php echo $this->url('admin/contratti-pubblici-aggiudicatari-operations', array(
            'lang'      => $this->params()->fromRoute('lang'),
            'id'        => $this->params()->fromRoute('id'),
            'action'    => 'addoperatore'
        )); ?>" method="post" id="frmaddoperatore">
        <div>
            <input type="submit" name="addOperatoreButton" value="Aggiungi azienda all'elenco partecipanti" class="btn btn-lg btn-primary">
        </div>
        <table class="table table-bordered dataTable" id="contratti-opeartori-rubrica-table">
            <thead>
            <tr>
                <th>&nbsp;</th>
                <th><abbr title="Codice fiscale">C.F</abbr> o <abbr title="Partita IVA">P.I</abbr></th>
                <th>Nome e Ragione Sociale</th>
            </tr>
            </thead>
        <?php foreach($this->operatori as $operatore): ?>
            <tr>
                <td><input type="checkbox" name="operatorerubrica[]" value="<?php echo $operatore['id'] ?>" class="editor-active" title="Seleziona operatore <?php echo utf8_encode($operatore['nome']) ?>"></td>
                <td><?php echo $operatore['cf'] ?></td>
                <td><?php echo !empty($operatore['nome']) ? utf8_encode($operatore['nome']) : utf8_encode($operatore['ragioneSociale']) ?></td>
            </tr>
        <?php endforeach; ?>
        </table>
            <div>
                <input type="submit" name="addOperatoreButton" value="Aggiungi operaori all'elenco partecipanti" class="btn btn-lg btn-primary">
            </div>
        </form>
    <?php else: ?>
    <div class="alert alert-warning">
        <h3>Nessun operatore selezionabile</h3>
    </div>
    <?php endif; ?>

<?php else: ?>
    <ul class="breadcrumb">
        <li><a href="#" title="Home page">Home</a> <span class="divider"></span></li>
        <li class="active">Contratti pubblici</li>
    </ul>

    <div class="alert alert-danger">
        <h2><?php echo $this->error ?></h2>
        <p><?php echo $this->errorMesssage ?></p>
    </div>
<?php endif; ?>
