<?php echo $this->render($this->formDataCommonPath.'breadcrumb.phtml'); ?>

<div>
    <a href="javascript:void(0)" id="lnkSearchExport" class="btn btn-primary">
        <i class="fa fa-search"></i> <?php echo $this->translate('Ricerca ed esportazione'); ?>
    </a>
</div>

<div id="frmFrmSearchExport" style="display: <?php echo ($this->sessionSearch) ? 'block' : 'none' ?>">

    <br>

    <?php

    $form = $this->formSearch;

    $form->setAttribute('action',   $this->url('albo-pretorio-search', array('action' => 'index')));
    $form->setAttribute('method',   'post');
    $form->setAttribute('role',     'form');
    $form->setAttribute('class',    'form-horizontal');
    $form->setAttribute('id',       'frmSearchExport');

    $form->get('numero_progressivo')->setAttribute('class', 'form-control');
    $form->get('numero_atto')->setAttribute('class', 'form-control');
    $form->get('testo')->setAttribute('class', 'form-control');
    $form->get('mese')->setAttribute('class', 'form-control');
    $form->get('anno')->setAttribute('class', 'form-control');
    $form->get('sezione')->setAttribute('class', 'form-control');
    $form->get('search')->setAttribute('class', 'btn btn-primary');
    $form->get('resetForm')->setAttribute('class', 'btn btn-danger');

    $form->prepare();

    echo $this->form()->openTag($form);

    ?>
    <div class="form-group">
        <label class="col-sm-2 control-label" for="<?php echo $form->get('numero_progressivo')->getAttribute('id') ?>">
            <?php echo $this->formLabel($form->get('numero_progressivo')) ?>
        </label>
        <div class="col-sm-2">
            <?php echo $this->formElement($form->get('numero_progressivo')); ?>
        </div>

        <label class="col-sm-2 control-label" for="<?php echo $form->get('numero_atto')->getAttribute('id') ?>">
            <?php echo $this->formLabel($form->get('numero_atto')) ?>
        </label>
        <div class="col-sm-2">
            <?php echo $this->formElement($form->get('numero_atto')); ?>
        </div>

        <div class="col-sm-2">
            <label class=" control-label" for="<?php echo $form->get('home')->getAttribute('id') ?>">
                <?php echo $this->formElement($form->get('home')); ?> <?php echo $this->formLabel($form->get('home')) ?>
            </label>
        </div>
    </div>

    <div class="form-group">
        <label class="col-sm-2 control-label" for="<?php echo $form->get('testo')->getAttribute('id') ?>">
            <?php echo $this->formLabel($form->get('testo')) ?>
        </label>
        <div class="col-sm-10">
            <?php echo $this->formElement($form->get('testo')); ?>
        </div>
    </div>

    <div class="form-group">
        <label class="col-sm-2 control-label" for="<?php echo $form->get('mese')->getAttribute('id') ?>">
            A partire da:
        </label>
        <div class="col-sm-2">
            <?php echo $this->formElement($form->get('mese')); ?>
        </div>
        <div class="col-sm-2">
            <?php echo $this->formElement($form->get('anno')); ?>
        </div>
        <label class="col-sm-2 control-label" for="<?php echo $form->get('sezione')->getAttribute('id') ?>">
            <?php echo $this->formLabel($form->get('sezione')) ?>
        </label>
        <div class="col-sm-4">
            <?php echo $this->formElement($form->get('sezione')); ?>
        </div>
    </div>

    <div class="form-group">
        <label class="col-sm-2 control-label" for="<?php echo $form->get('search')->getAttribute('id') ?>">
            &nbsp;
        </label>
        <div class="col-sm-4">
            <?php echo $this->formElement($form->get('csrf')); ?>
            <?php echo $this->formElement($form->get('search')); ?>

            <?php if ($this->sessionSearch): ?>
                <a href="<?php echo $this->url('albo-pretorio-search', array('action' => 'unsetsearch')) ?>" class="btn btn-danger" title="Azzera sessione di ricerca sugli atti dell'albo pretorio">Azzera ricerca</a>
            <?php endif; ?>
        </div>

        <div class="col-sm-6">
            <!--
            Esporta: <button type="submit" class="btn btn-success" id="csv_export">
                <i class="fa fa-file-excel-o"></i> CSV
            </button>

            <button type="submit" class="btn btn-danger" id="pdf_export">
                <i class="fa fa-file-pdf-o"></i> PDF
            </button>

            <button type="submit" class="btn btn-info">
                <i class="fa fa-file-text"></i> TXT
            </button>

            <button type="submit" class="btn btn-info">
                <i class="fa fa-file-text"></i> XML
            </button>

            <button type="submit" class="btn btn-info">
                <i class="fa fa-file-text"></i> JSON
            </button>
            -->
        </div>

    </div>

    <?php echo $this->form()->closeTag(); ?>
</div>

<?php if (empty($records)): ?>
    <div class="alert alert-warning" style="margin: 0; padding-top: 0">
        <h3>Nessun atto albo pretorio trovato</h3>
        <p><?php echo $this->translate("Non sono presenti atti nell'albo pretorio in archivio") ?>.</p>
    </div>
<?php else: ?>

    <?php

    echo $this->render('backend/templates/common/datatables_zend_pagination.phtml');
endif;

?>
<script>
    /* Change form action to export records */
    $('#csv_export').click(function() {
        $('#frmSearchExport').attr('action', '<?php echo $this->url('albo-pretorio-export', array('action' => 'csv', 'lang' => $this->params()->fromRoute('lang')) ); ?>');
    });

    $('#pdf_export').click(function() {
        $('#frmSearchExport').attr('action', '<?php echo $this->url('albo-pretorio-export', array('action' => 'pdf', 'lang' => $this->params()->fromRoute('lang')) ); ?>');
    });

    $('#txt_export').click(function() {
        $('#frmSearchExport').attr('action', '<?php echo $this->url('albo-pretorio-export', array('action' => 'txt', 'lang' => $this->params()->fromRoute('lang'))); ?>');
    });
</script>
