<?php echo $this->render('backend/templates/'.$this->template_backend.'datatable/datatable_breadcrumb.phtml'); ?>

<div>
    <a href="javascript:void(0)" id="lnkSearchExport" class="btn btn-primary">
        <i class="fa fa-search"></i> <?php echo $this->translate('Ricerca ed esportazione'); ?>
    </a>
</div>

<div id="frmFrmSearchExport" style="display: block">

    <br>

    <?php

    $form = $this->formSearch;

    $form->setAttribute('action',   $this->url('admin/albo-pretorio-summary', array('lang'=>'it')));
    $form->setAttribute('method',   'post');
    $form->setAttribute('role',     'form');
    $form->setAttribute('class',    'form-horizontal');
    $form->setAttribute('id',       'frmSearchExport');

    $form->get('numero_progressivo')->setAttribute('class', 'form-control');
    $form->get('numero_atto')->setAttribute('class', 'form-control');
    $form->get('testo')->setAttribute('class', 'form-control');
    $form->get('mese')->setAttribute('class', 'form-control');
    $form->get('anno')->setAttribute('class', 'form-control');
    $form->get('sezione')->setAttribute('class', 'form-control');
    $form->get('settore')->setAttribute('class', 'form-control');
    $form->get('search')->setAttribute('class', 'btn btn-primary');
    $form->get('resetForm')->setAttribute('class', 'btn btn-danger');

    $form->prepare();

    echo $this->form()->openTag($form);

    ?>
    <div class="form-group">
        <label class="col-sm-2 control-label" for="<?php echo $form->get('numero_progressivo')->getAttribute('id') ?>">
            <?php echo $this->formLabel($form->get('numero_progressivo')) ?>
        </label>
        <div class="col-sm-2">
            <?php echo $this->formElement($form->get('numero_progressivo')); ?>
        </div>

        <label class="col-sm-2 control-label" for="<?php echo $form->get('numero_atto')->getAttribute('id') ?>">
            <?php echo $this->formLabel($form->get('numero_atto')) ?>
        </label>
        <div class="col-sm-2">
            <?php echo $this->formElement($form->get('numero_atto')); ?>
        </div>
    </div>

    <div class="form-group">
        <label class="col-sm-2 control-label" for="<?php echo $form->get('testo')->getAttribute('id') ?>">
            <?php echo $this->formLabel($form->get('testo')) ?>
        </label>
        <div class="col-sm-10">
            <?php echo $this->formElement($form->get('testo')); ?>
        </div>
    </div>

    <div class="form-group">
        <label class="col-sm-2 control-label" for="<?php echo $form->get('mese')->getAttribute('id') ?>">
            A partire da:
        </label>
        <div class="col-sm-4">
            <?php echo $this->formElement($form->get('mese')); ?>
        </div>
        <div class="col-sm-6">
            <?php echo $this->formElement($form->get('anno')); ?>
        </div>
    </div>

    <div class="form-group">
        <label class="col-sm-2 control-label" for="<?php echo $form->get('sezione')->getAttribute('id') ?>">
            <?php echo $this->formLabel($form->get('sezione')) ?>
        </label>
        <div class="col-sm-4">
            <?php echo $this->formElement($form->get('sezione')); ?>
        </div>

        <label class="col-sm-2 control-label" for="<?php echo $form->get('settore')->getAttribute('id') ?>">
            <?php echo $this->formLabel($form->get('settore')) ?>
        </label>
        <div class="col-sm-4">
            <?php echo $this->formElement($form->get('settore')); ?>
        </div>
    </div>

    <div class="form-group">
        <label class="col-sm-2 control-label" for="<?php echo $form->get('search')->getAttribute('id') ?>">
            &nbsp;
        </label>
        <div class="col-sm-2">
            <?php echo $this->formElement($form->get('search')); ?>
        </div>

        <div class="col-sm-2">
            <?php echo $this->formElement($form->get('resetForm')); ?>
        </div>

        <div class="col-sm-6">
            Esporta: <button type="button" class="btn btn-success"> CSV</button>
            <button type="button" class="btn btn-danger"> PDF</button>
            <button type="button" class="btn btn-info"> XML</button>
            <button type="button" class="btn btn-info"> JSON</button>
        </div>
    </div>

    <?php

    /* Print form elements +/
    /*
    echo $this->partial('backend/templates/common/formdata_form_elements.phtml', array(
            'form'                  => $form,
            'formAction'            => null,
            'formId'                => 'alboPretorioSearch',
            'formTitle'             => $this->formTitle,
            'formDescription'       => $this->formDescription,
            'closeForm'             => 1,
            'formControlSpanWidth'  => isset($this->formControlSpanWidth) ? $this->formControlSpanWidth : 10,
            'formLabelSpanWidth'    => isset($this->formLabelSpanWidth) ? $this->formLabelSpanWidth : 2,
        )
    );
    */

    echo $this->form()->closeTag();

    ?>
</div>

<?php

echo $this->render('backend/templates/common/datatables_zend_pagination.phtml');
