<?php echo $this->render('backend/templates/'.$this->template_backend.'datatable/datatable_breadcrumb.phtml'); ?>

<?php if (empty($records)): ?>
    <div class="alert alert-warning">
        <?php if ($this->messageTitle): ?>
            <h1><?php echo $this->messageTitle ?></h1>
        <?php else: ?>
            <h1>Nessun dato in archivio</h1>
        <?php endif; ?>

        <?php if ($this->messageDescription): ?>
            <p><?php echo $this->messageDescription ?></p>
        <?php else: ?>
            <p>Nessun dato da elencare &egrave; stato trovato.</p>
        <?php endif; ?>
    </div>
<?php else: ?>
    <?php

    $this->searchFilterForm->prepare();

    $form = $this->searchFilterForm;
    $form->prepare();

    $formAction = '';
    $formId = 'formSearchFilter';

    $form->setAttributes(array(
        'action'    => $formAction,
        'method'    => 'post',
        'enctype'   => 'multipart/form-data',
        'name'      => $formId,
        'id'        => $formId,
        'role'      => 'form',
    ));

    ?>
    <div class="tab-pane active" id="home">

        <h3><?php echo $this->tableTitle ?></h3>

        <p><?php echo $this->tableDescription ?></p>

        <form class="form-inline" role="form" action="" method="post">

            <!--
            <div class="form-group">
                <input type="text" class="form-control" id="exampleInputName2" placeholder="Cerca..." maxlength="255">
            </div>
            -->

            <div class="form-group">
                <?php
                $form->get('categoryId')->setAttribute('class', 'form-control');
                echo $this->formElement($form->get('categoryId'));
                ?>
            </div>

            <button type="submit" class="btn btn-primary"><i class="fa fa-search"></i> Filtra</button>

        </form>

        <div>
            <br>
            <strong>Esporta in formato:</strong> PDF TXT XML CSV
        </div>

        <br>

        <?php echo $this->render($this->formDataCommonPath.'datatables_elements.phtml'); ?>

    </div>

<?php
endif;
