<?php echo $this->render('backend/templates/'.$this->template_backend.'datatable/datatable_breadcrumb.phtml'); ?>

<ul class="nav nav-tabs" role="tablist">
    <li class="active"><a href="#home" role="tab" data-toggle="tab"><i class="fa fa-list"></i> <?php echo $this->translate('Elenco articoli'); ?></a></li>
    <li><a href="#search" role="tab" data-toggle="tab"><i class="fa fa-search"></i> <?php echo $this->translate('Ricerca'); ?></a></li>
    <li><a href="#export" role="tab" data-toggle="tab"><i class="fa fa-external-link-square"></i> <?php echo $this->translate('Esportazione dati'); ?></a></li>
</ul>

<div class="tab-content">
    <div class="tab-pane active" id="home">
        <?php echo $this->render('backend/templates/common/datatables_zend_pagination.phtml'); ?>
    </div>
    
    <div class="tab-pane" id="search">
        <h3>Ricerca</h3>
         <div class="alert alert-warning"><h3>In costruzione</h3></div>
    </div>
    
    <div class="tab-pane" id="export">
        
        <h3>Esportazione dati</h3>
        <div class="alert alert-warning"><h3>In costruzione</h3></div>
        
    </div>
</div>
