<?php echo $this->render($this->formDataCommonPath.'breadcrumb.phtml'); ?>

<p>
    <a href="javascript:void(0)" id="lnkSearchExport" class="btn btn-primary">
        <i class="fa fa-search"></i> Ricerca ed esportazione
    </a>
</p>

<div id="frmFrmSearchExport" style="display: block">

    <br>

    <?php

    $form = $this->formSearch;

    $form->setAttribute('action',   $this->url('admin/contratti-pubblici-summary', array('lang'=>'it')));
    $form->setAttribute('method',   'post');
    $form->setAttribute('role',     'form');
    $form->setAttribute('class',    'form-horizontal');
    $form->setAttribute('id',       'frmSearchExport');

    $form->get('cig')->setAttribute('class', 'form-control');
    $form->get('importo')->setAttribute('class', 'form-control');
    $form->get('anno')->setAttribute('class', 'form-control');
    $form->get('ufficio')->setAttribute('class', 'form-control');
    $form->get('search')->setAttribute('class', 'btn btn-primary');
    $form->prepare();

    echo $this->form()->openTag($form);

    ?>

    <div class="form-group">
        <label class="col-sm-2 control-label" for="<?php echo $form->get('cig')->getAttribute('id') ?>">
            <?php echo $this->formLabel($form->get('cig')) ?>
        </label>
        <div class="col-sm-2">
            <?php echo $this->formElement($form->get('cig')); ?>
        </div>

        <label class="col-sm-4 control-label" for="<?php echo $form->get('importo')->getAttribute('id') ?>">
            <?php echo $this->formLabel($form->get('importo')) ?>
        </label>
        <div class="col-sm-4">
            <?php echo $this->formElement($form->get('importo')); ?>
        </div>

    </div>

    <div class="form-group">
        <label class="col-sm-2 control-label" for="<?php echo $form->get('anno')->getAttribute('id') ?>">
            <?php echo $this->formLabel($form->get('anno')) ?>
        </label>
        <div class="col-sm-2">
            <?php echo $this->formElement($form->get('anno')); ?>
        </div>

        <label class="col-sm-4 control-label" for="<?php echo $form->get('ufficio')->getAttribute('id') ?>">
            <?php echo $this->formLabel($form->get('ufficio')) ?>
        </label>
        <div class="col-sm-4">
            <?php echo $this->formElement($form->get('ufficio')); ?>
        </div>
    </div>

    <div class="form-group">
        <label class="col-sm-2 control-label" for="<?php echo $form->get('search')->getAttribute('id') ?>">
            &nbsp;
        </label>
        <div class="col-sm-2">
            <?php echo $this->formElement($form->get('search')); ?>
            <button type="reset" class="btn btn-danger">Reset</button>
        </div>

        <div class="col-sm-8">
            <!--
            Esporta:
            <button type="button" class="btn btn-success"><i class="fa fa-file-excel-o"></i> CSV</button>
            <button type="button" class="btn btn-danger"><i class="fa fa-file-pdf-o"></i> PDF</button>
            <button type="button" class="btn btn-info"><i class="fa fa-file-text"></i> XML</button>
            <button type="button" class="btn btn-info"><i class="fa fa-file-text"></i> JSON</button>
            -->
        </div>
    </div>


    <br><br>
    <?php

    echo $this->form()->closeTag();

    ?>
</div>

<?php

echo $this->render('backend/templates/common/datatables_zend_pagination.phtml');
