<?php echo $this->render($this->formDataCommonPath.'breadcrumb.phtml'); ?>

<div>
    <a href="javascript:void(0)" id="lnkSearchExport" class="btn btn-primary">
        <i class="fa fa-search"></i> <?php echo $this->translate('Ricerca ed esportazione'); ?>
    </a>
</div>

<div id="frmFrmSearchExport" style="display: <?php echo ($this->sessionSearch) ? 'block' : 'none' ?>">
    <?php

    if (!empty($this->formLanguage)):
        ?>
        <br>
        <?php
        echo $this->partial($this->formDataCommonPath.'_formdata_language.phtml', array(
            'formLanguage' => $this->formLanguage,
            'formAction' => $this->url('admin/contenuti-operations', array(
                'lang'                  => $this->params()->fromRoute('lang'),
                'languageSelection'     => $this->params()->fromRoute('languageSelection'),
                'modulename'            => $this->params()->fromRoute('modulename'),
                'action'                => 'changesummarylang',
            )),
        ));
    endif;

    if ($this->formSearch):

        $form = $this->formSearch;

        $form->setAttribute('action',   '');
        $form->setAttribute('method',   'post');
        $form->setAttribute('role',     'form');
        $form->setAttribute('class',    'form-horizontal');
        $form->setAttribute('id',       'frmSearchExport');

        $form->get('testo')->setAttribute('class', 'form-control');
        $form->get('sottosezioni')->setAttribute('class', 'form-control');
        $form->get('search')->setAttribute('class', 'btn btn-primary');

        $form->prepare();

        echo $this->form()->openTag($form);

    ?>

        <h4 class="text-center">Ricerca fra gli articoli</h4>

        <div class="form-group">
            <label class="col-sm-2 control-label" for="<?php echo $form->get('testo')->getAttribute('id') ?>">
                <?php echo $this->formLabel($form->get('testo')) ?>
            </label>

            <div class="col-sm-2">
                <?php echo $this->formElement($form->get('testo')); ?>
            </div>

            <label class="col-sm-2 control-label" for="<?php echo $form->get('sottosezioni')->getAttribute('id') ?>">
                <?php echo $this->formLabel($form->get('sottosezioni')) ?>
            </label>

            <div class="col-sm-2">
                <?php echo $this->formElement($form->get('sottosezioni')); ?>
            </div>

            <div class="col-sm-2">
                <label class=" control-label" for="<?php echo $form->get('inhome')->getAttribute('id') ?>">
                    <?php echo $this->formElement($form->get('inhome')); ?> <?php echo $this->formLabel($form->get('inhome')) ?>
                </label>
            </div>
        </div>

        <div class="form-group">

            <div class="col-sm-2">
                &nbsp;
            </div>

            <div class="col-sm-4">
                <?php echo $this->formElement($form->get('csrf')); ?>
                <?php echo $this->formElement($form->get('search')); ?>

                <?php if ($this->sessionSearch): ?>
                    <a href="<?php echo $this->url('main/contenuti-search', array('action' => 'unsetsearch', 'lang' => $this->params()->fromRoute('lang'))) ?>" class="btn btn-danger" title="Azzera sessione di ricerca sugli atti dell'albo pretorio">Azzera ricerca</a>
                <?php endif; ?>
            </div>

            <div class="col-sm-8">
                &nbsp;
            </div>
        </div>

        <?php echo $this->form()->closeTag(); ?>
    <?php endif; ?>
</div>

<?php

if (!empty($this->records)):
    echo $this->render('backend/templates/common/datatables_zend_pagination.phtml');
else:
    ?>
    <br>
    <div class="alert alert-warning">
        <h3>Nessun articolo trovato</h3>
        <p>Nessun articolo presente o trovato.</p>
    </div>
    <?php
endif;

?>

<?php

if ($this->showMessage):
    echo $this->partial($this->templateDir.'message.phtml', array(
        'messageType'   => $this->messageType,
        'messageTitle'  => $this->messageTitle,
        'messageText'   => $this->messageText,
    ));
endif;