<?php echo $this->render('backend/templates/'.$this->template_backend.'datatable/datatable_breadcrumb.phtml'); ?>

<div>
    <a href="javascript:void(0)" id="lnkSearchExport" class="btn btn-primary">
        <i class="fa fa-search"></i> <?php echo $this->translate('Ricerca ed esportazione'); ?>
    </a>
</div>

<div id="frmFrmSearchExport" style="display: block">

    <br>

    <?php

    $form = $this->formSearch;

    $form->setAttribute('action',   $this->url('admin/stato-civile-summary', array('lang'=>'it')));
    $form->setAttribute('method',   'post');
    $form->setAttribute('role',     'form');
    $form->setAttribute('class',    'form-horizontal');
    $form->setAttribute('id',       'frmSearchExport');

    $form->get('testo')->setAttribute('class', 'form-control');
    $form->get('mese')->setAttribute('class', 'form-control');
    $form->get('anno')->setAttribute('class', 'form-control');
    $form->get('numero_atto')->setAttribute('class', 'form-control');
    $form->get('numero_progressivo')->setAttribute('class', 'form-control');
    $form->get('sezione')->setAttribute('class', 'form-control');
    $form->get('search')->setAttribute('class', 'btn btn-primary');

    $form->prepare();

    echo $this->form()->openTag($form);

    ?>

    <div class="form-group">
        <label class="col-sm-2 control-label" for="<?php echo $form->get('testo')->getAttribute('id') ?>"> <?php echo $this->formLabel($form->get('testo')) ?></label>
        <div class="col-sm-10">
            <?php echo $this->formElement($form->get('testo')); ?>
        </div>
    </div>

    <div class="form-group">
        <label for="<?php echo $form->get('numero_atto')->getAttribute('id'); ?>" class="col-sm-2 control-label">Num. atto:</label>
        <div class="col-sm-4">
            <?php echo $this->formElement($form->get('numero_atto')); ?>
        </div>

        <label for="<?php echo $form->get('numero_progressivo')->getAttribute('id'); ?>" class="col-sm-2 control-label">Num. Progressivo:</label>
        <div class="col-sm-4">
            <?php echo $this->formElement($form->get('numero_progressivo')); ?>
        </div>
    </div>

    <div class="form-group">
        <label for="<?php echo $form->get('mese')->getAttribute('id'); ?>" class="col-sm-2 control-label">Atti a partire da:</label>
        <div class="col-sm-4">
            <?php echo $this->formElement($form->get('mese')); ?>
        </div>

        <label for="<?php echo $form->get('anno')->getAttribute('id'); ?>" class="col-sm-2 control-label">Anno:</label>
        <div class="col-sm-4">
            <?php echo $this->formElement($form->get('anno')); ?>
        </div>
    </div>

    <div class="form-group">
        <label class="col-sm-2 control-label" for="<?php echo $form->get('sezione')->getAttribute('id') ?>"> <?php echo $this->formLabel($form->get('sezione')) ?></label>
        <div class="col-sm-10">
            <?php echo $this->formElement($form->get('sezione')); ?>
        </div>
    </div>

    <div class="form-group">
        <label class="col-sm-2 control-label">&nbsp;</label>
        <div class="col-sm-10"><?php echo $this->formElement($form->get('expired')); ?>
            <label for="<?php echo $form->get('expired')->getAttribute('id') ?>" style="width: 80%"> <?php echo $this->formLabel($form->get('expired')) ?></label>
        </div>
    </div>

    <div class="form-group">
        <label class="col-sm-2 control-label">&nbsp;</label>
        <div class="col-sm-2">
            <?php echo $this->formElement($form->get('search')); ?>
        </div>

        <div class="col-sm-6">
            Esporta:

            <button type="submit" id="csv_export" class="btn btn-success" title="Esporta dati in formato CSV">
                <i class="fa fa-file-excel-o"></i> CSV
            </button>

            <button type="submit" id="pdf_export" class="btn btn-danger" title="Esporta dati in formato PDF">
                <i class="fa fa-file-pdf-o"></i> PDF
            </button>

            <button type="submit" id="txt_export" class="btn btn-info" title="Esporta dati in formato testo">
                <i class="fa fa-file-text"></i> TXT
            </button>

            <button type="submit" id="json_export" class="btn btn-info" title="Esporta dati in formato JSON">
                <i class="fa fa-file-text"></i> JSON
            </button>

            <button type="submit" id="xml_export" class="btn btn-info" title="Esporta dati in formato XML">
                <i class="fa fa-file-text"></i> XML
            </button>
        </div>
    </div>

    <div class="form-group">
        <label class="col-sm-2 control-label" for="">&nbsp;</label>
        <div class="col-sm-10">
            <button type="button" onclick="" id="resetForm" name="resetForm" class="btn btn-danger">Resetta dati di ricerca</button>
        </div>
    </div>

    <?php echo $this->form()->closeTag(); ?>

</div>

<?php echo $this->render('backend/templates/common/datatables_zend_pagination.phtml'); ?>

<script>
/* Change form action to export records */
$('#csv_export').click(function() {
    $('#frmSearchExport').attr('action', '<?php echo $this->url('stato-civile-export', array('action' => 'csv') ); ?>');
});

$('#pdf_export').click(function() {
    $('#frmSearchExport').attr('action', '<?php echo $this->url('stato-civile-export', array('action' => 'pdf') ); ?>');
});

$('#txt_export').click(function() {
    $('#frmSearchExport').attr('action', '<?php echo $this->url('stato-civile-export', array('action' => 'txt') ); ?>');
});
</script>